### PR TITLE
Add `Enumerable#grep(klass : T.class) forall T`

### PR DESCRIPTION
**Pull request by AlexWayfer**
It returns `Array(T)`.

### CODE REVIEW

**Comment by RX14** [comment]
I'm not sure if this is useful or common enough to out in the stdlib. Not sure about the naming at least.

Surely `array.compact_map { |x| x if x.is_a?(T) }` is short enough to use in the rare case you need to do something like this.

**Comment by AlexWayfer** [comment]
> I'm not sure if this is useful or common enough to out in the stdlib. Not sure about the naming at least.

It's from Ruby. And it's work with `klass === elem`, but not for `ary <<` (compiler checks `is_a?`, but not `===`).

> Surely array.compact_map { |x| x if x.is_a?(T) } is short enough to use in the rare case you need to do something like this.

I found [a wish to create shortcut for `.map(&.as(Type))`](https://github.com/crystal-lang/crystal/issues/4483#issuecomment-305260224) (from you), and now you're suggesting a longer way to the similar task.

**Comment by straight-shoota** [comment]
`.map(&.as(Type))` is entirely different and probably more common than filtering instances of a particular class from an array.

**Comment by RX14** [comment]
Unfortunately I don't think we're going to merge this. If we find in the future that this is a common operation i'm fine to reopen this :)

**Pull request closed without merging**
