### PR TITLE
Add `Number.rounding_mode` + `.{with,save}_rounding_mode`

### PR DESCRIPTION
**Pull request by Sija**
As per https://github.com/crystal-lang/crystal/issues/10414#issuecomment-798794701
Refs https://github.com/crystal-lang/crystal/pull/7126#pullrequestreview-616402001

### CODE REVIEW

**Comment by straight-shoota** [comment]
I would prefer to start a discussion about this feature proposal first, instead of jumping direclty into a PR.

**Comment by Sija** [comment]
@straight-shoota I already referenced the comments that were voiced before.

**Comment by straight-shoota** [comment]
Yes and in https://github.com/crystal-lang/crystal/pull/7126#pullrequestreview-616402001 I explicitly asked for a separate discussion. This is not a trivial addition. We should make sure to identify the correct use cases and design an approriate API for that.
Nothing like that has happend yet.

**Comment by Sija** [comment]
> This is not a trivial addition. We should make sure to identify the correct use cases and design an approriate API for that.

This sounds like over-complicating the issue.

The use case is the ability to globally change the default rounding mode since it's common that an external code:
- uses its own `Number::RoundingMode` as a default, which requires re-implementing this exact behavior in every shard that might want have such functionality.
- uses `Number#round` without allowing the developer to pass the `mode` argument to it. The only other option is to monkey-patch each and every method that does that, which is pretty awful.

API in this PR covers that, adding a class property + two yielding class methods.

**Comment by Sija** [comment]
Could this be moved forward?

**Comment by straight-shoota** [comment]
I'm not convinced about this implementation. So no approval from me without a dedicated discussion about use cases and alternatives.

**Comment by Sija** [comment]
@straight-shoota It's hard to discuss "not being convinced" statement. Could you please elaborate on what exactly makes you not convinced? btw, re: use cases I've already started a discussion that you didn't continue.

**Comment by beta-ziliani** [comment]
Hi @Sija , we took some time to discuss this with the team and concluded we will not move this forward. While we see that changing the behavior of the default rounding method is a reasonable request, we also believe that doing it on the fly, globally, provides an entry point to bugs. Moreover, the block-yielding methods makes it sound as if they could contain the global effect, but that's not really the case.

```crystal
Number.with_rounding_mode :ties_away do
  ties_away?
  ... # no ties away 😭
end

def ties_away?
  Number.rounding_mode = :ties_even # 😈
  ...
end
```

Therefore, I will close this PR, as I see no point in keeping it around. We can always re-open it if we change our minds. As mentioned, we encourage you to continue the discussion in a dedicated issue where we can weight other alternatives.

**Comment by Sija** [comment]
Hi @beta-ziliani, thanks for looking into it.

> While we see that changing the behavior of the default rounding method is a reasonable request, we also believe that doing it on the fly, globally, provides an entry point to bugs.

In order to minimize the scope of possible bugs stemming from globally changing the default, it could be changed to be a read-only property, changeable only within the scope of `with_rounding_mode` method.

> Moreover, the block-yielding methods makes it sound as if they could contain the global effect, but that's not really the case.

Well, it **is** the case, but in your example you're changing the global default within the `ties_away?` method, effectively overwriting the applied default within `with_rounding_mode`. Usually you'd use one **or** the other method exclusively.

**Comment by beta-ziliani** [comment]
>  In order to minimize the scope of possible bugs stemming from globally changing the default, it could be changed to be a read-only property, changeable only within the scope of `with_rounding_mode` method.

Note that this would easily break in a concurrent setting.

> Well, it is the case, but in your example you're changing the global default within the ties_away? method, effectively overwriting the applied default within with_rounding_mode. Usually you'd use one or the other method exclusively.

Well, the thing is that you might not know how the methods you call will behave w.r.t. the rounding option, so you might work under the assumption of one option, when in reality it changes mid-way the computation.

**Pull request closed without merging**
