### PR TITLE
Channel::Buffered, only enqueue one waiting fiber at a time

### PR DESCRIPTION
**Pull request by carlhoerberg**
Speeds up `Channel::Buffered` with many senders and/or receivers. 

```
original 184.39k (  5.42µs) (± 2.92%)  0.0B/op  42.21× slower
improved   7.78M (128.49ns) (± 2.07%)  0.0B/op        fastest
```

### CODE REVIEW

**Comment by carlhoerberg** [comment]
Gist for the benchmark: https://gist.github.com/carlhoerberg/103a130171e9ce1256317152eb9ee6e4

**Comment by bcardiff** [comment]
We will check if this improvement holds/are needed with the upcoming changes. Thanks for tracking this down.

**Comment by straight-shoota** [comment]
Why not merge it in right now? It's just a minimal change but provides a considerable performance improvement.
And it seems absolutely reasonable to do this. Any excess fibers are just going to be send back to wait in the `Channel` implementation.

**Comment by bcardiff** [comment]
Because there is ongoing work in Channels. I would rather merge/review altogether in this case and check this in different scenarios.

**Comment by RX14** [comment]
@bcardiff what ongoing work on channels? I feel I never know what's being worked on...

**Comment by asterite** [comment]
This PR is now obsolete after #8112

But please open a new PR if there are optimization opportunities. Thank you!

**Pull request closed without merging**
