### PR TITLE
Hide Channel internal implementation methods

### PR DESCRIPTION
**Pull request by j8r**
Some methods should not be part of the public API, being internal implementation details.
Obviously, `receive_impl` and `receive_internal` are ones.

Return type annotations are also added for `receive` and `receive?` to have them in the API docs.

### CODE REVIEW

**Comment by waj** [comment]
Thanks! `Channel`'s interface and docs is needing some love. There are other methods I'd like to hide from docs. `select_impl` looks obvious, but I think we could hide anything related to `SelectAction` as well. @bcardiff what do you think?  Methods to create instances of `SelectAction` are not even public anyway and it's an implementation detail right now. Other structs like `SelectState` and `DeliveryState` should be marked as `:nodoc:` as well.

@j8r would you like to make those updates as part of this PR?

**Comment by j8r** [comment]
What about methods receiving `SelectAction` or `Indexabel(SelectAction)` as an argument?

**Comment by waj** [comment]
I think those should be `:nodoc:` as well. Those methods are called when a `select` statement is used.

**Comment by j8r** [comment]
I agree with you @waj , and it will definitely be good to to enhance Channel API before 1.0.0.

Also some methods/classes can be changed from `:nodoc:` to `private` - which is better.

**Comment by bcardiff** [comment]
I agree that the `self.non_blocking_select`/`self.select` can be made `:nodoc:`. They are used by the compiler so private will not work on them. But for the user the api should be to use the `select` statement. 

We are leaving doing send + receive on array as a public API but I think it's safe to do so.

I don't follow why you are changing `Channel` to `AChannel` though.

**Comment by j8r** [comment]
Sorry @bcardiff , I was testing something and pushed accidentally.

**Comment by waj** [comment]
@j8r this looks great. Could you please run `crystal tool format`?

Also, `def self.select(ops : Indexable(SelectAction), has_else)` can be removed now. It was deprecated for some versions but it's not needed anymore and it was always internal anyway.

**Comment by straight-shoota** [comment]
Thanks @j8r

**Pull request merged**
