### PR TITLE
Add `File.executable?` for Windows

### PR DESCRIPTION
**Pull request by nof1000**

### CODE REVIEW

**Comment by hugopl** [comment]
See `spec/std/file_spec.cr:135`, there are some tests tagged as pending there for this that should be unskipped.

**Comment by straight-shoota** [comment]
@nof1000 Looks good :+1: Would you care enabling the mentioned specs for this?

**Comment by straight-shoota** [comment]
@nof1000 Are you still up to continue with this?

**Review by straight-shoota — APPROVED** [review]

**Comment by HertzDevil** [comment]
This part can probably be enabled for Windows:

https://github.com/crystal-lang/crystal/blob/b10165ef37605ecb384b114e1062f558fd388a35/src/process/executable_path.cr#L40-L51

**Comment by oprypin** [comment]
@HertzDevil Enabled in what sense?
Are you referring to the part that says it's *\*not\* a temporary stub*?
Well, I'm saying again, that implementation is complete and passes https://github.com/crystal-lang/crystal/blob/master/spec/manual/find_executable_spec.cr

**Review by caspiano — APPROVED** [review]

**Review by sdogruyol — APPROVED** [review]
Thank you @nof1000 🙏

**Pull request merged**
