### PR TITLE
Remove LLVM update comments

### PR DESCRIPTION
**Pull request by sdogruyol**
SSIA :+1:

### CODE REVIEW

**Comment by asterite** [comment]
I don't know who wrote those llvm intrinsics, but they don't seem to exist. Plus I don't see what's the point of `Math.div(x, y)` when `x / y` does the same thing (and seems to be implemented the same way).

I think we should remove these instead.

**Comment by RX14** [comment]
To make them compile, I suspect you need to add the `.f32` etc suffix to match the other bindings below. Not sure what their use is either, looking at them more carefully.

**Comment by asterite** [comment]
I'm 99% sure they don't exist. At least they are not listed in the [reference](https://llvm.org/docs/LangRef.html).

**Comment by RX14** [comment]
Interesting, I wonder how these ended up here then.

**Comment by sdogruyol** [comment]
@asterite removed :+1:

**Pull request merged**
