### PR TITLE
[WIP] Add file:line information to backtraces

### PR DESCRIPTION
**Pull request by ysbaddaden**
This is an example of using `addr2line`/`atos` for exception backtraces (and caller). This is only tested on Linux (where `addr2line` is provided by `binutils). It doesn't fail when`addr2line`is unavailable but prints`??:?`. Untested on OSX but should work too.

This requires the debug mode because debug location tables must be added to the executable. It could be nice to always add the file:line information, whatever the debug mode. This is easy to enable and doesn't increases the executable much (roughly 5%) but the compiler specs fail badly.

I added skips for whatever relates to some files (exceptions) to filter the backtrace from internal implementation details.

We should eventually have an executable parser (eg. ELF parser) capable to extract this information itself. But this ~~is HARD work and~~ will have to be duplicated for each platform (**edit**: actually it's not hard).

```
0x000000000045d9ba: Kls#callee1 at /home/github/crystal/test_addr2line.cr:3
0x0000000000428d6e: callee3 at /home/github/crystal/test_addr2line.cr:13
0x000000000042501a: ??? at /home/github/crystal/test_addr2line.cr:15
0x0000000000428c49: main at /home/julien/.cache/crystal/macro62426064.cr:12
0x00007fccf1903f45: __libc_start_main at ??:0
0x0000000000424959: ??? at ??:?
0x0000000000000000: ??? at ??:0
```

### CODE REVIEW

**Comment by ysbaddaden** [comment]
Note to self: rebase to have 2 commits, one moving things around and the second adding g the addr2line support, so the diff will be better to follow!

**Comment by ysbaddaden** [comment]
Now with better commits that should be easier to read :)

**Comment by ysbaddaden** [comment]
And now with support for `atos` on OSX. All targets should now be supported.

I can't figure why CI fails so badly. I can't reproduce any of the errors :cry:

**Comment by david50407** [comment]
It seems a bug in libevent (searched from Google)

**Comment by mverzilli** [comment]
@ysbaddaden this is great! Is there any use case for keeping the hexadecimal (address?) at the beginning of the line?

**Comment by asterite** [comment]
I don't know why it fails, but if I run this snippet of code:

```cr
# foo.cr
raise "OH NO!"
```

```
$ bin/crystal foo.cr
OH NO! (Exception)
Unhandled exception in spawn:
end of file reached (IO::EOFError)
# hangs there...
```

So that probably means there's something missing in the implementation.,,

**Comment by ysbaddaden** [comment]
I guess the "open the file then pass addresses as stdin" is quirky, or it should catch some errno. I'll revert to a basic "pass addresses as CLI args".

@mverzily thats the raw symbols address. It's nit useful to most people, but maybe some would like it, so they hexdump the binary and follow what ASM is doing? I'm not sure.

**Comment by ysbaddaden** [comment]
The problem is actually within `Process.run` which raises an `IO::EOFError` whenever I run the `addr2line -e PROGRAM_NAME` command :cry:

**Comment by ysbaddaden** [comment]
@asterite it doesn't hang on Linux, but crashes in SignalHandler while receiving the `SIGCHLD` signal, because `@write_pipe` is closed (`addr2line` i was capable to find this thanks to `addr2line`). If I comment the line 67 then it hangs after the `IO::EOFError` with no backtrace.

**Comment by ysbaddaden** [comment]
I found the issue and it lies in `Event::SignalHandler`. The pipes are closed _before_ receiving the `SIGCHLD` signal (which raises the IO::EOFError and sometimes IO::Error exceptions in fibers, hence the `Unhandled exceptions` message). The signal is never reported back to Process so `Process#wait` hangs forever...

Dropping the `at_exit { Event::SignalHandler.close }` in [src/kernel.cr](https://github.com/crystal-lang/crystal/blob/master/src/kernel.cr#L169) fixes the issue, but I have no idea why the code was here I the first place since the pipe would be closed anyway when the process actually exits.

I wonder, thought, why the `at_exit` handlers are run before the exception is printed?

**Comment by ysbaddaden** [comment]
Closed in favor of #3303.

**Pull request closed without merging**
