### PR TITLE
Use `@[::Primitive]` and `@[::Flags]` where necessary

### PR DESCRIPTION
**Pull request by HertzDevil**
This addresses the following to-do:

https://github.com/crystal-lang/crystal/blob/4140116007e387096deffa2aa13223bb262fa357/src/compiler/crystal/semantic/semantic_visitor.cr#L465-L471

I haven't found out a proper way to detect ambiguous uses of `@[Primitive]`, because doing so triggers some very odd behaviour with `Number::Primitive`'s definition, and also because I kept getting error traces that contain the whole 16k lines of the macro expansion in `src/primitives.cr`. Since `@[Primitive]` isn't really meant to be used outside the standard library, it shouldn't hurt to drop its special name lookup rule as a breaking change.

For `@[Flags]` they were actually detected by a compiler warning that is more or less the following code:

```crystal
def lookup_annotation(ann)
  if ann.path.single?("Flags")
    type = @program.flags_annotation
    actual_type = lookup_type(ann.path)
    unless actual_type == type
      program.report_warning(ann, "#{ann.path} resolves to #{actual_type}, use @[::#{type}] to unambiguously refer to the top-level annotation")
    end
  end
  # ...
end
```

I didn't add it to this PR either, as the same issues with `@[Primitive]` could arise here as well for hierarchies involving types named `Flags`, however unlikely in the wild. If we cannot emit proper warnings here, then a compile-time flag like `-Dstrict_global_annotations` or `-Dno_global_annotations` seems the most viable option.

The following `::` is not strictly necessary if `struct Flags` is the first declaration of `Foo::Flags`, because the annotation is resolved before the struct declaration:

```crystal
module Foo
  @[::Flags]
  struct Flags; end
end
```

But for clarity these are also added.

### CODE REVIEW

**Comment by asterite** [comment]
Just to be clear: the `::` in this PR are "just in case"?

**Comment by straight-shoota** [comment]
This makes me I wish we had some kind of separate namespace for annotations. That was on the table when annotations were introduced (#6063), but left to decide later. Maybe now could be said later... 🤔

**Comment by straight-shoota** [comment]
And it definitely doesn't make sense for the annotation syntax to refer to a non-annotation type. So IMO `Int::Primitive` should not be possible to resolve for `@[Primitive]`. Of course there could still be some custom annotation `Foo::Primitive` that might conflict with the top-level annotation. So I suppose this change is probably good to be on the safe side.
What about other annotations, such as `@[Raises]` - which is directly below one of the `@[Primitive]` annotations.

**Comment by HertzDevil** [comment]
`@[Raises]` uses the usual name lookup rules, so any library would have already used `@[::Raises]` should it need to refer to the top-level annotation, in case a conflicting type / constant exists. If we don't define `Int32::Raises` or even `Object::Raises` then those annotations should continue to work.

**Review by straight-shoota — APPROVED** [review]

**Pull request merged**
