### PR TITLE
Fixes to bigint 32bit

### PR DESCRIPTION
**Pull request by akzhan**
Just another selection of 32bit fixes from #4675 with additions.

### CODE REVIEW

**Comment by bew** [comment]
Could you explain briefly what were the issues before this PR?

**Comment by akzhan** [comment]
@bew GMP arithmetics highly depends on `LibGMP::Long` and `LibGMP::ULong` types to provide fast paths with integers of supported types.

LibGMP built with 32bit Long/ULong on 32bit machines, otherwise 64bit (for now).

So we must take in care it's `sizeof` to provide correct behavior.

**Comment by asterite** [comment]
@akzhan Is there a spec that was failing in 32 bits? I ask because these changes, without accompanying specs, seem like they aren't doing anything.

**Comment by akzhan** [comment]
@asterite Just tested `BigInt.+` on current master (#4931):

```
Failures:
  1) BigInt adds
     Failure/Error: (5.to_big_i + Int64::MAX).should be > Int64::MAX.to_big_i
       Expected 4294967300_big_i to be > 9223372036854775807
     # spec/std/big/big_int_spec.cr:84
Finished in 11.78 seconds
5281 examples, 1 failures, 0 errors, 4 pending
Failed examples:
crystal spec spec/std/big/big_int_spec.cr:79 # BigInt adds
```

Will add this spec to this branch.

**Comment by RX14** [comment]
It seems like you're changing `+` `-` `*` `/` so there should be specs for all of those that beak on 32bit.

**Comment by asterite** [comment]
@akzhan Awesome! Thank you :-)

**Comment by akzhan** [comment]
Latest CI failure looks like not related to the code (memory access (signal 11) in compiler).

**Comment by sdogruyol** [comment]
LGTM :+1:

**Comment by RX14** [comment]
Please remove the changelog until we decide #4936.

**Comment by akzhan** [comment]
Done

**Pull request merged**
