### PR TITLE
Remove calls to `Pointer.new(Int)`

### PR DESCRIPTION
**Pull request by straight-shoota**
This is a preparatory step to dropping the overload `Pointer.new(Int)` (#14669). It replaces all calls to this overloads with explicit casts to `UInt64` at the call site, which ends up resolving to the main overload `Pointer.new(UInt64)`.

### CODE REVIEW

**Comment by HertzDevil** [comment]
Do you think this is fine for 32-bit targets or even AVR?

**Comment by straight-shoota** [comment]
Probably not. But it's not changing anything from the current status, so that's not really relevant to this PR. Everything that worked before this PR, should continue to work.

`Pointer.new(Int)` is implemented the same way:

https://github.com/crystal-lang/crystal/blob/897bd10f260dd540257348d0461b25d3fff97461/src/pointer.cr#L421-L423

This patch merely pulls out the cast `to_u64!` to the call size.

A portable implementation would be possible with a `uintptr_t` type (and appropriate cast methods).

**Comment by ysbaddaden** [comment]
The one advantage is that now these pointer constants will be actual consts, and no more wrapped in a Crystal::Once to be defined at runtime.

Though I'm wondering if we couldn't introduce a `Pointer::Size` type (currently set to UInt64) to prepare for the introduction of a target specific pointer size :thinking:

**Comment by straight-shoota** [comment]
@ysbaddaden Yes, I think we should do that. But it's a separate change. We can easily come back to update these definitions then. And there'll be a lot more which need this treatment.

**Comment by ysbaddaden** [comment]
Are you sure it's separate? Introducing a target specific Pointer::Size might be, but introducing a hardcoded Pointer::Size as UInt64 seems like it would fit just right in to me.

**Comment by straight-shoota** [comment]
No, introducing `Pointer::Size` even if as an alias to `UInt64` is a separate change. Now we could pull that up and merge it before this PR. But I see little benefit. They can be merged in any order.

**Review by ysbaddaden — APPROVED** [review]

**Pull request merged**
