### PR TITLE
Add minimal LLVM OrcV2 bindings

### PR DESCRIPTION
**Pull request by HertzDevil**
Resolves part of #14856 to the extent required by #14886.

### CODE REVIEW

**Comment by JarnaChao09** [comment]
I didn't realize there was a PR just for the LLVM bindings, leaving this here for completeness's sake

https://github.com/crystal-lang/crystal/pull/14886#discussion_r1712704733

**Comment by straight-shoota** [comment]
Would it be possible to add a couple of specs for this?

**Comment by HertzDevil** [comment]
What kind of specs, though? The few ones we have are mostly for our own code, rather than simple wrappers

**Comment by straight-shoota** [comment]
Dunno. This was really just a question.
Suppose we'll have some tests when we use these bindings in our existing tests with JIT.

**Review by straight-shoota — APPROVED** [review]

**Pull request merged**
