### PR TITLE
Remove parser transform for nil? in macro expressions

### LINKED ISSUE #10534: NilLiteral.nil? return false
Hi,

As the title says:
```Crystal
{% puts nil.nil? %}
```
> false

I am not sure this is a bug, `NilLiteral` is not `nil`, but it feels weird.

Tested with 0.36.1, as 1.0.0 is not yet available on playgrounds.

### PR DESCRIPTION
**Pull request by straight-shoota**
Resolves #10534

### CODE REVIEW

**Comment by asterite** [comment]
What if we handle that `nil?` call somehow and give a compile error saying "Calling this method will always return false".

**Comment by oprypin** [comment]
@asterite Both on the issue and in response to this, I want to point out that a method can accept different types. If you check for a nilable type, then with your suggestion it would become impossible to use that method with a non-nilable type.

**Comment by straight-shoota** [comment]
"Calling this method will always return false" implies this method actually exist. But in the macro language, it doesn't need to exist at all.
Now the error message just says `undefined macro method 'Type#nil?'`. Sure that could be enhanced with something like a recommendation to use `== nil` instead. But IMO that's not that important. The important part is to fix the bug that `nil?` doesn't error in the macro language but doesn't work either.

**Comment by asterite** [comment]
What will be the value of this?

```crystal
{% puts nil.nil? %}
```

**Comment by straight-shoota** [comment]
It doesn't compile. `undefined macro method 'NilLiteral#nil?'`

**Comment by oprypin** [comment]
Sorry, in my comment I was thinking of a different situation, it's not applicable here. I'll remove the comment

**Comment by asterite** [comment]
> Now the error message just says undefined macro method 'Type#nil?'

Oh, I thought this "Now" meant "now before this PR", but it seems to be "in this PR".

I think this is fine then 👍

**Comment by asterite** [comment]
Just note that if we ever decide to be able to add custom methods to AST nodes in macros, `nil?` will be a valid method call. And in that case I guess we'd like that to return... maybe `true` only for the `NilLiteral` and `Nop` nodes? Maybe that should be the current behavior?

**Comment by Blacksmoke16** [comment]
@asterite I'd suggest not having `.nil?` return `true` for `Nop` nodes.  I'd be more in favor of adding a dedicated `.nop?` method.  The main reason being it would be easy to do like `ivar.default_value.nil?` which would return `true` for both cases of there being a default with a value of `nil` and no default at all.

**Comment by asterite** [comment]
Oh, yeah, that makes sense. I guess for now we can go with this, and later on change it if needed, still in a backwards compatible way.

**Review by asterite — APPROVED** [review]

**Comment by Blacksmoke16** [comment]
While trivial to fix and didn't actually work this PR was technically a breaking change.  Had some code that was doing like `!ann[0].nil?` that no longer compiles.

**Comment by straight-shoota** [comment]
I would consider the fact that this code compiled as a compiler bug. It should've always been an error.

Fixing bugs can obviously break code that relied on the bug behaviour, but that shouldn't prevent fixing bugs, right? 😄

**Comment by asterite** [comment]
In my mind calling `.nil?` at the macro level should check if the node is a `NilLiteral` or `Nop`. I think that's more intuitive.

**Comment by straight-shoota** [comment]
Yeah, maybe we should add that. It's not strictly necessary though. And I'm not sure about combining `NilLiteral` and `Nop`. So this should really be a dedicated feature discussion.

**Pull request merged**
