### PR TITLE
Fix edge cases in code parser and stringifier (found by fuzzing)

### PR DESCRIPTION
**Pull request by oprypin**
https://github.com/oprypin/crystal-fuzzing

### CODE REVIEW

**Comment by oprypin** [comment]
It's failing though... Wasn't able to figure out ranges+newlines yet

**Comment by oprypin** [comment]
Excluded the failing commit, will get back to that one later.

**Comment by oprypin** [comment]
(in another PR)

**Comment by bcardiff** [comment]
Thanks! Can the PR be named in a way it reflects the impact and no the procedure so it’s more meaningful as a changelog entry in the future?

**Comment by oprypin** [comment]
The commits are meaningful changelog entries, the PR is indeed arbitrarily grouped by procedure.

**Comment by asterite** [comment]
I think Range and newline doesn't need to be supported because `1.. \n` is parsed as an endless range now.

**Comment by oprypin** [comment]
Alright, then I will not attempt to cover it. Seems consistent with the rest of the language, things like 
```
(1
+2) == 2
```
But still doing it in a separate PR.
https://github.com/crystal-lang/crystal/pull/7888

**Comment by asterite** [comment]
Yes, now I'm actually not sure, probably endless range only makes sense when `)` comes afterwards.

**Comment by oprypin** [comment]
Well then, good that I split out the controversial thing.
This PR is still good though! :D

**Comment by straight-shoota** [comment]
Thank you @oprypin !

**Pull request merged**
