### PR TITLE
HTTP::Response: set default cookie domain

### PR DESCRIPTION
**Pull request by icyleaf**
Support [rfc2665#5.2.3](https://tools.ietf.org/html/rfc6265#section-5.2.3):

1. If domain attribute is empty, set request domain
2. Support the first character of the attribute-value string is "."
3. Convert the cookie-domain to lower case

### CODE REVIEW

**Comment by sdogruyol** [comment]
Ping :+1:

**Comment by icyleaf** [comment]
Ping?

It can not manage all request cookies for each domain if response was not set the domain, and it cant be use same cookies with same domain, or implement like [requests.Session](http://docs.python-requests.org/en/master/user/advanced/)

**Comment by asterite** [comment]
Can this be done without modifying the `Response` object? I don't understand why we need to add a `domain` attribute.

For example I can't see such attribute in [Ruby's Net::HTTPResponse](https://ruby-doc.org/stdlib-2.4.1/libdoc/net/http/rdoc/Net/HTTPResponse.html). I also can't see it in [Go's http](https://golang.org/pkg/net/http/).

Maybe there's a different, more unobtrusive way to accomplish this?

**Comment by asterite** [comment]
@icyleaf It would be nice to know why you closed this (how you solved it)

**Comment by icyleaf** [comment]
I fix it in my http client code here: https://github.com/icyleaf/halite/blob/master/src/halite/response.cr#L29

**Pull request closed without merging**
