### PR TITLE
Expand Int#to_s optimization from 0..1 to 0..9

### PR DESCRIPTION
**Pull request by Sija**
Why cover just these 2 cases if we can cover them all?

### CODE REVIEW

**Comment by RX14** [comment]
...because you can't? 2 in binary is `01`, not `2`.

**Comment by Sija** [comment]
@RX14 ah, forgot about binary, :facepalm:

**Comment by Sija** [comment]
@RX14 hmm, aren't octal numbers are lexed and turned into decimals before they reach `Int#to_s`?

https://github.com/crystal-lang/crystal/blob/49d722c16f25706c0469dd437a19ec0f84dbbe2a/src/compiler/crystal/syntax/lexer.cr#L1570

**Comment by RX14** [comment]
@Sija what? this has nothing to do with the compiler.

**Pull request closed without merging**
