### PR TITLE
Compiler: fix extend from generic types

### LINKED ISSUE #7167: Extending a module doesn't work for generics
This works fine (https://carc.in/#/r/5qsl):

```crystal
module Foo
  def foo
  end
end

class String
  extend Foo
end

pp! String.foo # => nil
```

But this fails (https://carc.in/#/r/5qsm):

```crystal
module Foo
  def foo
  end
end

class Array(T)
  extend Foo
end

pp! Array(Int32).foo
# undefined method 'foo' for Array(Int32).class
```

And also this (https://carc.in/#/r/5qsn):

```crystal
module Foo(T)
  def foo
  end
end

class Array(T)
  extend Foo(T)
end

pp! Array(Int32).foo
# undefined method 'foo' for Array(Int32).class
```

### PR DESCRIPTION
**Pull request by asterite**
Fixes #7167

### CODE REVIEW

**Comment by wontruefree** [comment]
I don't know if this belongs in this PR but why would parents return a `nil`.  Seems like if all classes return an array of `Types` and you call `parents` on a class will no parents you should get an empty array.

**Comment by asterite** [comment]
@wontruefree It's a good observation. I think I did it like that to avoid creating an empty array. But it probably makes sense to return an empty array in the default case because that will never be called, except for Object. I'll try it later (in a separate PR).

**Comment by asterite** [comment]
Actually a module has no parents by default. I don't think I'll make this change for now.

**Comment by wontruefree** [comment]
sounds good.  I was just making an observation.

**Pull request merged**
