### PR TITLE
Let `p` use inspect, `pp` just pretty print values, and introduce `p!` and `pp!` which also show the expression to print

### LINKED ISSUE #6019: Pretty printing et al.
Right now we have:

```
p value # pretty print value
pp value # pretty print value while also showing what are you printing
```

I think it's a bit confusing. In Ruby we have:

```
p value # inspect value
pp value # pretty print value
# (and there's no way to pretty print while also showing what are you printing)
```

I propose we:
- change `p` to the old meaning of "inspect"
- change `pp` to just pretty print a value
- add two new methods to inspect or pretty print a value and show what you are inspecting (like the current `pp`, but one using `inspect`, and one using `pretty print`)

What do you think? I have no idea for the names.

My main issue with `pp` is that it's both "pretty print" and "show what we are pretty printing". And somtimes just `p` leads to a lot of lines being printed, while `puts value.inspect` (so Ruby's `p`) is sometimes more clear.

Thoughts?

### PR DESCRIPTION
**Pull request by asterite**
Fixes #6019

### CODE REVIEW

**Comment by oprypin** [comment]
Don't forget examples
https://github.com/crystal-lang/crystal/search?q=pp&type=Code

**Comment by asterite** [comment]
If examples used `pp` and now the behaviour changes, it not a big deal. In fact, in the two occurrences I found it only receives one argument, so the printed expression is really not needed in the output (and this is one of the things that couldn't _easily_ be done before this PR).

**Comment by oprypin** [comment]
I just mean that they should be updated.

**Comment by oprypin** [comment]
I just mean that they should be updated, because their comments show output incorrectly.

**Comment by j8r** [comment]
Please @asterite use a letter instead of `!`, we have the choice in the alphabet (like `i`).

When I see a bang for me the method needs to be used we caution, because it has a special behavior. This isn't the case here.

**Comment by oprypin** [comment]
I dislike having 4 different methods, but 4 methods is what was agreed on in the issue.
Among the ways to name them, the one in this PR is my favorite, so I begrudgingly approve.

**Pull request merged**
