### PR TITLE
Explain 'crystal tool expand' in crystal(1) man page

### PR DESCRIPTION
**Pull request by MakeNowJust**
I'm sad 😢

### CODE REVIEW

**Comment by mverzilli** [comment]
No need to be sad! :)

**Comment by MakeNowJust** [comment]
Thank you!

**Comment by rdp** [comment]
No mention in the list of tools? "Run a tool. The available tools are: context, format, hierarchy, implementations, and types." FWIW :)

**Comment by mverzilli** [comment]
Hi @rdp! This pull request is already merged, so your suggestion is very likely to go through the cracks. Please either open an issue or a PR in cases like this. Thank you!

**Pull request merged**
