### PR TITLE
Add JSON/YAML serialization to `URI`

### PR DESCRIPTION
**Pull request by straight-shoota**
URI can be trivially serialized to a string in both JSON and YAML, so this adds the necessary conversion methods.

Note that this does not make `require "json"`/`require "yaml"` mandatory when using `require "uri"`. The methods just won't work unless JSON/YAML are also required.

### CODE REVIEW

**Comment by asterite** [comment]
I think these should live in "uri/json" and "uri/yaml" respectively.

It doesn't break now, but nothing prevents us in the future from type-checking the arguments even before you call the methods (a bit more reliable) and then it will break.

**Comment by straight-shoota** [comment]
Can we delay this until it becomes necessary if ever?

I know we do the same thing for other types, but it just feels like an unneccesary burdon on usability if you have to require these simple converter methods explicitly.

**Review by sdogruyol — APPROVED** [review]
Thank you @straight-shoota 🙏

**Review by caspiano — APPROVED** [review]
Would love this in 1.0.0 🥰

**Comment by beta-ziliani** [comment]
I am with Ary. I think we must keep it consistent with the rest of the lib. We can discuss later a refactor here and there.

**Review by jhass — APPROVED** [review]

**Pull request merged**
