### PR TITLE
Accept Connection="keep-alive, Upgrade" header in websocket handler

### PR DESCRIPTION
**Pull request by bcardiff**
Firefox is unable to establish websockets connection.
This is because the Connection header Firefox send "keep-alive, Upgrade", while Chrome will just send "Upgrade".

This PR fix the issue.
Would we prefer other check than `.includes?` ? The same method is used to check for "deflate" in `deflate_handler.cr`

Related source: https://support.mozilla.org/en-US/questions/1078689

cc: @luislavena ;-)

### CODE REVIEW

**Comment by asterite** [comment]
I was going to go with this solution too, but reading the HTTP RFC it seems a header can contain multiple comma separated values.

I'll coment more tomorrow, but I think there's a better, more correct solution here.

**Comment by asterite** [comment]
However, it seems that comma separated values depend on the header. For example the Connection header allows such behavior. Gotta love standards.

So, my vote is to split the header value by comma. We should do the same in other parts of the code dealing with that specific header.

**Comment by asterite** [comment]
Also note that this PR doesn't fix the problem. Firefox is sending a single header "Connection: keep-alive, Upgrade", so `includes?` won't find it, we have to split the value by commas, and strip them.

**Comment by bcardiff** [comment]
I change the implementation to use regex with word boundary both in websocket and in deflate.

**Comment by asterite** [comment]
@bcardiff Maybe add a spec to check that this fixes the problem with Firefox? :smile:

**Comment by luislavena** [comment]
> I changed the implementation to use regex with word boundary both in websocket and in deflate.

Wouldn't that rely on PCRE which has proven to be slower than `includes?`?

**Comment by asterite** [comment]
The problem is if the header is like "Connection: Upgradefoo", with `includes?` it will match it. Another way is to split each value by commas and strip, and then compare with Upgrade. 

Just tried this:

```crystal
require "benchmark"

string = ARGV[0]? || "keep-alive, Upgrade"

Benchmark.ips do |x|
  x.report("split") { string.split(',').any? { |s| s.strip == "Upgrade" } }
  x.report("regex") { string =~ /\bUpgrade\b/ }
end
```

Output:

```
split   1.95M (± 1.13%)  1.56× slower
regex   3.04M (± 0.93%)       fastest
```

So regex seems to be fine in this case.

**Comment by luislavena** [comment]
@asterite wasn't sure, thanks for the confirmation (remembered we had perf issues with URI parse, but that indeed was a more complex Regex).

:shipit: :wink:

**Comment by bcardiff** [comment]
Well we could do this https://gist.github.com/bcardiff/f3930c4797f52905977a

**Comment by bcardiff** [comment]
There i get rid of the regex and reach almost original performance again but with a more correct behavior.

It plays nicer with multiple entry headers since it will avoid concatenation.

```
$ ./bin/crystal samples/match.cr --release
Single header, single value

     includes  18.86M (± 4.32%)       fastest
includes_word  18.31M (± 4.33%)  1.03× slower
  split strip   3.59M (± 1.38%)  5.25× slower
        match   2.93M (± 2.56%)  6.43× slower


Single header, multiple values

     includes   7.02M (± 3.85%)       fastest
includes_word   6.79M (± 3.04%)  1.03× slower
  split strip   1.97M (± 1.01%)  3.56× slower
        match   2.69M (± 1.63%)  2.61× slower


Multiple header

     includes   2.35M (± 0.86%)  4.83× slower
includes_word  11.36M (± 4.98%)       fastest
  split strip   1.34M (± 2.11%)  8.50× slower
        match   1.62M (± 2.02%)  7.01× slower
```

```crystal
require "http"
require "benchmark"

def d(s)
  # avoid llvm optimizations
  ARGV[0]? || s
end

def find_upgrade(headers)
  puts ""
  word = d "Upgrade"
  Benchmark.ips do |x|
    x.report("includes") {
      headers["Connection"]?.try &.includes? word # this is a buggy implementation
    }
    x.report("includes_word") {
      headers.includes_word? "Connection", word
    }
    x.report("split strip") {
      headers["Connection"]?.try &.split(',').any? { |s| s.strip == word }
    }
    x.report("match") {
      headers["Connection"] =~ /\bUpgrade\b/
    }
  end
  puts ""
  puts ""
end

puts "Single header, single value"
find_upgrade HTTP::Headers{"Connection": d("Upgrade")}

puts "Single header, multiple values"
find_upgrade HTTP::Headers{"Connection": d("keep-alive, Upgrade")}

puts "Multiple header"
find_upgrade HTTP::Headers.new.tap { |header| header.add "Connection", d("keep-alive"); header.add "Connection", d("Upgrade") }
```

**Pull request merged**
