### PR TITLE
Improve WebSocket handshake validation (fixed)

### PR DESCRIPTION
**Pull request by straight-shoota**
Fixed #5327 to the changes to HTTP::Server API from #5776

### CODE REVIEW

**Comment by straight-shoota** [comment]
@RX14 Any idea about the broken pipe error in the specs? I can't reproduce it locally.

**Comment by RX14** [comment]
It's a linux thing so you'll have to reproduce it on linux

**Comment by straight-shoota** [comment]
I know 😁

It seems the error doesn't reproduce when this spec is run alone. And it looks very much similar to the error in #5958, probably related to `HTTP::Server#close`...

**Comment by straight-shoota** [comment]
It is indeed the same as the error discovered in #5958. For some reason on Linux there seems to be some strange behaviour when `HTTP::Server#close` closes the socket servers.
For now I'll disable closing the server in the specs, then it should be all green. It's certainly not optimal, but the error with `HTTP::Server` needs to be fixed independently from this.

**Pull request merged**
