### PR TITLE
Exhaustive case near and far

### PR DESCRIPTION
**Pull request by Sija**
This PR aims to be a small followup to #8424, it:

- Uses exhaustive `case` statements in few places throughout the stdlib
- Drops empty `else # go on / ignore / nothing to do` branches
- Removes deprecated `Log::Severity::Warning`

### CODE REVIEW

**Comment by Sija** [comment]
I was thinking about opening another PR just for dropping `Log::Severity::Warning`, but it's so small that I'm not sure it's worth the hassle... I can do it if preferred though.

**Comment by Sija** [comment]
Bump

**Comment by Sija** [comment]
Ping /cc @asterite @bcardiff @straight-shoota

**Comment by Sija** [comment]
Second approval any1? /cc @bcardiff @straight-shoota @waj @jhass

**Comment by Sija** [comment]
Yo, could this be merged or sth?

**Comment by asterite** [comment]
It needs a second review.

**Comment by Sija** [comment]
@asterite so when this will happen?

**Comment by asterite** [comment]
I don't know. But it doesn't matter, because until 1.0 is released whether this PR is merged or not doesn't change anything. In fact, even after it's merged it dosent produce visible changes.

**Comment by Sija** [comment]
@asterite That's the point, this PR doesn't bring any substantial changes so why does it takes almost 2 months already to get it through?

**Comment by Sija** [comment]
Is there anything holding this back? /cc @straight-shoota @jhass @bcardiff @waj

**Review by straight-shoota — APPROVED** [review]

**Pull request merged**
