### PR TITLE
Changelog for 1.11.2

### PR DESCRIPTION
**Pull request by straight-shoota**
Preview: https://github.com/straight-shoota/crystal/blob/changelog/1.11.2/CHANGELOG.md

### CODE REVIEW

**Comment by HertzDevil** [comment]
I suggest adding #14186 and #14221 since segfaults on 1.11.1 give `0x(???)` in the stack trace

**Comment by straight-shoota** [comment]
@HertzDevil Has this changed from 1.10?

**Comment by HertzDevil** [comment]
1.10.1: https://play.crystal-lang.org/#/r/gd8i
1.11.1: https://play.crystal-lang.org/#/r/gd8j

**Comment by straight-shoota** [comment]
I cherry-picked https://github.com/crystal-lang/crystal/pull/14186 and https://github.com/crystal-lang/crystal/pull/14221 to the release branch.

**Review by beta-ziliani — APPROVED** [review]

**Pull request merged**
