### PR TITLE
Remove IO.select

### PR DESCRIPTION
**Pull request by RX14**
IO.select frequently confuses users by blocking all fibers, and can easily be replaced by blocking CSP programs.

### CODE REVIEW

**Comment by sdogruyol** [comment]
I've bitten a few time by this too. It's confusing and hard to explain to newcomers 😭

**Comment by bararchy** [comment]
And above all unneeded with how Crystal works (non blocking, event loop, etc..)

**Comment by ysbaddaden** [comment]
Granted. This is long held legacy from before IO got evented. We now use better techniques (eg: epoll, kpoll) to automatically switch contexts as required.

Anybody coming here and lacking support for `IO.select`, you should `spawn` fibers to read/write to each IO, and let Crystal switch fibers as available/required. The following example will start a TCP and a UNIX servers, accepting requests concurrently (not blocking each other), then handle each request concurrently, too (not blocking servers from accepting other requests, nor blocking other requests):

```crystal
def server_loop(server)
  loop do
    spawn handle_client(server.accept)
  end
end

spawn do
  TCPServer.open(9292) { |server| server_loop(server) }
end

spawn do
  UNIXServer.open("/tmp/app.sock") { |server| server_loop(server) }
end

sleep
```

**Comment by Singond** [comment]
Does the above apply to one object shared between fibers? For example, say I have a `TCPSocket` open, and want to use one fiber for writing and another fiber for reading. Is it safe to simply pass the socket to both fibers? I guess this is all right when both fibers run on the same thread, but how about multithreading?

```crystal
require "socket"

sock = TCPSocket.new "example.org", 80

spawn do
  sock << "request\n"
end

spawn do
  while true
    puts sock.gets
  end
end

sleep
```

**Comment by straight-shoota** [comment]
Yes, that should be perfectly fine as long as reading and writing are clearly separated.
If you read/write concurrently on the same socket though, you might experience interference, even in a single thread. So this should be avoided.

**Comment by Singond** [comment]
All right, thanks for the clarification. Crystal really makes this kind of things easy.

By the way, it took me some time to find this thread when searching for the answer. Would it be possible to add this information into the official documentation? It might be helpful to some.

**Comment by zw963** [comment]
I create a new thread in form for discuss more deeper real-life use cases.

 https://forum.crystal-lang.org/t/need-document-for-how-porting-io-select-in-ruby-crystal/5374

**Pull request merged**
