### PR TITLE
[WIP] try to reproduce bug in 32bit

### PR DESCRIPTION
**Pull request by akzhan**
Just use Travis CI 32bit infrastructure to reproduce bug

### CODE REVIEW

**Comment by akzhan** [comment]
See https://travis-ci.org/crystal-lang/crystal/jobs/272416362 /cc @asterite

**Comment by akzhan** [comment]
https://travis-ci.org/crystal-lang/crystal/jobs/272483253 shows typical 32bit errors on old master branch.

Closing.

**Comment by RX14** [comment]
Next time can you please enable Travis on a fork of crystal and test there?

**Comment by akzhan** [comment]
@RX14 thanks, i simply never did this before (both travis on forks or 32bit builds).

**Pull request closed without merging**
