### PR TITLE
Re-introduce canonical URL for docs generator

### PR DESCRIPTION
**Pull request by straight-shoota**
The previous attempt in #8348 to use sitemaps to indicate preference of latest version over older ones to search engines doesn't seem to work. Instead, the solution applied for similar situations is canonical links. This mostly reinstates the canonical link behaviour prior to #8348

Hopefully finally resolves most of #5952

### CODE REVIEW

**Review by jhass — APPROVED** [review]
Code wise this seems fine. I cannot comment much on effectiveness or integration to our infrastructure.

**Comment by straight-shoota** [comment]
I don't think anyone can really tell. But it seems to be what most others are doing. And the alternative doesn't seem to work.

**Review by bcardiff — APPROVED** [review]

**Comment by bcardiff** [comment]
We need to tweak the Makefile docs target or change the DOCS_OPTIONS env variable in bin/ci and in distribution-scripts after 1.0 then.

**Comment by straight-shoota** [comment]
Yes, I'll do that as soon as this gets merged.

**Comment by straight-shoota** [comment]
I guess the bin/ci change could've been included here directly. But here it is: #10007 and crystal-lang/distribution-scripts#77

**Pull request merged**
