### PR TITLE
Update CI to use 0.30.1

### PR DESCRIPTION
**Pull request by bcardiff**

### CODE REVIEW

**Comment by bcardiff** [comment]
😢 oh, dear. 

> Assertion failed: (getActiveBits() <= 64 && "Too many bits for uint64_t"), function getZExtValue, file /var/cache/omnibus/src/llvm/llvm-6.0.1.src/include/llvm/ADT/APInt.h, line 1545.

**Comment by asterite** [comment]
Strange, it works fine on my machine with the same LLVM version (6.0.1).

I'm almost sure it's related to 128 bit integers. The error seem to happen in some LLVM code that uses big integers (and I assume they use that for i128, but I'm not sure).

It should be easy to debug (if reproducible) with gdb, when the crash happens you'll see what in our code caused it.

**Comment by asterite** [comment]
Another thing: it seems in Mac CI, and also while developing locally in Mac, LLVM 6 is used and not LLVM 8. The reason is that LLVM comes with OSX:

```
$ which llvm-config
/usr/local/bin/llvm-config
$ llvm-config --version
6.0.1
```

LLVM 8 is here:

```
/usr/local/opt/llvm/bin/llvm-config
```

`brew` recommends doing `export PATH="/usr/local/opt/llvm/bin:$PATH"` so it can find it.

So maybe one way to fix it would be to add `/usr/local/opt/llvm/bin/llvm-config` to the list of locations, before the default `llvm-config`. I don't know... Or just exporting that PATH in the Makefile.

**Comment by bcardiff** [comment]
@asterite the thing you are pointing it regarding the llvm used, are you saying it considering that these scripts in the build are using the omnibus package declaration? or you are comparing your local dev that is using llvm@8 due to homebrew?

**Comment by asterite** [comment]
I'm not sure I understand the question, but when I run `make crystal` locally it's using LLVM 6.0.1 instead of LLVM 8 (which I have in homebrew). And in CI it's also using LLVM 6.0.1, but I thought it would be using LLVM 8 by now.

**Comment by bcardiff** [comment]
The package built via omnibus is was bumped in this release from 3.9.1 to 6.0.1. 6.0.1 was built by circle ci recently in https://github.com/crystal-lang/distribution-scripts/pull/41/files and uploaded in the S3 where 3.9.1 was located since the beginning of times.

homebrew was bumped from 6.0.1 to 8.0.0.

**Comment by asterite** [comment]
Oh, sorry, I got confused. It seems CI is building crystal from source for some reason... I don't know how the build process is to I'll be silent from now on 😊

**Comment by bcardiff** [comment]
Damn, I thought you were on to something 🐇 😄

**Comment by asterite** [comment]
😄 

I guess my question is: why CI installs Crystal like that instead of using homebrew?

**Comment by bcardiff** [comment]
That's because we are (and should be) independent of brew cycle. Maybe the new custom llvm 6.0.1 package has something wrong. I'm still investigating. It seems to happen on release builds (even without omnibus in the middle). 🚧

**Comment by bcardiff** [comment]
It seems to explode in `GlobalOptLegacyPass` with something that returns a constant with size of 127 bits...

```
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
  * frame #0: 0x00007fff68e542c6 libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007fff68f0fbf1 libsystem_pthread.dylib`pthread_kill + 284
    frame #2: 0x00007fff68dbe6a6 libsystem_c.dylib`abort + 127
    frame #3: 0x00007fff68d8720d libsystem_c.dylib`__assert_rtn + 324
    frame #4: 0x000000010d96ba54 crystal`llvm::APInt::getZExtValue() const + 76
    frame #5: 0x000000010d6c6923 crystal`processInternalGlobal(llvm::GlobalVariable*, llvm::GlobalStatus const&, llvm::TargetLibraryInfo*, llvm::function_ref<llvm::DominatorTree& (llvm::Function&)>) + 9378
    frame #6: 0x000000010d6c43d8 crystal`processGlobal(llvm::GlobalValue&, llvm::TargetLibraryInfo*, llvm::function_ref<llvm::DominatorTree& (llvm::Function&)>) + 273
    frame #7: 0x000000010d6c3772 crystal`optimizeGlobalsInModule(llvm::Module&, llvm::DataLayout const&, llvm::TargetLibraryInfo*, llvm::function_ref<llvm::DominatorTree& (llvm::Function&)>) + 1656
    frame #8: 0x000000010d6cd984 crystal`(anonymous namespace)::GlobalOptLegacyPass::runOnModule(llvm::Module&) + 80
    frame #9: 0x000000010ddc63ea crystal`llvm::legacy::PassManagerImpl::run(llvm::Module&) + 618
    frame #10: 0x000000010dd5daf3 crystal`LLVMRunPassManager + 14
    frame #11: 0x000000010cc925f1 crystal`*Crystal::Compiler::CompilationUnit#compile:(LLVM::Module | Nil) + 2721
    frame #12: 0x000000010cc06df2 crystal`*Crystal::Compiler#codegen<Crystal::Program, Crystal::ASTNode+, Array(Crystal::Compiler::Source), String>:(Tuple(Array(Crystal::Compiler::CompilationUnit), Array(String)) | Nil) + 7506
    frame #13: 0x000000010cfb4607 crystal`*Crystal::Compiler#compile<Array(Crystal::Compiler::Source), String>:Crystal::Compiler::Result + 119
    frame #14: 0x000000010cf9e502 crystal`*Crystal::Command#run:(Bool | Crystal::Compiler::Result | Nil) + 1090
    frame #15: 0x000000010c6d37db crystal`__crystal_main + 14603
    frame #16: 0x000000010c6d82a8 crystal`main + 56
    frame #17: 0x00007fff68d193d5 libdyld.dylib`start + 1
    frame #18: 0x00007fff68d193d5 libdyld.dylib`start + 1
```

<details><summary>how to get the backtrace?</summary>
<p>

```
make clean deps
mkdir -p .build
cp /path/to/crystal-0.30.0-1/embedded/bin/crystal .build/crystal
sleep 2
touch src/compiler/crystal.cr

export CRYSTAL_CONFIG_LIBRARY_PATH="/path/to/crystal-0.30.0-1/embedded/lib"
export CRYSTAL_CONFIG_BUILD_COMMIT="4f8637f18"

lldb
(lldb) break set -E C++

./bin/crystal build -D preview_overflow -D compiler_rt --release  -o .build/crystal-fail src/compiler/crystal.cr -D without_openssl -D without_zlib

(lldb) process attach --pid 12801
... wait for it ...

(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
```

</p>
</details>

**Comment by asterite** [comment]
Oh, the stack trace points to `Crystal::Compiler::CompilationUnit#compile`, so it's when we are calling LLVM to compile the module... I'm almost sure it's a bug in LLVM.

**Comment by bcardiff** [comment]
But it’s odd. We’ve been using llvm 6 via brew and compiling the compiler in release mode every now and then locally.

Either the code now emits big constants somewhere. Or which passes are executed depends on how llvm was compiled. Or probably something else...

**Comment by bcardiff** [comment]
Status update:

llvm@6 in hombrew was always built with `LLVM_ENABLE_ASSERTIONS=OFF` (Defaults to ON if and only if CMAKE_BUILD_TYPE is Debug).
The llvm@6 we built in distribution-scripts has `LLVM_ENABLE_ASSERTIONS=ON` because we preferred that way since the beggings of time.
The issue is still present in llvm 8 (when `LLVM_ENABLE_ASSERTIONS=ON`).

The issue seems to be an llvm bug but since usually `LLVM_ENABLE_ASSERTIONS=OFF`, nobody notices/cares.

🚧🚧 still working 🚧🚧

**Comment by bcardiff** [comment]
This is the LLVM bug https://bugs.llvm.org/show_bug.cgi?id=42932

A workaround is on its way, but I am reaching another failing assert, but since it's scoped to debug information it is not a stopper issue.

<details>
<summary>backtrace of assert failing in debug info</summary>
<p>

```
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
  * frame #0: 0x00007fff68e542c6 libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007fff68f0fbf1 libsystem_pthread.dylib`pthread_kill + 284
    frame #2: 0x00007fff68dbe6a6 libsystem_c.dylib`abort + 127
    frame #3: 0x00007fff68d8720d libsystem_c.dylib`__assert_rtn + 324
    frame #4: 0x00000001053b7b09 crystal`llvm::LexicalScopes::getOrCreateRegularScope(llvm::DILocalScope const*) + 397
    frame #5: 0x00000001053b72bd crystal`llvm::LexicalScopes::extractLexicalScopes(llvm::SmallVectorImpl<std::__1::pair<llvm::MachineInstr const*, llvm::MachineInstr const*> >&, llvm::DenseMap<llvm::MachineInstr const*, llvm::LexicalScope*, llvm::DenseMapInfo<llvm::MachineInstr const*>, llvm::detail::DenseMapPair<llvm::MachineInstr const*, llvm::LexicalScope*> >&) + 337
    frame #6: 0x00000001053b70dc crystal`llvm::LexicalScopes::initialize(llvm::MachineFunction const&) + 124
    frame #7: 0x00000001053bf2e2 crystal`llvm::LiveDebugVariables::runOnMachineFunction(llvm::MachineFunction&) + 3200
    frame #8: 0x000000010542d5e9 crystal`llvm::MachineFunctionPass::runOnFunction(llvm::Function&) + 95
    frame #9: 0x0000000105d716af crystal`llvm::FPPassManager::runOnFunction(llvm::Function&) + 295
    frame #10: 0x0000000105d718dd crystal`llvm::FPPassManager::runOnModule(llvm::Module&) + 57
    frame #11: 0x0000000105d71cba crystal`llvm::legacy::PassManagerImpl::run(llvm::Module&) + 624
    frame #12: 0x000000010559c760 crystal`LLVMTargetMachineEmit(LLVMOpaqueTargetMachine*, LLVMOpaqueModule*, llvm::raw_pwrite_stream&, LLVMCodeGenFileType, char**) + 217
    frame #13: 0x000000010559c604 crystal`LLVMTargetMachineEmitToFile + 152
    frame #14: 0x000000010486d57d crystal`*Crystal::Compiler::CompilationUnit#compile:(LLVM::Module | Nil) + 861
    frame #15: 0x00000001047e086d crystal`*Crystal::Compiler#codegen<Crystal::Program, Crystal::ASTNode+, Array(Crystal::Compiler::Source), String>:(Tuple(Array(Crystal::Compiler::CompilationUnit), Array(String)) | Nil) + 6893
    frame #16: 0x0000000104b9c087 crystal`*Crystal::Compiler#compile<Array(Crystal::Compiler::Source), String>:Crystal::Compiler::Result + 119
    frame #17: 0x0000000104b86d8f crystal`*Crystal::Command#run:(Bool | Crystal::Compiler::Result | Nil) + 655
    frame #18: 0x00000001042b9e68 crystal`main + 56
    frame #19: 0x00007fff68d193d5 libdyld.dylib`start + 1
    frame #20: 0x00007fff68d193d5 libdyld.dylib`start + 1
```

</p>
</details>

A `0.30.0-2` darwin package will be released with llvm 3.9.1. And the workaround to use llvm 6 with assertions will come in the next release (0.31.0 or maybe 0.30.1). That way the CI will be able to move forward.

**Comment by bcardiff** [comment]
PR updated to build 0.31-dev against 0.30.1. Once build pass and merged the PRs to merge can be rebased on top of master. Hopefully, the 32 bits CI will fail less often 🤞.

**Pull request merged**
