### PR TITLE
Codegen: don't assign yield exp to underscore block arguments

### LINKED ISSUE #4711: Multiple block arguments of same name crashes compiler if values are of different type
Hello,

While working on something, I built a yielding-method, and later used it. While doing so, I didn't care about all block arguments, so intuitively, I named them `_`. Those two arguments are of different types, which crashes the compiler.

**Example code**

```crystal
def foo
  yield('0', 0)
end
foo{|_, _| } # First _ would be a Char, second a Int32
```

**Expected behaviour**

I expected the compiler to either:

* Note the `_` name and just throw the value away
* OR tell me that `_` is already of type `Char` or `Int32`, and can't take another type

**Compiler output**

```
BUG: trying to assign Int32 <- Char
0x7a1abb: *CallStack::unwind:Array(Pointer(Void)) at ??
0x1476e23: assign_distinct at .../crystal/src/compiler/crystal/codegen/cast.cr 276:5
0x1472502: assign at .../crystal/src/compiler/crystal/codegen/cast.cr 85:7
0x14b5efe: visit at .../crystal/src/compiler/crystal/codegen/codegen.cr 1410:17
0xb5a7ad: accept at .../crystal/src/compiler/crystal/syntax/visitor.cr 27:12
0x147d231: accept at .../crystal/src/compiler/crystal/codegen/codegen.cr 1986:7
0x149c56e: codegen_call_with_block at .../crystal/src/compiler/crystal/codegen/call.cr 284:13
0x14949cd: visit at .../crystal/src/compiler/crystal/codegen/call.cr 32:9
0xb5a82f: accept at .../crystal/src/compiler/crystal/syntax/visitor.cr 27:12
0x147d231: accept at .../crystal/src/compiler/crystal/codegen/codegen.cr 1986:7
0x148c489: visit at .../crystal/src/compiler/crystal/codegen/codegen.cr 574:9
0xb59b12: accept at .../crystal/src/compiler/crystal/syntax/visitor.cr 27:12
0x905dcf: codegen at .../crystal/src/compiler/crystal/codegen/codegen.cr 65:7
0x905d58: codegen:debug:single_module:expose_crystal_main at .../crystal/src/compiler/crystal/codegen/codegen.cr 63:5
0x13f5783: codegen at .../crystal/src/compiler/crystal/compiler.cr 22:7
0x13f7ef3: compile at .../crystal/src/compiler/crystal/compiler.cr 139:16
0x15377d9: compile at .../crystal/src/compiler/crystal/command.cr 264:7
0x8c97d2: run_command at .../crystal/src/compiler/crystal/command.cr 194:14
0x8c5b53: run at .../crystal/src/compiler/crystal/command.cr 105:11
0x8c517b: run at .../crystal/src/compiler/crystal/command.cr 49:5
0x8c513b: run at .../crystal/src/compiler/crystal/command.cr 48:3
0x77128b: __crystal_main at .../crystal/src/compiler/crystal.cr 8:1
0x785ed9: main at .../crystal/src/main.cr 12:15
0x7f894bc2843a: __libc_start_main at ??
0x7703aa: _start at ??
0x0: ??? at ??
```

This happens on `master` at 944c0837ccc338d38ba3008171bd6e2a9959cc9c down to at least version `0.23.0`.

Cya

### PR DESCRIPTION
**Pull request by asterite**
Fixes #4711

### CODE REVIEW

**Comment by RX14** [comment]
I guess using `_` variables was valid before, so this is a feature and a breaking change, instead of a bugfix?

**Comment by asterite** [comment]
No, they weren't valid before. We were just missing not assigning to them in the codegen.

**Comment by RX14** [comment]
So it's a bugfix? I see.

**Comment by asterite** [comment]
Indeed :-)

At some point "_" was a valid variable and block argument name. Eventually we made "_" be a variable that can be assigned to but never read. This is represented with the Underscore AST node. But then "_" was still allowed as block argument name. Changing that to use an Underscore AST node was very hard, so I just check against a "_" name. I implemented this but forgot to add the line above. It worked with just one "_" block argument though: that variable was assigned but could never be read. With two "_" that variable could be assigned twice with different types and that's where the bug happens. This PR changes the codegen so that "_" is never assigned a value.

**Pull request merged**
