### PR TITLE
LLVM 10 support

### PR DESCRIPTION
**Pull request by RX14**
Nice and easy upgrade for a change :)

### CODE REVIEW

**Comment by bcardiff** [comment]
Is that it? 

I was just checking and brew does not have llvm yet. Someday we could have CI for different llvm versions...

**Comment by RX14** [comment]
That's it! I compiled LLVM 10 and tested it working.

**Comment by wontruefree** [comment]
I am not sure if these are used but you might want to add it here too.
https://github.com/crystal-lang/crystal/blob/master/src/llvm/lib_llvm.cr#L21

**Comment by RX14** [comment]
It's not used so there's no need to add it.

**Pull request merged**
