### PR TITLE
Add flags missing from termios

### PR DESCRIPTION
**Pull request by gergelyk**
Adding flags from c_cc characters section. Refer to https://sites.uclouvain.be/SystInfo/usr/include/bits/termios.h.html

### CODE REVIEW

**Review by ysbaddaden — COMMENTED** [review]
There are a few issues to solve beforehand:

- these are non standard (as per https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/termios.h.html);
- there are only bindings for Linux while the other BSD targets also have most of them;
- last but not least, we won't use them in stdlib, and we don't intend to support everything from the C library in the compiler.

**Comment by gergelyk** [comment]
I agree. The only flag that I was missing in [this](https://github.com/gergelyk/ut50e-dashboard/blob/master/ut60e.cr) project in fact was VTIME. It seems to be part of non-canonical mode, like VSTART, VSTOP, etc. What do you think? Should this PR include only VTIME?

**Comment by ysbaddaden** [comment]
(I really should just restart my [posix shard](https://github.com/ysbaddaden/posix) as a `libc` shard, with libvirt VMs to autogenerate the bindings for all supported targets)

**Comment by straight-shoota** [comment]
Closing. We shouldn't add new unused libc bindings to stdlib until there's a decision that we definitely want to maintain them.

Collecting such bindings in a shard seems like a good idea.

**Pull request closed without merging**
