### PR TITLE
JSON::Any as_type? methods return Type or Nil

### PR DESCRIPTION
**Pull request by DougEverly**
Added methods to JSON::Any cast to Type without raising.

```crystal
require "json"

j = JSON.parse(%({"foo":2}))

if h =  j.as_h?
    puts h.keys
end
```

### CODE REVIEW

**Comment by jhass** [comment]
Could you rebase ontop of master to get rid of the merge commits?

**Comment by DougEverly** [comment]
Hosed another PR... reopening a clean one.

**Comment by jhass** [comment]
No need to, just force-push a clean branch. Have a look at our Contributing.md for some instructions

**Comment by DougEverly** [comment]
Ok, I think I got it. Looks like I needed to `git rebase --continue` when done.

**Comment by dsounded** [comment]
@jhass when this can be merged ?

**Comment by jhass** [comment]
I'd like a second core member opinion on it :)

**Comment by ysbaddaden** [comment]
No opinion from me. I still use `raw`, and never got Any to act as I wanted (eg: misses Enumerable methods like map, reduce, ...). I prefer to cast manually with `as Type` or `is_a?(Type)`.

**Comment by asterite** [comment]
This looks good and can be merged, I think it can be useful (I remember I had to use raw and `is_a?` for this, but using `as_h?`, etc., is more convenient).

@ysbaddaden We can make JSON::Any include Enumerable(JSON::Any), I just tried it and it worked. What do you think?

**Comment by ysbaddaden** [comment]
@asterite including Enumerable would be nice! Adding `parse_raw(str)` to skip a wrap/unwrap would great too.

**Pull request merged**
