### PR TITLE
Move Markdown to inside the compiler.

### PR DESCRIPTION
**Pull request by asterite**
The Markdown module is buggy and not feature complete. We shouldn't expose it in the standard library. For the compiler's purposes (`crystal doc`) it might be good but users should be encouraged to use a better library. Eventually the `crystal doc` tool should somehow use a different, better markdown library.

If with time we decide to improve it and make it feature complete and without bugs we could consider re-exposing it again. But right now this can't go like this in 1.0.

Related to #7463, #7009, #4613, #8113

### CODE REVIEW

**Comment by drujensen** [comment]
This light markdown is very useful for simple cases i.e. doc generation.  It's being used by Amber's html helpers.  The reason given for hiding this was to encourage use of `better` libraries but the only one I see available is https://github.com/icyleaf/markd.  It is a full featured common markdown but it is slow.  What is the recommended replacement?

**Comment by asterite** [comment]
I would recommend trying to optimize markd. You can also use the internal. Markdown type, it will still work but it's not recommended.

**Comment by asterite** [comment]
Also if you tell me how it's slow I can try to optimize it because I like those problems.

**Comment by drujensen** [comment]
I’m not sure why but the creator has benchmarks.  We don’t need full markdown. I guess we can extract what we need and write our own. 😔

**Comment by asterite** [comment]
@drujensen I'm currently optimizing markd, it's fun :-)

So far I went from 11.21 times slower than std's Markdown to 5.40 times slower. It's still slower, but the gap is getting smaller. And I plan to continue optimizing. Of course it won't reach std's performance because std is incomplete and has bugs and implementing the missing stuff will make it slower.

In fact maybe we should eventually just move markd into the standard library somehow and use it for the docs.

**Comment by straight-shoota** [comment]
> In fact maybe we should eventually just move markd into the standard library somehow and use it for the docs.

-> #4613

**Pull request merged**
