### PR TITLE
Don't interpret Proc typedefs as aliases

### PR DESCRIPTION
**Pull request by HertzDevil**
c.f. https://github.com/crystal-lang/crystal/issues/10001#issuecomment-760929546

### CODE REVIEW

**Review by bcardiff — APPROVED** [review]

**Review by asterite — APPROVED** [review]

**Comment by bcardiff** [comment]
@HertzDevil to clarify, the test case in https://github.com/crystal-lang/crystal/issues/10001#issuecomment-761009379 is passing on here, right?

For migration current code `type Callback = ...` should be redefined as `alias Callback = ...`. No other breaking-change is introduced here, right?

**Comment by HertzDevil** [comment]
@bcardiff That one still passes. This PR is only for the `type` to `alias` changes.

**Review by straight-shoota — APPROVED** [review]

**Comment by asterite** [comment]
@bcardiff what do you think about merging this one for 0.36.0? Since it's a breaking change it means 1.0 will have one less breaking change. It also fixes something in the language, because the behavior in this PR is more correct than the old one.

**Comment by bcardiff** [comment]
It can go into 0.36

**Pull request merged**
