### PR TITLE
Get version number from CHANGELOG.md when cannot get it from git

### LINKED ISSUE #4642: crystal 0.23 reports old version number
I installed crystal 0.23 from source. I've the following requirements:

- pre-compiled crystal-0.21.1-1-linux_x86-64
- gc 7.6
- llvm 3.9.1

In the source dir, I ran command 'make' and 'make spec'. All passed. But it seems crystal 0.23 is reporting 0.21.1 for me. See below.

$ ./crystal-0.21.1-1/bin/crystal -v
Crystal 0.21.1 [3c6c75e] (2017-03-06) LLVM 3.5.0

$ ./crystal-0.23.0-1/bin/crystal -v  
Using compiled compiler at `.build/crystal'
Crystal 0.21.1 (2017-06-29) LLVM 3.9.1

### PR DESCRIPTION
**Pull request by MakeNowJust**
Fixed #4642

### CODE REVIEW

**Comment by asterite** [comment]
It was working well. I always tagged the commit that I was using for doing a release. Omnibus checks out the repo from git so the tag would be there. I'm not sure we need to change anything.

**Comment by asterite** [comment]
(it would be interesting to know why it started to give incorrect versions)

**Comment by matiasgarciaisaia** [comment]
@asterite this tries to cover the usecase of downloading a zip/tar from Github, without repo history.

I think I'd just tag the version as `dev` in that case, and that's all. I wouldn't say a zip file is a given release version.

Maybe mixing this with a `-dev` suffix could do (something like `0.23.0-dev`).

But I'm not sure what I'd like the version to report on this builds - let alone the heuristics we apply.

**Comment by MakeNowJust** [comment]
@matiasgarciaisaia `dev` sounds bad because the user (i.e. @need47) builds crystal from **released** tar.gz, so `crystal version` should report correct version as possible.

However, this compiler is unofficial. We may tell about this is built outside of git repo. When `crystal` is built in git repo, `crystal version` reports git's SHA of built commit: `Crystal 0.22.0+156 [cb0ee67cb]`. So, when built outside of git repo, `crystal version` reports `[out of git]` additional information: `Crystal 0.23.1 [out of git]`.

**Comment by ysbaddaden** [comment]
I regularly compile from tarballs (e.g. alpine, raspbian, ...) not from git clones, so this change is welcomed!

**Comment by straight-shoota** [comment]
@MakeNowJust There is no way to tell if the code being build is from the released tar.gz or has a ton of other modifications, so I think it would make sense to assume it is not the release version by default.
If you know that you're building the release version (like @ysbaddaden) you just need to set `CRYSTAL_CONFIG_VERSION` appropriately as a way of saying "I know what I'm doing". Don't think this would be to much effort and provides a safe default.

**Comment by RX14** [comment]
If we don't know the compiler version and have no way of telling we should fall back to "Unknown" not the version of the compiler it was compiled with. If you're compiling with a tarball you can always set `CRYSTAL_CONFIG_VERSION`. Parsing the changelog seems brittle to me.

**Comment by MakeNowJust** [comment]
`unknown` sounds good to me. I think it is better than `dev` at least.

Additionally, in such a case we should display a warning message: `failed to get the version number from git, Crystal::VERSION would be set to "unknown" as fallback.` for example.

**Comment by ysbaddaden** [comment]
That depends.

Alpine's AKPBUILD automatically downloads the tarball for the version to compile. Since it's automated, I properly set the environment variable (but had to thought to set it).

On Ubuntu I now just download a tarball and build. I don't have to think to switch branches or checkout a tag, and have a clean install, distinct from the git clone. Easier. But version number is wrong, because I always forget to set the environment variable beforehand.

It's a tiny micro minor hitch. We shouldn't bother much, but having a wrong reported version number when building from an official tarball may lead to some confusion.

**Pull request closed without merging**
