### PR TITLE
Rewrite Channel

### PR DESCRIPTION
**Pull request by firejox**
for the further multi thread support
I think the design of channel should be changed.

### CODE REVIEW

**Comment by kostya** [comment]
is it fixed https://github.com/crystal-lang/crystal/issues/3900 https://github.com/crystal-lang/crystal/issues/3862?

**Comment by kostya** [comment]
how it performance in threadring benchmark https://github.com/kostya/crystal-benchmarks-game#threadring?

**Comment by spalladino** [comment]
Thanks for the PR @firejox. However, part of the team is currently working heavily on multi threading support, so I'd advise against submitting large changes relative to the design of channels, at least until this stabilizes.

Also, besides multithreading in particular, please refrain from submitting PRs that involve large changes without opening an issue to discuss it first: otherwise you risk spending a lot of time working on an implementation for something that was not to be accepted for some particular reason.

**Comment by firejox** [comment]
@kostya Yes, it would fix those issues. Every select will not run more than one times coroutine switch. and here is the performance https://gist.github.com/firejox/f9fb7c4b6d44501d0b1070c123a1fab6
it is slower than origin but still faster than other language.

**Comment by firejox** [comment]
@spalladino Sorry, I would open a issue and explain my design.

**Comment by firejox** [comment]
@spalladino Sorry for without opening issue first. Now I open a issue to discuss this.

**Comment by firejox** [comment]
Now the rewrite is done. 😃

**Comment by asterite** [comment]
Channel and all other concurrency-related stuff are only handled by the core team. And also they are working on it so these changes won't be compatible with them.

**Pull request closed without merging**
