### PR TITLE
Interpreter: clear finished hooks after intepreting

### LINKED ISSUE #12172: Interpreter: Defining class property in macro finished causes macro expanding errors in repl
## Bug Report
Given below code:
```crystal
class Server
  macro finished
    @@status = true
  end
end

pp server = Server.new
debugger
pp server
```

Run it with the interpreter then inspect `server`. It produces macro expanding error:

```
$ cr i bin/test.cr 
Using compiled compiler at /home/chao/git/personal/crystal/.build/crystal
#<Server:0x7f5c26895310>
From: bin/test.cr:9:4 <Program>#bin/test.cr:

    4:   end
    5: end
    6: 
    7: pp server = Server.new
    8: debugger
 => 9: pp server

pry> server
In bin/test.cr:2:3

 2 | macro finished
     ^
Error: expanding macro


There was a problem expanding macro 'finished'

Called macro defined in bin/test.cr:2:3

 2 | macro finished

Which expanded to:

 > 1 |     @@status = true
 > 2 |   
Error: can't use class variables at the top level
pry>
```
But defining instance property in macro `finished` does not have any problem.

System info:
```
$ cr -v
Using compiled compiler at /home/chao/git/personal/crystal/.build/crystal
Crystal 1.5.0-dev [9de815c99] (2022-06-29)

LLVM: 10.0.0
Default target: x86_64-pc-linux-gnu

OS: Ubuntu 20.04
```

### PR DESCRIPTION
**Pull request by asterite**
Fixes #12172

Some explanation:
- once the program is parsed and analyzed it computes a list of "finished hooks": code that must be analyzed and executed when the program ends
- analyzing the code was actually happening already: that's why `macro finished` was able to declare vars, etc.
- executing finished hooks is not done yet. That is, if you write `puts "Hi"` inside a finished hook, you won't see it in interpreted mode (I'm leaving that for a later PR)
- however, the finished hooks were kept in memory and re-analyzed whenever we entered a new line in pry. And it seems analyzing finished hooks in pry doesn't work very well right now
- so, far now, I'm just clearing the list of finished hooks right after interpreting some code. Ideally we'd also execute any finished hooks at the end of the program, but I played a bit with it and it's not so easy to do, so for now I'm not doing that
- but at least this is a small step forward and you can debug apps that have a finished hook

### CODE REVIEW

**Comment by asterite** [comment]
Well, in the end I added the ability to execute finished hooks in interpreted mode.

So you can try this:

```crystal
# foo.cr
macro finished
  puts "Bye!"
end

puts "Hello!"
```

If you execute that with `crystal i foo.cr`, previously the output was:

```
Hello!
```

Now it's:

```
Hello!
Bye!
```

You can also try this:

```crystal
# foo.cr
macro finished
  puts "Bye!"
end

puts "Hello!"
debugger
puts "Hello again!"
```

Then with `crystal i foo.cr` this happens:

```
$ crystal i foo.cr
Hello!
From: foo.cr:8:6 <Program>#foo.cr:

    3:   puts "Bye!"
    4: end
    5:
    6: puts "Hello!"
    7: debugger
 => 8: puts "Hello again!"

pry> continue
Hello again!
Bye!
```

Which makes sense, because `finished` is executed at the very end of the program.

That said, I don't think **executing** code is common in finished hooks. It's usually used to **define** code. But I think it still makes sense to execute it, just like in non-interpreted mode.

**Comment by asterite** [comment]
Oh, and you can also try this:

```
$ crystal i
icr:1:0> macro finished; puts 1; end; puts 2
2
1
=> nil
icr:2:0> macro finished; puts 3; end; puts 4
4
3
=> nil
```

That is, you can actually defined finished hooks in interactive mode, and they get executed.

**Comment by asterite** [comment]
@cyangle If you want/can, you can check if the interpreter works fine in your particular case with this PR

**Comment by cyangle** [comment]
@asterite Thanks a lot!

Now I can use the interpreter to debug my Lucky toy app:
```crystal
$ cr i src/toy.cr 
Using compiled compiler at /home/chao/git/personal/crystal/.build/crystal
Listening on http://0.0.0.0:8080
2022-06-30 22:50:29 +00:00
From: expanded macro: setup_call_method:15:3 Api::V1::Users::Show#call:

    10:         begin
    11:   logger.info do
    12:     "user_id: #{id}"
    13:   end
    14:   debugger
 => 15:   json(UserTwin.new(current_user!))
    16: end
    17:       end
    18: 
    19:       __temp_139 = run_after_pipes
    20: 

pry> id
"774107312037625857"
pry> current_user

GET /api/v1/users/774107312037625857 (7fbb6ac9-6096-4da8-b1a1-33ff01e43c7c)
 ▸ user_id: 774107312037625857
#<User:0x7f4b24983840 id: 774107312037625857, name: "Erick Schmidt", email: "braulio.murray@example.com", lock_version: 0, age: 18, created_at: 2022-06-27 05:53:23.634084000 UTC, updated_at: 2022-06-27 05:53:23.634085000 UTC, deleted_at: nil>
pry> current_user!
#<User:0x7f4b24983840 id: 774107312037625857, name: "Erick Schmidt", email: "braulio.murray@example.com", lock_version: 0, age: 18, created_at: 2022-06-27 05:53:23.634084000 UTC, updated_at: 2022-06-27 05:53:23.634085000 UTC, deleted_at: nil>
pry> current_user!.id
774107312037625857
pry> current_user!.name
"Erick Schmidt"
pry> UserTwin.new(current_user!)
#<UserTwin:0x7f4b309a1460 @age=18, @id=774107312037625857, @name="Erick Schmidt", @email="braulio.murray@example.com", @lock_version=0, @created_at=2022-06-27 05:53:23.634084000 UTC, @updated_at=2022-06-27 05:53:23.634085000 UTC, @deleted_at=nil>
```

I also tried it with the Lucky website, it worked. @jwoertink 

This is awesome!

**Comment by jwoertink** [comment]
whoa!! That's awesome @cyangle! Great work on this @asterite :heart:

**Comment by beta-ziliani** [comment]
Awesome! @asterite would it be hard to add specs? Do you want me to do that?

Also, for when this is merged, is this a reasonable change in the description? Thx!

---
Fixes https://github.com/crystal-lang/crystal/issues/12172

Some explanation:

 * once the program is parsed and analyzed it computes a list of "finished hooks": code that must be analyzed and executed when the program ends
 * analyzing the code was actually happening already: that's why macro finished was able to declare vars, etc.
 * ~~executing finished hooks is not done yet. That is, if you write puts "Hi" inside a finished hook, you won't see it in interpreted mode (I'm leaving that for a later PR)~~
 * however, the finished hooks were kept in memory and re-analyzed whenever we entered a new line in pry. ~~And it seems analyzing finished hooks in pry doesn't work very well right now~~
 * so, far now, I'm just clearing the list of finished hooks right after interpreting some code. ~~Ideally we'd also execute any finished hooks at the end of the program, but I played a bit with it and it's not so easy to do, so for now I'm not doing that~~
 * ~~but at least this is a small step forward and you can debug apps that have a finished hook~~

**Comment by asterite** [comment]
Hi @beta-ziliani! There are no specs for pry yet and doing that is a huge task, and for now I won't have time to do that.

**Comment by asterite** [comment]
Another thing is the interpreter is mostly experimental. If it doesn't work well, it's not a big deal because compiled programs are the ones shipped.

But I promise I'll introduce tests for pry later on, otherwise it will be hard to make it evolve in a safe way. But I'd like to leave it for later.

**Review by straight-shoota — APPROVED** [review]

**Pull request merged**
