### PR TITLE
Move Socket.ip? to Socket::IPAddress.ip?

### PR DESCRIPTION
**Pull request by straight-shoota**
The method is specific to `IPAddress`, so it shouldn't be defined in the parent namespace.

It could also be `Socket::Address.ip?`, but it fits more closely in `IPAddress`.

### CODE REVIEW

**Comment by asterite** [comment]
```crystal
if Socket.ip?(address)
  # ...
end
```

I think that was the point, it's almost readable English.

This new way is longer and redundant.

**Comment by bew** [comment]
Darn I agree with both of you here^^

In this case there could be a `Socket.ip?` that simply redirects to `Socket::Address.ip?` as a fancy-english-method?

**Comment by straight-shoota** [comment]
@bew That would be an alias. I don't think anyone would want that.

**Comment by bew** [comment]
Oh right ^^ didn't even see it coming

**Comment by RX14** [comment]
Maybe `Socket::IPAddress.parse?` which returns the `Socket::IPAddress` if it's valid, nil otherwise? Then it'd fit.

**Comment by straight-shoota** [comment]
That sounds good. `ip?` and `parse` (or rather `new(host, port)`) already do pretty much the same, so it looks like a nice solution. Will need some refactoring in the implementation, but I could give it a try.

**Comment by straight-shoota** [comment]
Or, well. The only issue is `port`. `Socket.ip?` is about checking if a string is an IP address. `IPAddress.parse` creates an instance of `IPAddress` and expects the argument to be a URI including an IP and port.

**Comment by RX14** [comment]
Oh, yeah. I keep forgetting `IPAddress` isn't an IP address. Really bad naming, if it has a port then it probably shouldn't be on `IPAddress` at all.

**Comment by wontruefree** [comment]
would it make more sense to have `Socket::Address.ip?` be `Socket::Address.valid?`?

**Comment by straight-shoota** [comment]
@wontruefree A path could also be a valid (UNIX) address.

**Comment by wontruefree** [comment]
I just thought it might a little redundant to have `IPAddress.ip?`

**Comment by ysbaddaden** [comment]
Asterite said it all: the proposed change doesn't improve anything. Further proposed alternatives bring more confusion. What's there to discuss further here? `Socket.ip?(address)` reads better and is simpler. Let's keep it.

**Pull request closed without merging**
