### PR TITLE
Fix deprecated warnings in some specs

### PR DESCRIPTION
**Pull request by mimame**
I hope to be useful.

Regards

### CODE REVIEW

**Comment by asterite** [comment]
There was a recent discussion about this. The idea is to test the deprecated methods to see that they still work because people might still be using them. We should only remove them once we remove the associated methods. So I'm not sure we'll merge this PR or similar PRs.

**Comment by asterite** [comment]
All of this to say, deprecation warnings in specs are not a big deal.

**Comment by mimame** [comment]
I see, very interesting discussion.
@asterite feel free to close the pull request

**Comment by bcardiff** [comment]
The motivation is to not have untested code in the std-lib since it might lead to code that does not actually compile.

Sometimes specs needs to be updated to get rid of the deprecation warning. That is a good change. This is the case when the spec uses the method but is not the tested method.

In other cases, the spec should be already present for the replacement alternative and probably the spec can be removed once the deprecation method is effectively removed.

**Pull request closed without merging**
