### PR TITLE
Fix check_type_allowed_as_proc_argument to show show type name

### PR DESCRIPTION
**Pull request by straight-shoota**
All other call sites of `check_type_can_be_stored` mention the respective type in the message, only for proc arguments this was missing.

Specs fail because `Class` type restriction sometimes reports as `Object`. Not sure about the reason or if that's intended, but it looks unexpected to me.
```cr
->(x : Class) { } # Can't use Object as a Proc argument type

def foo(&block : Class ->)
end

foo {} # Can't use Class as a Proc argument type

def foo(x)
end

->foo(Class) # Can't use Object as a Proc argument type
```

### CODE REVIEW

**Review by asterite — APPROVED** [review]
Looks good! Though CI is failing

**Comment by straight-shoota** [comment]
Yes, I mentioned that in the OP. Any idea why `Class` reports as `Object`?

**Comment by asterite** [comment]
It's a bug, but I can't remember why it happens.

Also, the original intention of the code was to show the invalid type inside a union type, but I guess that was unused.

**Comment by HertzDevil** [comment]
`Class`'s instance type is `Object`, and somewhere `Class` is treated like a metaclass. #10590 also observed this.

**Comment by straight-shoota** [comment]
Ah thanks, I had a vague idea that something about that had come up somewhere lately. I'll adapt the specs for now.

**Pull request merged**
