### PR TITLE
Add Hash/Indexable#dig/dig?

### PR DESCRIPTION
**Pull request by Sija**
Followup to #3536.

### CODE REVIEW

**Comment by j8r** [comment]
It would be also great to have `#dig(keys : Enumerable)`, where `keys` represents a variable sequence of keys.

**Comment by RX14** [comment]
Thought we decided against this. It was `.dig`  or `JSON::Any` and `JSON::Any` won because my proposal forgot that `JSON::Type` included more than `Hash` and `Array`. I proposed it could be solved by making `JSON.parse` return `Hash | Array` because the 95% usecase for json is arrays or hashes at the top level, but that idea wasn't well recieved.

@j8r that method would just produce insane types.

**Comment by Sija** [comment]
@RX14 I understood differently, also according to your own https://github.com/crystal-lang/crystal/pull/3536#issuecomment-403773699.
@j8r That would forgo all compile-time safety, ditto what @RX14 said.

I still see it as a very handy addition to stdlib and see no reason *not* to implement it.

**Comment by asterite** [comment]
I was against `dig` because I thought the implementation would make the return type be the union of everything. But this implementation is **brilliant**. 

```crystal
a = {1 => [[1, 2], [3, 4]]}

p typeof(a.dig(1, 0)) # => Array(Int32)
p a.dig(1, 0) # => [1, 2]

p typeof(a.dig(1, 0, 1)) # => Int32
p a.dig(1, 0, 1) # => 2
```

So I see it as a very nice, convenient way, to traverse deep structures. Now we would just need to add it to `JSON::Any` and `YAML::Any`... or remove those ugly `Any` wrappers altogether (I'd start by adding `dig/dig?` to those types, and eventually decide how to remove them).

**Comment by Sija** [comment]
> So I see it as a very nice, convenient way, to traverse deep structures.

Exactly.

>... or remove those ugly `Any` wrappers altogether (I'd start by adding `dig/dig?` to those types, and eventually decide how to remove them).

Yes, please! 🎉

**Comment by asterite** [comment]
@Sija Do you want to add `dig/dig?` to `Any` then? At least that way this PR will be "complete".

**Comment by Sija** [comment]
@asterite Done.
@codenoid Indeed, good to c u back! :)

**Comment by Sija** [comment]
Is it GTG now? CI fails seems not related, btw.

**Comment by bcardiff** [comment]
@Sija CircleCI had a bad week in their servers.

In darwin is still failing because it trying to compile the compiler with llvm 7, which is still not supported. The dependency of the formula is `llvm` plain and that leads to llvm 7 right now.

**Pull request merged**
