### PR TITLE
[CI] Add workflow for FreeBSD

### PR DESCRIPTION
**Pull request by straight-shoota**
Adds a CI workflow for FreeBSD. It executes in a virtual machine via [xhyve](https://github.com/machyve/xhyve) on a macOS runner via https://github.com/cross-platform-actions/action

There seems to be very little overhead, the entire test suite takes about 10 minutes longer than on macOS (which takes around 1 hour usually).
A successful run can be found here: https://github.com/crystal-lang/crystal/actions/runs/4118474285/jobs/7111023895

### CODE REVIEW

**Comment by beta-ziliani** [comment]
I already would prefer to reduce the amount of CI run. We mentioned to run it on nightlies. Or maybe after an approval?

**Comment by straight-shoota** [comment]
Yeah, we'll have to figure out how to do that. But I don't think we need to defer this PR for that because it affects other existing workflow as well.

**Comment by beta-ziliani** [comment]
the freebsd run timed out

**Comment by straight-shoota** [comment]
Now it succeeded but it's still running almost 6 hours. That's a lot more than the initial 71 minutes.
Not sure what's causing this.
Maybe we should insert more fine grained timestamps in the CI to get some idea.

**Comment by HertzDevil** [comment]
If you turn on timestamps in the log you can see that the compiler specs somehow spent almost 5 hours on a single line worth of tests: https://github.com/crystal-lang/crystal/actions/runs/4417604993/jobs/7743541466?pr=13053#step:3:754

**Comment by straight-shoota** [comment]
Nice, I didn't know about those timestamps 👍
 
Now it's just guessing what that might be 🤣 I've restarted the job to see if it reproduces. But judging be the previous timeout failures (and the quick run) I expect it takes some indeterminate amount of time.

**Comment by HertzDevil** [comment]
CI isn't failing anymore, but it looks like it is still taking almost 2 hours for the first line of tests

**Pull request closed without merging**
