### PR TITLE
Add Tuple#sample and Tuple#shuffle

### PR DESCRIPTION
**Pull request by jhass**
Fairly naive implementation for `Tuple#sample(Int)` for now, can be optimized when somebody is bored enough to do so ;)

### CODE REVIEW

**Comment by asterite** [comment]
Looks good! Though I wonder about `shuffle`. Maybe it's not very intuitive that it returns an Array. And in any case you can do `tuple.to_a.shuffle!`. What do you think?

**Comment by jhass** [comment]
I don't think `shuffle` can return a new tuple, at least it doesn't make much sense, since `{Int32, String, Bool}.shuffle` would return `{Int32|String|Bool, Int32|String|Bool, Int32|String|Bool}`, which is as hard to work with. Okay one bonus would be compile time bounds checking.

I think the trend towards explicit conversions isn't a too good one, it makes the language a bit more annoying it use ("Oh right, sigh, have to call `to_a` here") and leaves a doubt about whether the best implementation/variant is in use.

**Comment by bcardiff** [comment]
Having a tuple with {A|B, A|B} is as hard to work as with [A|B].

Couldn't the boundary check be obtained by a StaticArray(A|B, n) with n
being the tuple's length? I see this as an intermediate between Array and
Tuple.
On dom, 17 ene 2016 at 10:33 Jonne Haß <notifications@github.com> wrote:

> I don't think shuffle can return a new tuple, at least it doesn't make
> much sense, since {Int32, String, Bool}.shuffle would return {Int32|String|Bool,
> Int32|String|Bool, Int32|String|Bool}, which is as hard to work with.
> Okay one bonus would be compile time bounds checking.
>
> I think the trend towards explicit conversions isn't a too good one, it
> makes the language a bit more annoying it use ("Oh right, sigh, have to
> call to_a here") and leaves a doubt about whether the best
> implementation/variant is in use.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/manastech/crystal/pull/2018#issuecomment-172325799>.
>
-- 
Brian J. Cardiff

**Comment by asterite** [comment]
That's why I'm hesitant about adding `Tuple#shuffle`, because it's not clear what type it should return. I'd say `Array`, because that's the most used container type. StaticArray is mostly used in low-level situations.

**Pull request closed without merging**
