### PR TITLE
Use qualified type reference `YAML::Any`

### PR DESCRIPTION
**Pull request by zw963**
Current generated document not accurately.

image

this PR make those more accurately.

### CODE REVIEW

**Comment by straight-shoota** [comment]
What's the problem? I don't see any inaccuracy. `Any` within the `YAML`/`JSON` namespaces refers to `YAML::Any`/`JSON::Any`, respectively.

**Comment by zw963** [comment]
> What's the problem? I don't see any inaccuracy. `Any` within the `YAML`/`JSON` namespaces refers to `YAML::Any`/`JSON::Any`, respectively.

newbie user for use YAML.parse don't know what is the `Any` means, tell the user exactly `#as_a` will return `Array(YAML::Any)` is better than only `Array(Any)`, right?

Analysis from another angle, if you want return a JSON::Any from some convert methods, what is the Any stand for?

**Comment by asterite** [comment]
You can click Any and you will know.

**Comment by zw963** [comment]
> You can click Any and you will know.

Okay, click jump to same position.

So, Do we consider give uniform format is more neatly? (check following screenshot)

image

**Comment by asterite** [comment]
I mean, if you want the fully qualified name then it's a doc generator change. But types lookup in code works the same as in docs. If you know one you should understand the other.

**Comment by zw963** [comment]
> if you want the fully qualified name then it's a doc generator change

@asterite, although titled as document improvement, but that not the only reason:

1.  Use same style(all qualified or all not qualified) is better, for std-lib, if let me choice, i always prefer later, why not all use same form? 
2.  qualified name will result in a better performance? not sure, i means, ::YAML::Any is fairly straightforward, don't need lookup Any belong to which namespace, right?

**Comment by straight-shoota** [comment]
> why not all use same form?

Writing out the fully qualified name of every constant adds a lot of clutter and makes the code hard to read. In the context of `JSON` namespace, it should be sufficiently clear that `Any` refers to `JSON::Any`, not any of the other anys out there.

> qualified name will result in a better performance? not sure, i means, ::YAML::Any is fairly straightforward, don't need lookup 

Even a fully qualified name needs lookup of the name spaces for validation. I won't comment on any performance consideration of either variant because it's absolutely negligible. It doesn't make any difference.

This is entirely about developer ergonomics, not compiler performance.

**Review by beta-ziliani — APPROVED** [review]
This is bringing consistency in the code and docs. Thanks @zw963 !

**Review by straight-shoota — APPROVED** [review]
We talked about this issue and agreed that for the specific case of `Any` it makes sense to use qualified names because it's easy to get confused about it.

**Pull request merged**
