### PR TITLE
Reset location after block yielding in macro expansion

### PR DESCRIPTION
**Pull request by MakeNowJust**
This pull request Introduces `#<loc:save>` and `#<loc:reset>` new pragma comment, `#<loc:save>` saves current location and `#<loc:reset>` resets it. They are useful to keep original location when block yielding in macro expansion.

For example, this code makes broken error message:

```crystal
macro foo
  a = {{ yield }}
  a.ok
end

foo { 1 }
```

It cannot be compiled and error message is:

    in foo.cr:7: undefined method 'ok' for Int32

Error message points line 7 of foo.cr, but this code consists only 6 lines.

This bug comes from a location is not reset after block yielding in macro expansion. In fact, `foo { 1 }` expands to:

```crystal
a =  begin #<loc:"foo.cr",6,7>1 end
a.ok
```

So, the parser reports `a.ok` is on line 7 of foo.cr.

This pull request also fixes it by wrapping `#<loc:save>` and `#<loc:reeset>` to yielding expanded code, such a like:

```crystal
a =  #<loc:save>begin #<loc:"foo.cr",6,7>1 end#<loc:reset>
a.ok
```

It works well.

### CODE REVIEW

**Comment by asterite** [comment]
Super interesting! I actually had this idea too and eventually was going to implement it, though I imagined something more like a stack (push/pop). What do you think if we change it to `#<loc:push>` and `#<loc:pop>` and use a stack in the lexer? (I'd use a `record` to store all the info you are remembering now)

**Comment by MakeNowJust** [comment]
@asterite I'll try to implement `#<loc:push>` and `#<loc:pop>`. But, we cannot use `record` to remember old location. Because it is not immutable, it should be changed by lexer to report correct location.

**Comment by asterite** [comment]
Hmm... then I misunderstood something. I thought `loc:save` just saved the current location, then `loc:reset` reseted it. But it seems when you do `loc:save` then some tracking is done in many places... why is this needed?

**Comment by MakeNowJust** [comment]
For example, when given block is multiple lines:

```crystal
macro foo
  a = {{ yield }}
  a.ok
end

foo do
  :foo
  :bar
end
```

It is expands to:

```crystal
  a =  #<loc:save>begin #<loc:"foo.cr",7,3>:foo
#<loc:"foo.cr",8,3>:bar
end#<loc:reset>
a.ok
```

If `#<loc:save>` makes just copied and copied location's line number is not incremented, its location is wrong on `#<loc:reset>`.

**Comment by asterite** [comment]
Oooh... I understand now. Yes, the lexer needs to continue incrementing lines for the old line number. I think like you implemented it it's fine :-)

**Comment by MakeNowJust** [comment]
Thanks. I already implemented `#<loc:push>` and `#<loc:pop>` version, and now I run `make spec` on my environment. I'll write specs for `#<loc:push>` and `#<loc:pop>` (it is missing..), then I'll push it.

**Comment by asterite** [comment]
@MakeNowJust Great! Though now I'm not sure there's a use case for push/pop. I thought it was going to be useful to implement/fix this, but I'm not sure anymore. Can you think of a use case?

**Comment by MakeNowJust** [comment]
@asterite No, so I don't implement location stack at first. However, I think `#<loc:save>` and `#<loc:reset>` is not good naming. Perhaps `#<loc:push>` and `#<loc:push>` is better even if stack size is 1 only.

**Comment by asterite** [comment]
@MakeNowJust Thank you! And thank you for extracting a method for incrementing line numbers. I was actually going to ask if you wanted to do that, so it seems you somehow read my mind... :-P

**Pull request merged**
