### PR TITLE
Use a high-res logo in README.md

### PR DESCRIPTION
**Pull request by waj**
Use this new logo for the README file:

crystal

### CODE REVIEW

**Comment by Sija** [comment]
Would it be possible to use really high-res version, i.e. SVG?

**Comment by waj** [comment]
> Would it be possible to use really high-res version, i.e. SVG?

That would be infinite-res 🙂 
I tried but it doesn't play nice with the text with that font

**Comment by straight-shoota** [comment]
In SVG you'd need to convert the text to a path. Then this should work like a charm in infinite resolution ;)

**Comment by bcardiff** [comment]
This got reverted for now because it didn't play nice with the doc generator tool.

**Comment by straight-shoota** [comment]
Embedded SVG should work...

**Pull request merged**
