### PR TITLE
[CI] Update Windows job to LLVM 15

### PR DESCRIPTION
**Pull request by straight-shoota**
Goes on top of #13207

### CODE REVIEW

**Comment by HertzDevil** [comment]
Since LLVM 15, downloading the LLVM source is not enough, and the CMake archive must also be extracted alongside LLVM. The directory structure would look like:

```
cmake
- Modules
  - ...
- README.rst
llvm
- cmake
  - modules
  - platforms
  - ...
- CMakeLists.txt
```

**Comment by beta-ziliani** [comment]
efficiency is in the eye of the beholder. downloading two things means updating two things in the future :-)

**Comment by straight-shoota** [comment]
Yeah, but it's two things that sum up to about 50 MB vs. one thing that's 100 MB 😁

**Comment by beta-ziliani** [comment]
does it make sense to build for aarch64?

**Comment by beta-ziliani** [comment]
AArch64 is there already, I was questioning its use, but I got it now with your comment. I'll leave adding WebAssembly for now. We need to also add it in the macOS build; I don't know what's the story for linux.

**Comment by HertzDevil** [comment]
It's probably because the overflow conditions for 128-bit integers are not as simple as `T::MIN <= self <= T::MAX`, so the safe conversions have to replicate the overflow checks in `#codegen_out_of_range` exactly

**Comment by straight-shoota** [comment]
Let's see if #13222 finally fixes it =)

**Comment by straight-shoota** [comment]
Yes, CI is green: https://github.com/crystal-lang/crystal/actions/runs/4518906833/jobs/7959071198?pr=13208 👍

**Review by HertzDevil — APPROVED** [review]

**Pull request merged**
