### PR TITLE
Compiler: clear cache on linker error and try again

### LINKED ISSUE #9314: ~/.cache/crystal vs. Linux distro updates
Hello! When I updated Ubuntu from 19.04 to the 20.04, there is new `libevent` library version.

After that, my compilations with Crystal 0.34 started to break (linker errors) until I deleted `~/.cache/crystal`.

I assume that in Crystal binary caches (in `~/.cache/crystal`) there are fixed symbols to the libraries (like libevent, etc.), so if you update Linux distro with new versions of this libraries, the compiler tries to use these caches, which point to a library that no longer exists and -> bang, linker errors.

I understand, that this is not a direct Crystal problem (maybe), but for the first time, this was super weird for me (and for my colleagues too). Is there a way the compiler can cope better or advise developers better? I believe this can be a big problem for some people and they will start randomly reinstalling everything possible in this situation.

### PR DESCRIPTION
**Pull request by asterite**
Fixes #9314

Try these steps both without this PR and with this PR. In the first case you will get an ugly linker error. In the second case compilation will succeed.

---

Steps to reproduce:

```bash
$ rm -rf $(crystal env CRYSTAL_CACHE_DIR)
$ echo 'puts "hello world"' > foo.cr
$ crystal build foo.cr
$ cd $(crystal env CRYSTAL_CACHE_DIR)
```

Run `ls` there and `cd` into the first directory.

Then run this:

```bash
$ cp U-I-nt64.o _main.o
```

Then go back to where `foo.cr` is defined and compile again:

```bash
$ crystal build foo.cr
```

You get a linker error saying a lot of symbols are missing, which makes sense because I just overwrote an `.o` file with another `.o` file. (or not, with this PR)

### CODE REVIEW

**Comment by waj** [comment]
I still think this is a mistake. The compiler should not retry actions "just in case". For example, if there is a missing library in the system, would this delete all the object files, compile everything again just to end with the same error?

The only cases I see this is necessary is that random issue we have where the object files get corrupted when the build is cancelled (would we just forget about it and hide it with this workaround?) and these artificial cases where the cache is corrupted on purpose just to make it fail. There must be a reason why no other compiler behaves like that.

**Comment by waj** [comment]
BTW, even the author of #9314 said the issue could not be reproduced. So I'm sorry Ary, but I'm not sure what are we fixing here. That issue should be closed already.

**Comment by asterite** [comment]
@waj I get this error like once or twice a week. People report it [on the forums](https://forum.crystal-lang.org/t/compilation-error-in-crystal-0-35-1/2283/3) and on gitter. It's happening everywhere.

A linker error is very unlikely to happen. In case it happens, retrying once isn't very costly.

But feel free to close this and eventually reopen it and merge it, because I know this is the correct solution.

**Comment by asterite** [comment]
So, I checked our code and what the compiler does is:
- it generates the `.o` file to a temporary filename
- once that's done it copies the temporary filename to the final `.o` file

So I don't understand how can it happen that the `.o` file is left with half or incorrect data.

I see that we reuse an `.o` file if the `.bc` file that's in the cache is the same as the one we just generated. So maybe that logic is wrong (that's `IO.same_content?`) and the bc files are considered the same when they are not, then an incorrect `.o` file gets used.

So feel free to close this.

However, the issue exists and it happens to me quite frequently. It's also reported in the forums and gitter quite often.

**Comment by asterite** [comment]
@waj Just know that this was recently reported in the forums: https://forum.crystal-lang.org/t/compilation-error-in-crystal-0-35-1/2283

So okay, the author said they couldn't reproduce it. But it doesn't mean the issue doesn't exist. It's just hard to reproduce.

**Comment by asterite** [comment]
> There must be a reason why no other compiler behaves like that.

How do you know other compilers don't do some resilient checks like these against their cache?

**Comment by didactic-drunk** [comment]
>     * once that's done it copies the temporary filename to the final `.o` file

Copies or renames?  Copy leaves room for race conditions.

I had frequent corruption issues when 2 compile processes ran at the same time.

**Comment by asterite** [comment]
Sorry, renames.

And yes, you can't use the compiler twice at the same time, but it's not related to this issue or fix.

**Comment by jhass** [comment]
Keep in mind that a rename across filesystems is a copy and delete still.

**Comment by asterite** [comment]
Yes, but the problem I'm seeing is that an object file ends up with incorrect data, so I don't know what's going on.

**Comment by didactic-drunk** [comment]
Cheap checksum and verify?  If the checksum verifies but the code is wrong it's the generator.  Otherwise it's something else.

**Comment by asterite** [comment]
What we do is we compile each llvm module to a bc (byte code) file. We save that in a directory for next time. From a bc file you can tell llvm to create an o file. If on a second compilation the bc file we generate is exactly the same as the one we have in the cache directory, we use the o file that's there. For some reason, the o file that's there sometimes isn't correct. I don't know why.

**Comment by didactic-drunk** [comment]
Can the same name be used for different code/types?  Is the bc file always correct?

**Comment by asterite** [comment]
No. Yes.

**Comment by waj** [comment]
I think I found the problem. I can easily reproduce doing these steps:
  1. Compile a program in non release mode
  2. Compile the same program in release mode, but cancel at the middle of codegen (bc+obj) step
  3. Compile again the same program in release mode

Let me know if someone is able to reproduce without switching modes, but in this case the problem happens because step 1 writes both `_main.bc` and `_main.o` for non release mode. Then step 2 generates bitcode for release mode, compares with the existing `.bc` file and overwrites it because it's different. Before it finishes writing the `.o` the process is cancelled. Now the third time the `.bc` file matches because the program is again compiled in release mode so it assumes the `.o` is already generated. It tries to link, and boom!

I don't know yet the best option to solve this issue, but some ideas:
  1. Compare mtime's of `.bc` and `.o` files. Since the `.o` file is older than the `.bc` it shouldn't be reused
  2. Delete the `.o` file before writing the `.bc` file
  3. There is a `bc_flags` file stored in the cache dir that stores some attributes used during compilation. If this file changes, delete all the `.o` files

Maybe we should just apply all of them 😛

**Comment by waj** [comment]
Well... actually changing to release mode is not the only way to trigger the issue, but it is really easy to trigger the problem that way. Any compilation that generates different code over an existing cache directory is susceptible to this bug.

**Comment by didactic-drunk** [comment]
This explains my frequent issues.  Save `.cr` automatically triggers a normal build.  Sometimes I run a bench which compiles with --release.  Both run simultaneously but I try to kill one.

1. Race:
```
build 1 writes .bc with t1
build 2 writes .bc with t2
build 1 writes .o with t3
build 2 aborted

End result: .o.mtime >= bc.mtime but from a different build
```
2. Is insufficient as it leaves a race condition with 2 simultanous builds.  Same as 1.
3. Same race for simultaneous builds, made larger.

Modified solution:
1. Force the mtime on .o using utimes to be the same as the bc file.  Compare using ==, not >= when deciding what to delete.
2. Unnecessary as long as you write filename.tmp.random then rename.
3. Hold bc_flags open with an exclusive lock while writing to the dir.

**Comment by asterite** [comment]
@didactic-drunk I think that's a different issue. You can't run the compiler twice on the same file because the same cache directory is used so this will definitely lead to race conditions. The solution in that case is to use a lock of some sort. The issue in this PR is about two separate compilations leading to problems.

**Pull request closed without merging**
