### PR TITLE
Fix formatting absolute paths

### LINKED ISSUE #7559: Formatter is broken with absolute paths
Passing absolute paths to the formatter fails with

```
$ crystal tool format /data/programming/crystal-lang/beryl/master/src/i3bar.cr
Error: file or directory does not exist: .//data/programming/crystal-lang/beryl/master/src/i3bar.cr
```

I'm surprised nobody's noticed in the past month...

### PR DESCRIPTION
**Pull request by RX14**
Fixes #7559

### CODE REVIEW

**Comment by Sija** [comment]
Any test for this?

**Comment by RX14** [comment]
There weren't any tests for this command code before, and I can't be bothered to create a whole test harness for a bugfix

**Comment by RX14** [comment]
@asterite I can't find that method.

**Comment by asterite** [comment]
Sorry, my mistake, it exists in Ruby in Pathname

**Comment by straight-shoota** [comment]
#5635 adds such a method.

**Comment by straight-shoota** [comment]
Thank you @RX14 !

**Pull request merged**
