### PR TITLE
Add new `?~` (boolean `=~`) operator.

### PR DESCRIPTION
**Pull request by reitermarkus**
I always wondered why there is a `!~` operator, but not a boolean `=~` operator.

Usually, you would have to either use

```crystal
!!(var1 =~ var2)
```

or

```crystal
!(var1 !~ var2)
```

With this new operator, you can simply do this:

```crystal
var1 ?~ var2
```

Let me know what you think, thanks!

### CODE REVIEW

**Comment by Arcovion** [comment]
Ruby 2.4.0 introduced [`#match?`](http://ruby-doc.org/core-2.4.1/Regexp.html#method-i-match-3F) for this, lets do the same.
You could use `var2 === var1` instead but you have to switch the arguments around... `#match?` is more readable than both `?~` and `===`.

**Comment by asterite** [comment]
There's no need to do `!!` because the result is MatchData or Nil, so truthy or falsey.

**Comment by Sija** [comment]
@asterite unfortunately, there **is** a need for it, since at times you'd like to have a `Bool` return type value instead of `Regex::MatchData | Nil`.

**Comment by asterite** [comment]
I'll stick to fixing bugs. Maybe someone else can decide this better :-)

**Comment by akzhan** [comment]
In any case, the introduction of new operators must be very strongly justified.

So this pull request should be rejected. But You can add usual method.

**Comment by RX14** [comment]
@asterite I think having a strong opinion guiding the project is better than design by committee. I argued against some of your decisions in the past but it turns out that you were almost always right in the long run. 

Having too many operators is a bad thing, I think we have enough already. Using `!!(var1 =~ var2)` is short enough, and requires no new operators *just* for when you want to return `var1 =~ var2` from a function or expression.

**Comment by asterite** [comment]
@RX14 I agree. It's just that I don't want to take decisions alone anymore. All decisions should be discussed by the whole core team. Here I rushed to close this because I'm against it, but I didn't consult it with anyone else.

**Comment by Sija** [comment]
@asterite I was referring to the need of having `Bool` return value but this can be easily achieved by adding `Regex/String#match?` method like Ruby 2.4 did.

**Comment by molovo** [comment]
I agree with limiting the number of operators in premise, but in this instance I'd agree with @reitermarkus that it does seem rather counterintuitive to provide the negative `!~` but not have a positive equivalent, so on that basis I'd be for it.

**Comment by reitermarkus** [comment]
> Ruby 2.4.0 introduced `#match?` for this, lets do the same.

Ruby didn't actually introduce it for *this*, the reason was to remove the unnessary assignment to `$~` when only the return value is of interest.

> Having too many operators is a bad thing, I think we have enough already. 

Why is it a bad thing? It's not so much about the operators themselves, it's more about their usage, which in this case, is very specific.

> Using `!!(var1 =~ var2)` is short enough, and requires no new operators just for when you want to return `var1 =~ var2` from a function or expression.

`!(var1 =~ var2)` is even shorter than `!!(var1 =~ var2)`, so should we remove the `!~` operator just for that reason?

I think `?~` is the logical counterpart for `!~`, and fits better than `match?` and `!~`.

**Comment by ysbaddaden** [comment]
As outlined by @asterite, there is no need for such an operator. It already works:

```crystal
if "something" =~ /regexp/
  # match
end
```

Maybe a `match?` method that wouldn't assign a matchdata but only return a boolean would allow some optimisation. Yet, introducing another operator seems overkill.

**Comment by mverzilli** [comment]
Closing since there is enough consensus that we prefer not to create new operators without compelling reasons. In this case the general opinion is we can live without this.

**Pull request closed without merging**
