### PR TITLE
Quick fix for broken Int8#to_s

### PR DESCRIPTION
**Pull request by straight-shoota**
Quick fix for #10286 to use the unoptimized algorithm for `Int8#to_s`.

### CODE REVIEW

**Review by asterite — APPROVED** [review]

**Comment by bcardiff** [comment]
Did someone run some more coverage regarding this optimization? Or only the reported invalid cases were handled?

**Comment by asterite** [comment]
I think we should actually revert the optimization. It takes a lot more time to understand the code, and 10% is okay but lot super important, specially if there's a chance it has more bugs.

**Comment by straight-shoota** [comment]
Yeah, maybe it's better to revert the optimization entirely for now. It can be addeded again any time as soon as it's fixed.

**Comment by bcardiff** [comment]
Ok, I'm fine reverting this. [U]Int16 are fine so there are good chances that the issue is only present in 8 bits. But I would like some 1-time verification against BigInt for example to be sure about this kind of optimizations.

**Comment by asterite** [comment]
I think `BigInt` overrides `to_s`. And even if BigInt somehow uses this method, it won't work fine, with or without the optimization.

**Comment by bcardiff** [comment]
`BitInt` use `LibGMP.get_str`, my point is to compare with a different implementation and check the result is the same.
Previous `Int#to_s` implementation could also work as a witness.

On the last overflow reimplementation with waj we validate the results agains BigInt for example 🤓

**Pull request closed without merging**
