### PR TITLE
Add Enumerable#each_cons_pair and Iterator#cons_pair yielding a tuple

### PR DESCRIPTION
**Pull request by straight-shoota**
`Enumerable#each_cons` has a variable chunk size that can be selected dynamically.
This PR adds a special case for the most common use case of iterating over pairs. It simply yields tuples of adjacent items. This avoids heap allocations and makes it easier to use because you don't need to deconstruct an array.

```cr
# new:
[1, 2, 3, 4, 5].each_cons do |a, b|
  puts a * b
end
# old:
[1, 2, 3, 4, 5].each_cons(2, reuse: true) do |pair|
  a, b = pair
  puts a * b
end
```

Benchmark:
```
# iterating over (1..1000).to_a
new 228.27k (  4.38µs) (±17.91%)   0.0B/op        fastest
old  33.13k ( 30.19µs) (± 9.87%)  80.0B/op   6.89× slower
```

It's a convenience feature that also improves performance.

I've added the same behaviour to `Iterator#cons`

### CODE REVIEW

**Comment by asterite** [comment]
I like this!

What if we name it `each_cons2`? Then we could eventually add `each_cons3`, `each_cons4`, etc. if we really wanted to.

Though it's true that one of the most common cases for `each_cons` is 2... 🤔

**Comment by straight-shoota** [comment]
I don't see a reason for adding a number suffix. Iterating over pairs is by far the most common use case. If we wanted to add others, there's nothing hindering us from adding `each_cons3` later anyway.

**Comment by RX14** [comment]
Want to rebase for a merge commit?

**Comment by vlazar** [comment]
I love this optimization but I feel like the chosen size `2` mentioned explicitly in the method name like `#each_cons_pair` / `Iterator#cons_pair` would be even better.

**Comment by bcardiff** [comment]
I like @vlazar's suggestion. Otherwise, the expected block arguments differ based on the presence or not of the argument. I like the explicitness of `each_cons_pair`

**Comment by straight-shoota** [comment]
I guess that might be be good enhancement, but waiting for feedback on this suggestion.

**Comment by asterite** [comment]
I think `each_cons_pair` is good. My suggestion `each_cons2`, `each_cons3`, etc. might also be taken into consideration, though I doubt we'll spend effort adding each of these other special variants, so 👍  `each_cons_pair` from me.

**Comment by RX14** [comment]
+1 from me, might want to go ahead with this

**Comment by bcardiff** [comment]
`each_cons_pair` or `each_cons2` should be used as a name. Other than that LGTM.

**Comment by straight-shoota** [comment]
Renamed to `Enumerable#each_cons_pair` and `Iterator#cons_pair`.

**Pull request merged**
