### PR TITLE
fix IO::ARGF#read should always return i32

### PR DESCRIPTION
**Pull request by stakach**
seeing errors like this on nightly

image

### CODE REVIEW

**Comment by stakach** [comment]
This pull is probably not actually useful as I just made a stab at what needed to be changed

**Comment by asterite** [comment]
Probably some IO type outside of the std library is returning an Int64. I don't think that's totally wrong, so maybe we should revert this return type annotation

**Comment by stakach** [comment]
related to this pull #10580 
it might be related to the definition of SizeT
https://github.com/crystal-lang/crystal/blob/master/src/lib_c/aarch64-linux-musl/c/stddef.cr#L2

**Comment by straight-shoota** [comment]
As long as `Slice#size` is fixed to `Int32`, there's no point in returning `Int64` on `IO#read`. It's impossible to read more than `Int32::MAX`. So IMO the type restriction is good.

The real problem however is that the error message points to the abstract def, not the implementation which breaks the contract by returning `Int64`. That makes it hard to identify the culprit. I thought there was already an issue about that, but I can't find it.

**Comment by asterite** [comment]
But this is breaking someone's code. I don't think we are allowed to do that.

**Comment by straight-shoota** [comment]
Ooops, sry I incorreclt identified this error as being caused by adding a return type to an abstract def. But this is really not the case in #10580. It adds a type restriction to the implementation. As @stakach suggested, this might be caused by a missing conversion from ˋSizeTˋ. So maybe it's our own code that's broken. We should have noticed that, though because we run CI against aarch64-musl.

@stakach Can you provide information on the target platform and possibly a reduced reproduction?

**Comment by stakach** [comment]
This is where I'm seeing the error
https://github.com/PlaceOS/driver/runs/2844680637?check_suite_focus=true

Which looks like the fix is to call `.to_i32` on a `SizeT`

**Comment by asterite** [comment]
We can probably call `to_i32` on `read_count` right before we return it, from ARGF.

**Comment by asterite** [comment]
Could you try changing that in this PR and see if all specs pass here, and also pass in that ssh library?

**Review by oprypin — APPROVED** [review]

**Comment by straight-shoota** [comment]
This fix is just a workaround, though.

`ARGF#read` doesn't introduce a `Int64` type. It just receives the result from `IO#read` on the wrapped IO. And `IO#read` should return `Int32`. Unfortunately, there is currently no return type restriction on that abstract def. But adding that would be the correct fix.
We probably can't do that until 2.0, though.

But I think we should add a TODO comment and open an issue to track this.

**Pull request merged**
