### PR TITLE
Include Enumerable in CSV

### PR DESCRIPTION
**Pull request by tristil**
Include Enumerable in CSV, and add a test for `map_with_index`.

### CODE REVIEW

**Comment by tristil** [comment]
Let me know if I should add comments about justification to the commit message.

**Comment by chaniks** [comment]
You can write it here.  You can also report an issue first, and then reference it in both the commit message and the PR, which usually makes it easier to track things.

**Comment by tristil** [comment]
Updated commit message to explain justification and made test more robust.

**Comment by asterite** [comment]
@tristil Thank you! But CSV is not an enumerable. An instance of CSV is more like a cursor that always points to a row and you can fetch any of the columns by index, header name or regex. That's why `each` doesn't return the row ([your question in Google Groups](https://groups.google.com/forum/#!msg/crystal-lang/5zLAPFgVVB0/mMNEK7K7BQAJ)). In fact a CSV instance has just one instance variable for storing all rows, but it just stores one at a time, for efficiency (to avoid allocating new arrays for each row). You can invoke `to_a` on a `CSV` to get a copy of that row.

For an Enumerable (well, Iterator), you can use `CSV.each_row`:

```cr
CSV.each_row(string_or_io).with_index.each { |row, index| ... }
```

**Comment by tristil** [comment]
@asterite Okay, I understand now, and I see that this is well documented on the class. What confused me, besides not reading the documentation well, is that there is an `each` method which just calls `next` for you. My thinking was that anything that implements `each` should be an enumerable, but I guess the idea is that this could create problems because e.g. if you did `CSV.new(string_or_io).each(&.itself)` you would get back the same instance over and over again? I'm still vague on the principle that governs when something that implements `each` should include Enumerable, but I am satisfied that I can use the other interface, which cleans up my code. Thanks!

While I'm here, would it make sense to implement the `headers` functionality in CSV Parser? If so, I can take a shot at it.

**Comment by asterite** [comment]
@tristil The headers functionality is already there. What do you need to do?

**Comment by tristil** [comment]
@asterite So my new code is

```crystal
require "csv"

def get_rows
  text = File.read("vendors.csv")

  CSV.each_row(text).map_with_index do |row, index|
    next if index == 0

    row
  end.compact
end

rows = get_rows
```

The only reason I need the index is to skip the first row, which I would get for free with `headers: true` if I were using the standard interface. Right now it seems like you have to choose between using the iterator/parsing interface but you don't get the headers switch or using the standard interface. Seems like it would be good to have `CSV.each_row(text, headers: true)` for consistency?

**Comment by tristil** [comment]
@asterite I see now that wouldn't work unless it was returning hashes instead of `Array(String)`, which is a bigger chance than I was talking about. Looking at the Ruby interface they switch to returning `Row` objects when you set `headers: true`.

**Comment by chaniks** [comment]
Just for note, you can also use `Iterator#skip` to skip header, like:

```crystal
CSV.each_row(text).skip(1).to_a
```

And I think `CSV.each_row` is a lightweight convenient(utility) method for those who don't want to use the full CSV implementation. In that case, returning an array might be reasonable.

**Comment by tristil** [comment]
@chaniks That `skip` is nice, thanks.

**Pull request closed without merging**
