### PR TITLE
Raise syntax error when using out as an arg

### PR DESCRIPTION
**Pull request by esse**
That commit fixes issue #6042.

### CODE REVIEW

**Comment by bew** [comment]
Can you add a spec somehow?

**Comment by Sija** [comment]
@bew it's there, see the diff.

**Comment by straight-shoota** [comment]
I'm not sure this is right. There should not really be an issue with accessing `out` as local variable. #6042 could be fixed differently.

**Comment by straight-shoota** [comment]
I'm pretty sure @MakeNowJust didn't just forget to add a restriction to `out`  in #5930.

**Comment by asterite** [comment]
`out` as a local variable should be forbidden. `out` is a keyword and it can be confused with the `out var` syntax.

**Comment by asterite** [comment]
That said, `out` taken as a keyword just for interacting with C seems like a bad design choice.

**Comment by asterite** [comment]
Basically...

```crystal
out = 1
foo(out) # Error: expecting variable or instance variable after out
```

That's why `out` should not work for local variables, because you can't pass them to other methods.

**Comment by straight-shoota** [comment]
Then all keywords should be forbidden?

`out var` could be confused with a method call, but not really with a local variable called `out`.

**Comment by straight-shoota** [comment]
If `out` is not followed by a variable name, it's not a keyword.

**Comment by asterite** [comment]
@straight-shoota That's just confusing, but if someone wants to implement that, please go ahead (and revert this PR).

**Pull request merged**
