### PR TITLE
Include fragment within URI `#full_path`

### PR DESCRIPTION
**Pull request by Blacksmoke16**
Previously it was only included in the full URL representation via `.to_s`.

### CODE REVIEW

**Comment by straight-shoota** [comment]
What's the reason for this proposed change?

**Comment by Blacksmoke16** [comment]
@straight-shoota It seemed like an obvious bug given the fragment is part of the path and this method `Returns the full path of this URI.`.  I'm working on adding URL generation to Athena and noticed that the only way to include the fragment was generating the full URL, versus an absolute path.

**Comment by straight-shoota** [comment]
It's even documented that the fragment is not included in the result of this method.

Cause of confusion is probably the name: `full_path` is an unspecified term and open to interpretation. `path` in an URI context is _just_ `path` and there is no "full" version of it.

The intention is clear when you look at where this method is used: `HTTP::Client` calls `full_path` to get the request target (in origin form). The fragment is not part of that.

What you're looking for is essentially to relativize the URI against scheme and authority.

Those are different use cases. Maybe `URI` should have different helper methods for both of them. Maybe neither of them. I'm not sure. But I'm pretty sure we should better rename or remove `URI#full_path` because the terminology is undefined.

**Comment by asterite** [comment]
I think the fragment is more of a browser thing. Servers don't do anything with it. For example in Ruby there's [request_uri](https://ruby-doc.org/stdlib-1.9.3/libdoc/uri/rdoc/URI/HTTP.html#method-i-request_uri) but it doesn't return the fragment.

Maybe we can add an option to include it?

**Comment by vlazar** [comment]
Servers don't do anything with `fragment` but it's part of URI.

The URI parts are https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Definition

So maybe `full_path` should be renamed to plain and simple `path_and_query` since it returns `path + query` of the URI?

**Comment by vlazar** [comment]
On the related note of consistency (see https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Examples) and the upcoming Crystal 1.0 release.

- There is no `URI#authority` method. Should it be added?
- The `URI#query_params` can probably be renamed to just `URI#query`?

**Comment by Blacksmoke16** [comment]
> So maybe `full_path` should be renamed to plain and simple `path_and_query` since it returns `path + query` of the URI?

That would make sense.  I guess it introduces the question of should there then be like `path_and_query_and_fragment` and/or `path_and_fragment`.  At that point it would prob be easier to just have the user build what they want using the getters on the `uri` object itself.

> * The `URI#query_params` can probably be renamed to just `URI#query`?

`#query` returns the string representation of the query part of the uri.  `#query_params` returns a `HTTP::Params` object related to the query part of the uri.  I.e. its a shortcut to like `HTTP::Params.parse uri.query || ""`.

**Comment by Blacksmoke16** [comment]
Closing in favor of https://github.com/crystal-lang/crystal/pull/10099.

**Pull request closed without merging**
