### PR TITLE
Specify pkgconfig name for gc

### PR DESCRIPTION
**Pull request by jhass**
Redux #9395

Since Stephie didn't do the general follow up yet, I'll just do what I run into :P

### CODE REVIEW

**Comment by bcardiff** [comment]
That will break using the embedded library if the bdw-gc is installed. 

Eventually we want that pkg_config argument, but not until a new release of the gc or until we formalise the overrides of libraries.

**Comment by jhass** [comment]
Mmh, then I guess it's a bug in the spec helpers not passing some link flags that the original compiler does pass? How does it work on CI?! 😕

```
bin/crystal spec -v spec/compiler/codegen/primitives_spec.cr
Code gen: primitives
  codegens bool
  codegens int
  codegens long
  codegens int128ld: library not found for -lgc (this usually means you need to install the development package for libgc)
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of command failed with code: 1: `clang "${@}" -o /var/folders/wh/wcmzz8xd5gzfrrynkvvh4x640000gn/T/cr-spec-52bb2152/primitives/crystal-spec-output  -rdynamic -lpcre -lgc -lpthread /Users/jhass/projects/crystal/src/ext/libcrystal.a -L/usr/local/Cellar/libevent/2.1.11_1/lib -levent -liconv -ldl`
```

**Comment by waj** [comment]
@jhass I'm able to reproduce the issue once I uninstalled bdw-gc (`brew uninstall bdw-gc`). But how is that you can fix it enabling the `pkg_config`?
Anyway, it seems that effectively the `CRYSTAL_LIBRARY_PATH` is not being forwarded to the specs and it might be using globally installed libgc in the CI instead.

**Comment by jhass** [comment]
Oh, I also have CC=clang set for some reason 🤔

**Comment by jhass** [comment]
Yeah, unsetting `CC` makes it work. We probably still should make sure the spec helpers pass the link flags on though.

**Comment by bcardiff** [comment]
FYI, I'm working on removing all the LIBRARY_PATH overrides in docker images :-)

**Pull request closed without merging**
