### PR TITLE
Blank? second attempt

### PR DESCRIPTION
**Pull request by kostya**
i so many times need this function, and just put in code everytime: https://github.com/kostya/myhtml/blob/master/examples/texts.cr#L28

maybe change name to `unicode_whitespaced?`

### CODE REVIEW

**Comment by BlaXpirit** [comment]
This pull request breaks a convention: every other method on `Char` (like `alpha?` and `upcase`) deals only with ASCII text.

Crystal needs extensive support for Unicode and its categories, but the language creators have expressed the wish to keep that in a `Unicode` module.

**Comment by asterite** [comment]
Note that I'm not against generally supporting Unicode in String and Char, it's just that I think it's super hard to do right now, so I consider it low priority (for myself, if anyone wants to implement it please go ahead)

**Comment by bcardiff** [comment]
`#blank?` Should be aligned with `#whitespace?`. I kind of prefer defaulting to unicode operations. Even on case related functions. I think we should settle down what we want before making only some methods unicode friendly.

**Comment by ozra** [comment]
Unicode sounds good as standard for everything on Char. Perhaps there would be room for an `AsciiChar` (or `ASCIIChar` according to idiomatic naming?) for when needing max-juice to process text-records and transactions specified to being ASCII. Or not.

**Comment by kostya** [comment]
extract to here https://github.com/kostya/blank, because use in some projects.

**Pull request closed without merging**
