### PR TITLE
Rename MemoryIO to IO::Memory

### PR DESCRIPTION
**Pull request by RX14**
With `IO::Delimited`, `IO::Hexdump` etc. `IO::Memory` seems like a much more consistent name than `MemoryIO`.

### CODE REVIEW

**Comment by RX14** [comment]
This PR is obviously going to become out of date quite quickly as `MemoryIO` is used very often, so it would be a good idea to make a decision on this sooner rather than later.

**Comment by asterite** [comment]
I also think it's more consistent with the other IOs, but typing `IO::Memory` is a bit slower than typing `MemoryIO`. Nevertheless I agree it would be convenient to make the change. I'll check with @waj this week.

**Comment by ysbaddaden** [comment]
Same here. `MemoryIO` reads better than `IO::Memory`, but the same can be said of `IO::Delimited`, `IO::Buffered`... so it would fit better.

**Comment by asterite** [comment]
Well, we could rename `IO::Delimited` to `DelimitedIO`, etc. I actually think that this is a better change. `IO::Memory` is not a memory. We have `Char::Reader`, but there it makes sense: it's a reader.

**Comment by mverzilli** [comment]
It does feel tidier to group all Crystal IO services under the same namespace. And it could get even better once we develop more advanced editor tools. Just type `IO::` and you get a nice dropdown with the menu of IO resources at your service, which is an organic way of learning about the std.

**Comment by RX14** [comment]
I don't feel like "typing cost" is a particularly good motivation for any change. Most time spent programming is spent looking at or thinking about code, so naming and syntax should be optimised for *readability* not *typability*. `IO::Memory` reads the same or better than `MemoryIO` to me.

**Comment by timcraft** [comment]
How about StringIO? Easier to find for anyone coming from other languages (Ruby and Python both have StringIO), and fits with the point asterite makes about it being an IO.

**Comment by RX14** [comment]
@timcraft except it's not a StringIO because it can contain raw bytes that aren't UTF-8 code points, and renaming just `MemoryIO` doesn't fix the inconsistency in the slightest.

**Comment by RX14** [comment]
Still no movement on this? Unfortunately it's a PR that has to be merged soon after it's updated, and this PR wasn't as simple as running `s/MemoryIO/IO::Memory/g` on the repo.

**Comment by luislavena** [comment]
> Well, we could rename `IO::Delimited` to DelimitedIO, etc. I actually think that this is a better change. IO::Memory is not a memory. We have Char::Reader, but there it makes sense: it's a reader.

@asterite wouldn't this be similar to the decision of renaming `BufferedChannel` to `Channel::Buffered` and similar to `UnbufferedChannel`?

While type-to-result ratio for `IO::Memory` is more heavy, the question if is translates meaning quicker: is `MemoryIO` a type of `IO`? Is `IO::Delimited` similar?

Reading the documentation:

- `IO::Delimited` - An IO that wraps another IO, and only reads up to the beginning of a specified delimiter.
- `MemoryIO` - An IO that reads and writes from a buffer in memory.

The thing with `Char::Reader` can also be extended to `StringPool` or `StringScanner`, they are helpers that *relates* to `Char` or `String` respectively, but they are not by definition a defined subtype of `Char` or `String`.

IMO `MemoryIO` is easier to type in than `IO::Memory` but there are more things than typing speed to take in consideration :smile: 

Cheers.

**Comment by asterite** [comment]
Closed by #3563

**Pull request closed without merging**
