### PR TITLE
Clarify that unions are allowed in JSON.mapping

### PR DESCRIPTION
**Pull request by RX14**

### CODE REVIEW

**Comment by straight-shoota** [comment]
For reference: [question about this on SO](https://stackoverflow.com/questions/48029005/how-does-json-mapping-macro-work-with-union-types-of-arguments)

Besides fixing the obvious mistake it would also be great to clarify the behaviour regardin union types.

**Comment by bcardiff** [comment]
It's not true that an alphabetical order is used. First the primitive ones are used https://github.com/crystal-lang/crystal/blob/master/src/json/from_json.cr#L192
and the the alphabetical of non primitives is used (but mainly as a side effect of [how unions are stored](https://github.com/crystal-lang/crystal/blob/8514651b7721b6460f313ec50a218ff1e2a1779c/src/compiler/crystal/program.cr#L354))

**Comment by RX14** [comment]
@bcardiff I'm half tempted to use the dreaded words "implementation-defined behaviour" to describe the order...

**Comment by asterite** [comment]
I would say "implementation defined". If two models can be parsed without problem from a same JSON, then you can't rely on which one you'll get and you probably have to use some other way to parse that.

**Comment by RX14** [comment]
Changed to just "undefined". It doesn't really matter to the user if it's implementation-defined or not. It's simply behaviour they cannot rely on, hence undefined.

**Pull request merged**
