### PR TITLE
Fix #3197

### LINKED ISSUE #3197: Aliased generic and restriction mismatch
Perhaps this another part of #2665 - but I think it's probably simpler.

```crystal
alias HashAlias = Hash

def my_fun(a : HashAlias(String, String))
  pp a
end

my_fun({"foo" => "bar"})
```
=>
```
Error in line 7: no overload matches 'my_fun' with type Hash(String, String)
Overloads are:
 - my_fun(a : HashAlias(String, String))
```

### PR DESCRIPTION
**Pull request by ozra**

### CODE REVIEW

**Comment by ysbaddaden** [comment]
Look great, but I'd like @asterite to look at this first :-)

**Comment by ozra** [comment]
Yes, I think that's best too; it works, but it might not "be the right place for solving it" B-) I'm still far from groking the semantic parts of the compiler.

**Comment by asterite** [comment]
@ozra Thank you, the fix is OK :-)

There's no need to only `remove_alias` if it's an `AliasType`: the method is also defined on `Type` as returning `self`.

Lately I'm trying to document the compiler as much as I can. Ideally anyone should be able to jump in and understand the code (I honestly believe it's not that complex). But it might take a while for me to do so.

**Comment by ozra** [comment]
Yes, I've seen more and more comments - they're really helpful in acquainting the terrain! Keep it up!

**Pull request merged**
