### PR TITLE
updating the example comments to be usable by curl

### PR DESCRIPTION
**Pull request by wontruefree**
This helps with problems mentioned in issue 5728
https://github.com/crystal-lang/crystal/issues/4728

### CODE REVIEW

**Comment by jhass** [comment]
Mh, I really wonder whether we can't bind to all addresses localhost (or any named host) has.

**Comment by wontruefree** [comment]
Isn't this a problem with some local resolvers?
And this is only a documentation change.

**Comment by RX14** [comment]
Binding to `localhost` should be the same as binding to `127.0.0.1` is ipv4 is enabled and `::1` if ipv6 is enabled and both if both are enabled. Or actually whatever addresses `localhost` resolves to.

The point is that we shouldn't have to change this documentation: it should work. If it doesn't it's a bug and it should be fixed instead of jsut changing the documentation.

**Comment by wontruefree** [comment]
I like localhost better.  If someone closes the issue I will close the PR.

**Comment by bcardiff** [comment]
I recall issues on mac where using localhost was not working and 127.0.0.1 was the fix on different products/stacks. Maybe I am used to write whether I want to bind to 0.0.0.0 or to 127.0.0.1 so many times that seems natural to me that an ip is used instead of the localhost word.

If the scenario could be improved for localhost, I would say to create a different issue. Having better documentation for the current state is an improvement.

**Comment by RX14** [comment]
`127.0.0.1` is an ipv4 addreess. I don't think we should be encouraging solutions that only work for ipv4, not ipv6.

**Comment by wontruefree** [comment]
After more searching I think the curl can be fixed but I am not sure if this is the solution.  However the browser does not work for me unless I add the protocol and content-length.

Something like this.

```
require "socket"

server = TCPServer.new("localhost", 1234)
loop do
  server.accept do |client|
    message = client.gets
    client << "HTTP/1.1 200\n"
    client << "Content-Length: #{message.as(String).size}\n\n"
    client << message # echo the message back
  end
end
```

**Comment by wontruefree** [comment]
I think more needs to be discussed about this in the issue and what the examples should be showing.

**Pull request closed without merging**
