### PR TITLE
Drop parentheses around `->` inside certain comma-separated lists

### LINKED ISSUE #14216: `ProcNotation` followed by anonymous `fun` parameter breaks on macro interpolation
This is valid code, because parameters of lib funs do not require a name:

```crystal
lib Foo
  # first parameter is `x : ::Proc(Int, Int)`
  # second parameter is ` : Int`
  fun foo(x : Int -> Int, Int)
end
```

Macro interpolation of the above AST node adds a pair of parentheses around the `ProcNotation` restriction:

```crystal
lib Foo
  fun foo(x : (Int -> Int), Int) # Error: expecting token '->', not ')'
end
```

Either the syntax should allow this, or those parentheses should be dropped. This appears in the Bionic bindings and is not a typo:

```crystal
# src/lib_c/aarch64-android/c/pthread.cr
lib LibC
  fun pthread_create(__pthread_ptr : PthreadT*, __attr : PthreadAttrT*, __start_routine : Void* -> Void*, Void*) : Int
end
```

Related: #11966

### PR DESCRIPTION
**Pull request by HertzDevil**
Fixes #14216.

The formatter is not affected, since it will preserve any number of parentheses around a `ProcNotation`.

### CODE REVIEW

**Review by straight-shoota — APPROVED** [review]

**Comment by HertzDevil** [comment]
I have been thinking about this: if macro interpolation transforms `{T}` to `::Tuple(T)`, `{x: T}` to `::NamedTuple(x: T)`, `T[1]` to `::StaticArray(T, 1)`, and `T*` to `::Pointer(T)`, wouldn't it make sense to simply turn all the `->`s into `::Proc`s? Maybe that would be the simplest fix after all?

That leaves unions but IIRC there were still some edge cases making `T | U` and `::Union(T, U)` not semantically equivalent.

**Comment by straight-shoota** [comment]
Yeah I think that makes sense 👍

**Comment by HertzDevil** [comment]
Well:

```crystal
lib Lib
  fun foo(x : Int, Int)           # Error: expecting token '->', not ')'
  fun foo(x : Pointer(Void), Int) # Error: expecting token '->', not ')'
end
```

**Review by straight-shoota — APPROVED** [review]

**Comment by straight-shoota** [comment]
This seems awefully complex, but I guess there's no other way to handle the ambiguity issues around `->` 😭

**Pull request merged**
