### PR TITLE
Expose HTTP response headers in HTTP::WebSocket::Protocol

### PR DESCRIPTION
**Pull request by skateman**
Sometimes you might be curious about the HTTP response headers after a successful websocket upgrade. I haven't found any tests for the Protocol class, so I did not create any tests. However, if you really need tests for this, please let me know if I have to create a file or add something into the spec file for `HTTP::Websocket`.

### CODE REVIEW

**Comment by straight-shoota** [comment]
The `Protocol` class is an implementation detail and hence not tested. So I'm not sure how this patch is supposed to be usable. People don't directly interact with `WebSocket::Protocol`. Since there are no public methods, the response headers are entirely inaccessible.

If this is to be added, it should probably be added in the `WebSocket` class.

**Comment by skateman** [comment]
@straight-shoota you're right, I forgot to push the getter/delegation.

**Comment by straight-shoota** [comment]
Still, the ivar should go to `WebSocket`, not `Protocol` it has nothing to do with the protocol implementation.

**Comment by skateman** [comment]
@straight-shoota I agree, but as far as I understand, the response headers are only available [this](https://github.com/crystal-lang/crystal/pull/7211/files#diff-c30599f135415930b128db8e9064bbe2R242) method. So I have to expose it somehow, you're saying the instance variable is not a good solution can you please tell me in what direction should I change it? I'm not that familiar with Crystal, not sure how else can I pass these headers to the `WebSocket` class.

**Comment by straight-shoota** [comment]
Why don't you open an issue first, detailling what exactly you want to achieve? 
That's probably better to discuss how this can be implemented.

**Comment by straight-shoota** [comment]
Closing because this PR doesn't do what it's supposed to. The issue is tracked at #7213.

**Pull request closed without merging**
