### PR TITLE
Add forward_missing_to @object to Colorize

### PR DESCRIPTION
**Pull request by wyhaines**
While working with code in a few other areas, including Benchmark::IPS, I tripped a little over the fact that a colorized String (or any other object) becomes an instance of `Colorize::Object(T)`, and can no longer be used as it's original object type.

There are many times where one may want to inject some color or mode changes into a String and still transparently use the resulting object as if it were a String.

This patch adds a `forward_missing_to @object`, which in most cases where the type signature allows it, lets a colorized object like a colorized String duck type its way through life as if it were still a String, which simplifies many things.

The patch also adds a `mode` method like the `fore` and `back` methods, because without it, `forward_missing_to` caused spec failures. I also added a basic spec to exercise the method forwarding as part of this change.

### CODE REVIEW

**Comment by straight-shoota** [comment]
This doesn't click with me right away. Could you detail a bit about your use cases? Ideally, please create an issue for this so we can separate general discussion about this feature from the concrete implementation in this PR.

**Comment by asterite** [comment]
> and still transparently use the resulting object as if it were a String

In my mind `colorize` is the last thing you call before moving that object into the output. If you need to do some things with the original string, I would preserve that as a separate variable.

I think adding `forward_missing_to` would make things a bit harder to understand.

**Comment by wyhaines** [comment]
As requested, to short circuit a lot of discussion on the PR, I have created an issue:

https://github.com/crystal-lang/crystal/issues/13007

**Comment by wyhaines** [comment]
I am closing this PR, having been convinced that the use case isn't generally worth the potential downsides.

**Pull request closed without merging**
