### PR TITLE
Fix `Complex.multiplicative_identity`

### LINKED ISSUE #12050: Complex.multiplicative_identity doesn't work
I was doing some random test and I discover that `Complex.new(1,3).multiplicative_identity` doesn't compile. Then I realize that it was missing a `self.` to the method definition:

https://github.com/crystal-lang/crystal/blob/b7377c0419ae5c1ce91e8298f075b3ff15636c54/src/complex.cr#L268-L274

## crystal version
1.4.1

### PR DESCRIPTION
**Pull request by I3oris**
Fix #12050 and add spec for `Complex.zero`, `Complex.additive_identity` and `Complex.multiplicative_identity`.

### CODE REVIEW

**Review by straight-shoota — APPROVED** [review]

**Comment by HertzDevil** [comment]
Can we rename the def directly without deprecating the instance method here?

**Comment by beta-ziliani** [comment]
Technically, yes, since it was clearly never used, but what name do you want to give it? I mean, it pars with the additive identity, so it sounds like the right name (or the two should be renamed, and then it's a breaking change).

**Comment by straight-shoota** [comment]
Who says it's never been used? It's very unlikely, but not guaranteed. Probably better be safe than sorry.

**Review by beta-ziliani — APPROVED** [review]
Thanks @I3oris !

@HertzDevil: For the moment, I'm putting it in the milestone, but we can do the renaming later before 1.5.0.

**Comment by HertzDevil** [comment]
To be clear it wasn't about renaming the method altogether, but `Complex.multiplicative_identity` and `Complex#multiplicative_identity` are still two different methods, and the latter exists before 1.0.0. So following standard practice it should be marked as `@[Deprecated]` however unlikely it is used in the wild.

**Comment by beta-ziliani** [comment]
You're totally right. 

@I3oris do you mind keeping the original code, adding `@[Deprecated("Use `Complex.multiplicative_identity` instead")` (or similar)? Or we can handle it if you prefer. Thanks!

**Comment by I3oris** [comment]
Hello,

I think it's not necessary to set the method deprecated, it's sure nobody never used, actually, the previous method doesn't compile at all, `new` is not defined as instance method (https://play.crystal-lang.org/#/r/d62f). And it seem to be like that since its creation in #10151.

**Comment by straight-shoota** [comment]
You're right. The method doesn't compile. So there's no need for deprecation.

**Pull request merged**
