### PR TITLE
Remove IO#read_nonblock

### PR DESCRIPTION
**Pull request by jhass**

### CODE REVIEW

**Comment by asterite** [comment]
This is because using `raw` would be the same, right?

**Comment by jhass** [comment]
Using `raw` doesn't has anything to do with any change of this PR, so I'm not sure what you're referring to.

**Comment by asterite** [comment]
Mmm... I mean, raw plus the fact that a file descriptor is non-blocking by default would achieve the same thing as the old read_nonblock?  I'm confused because I don't know what was the purpose of read_nonblock, maybe it had sense before we turned everything non-block by default?

**Comment by jhass** [comment]
I guess so yeah. `raw` simply affects how the terminal communicates to our process, not how the IO behaves.

**Pull request merged**
