### PR TITLE
Improve Hash#values_at docs

### LINKED ISSUE #9952: Hash: indexed or not (officially)?
This issue's goal is to clarify if the Hash is supposed to be exposed indexed or not.

The Hash implementation uses an index and preserves order, that's why it is possible to have methods related to key indexes, like `Hash#key_index(key)`, `#first_*`, `#last_*`, and hidden implementation method like `get_entry(index)`.

## Today

- The public API states an Hash is ordered
> Enumeration follows the order that the corresponding keys were inserted.
- some methods mention indexes `#key_index` and `values_at(*indexes : K)` (the former should be `keys`)
- indeed, some methods related to indexes lacks. Note that `Indexable#[index]` would conflict with the existing `Hash#[key]`

## Next

- If Hash is assumed to be indexed, maybe investigate to add methods related to indexes, maybe even including `Indexable` (:warning: conflicts)
- If Hash is not assumed to be indexed, drop `Hash#key_index`.

Anyway, `Hash#values_at(*indexes : K)` should be renamed to `Hash#values_at(*keys : K)`.

### PR DESCRIPTION
**Pull request by j8r**
Closes #9952.

### CODE REVIEW

**Comment by docelic** [comment]
Hey @j8r, I was looking at the definition of methods `#key_index` and `#values_at`.

```
def key_index(key) 
def values_at(*indexes : K)
```

Both of these functions accept the key(s) as argument, not indexes.
In that context, I believe that, while you are at it, `values_at` should actually be fixed to say `*keys` rather than `*indexes`, right?

**Review by straight-shoota — APPROVED** [review]

**Comment by straight-shoota** [comment]
@docelic That's already in this PR!

**Comment by j8r** [comment]
That's not a breaking change, how can it be @straight-shoota ?

**Comment by straight-shoota** [comment]
I probably didn't realize the argument rename doesn't have a practical relevance because it's a splat.

**Review by asterite — APPROVED** [review]

**Pull request merged**
