### PR TITLE
Remove now unsupported llvm versions

### PR DESCRIPTION
**Pull request by rdp**

### CODE REVIEW

**Comment by rdp** [comment]
6.x etc. all seem to fail compiling these days.

**Comment by caspiano** [comment]
Would it be worth adding a smoke test for the range of supported LLVM versions?

**Comment by Sija** [comment]
Removing supported llvm versions should incl. code cleanups as well.

**Comment by j8r** [comment]
Yes, some macro conditions can be removed at https://github.com/crystal-lang/crystal/blob/master/src/llvm/ext/llvm_ext.cc

**Comment by straight-shoota** [comment]
> Would it be worth adding a smoke test for the range of supported LLVM versions?

A first step for that is in #11343. It's not a smoke, but a full compiler test.

**Comment by HertzDevil** [comment]
What do we do from here? Add a matrix to the LLVM 13 job?

**Comment by straight-shoota** [comment]
Adding CI for older, supported versions LLVM is not really a part of this issue. It is about removing older, unsupported versions.

The way forward, additionally to removing the versions from `llvm-versions.txt`, is cleaning up code that specifically deals with the removed versions.

**Comment by HertzDevil** [comment]
I think we should drop support for 7.1 as well because it doesn't support methods like `LLVMBuildLoad2` that would eventually become necessary due to LLVM's transition to opaque pointers (see #12484).

**Comment by straight-shoota** [comment]
Yeah, I think we can safely drop support for LLVM 7 at this point.

**Comment by straight-shoota** [comment]
Or maybe even more?

In light of https://forum.crystal-lang.org/t/compilation-issue-with-crystal-1-6-x/5038 it seems that older LLVMs can cause problems. So perhaps we should at least spit out a warning when linking against anything older than LLVM 13 or so?

**Comment by HertzDevil** [comment]
It is too quick to say that it's LLVM's problem instead of ours with that issue. Besides, LLVM 11.1 was the most recent version available by the time Crystal 1.0.0 was released, and it would be odd to drop support for it within Crystal 1.x.

There is also the question of whether certain long-term support OSes could keep up with LLVM releases; we certainly hope that the default LLVM works out of the box. For reference, LLVM bumps its major version every 6 months or so.

**Comment by straight-shoota** [comment]
Yeah, I don't mean to anticipate the actual cause of that issue. Whether that is on LLVM or not, we *know* that there are relevant bugs in older LLVM releases.

And we don't need to drop support entirely, but adding a warning might be good. It can be shown when building the compiler, so it won't bother when using the compiler.

**Pull request closed without merging**
