### PR TITLE
Adds `Array#prepend` and `Array#append`.

### PR DESCRIPTION
**Pull request by chris-huxtable**
Aliases for `unshift` and `push`.

Hopefully this won't be super controversial.

The current `unshift`/`push`aren't well matched and a PITA to remember. Ruby recently, in 2.5, finally added them. I think it would make sense to add them to our `Array` as well.

### CODE REVIEW

**Comment by asterite** [comment]
They are controversial. We don't have aliases in Crystal.

**Comment by RX14** [comment]
Perhaps rename unshift to prepend, but no aliases please.

**Comment by chris-huxtable** [comment]
If absolutely no alias's are permitted I would propose replacing `unshift` and `push`. Even though that would be a crippling, breaking change.

**Comment by chris-huxtable** [comment]
If it helps I can `sed -i 's/.unshift/.prepend/g' **/*.cr && sed -i 's/.push/.append/g' **/*.cr` and push that.

**Comment by Sija** [comment]
Removing `Array#push` and/or `Array#unshift` will break a lot of code since they are well-known widely-used idioms.

**Comment by chris-huxtable** [comment]
@Sija - Thats why I am proposing the aliases.

**Comment by Sija** [comment]
@chris-huxtable I know, yet `Crystal` doesn't like those.

**Comment by chris-huxtable** [comment]
Something that I think is unfortunate as in different contexts similar functions have different names. Let alone the issue with `unshift`.

**Comment by straight-shoota** [comment]
Whatever gets decided, it will have some downside.

* `push`/`unshift` are widely known and very common accros languages, but difficult to get used to for beginners.
* `append`/`prepend` are much easier to comprehend - starting from a blank state they should really be preferred IMO. Yet, having only those would break much code and would alienate experienced programmers.
* having both would introduce aliases which should be avoided in Crystal.

I don't know which way is best. We should look for the least evil.

**Comment by chris-huxtable** [comment]
I don't really understand the aversion of aliases other then API bloat and support. Which aren't insignificant issues. But an outright 'ban' I think as equally problematic. 

One fo the other things that has confused me is the 'prescriptive' nature of crystal Which is very Python. Where as Ruby is more 'descriptive' which is one of the things i like about it. There is more then one way to skin a cat.

**Comment by Sija** [comment]
> We should look for the least evil.

No such thing exists, I'd look for better solution :)

**Comment by RX14** [comment]
But having direct aliases with no difference always creates more api for no gain. So why bother? 

I like push and pop for the end of a list, buy  also like prepend and ??? For the start of a list. 

Why not just have insert and delete with, 0 and -1 for both these cases?

**Comment by chris-huxtable** [comment]
@RX14 - That strikes me as a bit extreme.

**Comment by asterite** [comment]
Array as it is now works fine. These aliases were just recently introduced in Ruby, I never needed them. Old Ruby coders will now find these new aliases and wonder why they exist. This means they have to learn new things. Maybe decide what name to use from now on.

All of this is a big waste of time, nothing else.

**Comment by ysbaddaden** [comment]
I'm getting tired of issues and pull requests that merely revolve around "matter of taste and preference". Nobody will agree.

We have push, pop, shift and unshift. They're ubiquitous across many languages. They're fine. Close subject. Please.

**Comment by chris-huxtable** [comment]
Clearly this doesn't have support. For those who would like options I have thrown together [extras.cr](https://github.com/chris-huxtable/extras.cr) which adds `Array.append`, `Array.prepend` and others I have been shimming into projects. PR's welcome. Closing.

**Comment by rdp** [comment]
I know it came from Ruby but... `#unshift` is really awkward... :|  Rename with deprecation possible? :)

**Pull request closed without merging**
