### PR TITLE
Compiler: reset nilable vars inside block method

### LINKED ISSUE #10087: Nilable local var incorrectly initialized within method with block
This code prints `Hello` twice, but it should only do it once:

```crystal
def foo(x)
  if x
    bug = "Hello"
  end

  puts bug

  yield
end

[true, false].each do |x|
  foo(x) { }
end
```

It's happening because the implicit initialization of the `bug` variable is done in the entry block of the caller, where all the `alloca` are generated. But I think it should be done in the entry block of the method instead, so it is reinitialized each time.

### PR DESCRIPTION
**Pull request by asterite**
Fixes #10087, I think.

### CODE REVIEW

**Review by straight-shoota — COMMENTED** [review]
The example is really big and thus hard to understand. I don't have great idea to make it more concise, though.
Maybe move everything (or at least `foo`) into `Foo` namespace to directly access the class variable?

**Comment by asterite** [comment]
Good point. Spec is simpler now!

**Review by straight-shoota — APPROVED** [review]

**Review by waj — APPROVED** [review]

**Comment by waj** [comment]
Now the variable is cleared twice: right after the `alloca` and at the entry of the block. But I think is good enough for now. Thanks!

**Comment by asterite** [comment]
@waj 👋 

Good catch! I added another commit, now the variable is only reset once.

**Pull request merged**
