### PR TITLE
Compiler: add more locations

### LINKED ISSUE #5593: Compiler bug caused by Benchmark.bm
Hi,

I ran into the following when attempting to benchmark some code.

```
Module validation failed: inlinable function call in a function with debug info must have a !dbg location
  %101 = call i8* @__crystal_malloc64(i64 ptrtoint (i32* getelementptr (i32, i32* null, i32 1) to i64))

Crystal::CodeGenVisitor#finish:Nil
Crystal::Compiler#codegen<Crystal::Program, Crystal::ASTNode+, Array(Crystal::Compiler::Source), String>:(Tuple(Array(Crystal::Compiler::CompilationUnit), Array(String)) | Nil)
Crystal::Compiler#compile<Array(Crystal::Compiler::Source), String>:Crystal::Compiler::Result
Crystal::Command#run_command<Bool>:Nil
Crystal::Command#run:(Bool | Crystal::Compiler::Result | IO::FileDescriptor | Nil)
main

Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```

Version information:

```
Crystal 0.24.1 (2017-12-26)

LLVM: 5.0.1
Default target: x86_64-apple-macosx
``` 

This is the smallest repro I've been able to come up with:

```crystal

require "benchmark"

Benchmark.bm do |x|
  (1..2).each do |i|
    x.report "block #{i}" do
      i.times { 1 * i }
    end
  end
end

```

### PR DESCRIPTION
**Pull request by asterite**
Fixes #5593

This adds more missing locations.

In theory all nodes should have a location. I tried to fix most of them but many are still missing (but they can be done later). One easy way to check this is to puts a `pp node` in [here](https://github.com/crystal-lang/crystal/blob/80cbe6603f938fc2200b785bd3fb2edbd854a17d/src/compiler/crystal/codegen/debug.cr#L225) and slowly fix those cases (but I don't have time for that now).

### CODE REVIEW

**Comment by luislavena** [comment]
Quick question @asterite, this appears similar to #5595? Any difference to note?

Thank you.

**Comment by asterite** [comment]
@luislavena Yes, the previous didn't work and github doesn't let me reopen it for some reason. And then this one works (or should work, lets see what CI says), I fixed a few more things :-P

**Comment by RX14** [comment]
Is there a way to enforce all nodes have a location? Do we want that? I guess it'd mean more crashes short-term, but a more robust compiler long-term.

**Comment by asterite** [comment]
Yes, there is a way: just raise an error in the line I pointed.

Well... that would mean we would find about these problems earlier. I don't know how to guarantee every node has a location, though. Maybe the location property should be required and it should be passed when creating a node, I don't know.

**Pull request merged**
