### PR TITLE
Crystal wrapper script enhancements

### PR DESCRIPTION
**Pull request by j8r**
Follow up of #12955, helped by ShellCheck. Tested on Linux with dash, bash and zsh.

I've noticed there is no need to export `$CRYSTAL`, since it is not used anywhere else in the repository. The refactored case/in condition also now handles the case if `CRYSTAL="   "`.

### CODE REVIEW

**Comment by j8r** [comment]
This changes may be considered optional, but they improve the code clarity and reliability overall.

**Comment by HertzDevil** [comment]
The shebang should be changed if the script no longer runs on pure `sh`

**Comment by j8r** [comment]
What do you mean? It is supposed to still be POSIX.

**Comment by straight-shoota** [comment]
You mentioned you have tested it with dash, bash and zsh. Not sh.

**Comment by j8r** [comment]
`sh` is nowadays a symlink to `dash` on Debian-based OSes, and to `zsh` on mac.

I have also tried on `busybox sh` too on Alpine.
`dash` is usually the most limited shell and somewhat closest to POSIX.

**Comment by j8r** [comment]
If by `sh`, you meant `bash --posix` - yes I tried it too.

**Review by straight-shoota — APPROVED** [review]

**Comment by j8r** [comment]
I should haved merged master to the branch instead of rebasing, sorry.

**Comment by j8r** [comment]
I should have merged master to the branch instead of rebasing, sorry.

**Review by straight-shoota — APPROVED** [review]

**Review by HertzDevil — APPROVED** [review]

**Pull request merged**
