### PR TITLE
Restore STDIN|OUT|ERR blocking state on exit

### PR DESCRIPTION
**Pull request by bew**
Extracted from #5413 to have it merged faster, as it could fix issues in #2713.

### CODE REVIEW

**Comment by bew** [comment]
@bcardiff @RX14 there is an error on `test_darwin` (unrelated to this PR):
```
Undefined symbols for architecture x86_64:
  "_LLVMInitializeInstCombine", referenced from:
      _*LLVM::PassRegistry#initialize_inst_combine:Nil in L-L-V-M-5858P-assR-egistry.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by sam0x17** [comment]
fixes it for me!

```
bin$ ./crystal --version
Using compiled compiler at `.build/crystal'
Crystal 0.22.0+761 [9e09234f4] (2018-03-10)

LLVM: 4.0.1
Default target: x86_64-pc-linux-gnu
bin$ nano
bin$ 
```

**Comment by RX14** [comment]
Travis for OSX is broken because homebrew upgraded to LLVM 6. We should pin llvm@5.

**Comment by sam0x17** [comment]
Thanks a ton. Any idea when we'll see this in a hotfix/release? I'll compile master and use it locally for now.

**Comment by RX14** [comment]
0.25.0, whenever that releases.

**Pull request merged**
