### PR TITLE
Drop deprecated definitions

### PR DESCRIPTION
**Pull request by bcardiff**
I think these are all the deprecated definitions. If some are really recent and we will prefer to keep them during 1.x please comment.

For example I am not dropping the recent alias `HTTP::Params` mostly because there is no deprecation warning on it. But if others prefer it can be dropped in this PR also.

### CODE REVIEW

**Review by straight-shoota — APPROVED** [review]

**Comment by HertzDevil** [comment]
`has_attribute?` should be removed by reverting 1340fd9 and 5ebf6f0 since there is some extra code there to deal with a tentative macro deprecation mechanism.

**Comment by bcardiff** [comment]
@HertzDevil you mean reverting the name_loc forwarding to the macro interpreter, right? I think I prefer to keep those. Granted they are not used, but is a nice addition to improve error reporting in macros on future messages. The rest of those commits was reverted or adapted to annotations.

**Comment by HertzDevil** [comment]
Looks like we missed `Enumerable#join`...?

**Comment by straight-shoota** [comment]
Yeah. But that's not a big deal. Can be removed any time.

**Pull request merged**
