### PR TITLE
Reverse order of restriction/default_value in method definitions

### PR DESCRIPTION
**Pull request by asterite**
To specify a method argument with a type restriction and a default value you currently need to do:

```crystal
def foo(x = 1 : Int32)
end
```

With this PR, this is also possible:

```crystal
def foo(x : Int32 = 1)
end
```

In the future we will deprecate the first syntax.

Since we'll be making type annotations on instance variables mandatory, and since we already can do things like:

```crystal
property x : Int32
```

it makes sense if we could also do:

```crystal
property x : Int32 = 1
```

Or:

```crystal
record Point,
  x : Int32 = 0,
  y : Int32 = 0
```

Right now `x : Int32 = 1` doesn't parse, but it could eventually parse as a TypeDeclaration node with an initializer. Macros such as `property` and `record` could use this initializer. Then, of course, the TypeDeclaration node by itself would declare the var and initialize it (#919).

But, if we are going to do this, it would be nice to keep consistency and have method arguments follow the same order (which is also a bit more intuitive, I think).

### CODE REVIEW

**Comment by asterite** [comment]
(there is a bit of duplicated code in the PR, but it will go away once we remove the first syntax, so that's why I didn't bother to refactor)

**Comment by asterite** [comment]
I also made the formatter change the old syntax to the new syntax, so the migration is easier :-)

Anyone has any reason against this change? Otherwise I'll merge it. /cc @waj @jhass @ysbaddaden

**Comment by ysbaddaden** [comment]
Syntax looks weird. But the original was just as weird, so I guess it won't change much.

**Comment by ozra** [comment]
I like it, that's how it's currently haxored together in Onyx, though, there, for the inst-var, two consecutive nodes are gen'ed in order to handle the restriction and the assign.

If there's anything I can be tasked with to get it to use a single node, I'd be happy to help.

**Pull request merged**
