### PR TITLE
Add explanatory message to linker command output on link failure

### PR DESCRIPTION
**Pull request by RX14**
When the linker fails to find shared object files, print an explanatory message after the original output to aid users in debugging their problem.

See https://github.com/crystal-lang/crystal/issues/5291.

### CODE REVIEW

**Comment by asterite** [comment]
I like this. I always thought about doing this but was lazy to.

Maybe we could show the relevant messages at the end of the compilation? I think having those new messages intermixed with everything else makes them easier to miss. Alternatively, we could show those messages in yellow, similar to `did you mean?` messages.

Yet another possibility is even checking what `lib` declarations are attached to the `-lflag` flags, and saying "development libraries for LibYAML` or something that (but maybe this doesn't help much).

**Comment by RX14** [comment]
@asterite yeah I think highlighting in yellow is a good idea. I'll do that.

**Comment by RX14** [comment]
Added colour highlighting.

**Comment by asterite** [comment]
Just tried this in mac: it doesn't work. The error I get is:

```
ld: library not found for -lfoo
```

so we probably need a different path for mac.

**Comment by RX14** [comment]
On that note: a test file
```
@[Link("nonexistant")]
lib Nope
  fun bar
end

Nope.bar
```

Running this should produce the error.

**Comment by RX14** [comment]
@asterite The difference is `lld` vs gnu `ld`. `gold` and `bfd` use "cannot find -lfoo" the same as GNU ld.

I'll just replace both strings on all platforms.

**Comment by RX14** [comment]
Fixed when using `lld`.

**Comment by asterite** [comment]
Still doesn't work for me. None of the `gsub` calls catch the error I get:

```
ld: library not found for -lfoo
```

**Comment by RX14** [comment]
@asterite oh, looks like the strings are different on my lld to yours...

**Comment by asterite** [comment]
Mmm... I'm using `ld` on mac, not sure it's GNU-related, gold, or anything like that.

**Comment by RX14** [comment]
@asterite updated!

**Pull request merged**
