### PR TITLE
Allow flat rescue/ensure/else block in do/end block

### PR DESCRIPTION
**Pull request by MakeNowJust**
This feature is imported from Ruby 2.5: https://bugs.ruby-lang.org/issues/12906

Now, we can write such a code:

```crystal
%w(foo bar).each do |x|
  raise x
rescue e
  p e
end
```

### CODE REVIEW

**Comment by RX14** [comment]
Is there any examples where this could be used in the stdlib? I think they would help a lot in making a decision on this PR.

**Comment by straight-shoota** [comment]
There are quite a few:

* [compiler/crystal/codegen/cache_dir.cr:81](https://github.com/crystal-lang/crystal/blob/master/src/compiler/crystal/codegen/cache_dir.cr#L81)
* [compiler/crystal/macros/macros.cr:196](https://github.com/crystal-lang/crystal/blob/master/src/compiler/crystal/macros/macros.cr#L196)
* [compiler/crystal/semantic/top_level_visitor.cr:618](https://github.com/crystal-lang/crystal/blob/master/src/compiler/crystal/semantic/top_level_visitor.cr#L618)
* [compiler/crystal/tools/doc/highlighter.cr:11](https://github.com/crystal-lang/crystal/blob/master/src/compiler/crystal/tools/doc/highlighter.cr#L11)
* [file_utils.cr:218](https://github.com/crystal-lang/crystal/blob/master/src/file_utils.cr#L218)
* [file_utils.cr:313](https://github.com/crystal-lang/crystal/blob/master/src/file_utils.cr#L313)
* [http/common.cr:222](https://github.com/crystal-lang/crystal/blob/master/src/http/common.cr#L222)
* [kernel.cr:132](https://github.com/crystal-lang/crystal/blob/master/src/kernel.cr#L132)

**Comment by ysbaddaden** [comment]
My gut reaction was: "oh, looks sweet". It fits with the `def/rescue/end` syntax we already have. Looking at some of the stdlib examples, I believe it would be nice sugar.

Would the following work?

```crystal
spawn do
  something
rescue ex
  logger.error(ex)
end
```

**Comment by MakeNowJust** [comment]
@straight-shoota Thank you very much!! And we should fix them after merged this and released next version.

@ysbaddaden Yes, of course!

**Comment by asterite** [comment]
Can the formatter handle this?

**Comment by MakeNowJust** [comment]
@asterite Of course. I did't touch formatter code, but formatter worked fine. That's fantastic.

**Comment by RX14** [comment]
Would be nice if we cleaned up the places where rescue was in a block in the stdlib. 

My first thought was that it doesn't look right because I'm not used to it, but its consistent with the other block types like def and begin, so I think it's fine. Its a bit more visually noisy than the def and begin variants in the language already though.

**Comment by RX14** [comment]
Oh, and a formatter spec would be nice even if it wasn't broken before.

**Comment by straight-shoota** [comment]
Just a quick thought: What about `while`? It's used very similar to a block, especially compared to `each` or `loop` (which is implemented using `while`), and perhaps it would be nice if it had similar features...
It could however lead to some misunderstandings regarding `break` and `next`. It would be reasonable to assume that both trigger `ensure`, or only `next` or maybe even none of them - depending on the context. That's why I'm skeptical, but maybe there are other thoughts about this.

**Comment by bew** [comment]
> It could however lead to some misunderstandings regarding `break` and `next`. It would be reasonable to assume that both trigger `ensure`, or only `next` or maybe even none of them - depending on the context. That's why I'm skeptical, but maybe there are other thoughts about this.

Note: there's also `next` for blocks

**Comment by straight-shoota** [comment]
True. And `break` also. So this is also relevant with respect to blocks.

**Comment by MakeNowJust** [comment]
@RX14 Added formatter spec for this.

**Comment by asterite** [comment]
I know Ruby is adding this for 2.5, but after thinking about this a bit more, I wonder if this code is clear:

```crystal
[1, 2, 3].each do |x|
  # do something
ensure
  # clean up
end
```

Is the `ensure` executed after all the items, or once for each item? I know it's after each item, but maybe it's a bit confusing. For a method there's no problem because it's done after the whole method. But for a block that can be executed many times, I don't know...

**Comment by MakeNowJust** [comment]
`ensure` runs against each items, it seems clear to me because `ensure` appears inside block and the block runs against each items.

**Comment by asterite** [comment]
I still :+1: this

**Comment by Brusalk** [comment]
My 2c is that I don't find it _that_ obvious (at a glance) that the ensure will be executed for each block invocation. I like the syntax for blocks that'll execute exactly once, for sure.

I think we should be sure to very clearly and explicitly document this behavior.

**Pull request merged**
