### PR TITLE
Separation of constructor methods in docs

### PR DESCRIPTION
**Pull request by Sija**
Simple implementation of idea from issue #4071.

### CODE REVIEW

**Comment by jhass** [comment]
Mmh in general I like this, what I would even more like however is if it also would include any factory methods, so I come to wonder if this wouldn't decrease the visibility of these, since you will no longer scan the class methods in order to discover the ways you can get an instance of the class.

**Comment by Sija** [comment]
@jhass I'd love to include factory methods as well, alas I couldn't find any decent way to filter them out of regular class method list (except by checking return type which is not that reliable since it might be unset).

**Comment by bcardiff** [comment]
Maybe we should add something like `:nodoc:` to set the section.

`
# :factory:
# :constructor:
# :section=constructor:
`

**Comment by Sija** [comment]
👍  for `:factory:`

**Comment by bcardiff** [comment]
NB: If a comment is applied to mark as factory, then the subtraction of methods needs to be done on class and instance methods.

```crystal
class Nat
  # :factory:
  def self.zero
  end

  # :factory:
  def succ
  end
end
```

**Comment by ysbaddaden** [comment]
Do we really want to start introducing some documentation-specific annotations?

Instead, what about using the specified return type of class methods (which the type inference *already* uses)? Maybe it could use the inferred type, too. If a class method of class X returns a type X, then it's a factory.

**Comment by Sija** [comment]
@ysbaddaden Would be perfect, yet return type annotations are not always available IIUC.

**Comment by ysbaddaden** [comment]
Then specifying return type of factories would have double bonus:

- be inferred by the compiler;
- be explicit in docs.

Eventually, could the doc generator infer types? just like the compiler does (first pass)? that seems doable, to me.

**Comment by Sija** [comment]
@ysbaddaden I've pushed another commit adding factory methods to the list.

**Comment by bcardiff** [comment]
@ysbaddaden 
> Eventually, could the doc generator infer types?

Not necessarily. The type inference act upon invocation. The only invocations could be the one in the specs.

I'm ok with using an explicit return type as a flag to identify factory methods.

**Comment by Sija** [comment]
Anything more to do here before merging?

**Comment by asterite** [comment]
@Sija I think this needs a bit more discussion, though initially I really like the idea :-)

**Comment by Sija** [comment]
@asterite Sure thing, I was a bit too hasty with "before merging" part ;)

**Comment by Sija** [comment]
Now, when the check is more permissive, singleton methods like `Fiber.current` will get listed as constructors. To control this behavior we could introduce, in the vein of the first proposal, `:nofactory:` doc marker.

**Comment by Sija** [comment]
@asterite any decisions yet?

**Comment by asterite** [comment]
We can separate `new` methods. But considering all class method that return `self` as constructors doesn't sound quite right. Plus, class methods are usually fewer than non-class methods, and most of them are usually constructors, so I'm not sure about this. It will bring a lot of discussions about "what is a constructor".

**Comment by Sija** [comment]
That's true, there are cases where this distinction can't be done automagically. To combine best of both worlds I'd go for new section titled "Factory methods" in which `#new` methods are added automatically + `:factory:` annotation which would allow adding given method to above-mentioned section.

**Comment by Sija** [comment]
@asterite ping? r we ready for some action? :)

**Comment by Sija** [comment]
@asterite ping :)

**Comment by asterite** [comment]
@Sija I like it! Thank you! 🎉

**Pull request merged**
