### PR TITLE
Fix String#camelcase(lower: true)

### PR DESCRIPTION
**Pull request by vladfaust**
:eyes:

### CODE REVIEW

**Comment by j8r** [comment]
I don't see how `lower` is better than `downcase`, really.
That's a bit offtopic, but should the API use `lowercase` or `downcase`, `uppercase` or `upcase` generally? Their use are mixed as for now.

**Comment by asterite** [comment]
Actually, I think `lower` is fine. In wikipedia there's "upper camel case" and "lower camel case", so `camelcase(lower: true)` would use the "lower" variant.

**Comment by vladfaust** [comment]
👍

**Comment by straight-shoota** [comment]
For reference: duplicate of #7730

**Pull request closed without merging**
