### PR TITLE
Add base64 to prelude

### LINKED ISSUE #10323: Base64 doesn't need to be required anymore
I was very surprised by this.

It turns out, Random has two methods, `base64` and `urlsafe_base64`, and Random is required by default.

I really think those two methods should belong to `Base64`. Or, they should be available only if you require base64.

### PR DESCRIPTION
**Pull request by straight-shoota**
It is already part of the prelude because `random.cr` requires `base64`,
this patch just makes it explicit.

Resolves  #10323

### CODE REVIEW

**Review by asterite — APPROVED** [review]
Thanks!

Eventually we should about having a sort of `private require` though I have no idea how would that work.

**Comment by Blacksmoke16** [comment]
Should it also be added to `docs` mian to make that explicit too?

**Comment by straight-shoota** [comment]
When it's already in the prelude, there's no reason to put it in `docs_main.cr`.

**Comment by asterite** [comment]
> When it's already in the prelude, there's no reason to put it in docs_main.cr.

For that matter, what's the benefit of putting it in `prelude` if it's already required?

**Comment by straight-shoota** [comment]
That's different: `base64` is indirectly part of the prelude, this just makes it explicit. The benefit is documentation. The entire prelude is implicitly part of the docs generator, `docs_main.cr`'s purpose is to pull in files that are not in the prelude. Some parts of the prelude are required from `docs_main.cr` as well. Others are not. This could probably be improved, but it's independent of `base64`.

**Review by jhass — APPROVED** [review]

**Review by sdogruyol — APPROVED** [review]
Thank you @straight-shoota 🙏

**Pull request merged**
