### PR TITLE
Add Gitter badge

### PR DESCRIPTION
**Pull request by j8r**
This pull request adds this gitter badge to the `README.md`:

[Join the chat at https://gitter.im/crystal-lang/crystal](https://gitter.im/crystal-lang/crystal?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

### CODE REVIEW

**Comment by Sija** [comment]
Are `utm_*` url parameters needed for anything particular (aside of feeding _Gitter_'s backend stats)?

**Comment by j8r** [comment]
This is the default parameters when a new badge is created.
I'm thankful to GitLab to bring us a nice free and now (mostly) open sourced chat.
If this non-sensitive data can help them to improve their product, I don't mind much.
We can indeed remove this paramaters if most of us really want to.

**Comment by Sija** [comment]
Well, sorry if I'll sound unthankful but bloated url looks just awful + has terrible UX (think copying it through other channels - you'd either need to edit it manually or you'll mess with Gitter's stats - since such click would not come from the badge itself anymore).

**Comment by j8r** [comment]
Agree @sija , no parameters would be the best, as said in https://github.com/gitterHQ/readme-badger/issues/37

**Pull request merged**
