### PR TITLE
Introduce floats canonicalize, min, max intrinsics etc.

### PR DESCRIPTION
**Pull request by akzhan**
See http://llvm.org/docs/LangRef.html#llvm-canonicalize-intrinsic for details.

It is first step to rework Floats hashing.

### CODE REVIEW

**Comment by asterite** [comment]
Sorry, but I don't understand why this is useful, why there are so many `{% if false %}` and what's the current problem with Float#hash.

**Comment by RX14** [comment]
In addition to what @asterite said, if there's a LLVM intrinsic why aren't we binding and using it in [instrinsics.cr](https://github.com/crystal-lang/crystal/blob/5370fafdd8744c9f5b8443bc35c65fc6926d2341/src/intrinsics.cr).

**Comment by akzhan** [comment]
@asterite There are two problems now:

1) `Float32.hash` doesn't normalize values before hash, so two representations of same floating value differ. It's wrong (as seen by Python hash algorithm, for example).

2) `Float64.hash` is totally wrong due to #3932. It will be solved later.

And I have a question - how to embed checks for existence of imported function in Library? llvm.canonicalize available from LLVM 5, llvm.minmax available from 3.N (I doesn't check which N).

@RX14 Yes, I have seen intrinsics, but doesn't understood criteria to place them into Intrinsics or LibM.  Looks like they exists everywhere.

**Comment by RX14** [comment]
Could we just xor the lower and higher 32 bits of the float64 together?

**Comment by RX14** [comment]
@akzhan We don't currently have support for LLVM 5 and we won't until at least the release candidates. There's LLVM version constants defined [here](https://github.com/crystal-lang/crystal/blob/789421cb6753a4b58a3056b1b198dbf267fafc3a/src/llvm/lib_llvm.cr#L28)

**Comment by akzhan** [comment]
> Could we just xor the lower and higher 32 bits of the float64 together?

It does bad distribution.

I prefer this:

https://github.com/python/cpython/blob/master/Python/pyhash.c#L34

**Comment by akzhan** [comment]
> We don't currently have support for LLVM 5 and we won't until at least the release candidates. There's LLVM version constants defined here

It is not the problem, I will add IS_50 constant if needed.

But `bin/crystal` doesn't compile code with `{% if LibLLVM::IS_36 `, without recompilation of itself.

OK, will replace, recompile and try.

**Comment by ysbaddaden** [comment]
No. We don't support LLVM5 and compiling and linking against LLVM5 will just fail.

**Comment by akzhan** [comment]
@ysbaddaden I want just to add

```crystal
    IS_50 = {{LibLLVM::VERSION.starts_with?("5.0")}}
```

and test for it with

```crystal
  {% if LibLLVM::IS_50 %}
  fun canonicalize_f32 = "llvm.canonicalize.f32"(value : Float32) : Float32
  fun canonicalize_f64 = "llvm.canonicalize.f64"(value : Float64) : Float64
  {% end %}
```

and other places.

To not rewrite code later.

**Comment by akzhan** [comment]
@RX14 So #4560  `frexp` is introduced to implement `Float64.hash` later. And just because it is sodlib.

**Comment by ysbaddaden** [comment]
1. it should be `.starts_with?("5.")` because there will only be major releases (and sometimes patch releases, numbered as minor);
2. don't bother with LLVM5 until we start supporting it (next september, at best);
3. fix issues in a LLVM 3.8+ compatible way, and add a note that LLVM 5+ could help.

**Comment by RX14** [comment]
`minnum` was introduced in LLVM 3.6 for the reference

**Comment by akzhan** [comment]
Thanks, @RX14. Looks like I want to get #4396 landed and forget about old LLVMs.

**Comment by akzhan** [comment]
Thanks to @RX14 and @ysbaddaden for your help.

Now it's ready.

P.S.: Sory for bad commits  since I did not have a working VM during the day.

**Comment by akzhan** [comment]
Looks like compiler cannot be built using LLVM <4.0,  it raises on LLVM 3.8/Travis:

```
in src/llvm/abi.cr:2: class declaration can't have attributes
abstract class LLVM::ABI
```

I don't know, is it OK?

**Comment by akzhan** [comment]
Looks like I must not use `LibLLVM::IS_*` anywhere in stdlib.

This pull request will be [WIP] until #4396 landed.

Anyway I can rework Float caching with `frexp` only.

**Pull request closed without merging**
