### PR TITLE
Allow linking to certain section of a type

### PR DESCRIPTION
**Pull request by Blacksmoke16**
Allows doing like `` `Foo@some-section` `` And have it generate a link like `/path/to/Foo.html#some-section`.

### CODE REVIEW

**Comment by straight-shoota** [comment]
I like the idea, but I'm not convinced about the syntax. I'd rather not add such a random new syntax feature without having a bigger plan how we'd like the doc generator to develop.

**Comment by Blacksmoke16** [comment]
@straight-shoota I think it reads fairly well, but I'm open to other suggestions.  

> I'd rather not add such a random new syntax feature without having a bigger plan how we'd like the doc generator to develop.

Couldn't that same argument be said about any doc related feature? Given that discussion is probably super low priority I my as well just close this PR now...

**Comment by straight-shoota** [comment]
> Couldn't that same argument be said about any doc related feature?

Not about any feature. But this is a feature that alters how markdown is interpreted. And this is a somewhat delicate topic and I don't think we'd be happy to carry around a quickly introduced syntax feature when it doesn't fit with other features.
IMO it doesn't make much sense to discuss this right now and isolated. Instead, we should collect ideas like this for an upcoming doc-generator overhaul.

**Comment by Blacksmoke16** [comment]
Closing as this is pending discussions around the future of the doc generator.  Plus I have since migrated to https://forum.crystal-lang.org/t/new-documentation-site-generator-mkdocstrings-crystal/2848 which supports this.

**Pull request closed without merging**
