### PR TITLE
Improve syntax highlighter

### PR DESCRIPTION
**Pull request by I3oris**
Here the PR fixing #12408.

There separated commit for each of five issues. Plus a sixth commit for `def //`, because it required a bit more logic than other operator: `//` here is not parser as `op_slash_slash`, but as two `delimiter_start`, so we need to know two tokens before if there is a def. Instead I chosen to read the character after with `lexer.current_char` because it was more simple.

### CODE REVIEW

**Review by straight-shoota — APPROVED** [review]

**Comment by HertzDevil** [comment]
The first commit breaks the following:

Screenshot_20220902_100751

**Comment by I3oris** [comment]
Thanks for the review!
1) `foo /abc/` is problematic.., ~~because when we parse `foo /abc` we doesn't know yet if it will be a regex or a division. We need to wait the delimiter end, and store all tokens before colorize them~~.
If I understand well, `foo /abc` `foo /1` `foo /a + 5` (with space before) is always parsed as regex as long as the token before is a IDEN.
Elsewhere it's a division `1 /2` `foo() /2` `FOO /2` `@foo /2`.
 2) Both red or white look fine to me. Not sure what color choose.

**Comment by I3oris** [comment]
in fact, the coloration could depend of if it's a local variable of not:

```crystal
x = 1
x /2 # => ok division
```
```crystal
def x; end
x /2 # => Error: Unterminated regular expression (should colorized as regex)
```

However the syntax highlight have no notion of local vars because is use only the lexer. (And I think this is good, it does't need more)
So I think in this case it's acceptable to colorize `x /2` always has regex, independently of what is `x`. 
The coloration would be wrong for `x = 1; x /2` but as the main usage of highlighter is for the docs, the user could well format its code and writes  `x = 1; x / 2`.

**Review by straight-shoota — APPROVED** [review]

**Comment by I3oris** [comment]
I push the commit for colorize `$?` `$~` in white. If anyone would prefer in red you can tell it, but I finally choose to do the same as before. :man_shrugging:

**Comment by I3oris** [comment]
What's wrong with the CI? Do I miss something with 1.5.1? (Note I'm not fully used with git open source process yet).

**Comment by straight-shoota** [comment]
There seem to be some connectivity issues with docker hub. Not related to any change in this PR, it's happening all over the place.

**Comment by I3oris** [comment]
Ok good news (for the PR, not in general..)

**Review by HertzDevil — APPROVED** [review]

**Comment by straight-shoota** [comment]
* Fix 1/2 treated as regex.
* Fix missing dollar in global match data index.
* Fix wrong context in string interpolation.
* Colorize all operators (&**, &+=, &&=, ...).
* Fix wrong coloration of def operators (def +, def []=).
* Fix coloration for def //.

**Pull request merged**
