### PR TITLE
Do not use globals for regex

### PR DESCRIPTION
**Pull request by asterite**
This is mainly a compiler refactor.

When you use a regex literal:

```crystal
/hello/
```

what the compiler did, before this PR, is something like this:

```crystal
if (temp = $global)
  temp
else
  $global = Regex.new("hello")
end
```

**YES, it was using global variables**, which we removed from the language a long time ago. But the code around them was still kept because it was used for regex.

This is all fine, except that if, say, someone wants to write an interpreter for crystal ( 😉  ), they will have to implement global variables just for this.

This PR changes that logic to use a constant instead. So now it's more like this:

```crystal
GLOBAL
```

Suspicious... where is GLOBAL declared? It's done internally as part of expanding the regex literal, there's no visible assignment to it. But it works!

An extra benefit is that the old check wasn't fiber/thread safe. Reading a constant is fiber/thread safe, so this isn't just a refactor to make implementing the interpreter easier to do.

~~With that, all the logic related to global variables is removed from the compiler. There was an AST node named `Global` which was still used for the special variables `$~` and `$?`: this PR renames this node to `SpecialVar`.~~

### CODE REVIEW

**Comment by HertzDevil** [comment]
Does renaming an AST node type name not constitute a breaking change to the macro language?

**Comment by asterite** [comment]
> Does renaming an AST node type name not constitute a breaking change to the macro language?

Oh, I guess so... Hmm... I'll just undo the last commit then.

**Review by straight-shoota — APPROVED** [review]
A PR with lots of code removals that still brings actual improvements is really lovely.

**Comment by asterite** [comment]
Do we know why CI fails? It seems to be failing in a lot of PRs...

**Comment by straight-shoota** [comment]
I don't know what's wrong with aarch64 specs. But it doesn't seem to be related to this patch.

**Comment by HertzDevil** [comment]
Before and after, prepared using a local instance of Compiler Explorer: https://gist.github.com/HertzDevil/182951aa615da448752729d71a45705d

**Comment by asterite** [comment]
Do you think it's better or worse? I guess worse because of the atomic initialization, right?

**Pull request merged**
