### PR TITLE
Implement Array#delete_if

### PR DESCRIPTION
**Pull request by carlhoerberg**

### CODE REVIEW

**Comment by asterite** [comment]
Thank you! But this functionality already exists: `reject!`

**Comment by carlhoerberg** [comment]
Oh that's right. `Hash` and `Deque` implements `delete_if` so I now made `Array#delete_if` an alias for `reject!`

**Comment by asterite** [comment]
Oh, I didn't know those other types have `delete_if`.

Given that Crystal tries to avoid having aliases, I think we should actually delete those methods from Hash and Deque, or rename them to reject! if they don't already exist.

**Comment by carlhoerberg** [comment]
Imho, `delete_if` reads better than reject, but anyway isn't this language
about expressiveness? Like why have `unless` when you have `if !`? That's
also just an alias...

**Comment by jhass** [comment]
`!` is a method call, so not quite an alias there :) The right comparison here would be "why have `reject { x }` when you have `select { !x }`", which clearly are not aliases anymore, they work very similarly but not the same.

While programming, expressiveness is about making code easier to follow and not giving the highest degree of possible expressions. It's good for a painter to have as many shades of red as possible, but when talking about the work piece, it reduces confusion when you can just say "use the red", instead of being able to say "use the crimson", "what's that?", "oh it's just like red". Less things you need to know makes communication and understanding easier :)

**Comment by j8r** [comment]
@carlhoerberg The semantic of `reject!` is more consistent with the "language principles" (which should be written somewhere):
- avoid aliases
- for a given method, add a trailing `!` to connote potential unwanted side-effect (like mutation)

**Comment by asterite** [comment]
I feel ambivalent about aliases. In Ruby it's nice that you can do `array.take(3)` or `array.first(3)`, same with `reject!` and `delete_if`. The downside to aliases is:
- any container will have to implement those aliases, not only in the std but in shards
- people in a team could debate or be confused about why in some places one name is used and in another another one

But that's it. I don't have a strong opinion about this. But for a really long time now we've been avoiding aliases and I don't think we should start incorporating them now.

**Comment by carlhoerberg** [comment]
There's so many aliases already, and so many method signatures for the same method, and it's all about expressiveness, convenience and developer velocity. I can't see the harm in both having `Array#<<` and `Array#push` (which again is inconsistent with `!` being used mutating effects), nor in having `Hash#delete_if` and `Hash#reject!`. 

But if you want to go purist (but still inconsistent, unless you deprecate 10% of the std lib), well, then can we at least add `delete_if`, `push` etc. to the docs so it's searchable?

**Comment by asterite** [comment]
The reason we have `<<` and `push` is because they were the first things we added to the std, before we decided we don't want aliases.

Thinking a bit more about this, `push` is slightly different in that it allows multiple elements to be added at once.

Another thing is, `Array` can be used as a stack. So you can do `push` and `pop` in sections of the code to make it clear it's being used as a stack.

But `reject!` and `delete_if` have the same semantic and don't provide a different context.

I think it's okay to add `delete_if` to docs if that makes it easier to search them. But it only makes it easier for people coming from Ruby, so it won't benefit everyone. I don't know how it should be mentioned in the docs... "If you come from Ruby, this is the same as `delete_if`"? Reads a bit weird.

In any case, I don't take decisions anymore about these things, I limited myself to just fixing bugs. So the other core team members will have to decide this.

**Comment by straight-shoota** [comment]
Maybe we should consider standardizing on either `delete_if` or `reject!` for all container types. Having different method names for the same thing on different types is pretty much equivalent to having an alias on the same type.

**Comment by oprypin** [comment]
Hmm that's a mess.

* Array
   * [`reject!`](https://crystal-lang.org/api/0.35.1/Array.html#reject!(&)-instance-method) returns `self`
* Hash
   * [`reject!`](https://crystal-lang.org/api/0.35.1/Hash.html#reject!(&block:K,V-%3E_)-instance-method) returns `self` or `nil`
   * [`delete_if`](https://crystal-lang.org/api/0.35.1/Hash.html#delete_if(&)-instance-method) returns `self`
* Deque
   * [`delete_if`](https://crystal-lang.org/api/0.35.1/Deque.html#delete_if(&)-instance-method) returns `true` or `false`

Also note on `Hash`'s implementations. For some reason one of them defers deletions until after the end of iteration, while the other one considers it fine to delete during iteration.

**Comment by j8r** [comment]
@oprypin If it was done like this for Hash, it was for a reason:
```cr
h = {"one" => "ONE", "two" => "TWO"}
h.each do |k|
  h.delete k
end
p  h {"one" => "ONE", "two" => "TWO"}
```

**Comment by j8r** [comment]
@oprypin If it was done like this for Hash, it was for a reason:
```cr
h = {"one" => "ONE", "two" => "TWO"}
h.each do |k|
  h.delete k
end
p  h #=> {"one" => "ONE", "two" => "TWO"}
```

**Comment by asterite** [comment]
Maybe you'd like pp use each_key

**Comment by j8r** [comment]
Ha sorry :sweat_smile: . I thought Crystal got me saved, but #8893 not merged yet. I'm still quite sure it was done for a reason.

**Comment by j8r** [comment]
Not sure if has a real use-case, there can be a difference between `Hash#reject!` and `Hash#delete_if`:
```cr
h1 = {1 => "1", 2 => "2"}
h2 = h1.dup
h1.reject! do |k, v|
  h1[k - 1] = (k - 1).to_s
end
p h1 #=> {0 => "0", 1 => "1"}

h2.delete_if do |k, v|
  h2[k - 1] = (k - 1).to_s
end
p h2 #=> {0 => "0"}
```

**Comment by asterite** [comment]
It seems I implemented `delete_if` and somebody else implemented `reject!` so I'm inclined to say `delete_if` is the correct one ;-)

Just kidding.

I think deleting while iterating the hash is totally fine because in the current implementation the deleted entry is just marked as deleted, so it's totally safe to do that. And it's more efficient than building a secondary list of keys.

Next steps:
- remove `delete_if` from `Hash` and `Deque`
- rename `Deque#delete_if` to `Deque#reject!`

Let me know if someone wants to do it. Otherwise I'll do it next week.

**Comment by j8r** [comment]
By the way, why `Hash#each` yields a tuple and not the key and value (why `yield({key, value})` vs `yield key, value`)?

**Comment by oprypin** [comment]
To satisfy interface `Enumerable({K, V})`

**Comment by bcardiff** [comment]
Given that the discussion is settled on the `reject` side I'm closing this PR.

It's still pending if we should keep `Hash#reject!` to return always `self` (which would be a silent breaking-change) or to make `{Array, Dequeue}#reject!` return `self` or `nil`. Ruby does the latter and it will also be a type-safe breaking-change. It sounds to me is the right way to go.

**Pull request closed without merging**
