### PR TITLE
Change short_reference for top-level methods to `::foo`

### PR DESCRIPTION
**Pull request by keshavbiswa**
Closes part of: #13957

### CODE REVIEW

**Comment by straight-shoota** [comment]
A couple of specs expect the old format and break due to this change. The expectations need to be adjusted accordingly.

**Comment by Blacksmoke16** [comment]
@keshavbiswa As called out in https://github.com/crystal-lang/crystal/blob/master/CONTRIBUTING.md#minimum-requirements, try not do force pushes. Normal commits are preferred 🙏.

**Review by straight-shoota — APPROVED** [review]

**Review by HertzDevil — APPROVED** [review]

**Comment by straight-shoota** [comment]
Congrats on your first contribution @keshavbiswa 🎉 Welcome to the club of compiler developers!

**Comment by keshavbiswa** [comment]
Thanks 🙂

**Pull request merged**
