### PR TITLE
Use `GC.malloc_atomic` with `GC.realloc`, not `Pointer#realloc`

### PR DESCRIPTION
**Pull request by HertzDevil**
This PR ensures that pointers allocated using `GC.malloc` and `GC.malloc_atomic` are only reallocated using `GC.realloc`. This is necessary for the interpreter to run on Windows properly, and may also be relevant on other systems if eventually the interpreter's GC is distinct from the compiler's own GC.

`Pointer.malloc` and `Pointer#realloc` are defined as primitives. For compiled code, these internally call the top-level funs `__crystal_malloc64`, `__crystal_malloc_atomic64`, and `__crystal_realloc64`, which in turn forward to the class methods on `GC`, so `Pointer` and `GC`'s methods happen to be exactly the same:

https://github.com/crystal-lang/crystal/blob/a5054ce80659975b7bf5ac5240c3bb63dc85093c/src/gc.cr#L16-L47

For interpreted code, the same primitives call `Pointer.malloc` and `Pointer#realloc` from the compiler itself:

https://github.com/crystal-lang/crystal/blob/a5054ce80659975b7bf5ac5240c3bb63dc85093c/src/compiler/crystal/interpreter/instructions.cr#L1004-L1015

Currently, the compiler on Windows is statically linked, whereas `LibGC` inside interpreted code would be dynamically loaded (using #11573 and #12140); there would be two copies of the garbage collector which do not conflict like on Unix-like systems. Consequently, allocating memory from one allocator and then reallocating it in another is undefined behavior.

All instances of `GC.malloc` in the repository are already paired to `GC.realloc`. Note also that adding `@[Primitive]` to `GC`'s class methods doesn't work because these have different signatures than the methods in `Pointer`.

### CODE REVIEW

**Review by straight-shoota — APPROVED** [review]

**Comment by straight-shoota** [comment]
I'm wondering if we should also take steps to reduce the error probability through the API. `Pointer#realloc` is very inviting to be used, even if the pointer was allocated via `GC.malloc`. The fact that it doesn't make a difference in most cases, doesn't help either.

An idea might be to make `Pointer#realloc` a class method `Pointer.realloc`. So there'd be `Pointer.malloc`/`Pointer.realloc` analog to `GC.malloc`/`GC.realloc`.

**Comment by asterite** [comment]
There's another one in `io_spec.cr`

I think the main issue is that there's no `Pointer.malloc_atomic`, so we have to use `GC.malloc_atomic`. So maybe we should consider adding that. It would remove all uses of `GC.realloc`.

We could even hide `GC.malloc` and `GC.realloc` completely with that.

**Comment by straight-shoota** [comment]
`Pointer.malloc` uses `GC.malloc_atomic` when the pointer type is known to contain no pointers.
So I suppose it could simply be implemented in stdlib by delegating to `Pointer(UInt8).malloc`:
```cr
struct Pointer(T)
  def self.malloc_atomic(size : UInt64)
    Pointer(UInt8).malloc(size * sizeof(T)).as(T*)
  end
end
```

**Comment by HertzDevil** [comment]
It would be odd if `Pointer.malloc` may allocate atomically and `Pointer.malloc_atomic` always does so. For consistency we would need yet another method that never allocates atomically. In particular, this seems to be required here:

https://github.com/crystal-lang/crystal/blob/f160040b7f073f6cb56f2c440b2be521f84a5003/src/log/metadata.cr#L33-L38

This raises another question actually. If the interpreter calls `Pointer(Void).malloc` for _any_ use of `Pointer.malloc` in interpreted code, wouldn't that always choose the atomic version? Is that fine?

**Comment by straight-shoota** [comment]
`Pointer(Void).malloc` is actually *not* atomic because `Void` is considered as potentially containing inner pointers (because it's just unknown what type it actually is).

https://github.com/crystal-lang/crystal/blob/f160040b7f073f6cb56f2c440b2be521f84a5003/src/compiler/crystal/codegen/types.cr#L48-L61

**Pull request merged**
