### PR TITLE
examples: fix (2022-03)

### PR DESCRIPTION
**Pull request by maiha**
Let's catch up examples before Crystal 1.4 😃 

* checker: https://github.com/maiha/crystal-examples
* compiler: Crystal 1.4.0-dev [458595ff8] (2022-03-23)
* last commit: 458595ff8

Best regards,

### CODE REVIEW

**Review by straight-shoota — APPROVED** [review]

**Comment by maiha** [comment]
Also, there is an error in `crypto/bcrypt`, but I don't know how to fix it, so I am leaving it alone.
https://github.com/crystal-lang/crystal/blob/master/src/crypto/bcrypt.cr#L69

```crystal
require "crypto/bcrypt"
password = Crypto::Bcrypt.new "secret", "salt_of_16_chars"
```

```console
Unhandled exception: Invalid salt size (Crypto::Bcrypt::Error)
  from crystal/src/crypto/bcrypt.cr:93:5 in 'initialize'
  from crystal/src/crypto/bcrypt.cr:91:3 in 'new'
```

**Comment by straight-shoota** [comment]
The second argument needs to be a base64 encoded string that represents a byte slice with size 16.

**Comment by Blacksmoke16** [comment]
> On second thought... maybe we shouldn't provide an actually working salt value in the example.

I'd go as far as saying:

> You probably want to use `Crypto::Bcrypt.hash_secret` instead.

given there is really no reason to supply your own salt. PHP's docs even say:

image

**Comment by maiha** [comment]
> maybe we shouldn't provide an actually working salt value in the example

Agreed.

I want to correct only the ones that are definitely wrong, so I will leave the others as they are.

**Review by beta-ziliani — APPROVED** [review]
Thanks!

**Pull request merged**
