### PR TITLE
Fix Indexable.range_to_index_and_count to not raise IndexError

### LINKED ISSUE #10170: Negative range in nullable string brackets raises an out of bounds exception
**Expected:** `"abc"[-5..-1]?` shouldn't raise.

[Reproducible code using version 0.35.1](https://play.crystal-lang.org/#/r/a7di)

Example:

```crystal
str = "abcd"
str[1..]?    #=> "bcd"
str[-1..]?   #=> "d"
str[5..6]?   #=> nil
str[-6]?     #=> nil
str[-5..-1]? #=> Raises "Index out of bounds"
str[-5..]?   #=> Raises "Index out of bounds"
```

### PR DESCRIPTION
**Pull request by straight-shoota**
Fixes #10170

### CODE REVIEW

**Comment by Sija** [comment]
I'd add instead nilable `Indexable.range_to_index_and_count?`

**Comment by straight-shoota** [comment]
That'd be more complicated for splatting the tuple.

**Comment by asterite** [comment]
The problem with this is that now this method is inlined in every other method. Previously it was a different call. Can we maybe make two versions, one with a question mark? And a third one that yields.

**Comment by straight-shoota** [comment]
Is inlining so bad here?

**Comment by asterite** [comment]
`Indexable.range_to_index_and_count` is 20 lines long. It will make those 20 lines appear in every array instance, and that's generic.

I just read @Sija 's suggestion, that's what I'd do to (and it's how it's done everywhere else)

**Comment by straight-shoota** [comment]
I let `Indexable.range_to_index_and_count` return `nil` and used inline return/raise which works pretty fine :+1:

**Comment by Sija** [comment]
@straight-shoota It won't be needed to add all this boilerplate code (`raise IndexError.new`) if you'd add a nilable method version.

**Comment by straight-shoota** [comment]
`return nil` is still necessary, so I'd leave it like that and use a single method for both variants.

**Review by asterite — APPROVED** [review]

**Pull request merged**
