### PR TITLE
Fix: setup signal handlers in interpreted code

### LINKED ISSUE #12241: Interpreter: Process#run broken with defunct child process
Start the repl, then run another shell command via `Process`, then it's frozen forever.

The child process is defunct.

```
$ cr i
Using compiled compiler at /home/chao/git/personal/crystal/.build/crystal
icr:1:0> status = Process.run("ls")
```
```
$ ps aux | grep ls
chao      185966  0.0  0.0      0     0 pts/4    Z+   01:29   0:00 [ls] <defunct>
```

### PR DESCRIPTION
**Pull request by ysbaddaden**
Adds a couple interpreter primitives to handle signals properly between the interpreter (receives signals and forwards them to the interpreted code signal pipe) then the interpreted fiber will receive the signal (though the pipe) and handle it.

The interpreted code is thus in control of what signals it wants the process to receive, while avoiding the issue where a signal handler would be interpreted code (i.e. recipe for disaster).

Fixes the default handler for SIGCHLD into the interpreted code, so `Process.run` ~~now works as expected and~~ don't hang forever anymore. The interpreter will still randomly segfault because `fork` should probably be an interpreter primitive (see the comments below).

refs #12241

### CODE REVIEW

**Comment by ysbaddaden** [comment]
*Hypothesis:* the signal handler is messing with the interpreter. Let's try registering an alternate stack with [sigaltstack()](https://www.man7.org/linux/man-pages/man2/sigaltstack.2.html) and pass `SA_ONSTACK` to `sigaction`...

**Comment by ysbaddaden** [comment]
Hypothesis B was the issue.

We needed a couple interpreter intrinsics after all. The interpreter is registering the handlers (can't run interpreted code in C signal handlers), so it receives the signals and forwards them to the interpreted signal pipe, and the signal loop of the interpreted code will invoke the interpreted handlers :+1: 

Note: the interpreter won't handle signals anymore, but it already didn't handle them after starting to interpret code, since the interpreter bypasses the fiber scheduler (it directly resumes fibers) so the signal loop fiber was _never_ resumed.

**Comment by ysbaddaden** [comment]
With this patch, I can run the full [minitest.cr](https://github.com/ysbaddaden/minitest.cr) test suite using the interpreter :heart:

**Comment by ysbaddaden** [comment]
Running the std specs with the interpreter was painfully slow, so I compiled crystal in release mode and then tried to run the specs, but it segfaulted after a bunch of forks, and before returning reporting any progress. I tried running:

```console
$ SPEC_SPLIT="3%4" bin/crystal i spec/std_spec.cr
```

A gdb session shows that the interpreter eventually segfaults:

```gdb
Program received signal SIGSEGV, Segmentation fault.
0x0000555555e2181e in interpret ()
    at /home/julien/work/crystal-lang/crystal/src/compiler/crystal/interpreter/interpreter.cr:354
354           {% begin %}
(gdb) bt
#0  0x0000555555e2181e in interpret ()
    at /home/julien/work/crystal-lang/crystal/src/compiler/crystal/interpreter/interpreter.cr:354
#1  0x0000555555c4a753 in interpret ()
    at /home/julien/work/crystal-lang/crystal/src/compiler/crystal/interpreter/interpreter.cr:252
#2  0x00005555561ca274 in interpret ()
    at /home/julien/work/crystal-lang/crystal/src/compiler/crystal/interpreter/repl.cr:92
#3  interpret_and_exit_on_error ()
    at /home/julien/work/crystal-lang/crystal/src/compiler/crystal/interpreter/repl.cr:96
#4  0x00005555561c6587 in run_file ()
    at /home/julien/work/crystal-lang/crystal/src/compiler/crystal/interpreter/repl.cr:65
#5  repl () at /home/julien/work/crystal-lang/crystal/src/compiler/crystal/command/repl.cr:47
#6  0x0000555556126ea4 in run () at /home/julien/work/crystal-lang/crystal/src/compiler/crystal/command.cr:104
#7  0x000055555574671c in run () at /home/julien/work/crystal-lang/crystal/src/compiler/crystal/command.cr:55
#8  run () at /home/julien/work/crystal-lang/crystal/src/compiler/crystal/command.cr:54
#9  __crystal_main () at /home/julien/work/crystal-lang/crystal/src/compiler/crystal.cr:11
#10 0x000055555574cf59 in main_user_code () at /home/julien/work/crystal-lang/crystal/src/crystal/main.cr:118
#11 main () at /home/julien/work/crystal-lang/crystal/src/crystal/main.cr:104
#12 main () at /home/julien/work/crystal-lang/crystal/src/crystal/main.cr:130
```

**Comment by ysbaddaden** [comment]
Interestingly the specs that failed when calling out to `crystal i` can still fail when calling out `crystal build` on CI, meaning the interpretation ain't the issue, but something else (subprocess std in/out/err communication?) :thinking:

**Comment by ysbaddaden** [comment]
I think the problem, now, is support for `fork`.

It's likely unsafe to fork/exec in the interpreted code, and we should `fork` and `exec` from the interpreter directly... or maybe we should use [posix_spawn](https://www.man7.org/linux/man-pages/man3/posix_spawn.3.html) instead for interpreted code on UNIX? Or we should have an intrinsic for spawning a process in the interpreter (i.e. call fork/exec _out_ of the interpreted code) :thinking:

**Comment by ysbaddaden** [comment]
Merged with master and I disabled the specs that rely on `Process.run` because we'll likely need a `fork` interpreter primitive for that.

**Review by straight-shoota — APPROVED** [review]

**Comment by straight-shoota** [comment]
I expect this might conflict with https://github.com/crystal-lang/crystal/pull/15141 because signal handling is not implemented in the interpreter on Windows.

**Comment by ysbaddaden** [comment]
@straight-shoota I don't think it will have any impact: we don't use the signal loop on win32, nor do we even run the signal specs on win32, and spawning sub-processes works differently —I suspect the interpret already supports `Process.run` on Windows.

**Comment by HertzDevil** [comment]
#15141 is for compiler specs pertaining to the interpreter, stdlib specs for `Process` under the interpreter are already enabled in #14964 and indeed work.

**Comment by straight-shoota** [comment]
This is not forward-compatible. Stdlib with this patch does not work with a 1.14 compiler.

**Comment by straight-shoota** [comment]
Unfortunately, the fixup for backwards-compatibility in https://github.com/crystal-lang/crystal/pull/15178 broke this fix. It never actually worked in a released version.
It's now being restored in https://github.com/crystal-lang/crystal/pull/15892

**Pull request merged**
