### PR TITLE
Add overloads to include context for a specific entry

### PR DESCRIPTION
**Pull request by Blacksmoke16**
Reboot of #9110

* Add overloads to `Log` to support passing entry specific context.  Including:
  * Hash
  * NamedTuple
  * named arguments

### CODE REVIEW

**Comment by RX14** [comment]
Is this solved by https://github.com/crystal-lang/crystal/pull/9146 ?

**Comment by Blacksmoke16** [comment]
This PR uses #9146, but mainly just adds additional overloads to make doing what that allows easier.  E.x.

```cr
Log.info(user_id: user.id) { "User logged in" }
```

versus

```cr
Log.info { Log.context.set user_id: user.id; "User logged in" }
```

**Comment by Blacksmoke16** [comment]
Any thoughts on this?

**Comment by straight-shoota** [comment]
#9188 proposes `Entry#data` as an alternative which IMO seems more favourable.

**Comment by Blacksmoke16** [comment]
Closing in favor of #9188.

**Pull request closed without merging**
