### PR TITLE
IO::Hexdump: forward missing methods to underlaying IO

### PR DESCRIPTION
**Pull request by carlhoerberg**
Allows you do things like `IO::Hexdump#pos` when the underlaying IO supports it.

### CODE REVIEW

**Comment by asterite** [comment]
I'm a bit hesitant to use `forward_missing_to`. If you look at the stdlib, we only use it in `HTTP::Headers` and even there I'm not sure we should be using it.

Why not call `pos` on the underlying IO?

**Comment by carlhoerberg** [comment]
Ok, I'll update the PR later today

**Comment by Sija** [comment]
Or maybe use a `delegate :peek, :close, :closed?, :flush, :tty?, :pos, to: @io`?

**Comment by Sija** [comment]
@carlhoerberg https://github.com/crystal-lang/crystal/pull/8908#issuecomment-600734492

**Comment by straight-shoota** [comment]
Thank you!

**Pull request merged**
