### PR TITLE
Lint: Remove redundant `next` calls

### PR DESCRIPTION
**Pull request by Sija**
Another PR aimed at small refactors, this time - removing needless `next` calls.

### CODE REVIEW

**Comment by straight-shoota** [comment]
Hm. Not sure about this one... I think the `next` has some purpose here to highlight that this branch re-enters the block (as opposed to the `raise` and `return` branches).

**Comment by Sija** [comment]
It's pretty symmetric in re: to the other branches (and places), so yeah, I guess it's clearer this way 👍

**Comment by Sija** [comment]
Shall I close it then?

**Comment by straight-shoota** [comment]
Let's keep it open for a couple of days to see if there are other opinions.

**Comment by mattrberry** [comment]
I didn't realize until this PR that `next` accepted an argument. Tossing in a preference towards keeping it as it is for symmetry and clarity

**Comment by straight-shoota** [comment]
I think there's no strong argument in favour of this change, let's keep it as it is.

**Pull request closed without merging**
