### PR TITLE
Style: Use `loop` instead of `while true`

### PR DESCRIPTION
**Pull request by Sija**
This PR replaces `while true` usage with `loop`, which I believe is more expressive, whereas `while true` is a C reminiscence.

### CODE REVIEW

**Comment by asterite** [comment]
Please no. Compiling a loop is slower than compiling a while. Plus variables introduced in a while behave differently that in a loop, so you might be subtly changing semantic.

**Comment by Sija** [comment]
> Please no. Compiling a loop is slower than compiling a while.

Would making it a macro help?

> Plus variables introduced in a while behave differently that in a loop, so you might be subtly changing semantic.

Could you expand on that, please?
AFAIK `loop` creates a scope, whereas `while` doesn't, but that's IMO a feature ;)

**Comment by mattrberry** [comment]
> Compiling a loop is slower than compiling a while.

How significant is this? Just wondering if it's worth updating any of my applications

**Comment by HertzDevil** [comment]
I would remove `loop` by 2.0 or later because `break`ing values out of `while` is now possible.

The lexical scope is not a "nice" feature to have. At least I wouldn't consider it a feature if `while` / `loop` is the only control expression that has it and others like `if` and `case` don't.

**Comment by asterite** [comment]
I actually don't know how much slower it is. Maybe it's not slower. But this is a style change, and it's usually a personal preference. I guess I like the phrase "if it ain't broken don't try to fix it"

**Comment by Sija** [comment]
Closing PR due to the lack of interest.

**Pull request closed without merging**
