### PR TITLE
[CI] Re-enable test_darwin on circle-ci

### PR DESCRIPTION
**Pull request by straight-shoota**
This re-activates `test_darwin` job on circle-ci as a temporal workaround for #10110.

We were using this job before but it broke with LLVM 10 and got disabled in #9763. #10078 finally removed the entire `test_all_platforms` workflow on circleci because all PR-jobs were moved to GitHub Actions.

Now the job works again and the nix-based alternative on GitHub Actions is broken instead.

We can see that is works because the job did not succeed, since master is broken on macos (#10475) which wasn't reported by the GitHub Action job.

### CODE REVIEW

**Comment by straight-shoota** [comment]
Until we figure out how to fix nix-shell errors to fail the build (#10110), we should also reactive `test_darwin` on circle-ci.
This is probably even more important than #10480.

**Comment by straight-shoota** [comment]
Oh well, this was actually already merged with #10479 but it's broken again because brew setup needs some extra steps now (see 088fa18).

**Comment by bcardiff** [comment]
Note that on_osx will not exec the command on github ci: on_osx, on_linux, and on_nix_shell are mutually exclusive. 

I think you are not expecting this.

**Comment by straight-shoota** [comment]
No, I am aware of that. The fix is intended for circleci because that's breaking without the last commit (https://circleci.com/gh/straight-shoota/crystal/3069?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link).

Github Actions doesn't use brew currently. This migth affect #10480 though.

**Comment by bcardiff** [comment]
Oh. Ok. The mention of GitHub in the comment confused me.

**Review by bcardiff — APPROVED** [review]

**Pull request merged**
