### PR TITLE
Remove SemanticVersion

### PR DESCRIPTION
**Pull request by sdogruyol**
I think that we should remove `SemanticVersion` from Crystal std and move it into a shard. This PR removes it.

### CODE REVIEW

**Comment by RX14** [comment]
Why?

**Comment by sdogruyol** [comment]
Even though Crystal follows the SemVer spec, it's not directly tied with each other to be in std. Also `SemanticVersion` probably has the least practical real world usage amongst stuff which were discussed to be removed from std like `Markdown`.

**Comment by straight-shoota** [comment]
I think it's still useful as a macro feature.

Despite the name, the implementation isn't even specific to SemVer, but can even be used with different versioning schemes. So maybe it should be renamed?

But I don't see a reason to remove it, especially considering the implementation is pretty straightforward.

**Comment by asterite** [comment]
I also don't see a need to remove it, plus the macro to compare versions is very useful and without `SemanticVersion` it wouldn't be possible.

**Comment by sdogruyol** [comment]
On a second thought, it does no harm to keep it :+1:

**Pull request closed without merging**
