### PR TITLE
Turn Random::System into a module (+docs)

### LINKED ISSUE #4505: Random::System should be a module
Followup to #4450

The recently added `Random::System` takes bytes from some source provided by the system. I [suggested](https://github.com/crystal-lang/crystal/pull/4450#discussion_r118019544) [previously](https://github.com/crystal-lang/crystal/pull/3434/files#diff-eac01542bbae5a5bc3e85cae61bc5109R28) that it should be a module, not a [struct without members](https://github.com/crystal-lang/crystal/pull/4450/files#diff-7228d011591bde19e79bed9633ead94dR8).

I think this emphasizes the fact that by definition `Random::System` cannot have state associated with it, makes it more convenient to use and showcases Crystal's powerful type system. `Random::System` would be possible to use as if it's an instance of `Random` in all cases (you really just drop the `.new` part), without needing to create these fake instances -- makes no sense to keep one and makes no sense to create one every time.

```crystal
module Random::System
  extend Random
...

Random::System.is_a? Random
Random::DEFAULT.is_a? Random
```

I feel that this suggestion has been drowned out by [unrelated discussion](https://github.com/crystal-lang/crystal/pull/4450#issuecomment-303436771) so I want to make a dedicated issue for it.

### PR DESCRIPTION
**Pull request by oprypin**
Fixes #4505

### CODE REVIEW

**Comment by oprypin** [comment]
I just can't come up with a better example, but I feel that it's important to show how to pass this module as as if it's an instance. I removed the comment from it...

**Comment by ysbaddaden** [comment]
This is :+1: for me. If @mverzilli or @bcardiff agrees, please merge :)

**Comment by Sija** [comment]
@matiasgarciaisaia _osx_ build [failed](https://travis-ci.org/crystal-lang/crystal/builds/243809152) again, just FYI.

**Comment by mverzilli** [comment]
Restarted the OSX job that had failed. I know it passed in CircleCI but it feels weird to merge a PR that's red in Travis. Probably OCD, you name it!

**Comment by oprypin** [comment]
It passed BTW

**Comment by mverzilli** [comment]
Thanks!

**Pull request merged**
