### PR TITLE
Fix overflow checking for operations with mixed sign

### LINKED ISSUE #9277: i32 + u64 produces an overflow error
Reproduce with `-1 + 0u64`

I'm not entirely sure what's going on here, but the codegen listing is as such:

```llvm
  %0 = call { i64, i1 } @llvm.uadd.with.overflow.i64(i64 -1, i64 0), !dbg !11649
  %1 = extractvalue { i64, i1 } %0, 0, !dbg !11649
  %2 = extractvalue { i64, i1 } %0, 1, !dbg !11649
  %3 = icmp ult i64 %1, -2147483648, !dbg !11649
  %4 = and i1 false, %3, !dbg !11649
  %5 = icmp ugt i64 %1, 2147483647, !dbg !11649
  %6 = or i1 false, %5, !dbg !11649
  %7 = or i1 %4, %6, !dbg !11649
  %8 = or i1 %2, %7, !dbg !11649
  %9 = call i1 @llvm.expect.i1(i1 %8, i1 false), !dbg !11649
  br i1 %9, label %overflow, label %normal, !dbg !11649
```

Seems like it should be using a signed add? Perhaps something to do with `codegen_binary_extend_int`?

### PR DESCRIPTION
**Pull request by waj**
This is a rebuilt of arithmetic operations with overflow checking (`+`, `-`, `*`) to fix issues on cases with arguments of different sign.

I implemented the same approach used by clang (https://github.com/llvm/llvm-project/blob/796898172c48a475f27f038e587c35dbba9ab7a6/clang/lib/CodeGen/CGBuiltin.cpp#L3378-L3465) for the builtin operations (`__builtin_add_overflow`, etc.) and using the same workaround for multiplication of integers mixed sign. This workaround is needed to avoid internal i128 multiplication for i64 values and to avoid sigfaults for i128 multiplications.

This also adds specs to test operations between all integer types, using some extreme values from each type and contrasting results using BigInt.

Before implementing this approach I've been testing a port of [SafeInt](https://github.com/dcleblanc/SafeInt). It's a more exhaustive case by case approach that produces shorter binary code, but it requires more work and detailed testing. I assume shorter also means faster although I didn't perform any benchmark. I decided to go with this easier but correct code first.

Fixes #9277

### CODE REVIEW

**Comment by RX14** [comment]
Is it correct that this uses non-power-of-two LLVM types like `i33`?

**Comment by bcardiff** [comment]
Yes, since LLVM 2.5. Spooky 👻 

> The LLVM native code generator now supports arbitrary precision integers. Types like i33 have long been valid in the LLVM IR, but were previously only supported by the interpreter. Note that the C backend still does not support these.
https://releases.llvm.org/2.5/docs/ReleaseNotes.html

**Comment by asterite** [comment]
Hmm... yeah, like i128 is "supported". But I guess if CI passed then everything's fine :-)

**Comment by waj** [comment]
i128 is supported but it requires compiler-rt. In macOS normaly clang is used during linking and it makes it automatically available. That's why I enabled `Int128` and `UInt128` tests only in `darwin`. We need to fix it but that's a separate issue.

**Pull request merged**
