### PR TITLE
Formatter: add trailing comma to calls if there is a newline at the beginning

### PR DESCRIPTION
**Pull request by asterite**
This:

```crystal
foo(
  1,
  2
)
```

will be formatted to this:

```crystal
foo(
  1,
  2,
)
```

Before this PR a comma or not a comma were both valid. This might lead to some discussions between team members: do we use trailing commas or not? The formatter here makes that choice (as almost always) and puts a comma. The comma is nicer because adding a newline makes a diff cleaner: just a newline is added, a comma on the previous line is not needed.

This is also consistent with how array, tuple and hash literals are currently formatted. This:

```crystal
[
  1,
  2
]
```

gets formatted to:

```crystal
[
  1,
  2,
]
```

Also this:

```crystal
foo(
  1,
  2)
```

was previously left as is, but now it gets formatted to:

```crystal
foo(
  1,
  2,
)
```

Again, this is similar to what happens with arrays, tuples and hashes. This:

```crystal
[
  1,
  2]
```

gets formatted to this:

```crystal
[
  1,
  2,
]
```

However, note that if there's no newline at the beginning of the call, this is not done:

```crystal
foo(1,
  2)
```

The above will be left as-is. This is also consistent with arrays:

```crystal
[1,
 2]
```

(left as-is).

So overall this just brings consistency to call arguments and array, tuple and hash literals.

### CODE REVIEW

**Comment by straight-shoota** [comment]
I don't like how this works for arguments on a single line. Now it turns this:
```cr
Base64.strict_encode("Now is the time for all good coders\nto learn Crystal").should eq(
  "Tm93IGlzIHRoZSB0aW1lIGZvciBhbGwgZ29vZCBjb2RlcnMKdG8gbGVhcm4gQ3J5c3RhbA==")
```
into this:
```cr
 Base64.strict_encode("Now is the time for all good coders\nto learn Crystal").should eq(
  "Tm93IGlzIHRoZSB0aW1lIGZvciBhbGwgZ29vZCBjb2RlcnMKdG8gbGVhcm4gQ3J5c3RhbA==",
)
```
This example is from the patch.

I think it looks ugly if there's only a single argument.
If the method doesn't accept any more arguments adding a comma could even be considered confusing. It suggests you could add more arguments.
That's the difference between method arguments and collections: Collections can always have additional elements. Method calls don't always accept additional arguments. Maybe that's a reason why this wasn't done before?

**Comment by asterite** [comment]
I write code like that and I think it looks fine.

After all, this is and will always be a matter of preference.

**Comment by asterite** [comment]
Also Rubocop with some setting complains if you don't add a trailing comma in a call that has newlines. So I think this is fine and not something super unexpected or strange.

**Comment by asterite** [comment]
And by the way, this was wanted by @waj so we already two who want this :-)

(not that it means anything, but this isn't just me sending this proposal)

**Comment by straight-shoota** [comment]
I see what you mean to accomplish. But I'd rather have the diff for adding another argument touch the previous line instead of having trailing commas everywhere, even when they make no sense at all because there can never be another argument.

**Comment by asterite** [comment]
> If the method doesn't accept any more arguments, adding a comma could even be considered confusing. It suggests you could add more arguments.

That happens when you continue working on the code and you realize you need to pass one more thing to the method. Then you will need to add an argument, and in your diff you will have a change in a line that didn't change at all, just that a comma was added.

**Comment by j8r** [comment]
How about method arguments?
```cr
def met(
  a,
  b,
  c,
)
end
```
Gets formatted to:
```cr
def m(
  a,
  b,
  c
)
end
```
The formatting of arguments in a method call is consistent with the one of inside method declarations.

By the way I have no strong opinions on this, I 'm just showing this fact.

**Comment by asterite** [comment]
Method arguments are usually short and fit into a single line. If they fit in multiple lines, you put them one next to the other. That's less common but I can do it if it's wanted.

But my feeling here is that this is not wanted at all.

**Comment by j8r** [comment]
I didn't say I wanted this too.
Your first argument can also be applied to method calls. Usually, they are even shorter than method arguments (because no type annotations).

**Pull request closed without merging**
