### PR TITLE
OptionParser: optional options and arguments shifting

### PR DESCRIPTION
**Pull request by urde-graven**
This is patch from https://github.com/crystal-lang/crystal/issues/5338#issuecomment-452672895. Its argument's parsing changes are compatible with Ruby, but not interface to maintain backward compatibility. I also converted option_parser_spec.cr from crystal to Ruby ([option_parser_spec.rb](https://gist.github.com/urde-graven/1f4a501b2cc0ee2175f2910a8fd55a13)) with following results:
```
rspec ./option_parser_spec.rb:134 # OptionParser has required option with = (3) raises
rspec ./option_parser_spec.rb:228 # OptionParser does to_s with very long flag (#3305)
rspec ./option_parser_spec.rb:255 # OptionParser calls the handler for invalid options
rspec ./option_parser_spec.rb:268 # OptionParser calls the handler for missing options
rspec ./option_parser_spec.rb:511 # OptionParser raises if flag doesn't start with dash (#4001)
rspec ./option_parser_spec.rb:368 # OptionParser -- returns a pair with things coming before and after --
rspec ./option_parser_spec.rb:385 # OptionParser -- returns a pair with things coming before and after --, without --
```

1. Argument `--flag=` generates  empty string for option `--flag=FLAG` in Ruby, but exception OptionParser::MissingArgument in Crystal. This behavior was not changed in this patch.
2. Cosmetic difference:
```
Diff:
       @@ -1,5 +1,5 @@
        Usage: foo
       -    --very_long_option_kills=formatter
       +        --very_long_option_kills=formatter
                                             long
            -f, --flag                       some flag
            -g[FLAG]                         some other flag

```
3. `opts.invalid_option` callback does't exist in Ruby
4. ` opts.missing_option` callback does't exist in Ruby
5. `opts.on("foo", "")` is supported in Ruby and its result is `Usage: prog_name [options] [foo]`
6. (and 7.) `opts.unknown_args` callback does't exist in Ruby

Ruby also  respects for example `POSIXLY_CORRECT` env. var. ("If the environment variable POSIXLY_CORRECT is set, all options must precede non-options on the command line.") and have hidden options ` --*-completion-bash` and `--*-completion-zsh`.

### CODE REVIEW

**Comment by straight-shoota** [comment]
Compatibility with Ruby is not a huge issue. But could you please detail the breaking changes this PR introduces?

**Comment by urde-graven** [comment]
I am not aware of any for common programs that does not rely on some fixed behavior, which is unlikely. Perhaps for programs that have nonstandard  definition of flags, such as text at the end or beginning before "-" character - see changes in process_handler.

**Comment by straight-shoota** [comment]
Okay, from your description I understood there would be (relevant) breaking changes.

**Comment by urde-graven** [comment]
I don't understand, which one do you mean? Of programs, which depends on wrong behavior? So what next?

**Comment by urde-graven** [comment]
Even If there was any such marginal breaking change, I felt that I had seen that you did not hesitate to do big breaking changes somewhere else fairly commonly. So do you want to change process_handler to be sure, or what?

**Comment by asterite** [comment]
@urde-graven I think it's just to know whether this change is a breaking change so that it appears in the Changelog and people are aware of it 🙂

**Comment by straight-shoota** [comment]
@urde-graven You wrote "but not interface to maintain backward compatibility." `backward compatibility` being the keyword.

But yeah, as @asterite said, breaking changes are acceptable, but if they happen, it needs to be understood.

**Comment by urde-graven** [comment]
:smile: I'll look into the changelog, to know what you consider as breaking change. OptionParser is not a documented and has not defined interface, so you can not tell what is bug fix and what is change of behavior. In any case, I tried to make it backward-compatible, and changed only what I thought, no one would probably use and should not use. Why don't we take a look into code maybe we'll block right on it?

**Comment by asterite** [comment]
OptionParser is the first thing people use to parse options. I'm almost sure it'd used in most Crystal code out there. Why shouldn't it be used?

**Comment by urde-graven** [comment]
I didn't meant OptionParser as a whole, but its changes, for example text at the end or beginning of the flags definition.

**Comment by asterite** [comment]
Oooh... I see. Yes, makes sense.

**Comment by straight-shoota** [comment]
Closing stale PR. The changes might still be good (although it's hard to grasp, so 🤷), but the implementation isn't usable anymore.
Feel free to open a new issue about discussing these or other changes to `OptionParser` features.

**Pull request closed without merging**
