### PR TITLE
Fix spelling errors

### PR DESCRIPTION
**Pull request by camreeves**
A friend created a long list (3500+ entries) with cspell for the codebase and I've manually corrected a bunch.

A thank you to @caspiano for the initial list.

### CODE REVIEW

**Review by jhass — APPROVED** [review]
Let's hope nobody depends on the misspelled error message :D

**Review by bcardiff — APPROVED** [review]

**Comment by jhass** [comment]
I wonder if we can have something like this as a CI check / GitHub review bot thingy?

**Comment by camreeves** [comment]
> I wonder if we can have something like this as a CI check / GitHub review bot thingy?

That’s definitely possible to some extent. I found that looking for commonly transposed digraphs led to finding typos in the list much quicker but I do fear that automating it would produce lots of false positives.

**Comment by jhass** [comment]
Ah, I didn't realize you filtered by hand. Nevermind me! :)

**Comment by bcardiff** [comment]
Thank you @camreeves. 🙇  Those were a lot of tpos!

**Pull request merged**
