### PR TITLE
Improve socket specs

### PR DESCRIPTION
**Pull request by straight-shoota**
Adds new and improves existing specs for `Socket`, `TCPSocket`, `TCPServer`, `UNIXServer` and `UDPSocket`.

The diff is best viewed with `-w`/`&w=1` to ignore whitespace.

<del>This is still work in progress, I'm publishing it as PR to validate if the specs perform correctly on all platforms.</del>

### CODE REVIEW

**Comment by ysbaddaden** [comment]
Some specs are lost. For example `SO_REUSEPORT` or ipv4 connections to ipv6 server running on `::`.

**Comment by straight-shoota** [comment]
>  ipv4 connections to ipv6 server running on `::`.

Was there a explicit spec for that? I can't find it... But I can add it, of course.

**Comment by straight-shoota** [comment]
The specs that are now failing might be bugs, but I'm not sure.

* LINUX: When querying a previously set `recv_buffer_size`, a different value is returned.
* ALL: Connecting with an an IPv6 address (`::1`) to an IPv4 server (`0.0.0.0`) fails. Not sure if that is expected. The other way around (`127.0.0.1` to `::`) works.
* MACOS: UDPSocket can't send broadcast to `255.255.255.255`.

**Comment by RX14** [comment]
@straight-shoota connecting ipv6 to ipv4 is expected to fail. Binding to `::` binds to v4 and v6, binding to `0.0.0.0` binds to v4 only. Depending on kernel options though, which might make this test brittle

**Comment by straight-shoota** [comment]
So, it's probably better not to spec this?

**Comment by straight-shoota** [comment]
The spec connecting with `127.0.0.1` to `::` fails on FreeBSD.

**Comment by RX14** [comment]
@straight-shoota whether `::` binds to ipv4 is entirely OS-dependant and depends on sysctl values, see http://man7.org/linux/man-pages/man7/ipv6.7.html ctrl-f `IPV6_V6ONLY`. It's default value is controlled via sysctl. So *if* we could specifically specify this flag then we could spec the behaviour, but as it is, we leave this at default setting, so we shouldn't spec this.

**Comment by straight-shoota** [comment]
The two failing specs are now marked as pending and I'll open new issues for tracking them.
Now the specs compile on every platform.

The fails on travisci are unrelated to this PR.

**Comment by straight-shoota** [comment]
Can this get a review, please?

**Comment by straight-shoota** [comment]
I added two additional specs that came up during refactoring.

**Comment by wontruefree** [comment]
Thank you @straight-shoota !

**Pull request merged**
