### PR TITLE
Disallow creating `Big*` numbers from infinity or NaN

### PR DESCRIPTION
**Pull request by HertzDevil**
`BigInt`, `BigFloat`, `BigRational`, and `BigDecimal` do not support infinity or NaN; trying to construct them will raise SIGFPE or some other less specific Crystal exception. This PR makes such attempts raise `ArgumentError`.

### CODE REVIEW

**Review by straight-shoota — APPROVED** [review]
First character of the error message should be upper cased.

**Comment by HertzDevil** [comment]
Majority is not all and does not constitute a mandatory style guide. That's why that issue exists.

**Comment by Sija** [comment]
True, what's the point of introducing more of the style that's a lesser occurrence though?

**Comment by HertzDevil** [comment]
If the linked issue is not about stdlib errors, then that means the casing here is not an issue to begin with. Then that issue should be adapted for the stdlibs as well, not this PR.

**Comment by Sija** [comment]
> If the linked issue is not about stdlib errors [1], then that means the casing here is not an issue to begin with [2].

Nope, that's a logical fallacy. [1] does not imply [2] in any way.

Thing is, stdlib errors are title-cased in majority of the cases (remaining minority is probably more of an omission), some of the examples:

- https://github.com/crystal-lang/crystal/blob/27f395066e256a162c1c6694c476b23aa2253484/src/gc.cr#L20
- https://github.com/crystal-lang/crystal/blob/27f395066e256a162c1c6694c476b23aa2253484/src/csv.cr#L210
- https://github.com/crystal-lang/crystal/blob/27f395066e256a162c1c6694c476b23aa2253484/src/env.cr#L57
- https://github.com/crystal-lang/crystal/blob/27f395066e256a162c1c6694c476b23aa2253484/src/xml.cr#L56
- https://github.com/crystal-lang/crystal/blob/27f395066e256a162c1c6694c476b23aa2253484/src/mime.cr#L160
- https://github.com/crystal-lang/crystal/blob/27f395066e256a162c1c6694c476b23aa2253484/src/uuid.cr#L54
- https://github.com/crystal-lang/crystal/blob/27f395066e256a162c1c6694c476b23aa2253484/src/range.cr#L375
- https://github.com/crystal-lang/crystal/blob/27f395066e256a162c1c6694c476b23aa2253484/src/tuple.cr#L162
- https://github.com/crystal-lang/crystal/blob/27f395066e256a162c1c6694c476b23aa2253484/src/deque.cr#L63
- https://github.com/crystal-lang/crystal/blob/27f395066e256a162c1c6694c476b23aa2253484/src/complex.cr#L57
- https://github.com/crystal-lang/crystal/blob/27f395066e256a162c1c6694c476b23aa2253484/src/io/argf.cr#L57
- https://github.com/crystal-lang/crystal/blob/27f395066e256a162c1c6694c476b23aa2253484/src/char.cr#L684
- https://github.com/crystal-lang/crystal/blob/27f395066e256a162c1c6694c476b23aa2253484/src/random.cr#L120
- https://github.com/crystal-lang/crystal/blob/27f395066e256a162c1c6694c476b23aa2253484/src/io/memory.cr#L351
- https://github.com/crystal-lang/crystal/blob/27f395066e256a162c1c6694c476b23aa2253484/src/ecr/lexer.cr#L106
- https://github.com/crystal-lang/crystal/blob/27f395066e256a162c1c6694c476b23aa2253484/src/enum.cr#L451
- https://github.com/crystal-lang/crystal/blob/27f395066e256a162c1c6694c476b23aa2253484/src/regex/pcre.cr#L11
- https://github.com/crystal-lang/crystal/blob/27f395066e256a162c1c6694c476b23aa2253484/src/xml/reader.cr#L128

I don't get why can't you just acknowledge this fact and move along?

**Review by straight-shoota — APPROVED** [review]

**Pull request merged**
