### PR TITLE
Fix indentation after comment inside 'when'

### LINKED ISSUE #5654: formatter bug, case with comments
```crystal
res = case x
      when 1, # 1
           2, # 2
           3  # 3
        1
      end
```

formatted to 
```crystal
res = case x
      when 1, # 1
 2,           # 2
 3            # 3
        1
      end
```

### PR DESCRIPTION
**Pull request by MakeNowJust**
Fix #5654

### CODE REVIEW

**Comment by RX14** [comment]
It still bugs me that all these formatter test cases are unreadable.

In my opinion all the formatter test cases should be in a bunch of annotated, parsed, .cr files, with one file per test and then you can actually see the indenting instead of working it out in your head by looking at `\n`. Or at the least they should use heredocs.

**Comment by asterite** [comment]
We can probably copy what the guys over at rufo ended up doing: https://github.com/ruby-formatter/rufo/blob/master/spec/lib/rufo/formatter_source_specs/align_chained_calls.rb.spec

**Comment by asterite** [comment]
Another issue is that this "newline check comment" appears many times in the formatter. When I did rufo I made sure this logic was done only once (or as few times as possible)... but of course I had the knowledge of this formatter to begin with. The formatter, as all other pieces, probably need a good refactoring/rewrite.

**Comment by RX14** [comment]
@asterite yeah that's pretty much what I intended.

**Pull request merged**
