### PR TITLE
Correct IO#read_fully example

### PR DESCRIPTION
**Pull request by MakeNowJust**

### CODE REVIEW

**Comment by RX14** [comment]
Doc alterations shouldn't be ci skip because the formatter would fail after this change.

**Comment by MakeNowJust** [comment]
@RX14 ok

**Comment by MakeNowJust** [comment]
@asterite @waj if you have free time (indeed), could you tell me? How do you think above @RX14 opinion?

**Comment by asterite** [comment]
@MakeNowJust I agree with @RX14, in this case the comments inside the comments should be aligned. If you run the formatter it will fix this. So `[ci skip]` shouldn't be used.

**Comment by MakeNowJust** [comment]
@asterite Thanks! I will remove `[ci skip]` on next commit, and fix this.

**Pull request closed without merging**
