### PR TITLE
Don't pass socket file descriptors to subprocesses on Unix (`SOCK_CLOEXEC`)

### LINKED ISSUE #14630: Sockets are inherited by subprocesses
## Bug Report

```crystal
require "socket"
s = TCPServer.new("127.1", 1234)
Process.new("sleep", {"99"})
s.close
s = TCPServer.new("127.1", 1234)
```

### Result
```
Unhandled exception: Could not bind to '127.1:1234': Address already in use (Socket::BindError)
```

### Reason
The first server socket is inherited by the subprocess and hence the port is still in use when the second socket is bound. Just like files are opened with `O_CLOEXEC` sockets should be opened with the `SOCK_CLOEXEC` flag. 

https://www.man7.org/linux/man-pages/man2/socket.2.html
https://www.man7.org/linux/man-pages/man2/open.2.html

### Monkey-patch fix
```crystal
require "socket"

module Crystal::System::Socket
  private def create_handle(family, type, protocol, blocking) : Handle
    {% if LibC.has_constant?(:SOCK_CLOEXEC) %}
      type = type.to_i | LibC::SOCK_CLOEXEC
    {% end %}
    fd = LibC.socket(family, type, protocol)
    raise ::Socket::Error.from_errno("Failed to create socket") if fd == -1
    fd
  end
end
```

### PR DESCRIPTION
**Pull request by carlhoerberg**
The comment 8 lines down suggests that this has been lost at some point.

Fixes #14630

### CODE REVIEW

**Review by ysbaddaden — APPROVED** [review]
Searching the history, I think we never had it. Let's fix that!

**Review by straight-shoota — COMMENTED** [review]
This seems like the right thing to do. It was probably just missed in the original implementation.

**suggestion:** Add comments with cross-references between the different implementations in `create_handle` and `initialize_handle`.
I'm also wondering if the `fcntl` part shouldn't be moved to `create_handle`, but that's a different issue.

**Comment by straight-shoota** [comment]
**suggestion:** Add a simple spec to ensure this doesn't get lost somewhere. A simple check for `close_on_exec?` should do:

```
it "socket closes on exec by default" do
  socket = Socket.new(Socket::Family::INET, Socket::Type::STREAM, Socket::Protocol::TCP)
  socket.close_on_exec?.should be_true
end
```
```

**Review by ysbaddaden — APPROVED** [review]

**Comment by ysbaddaden** [comment]
I disabled the spec for windows. This is an UNIX only consideration.

**Comment by straight-shoota** [comment]
We still need to take a look at the Windows stuff. I've created #14636 to track that.

**Review by straight-shoota — APPROVED** [review]

**Pull request merged**
