### PR TITLE
Add compile time string interpolation for char/num/bool constants

### LINKED ISSUE #12521: Discussion: Inline constants in the generated code
#### What aspect of the language would you like to see improved?
I'm curious whether we can propagate known constants in Crystal to the emitted LLVM so they can be stored as data.

#### What are the reasons?
It should ideally result in more efficient code and less strain on the garbage collector.

#### Include practical examples to illustrate your points.
The specific example that made me think of this is that I want the UI of my app to provide hints for keyboard shortcuts. For example:
```crystal
MODIFIER_KEY_STR = {% if flag?(:darwin) %} "Cmd" {% else %} "Ctrl" {% end %}
{"Fullscreen", "{MODIFIER_KEY_STR}+F"}
```
Today, this generates a call to `String.interpolation`, which allocates a new string on every call. This also happens when concatenating the strings with `+`. Since `MODIFIER_KEY_STR` is a constant, I'd hope that we could concatenate the strings at compile-time and store the resulting constant in the binary.

#### Optionally add one (or more) proposals to improve the current situation.
I have no idea what this would look like in the compiler.

### PR DESCRIPTION
**Pull request by mattrberry**
This updates the approach for compile-time string interpolation, as well as adds the ability to interpolate CharLiteral, NumberLiteral, and BoolLiteral.

Resolves #12521

### CODE REVIEW

**Comment by HertzDevil** [comment]
This would mean that those interpolations would always pick the `#to_s` definitions in the compiler itself, rather than in the standard library. This would lead to rather confusing behavior if e.g. the output of `#to_s` has changed (such as moving from Grisu3 to Dragonbox) or one is working with a nonstandard prelude. So I would advise against extending this to non-string literals; they should be interpolated in a macro context instead if desired.

**Comment by mattrberry** [comment]
Interesting, I didn't realize the compiler defined its own `#to_s` methods for Char, Number, and Bool. Do you mean in the case where they return a MacroId, specifically the `NumberLiteral#to_number`?

**Comment by HertzDevil** [comment]
I mean the `#to_s` definition of the standard library at the point of time when the compiler was built.

**Comment by straight-shoota** [comment]
I suppose for `CharLiteral`, `BoolLiteral` and integer `NumberLiteral` the result should be pretty much fixed. Only floating point `NumberLiterals` *could* be subject to change because there's more "artistic freedom" in how to represent a float as a string.

However, I can't see a particularly relevant use case for either of those types that such an optimization would yield a noticeable benefit. String literal expansion is pretty common, but characters, bools or numbers... probably not so much.
@mattrberry Do you have any particular application in mind?

**Comment by asterite** [comment]
Just my opinion: I like this PR, I think it has value. Overriding to_s for any of these types with a different behavior doesn't make sense. Nobody would do that. And if they do, many other things will break before this.

**Comment by mattrberry** [comment]
> Do you have any particular application in mind?

My initial use-case was covered with just the StringLiteral expansion, so I don't have a real-world example of what I'd use this change for.

For CharLiteral I imagine a similar use to StringLiteral. I can picture a NumberLiteral maybe being used as a version string in multiple places across an app, where the author wants to interpolate it into various UI strings. BoolLiterals seem less useful, but I figured I'd toss those in anyway. Fwiw (probably nothing), Dart interpolates string, number, and boolean literals at compile-time.

Would changing `to_s` for any of these types not be a breaking API change? I see this as an easy win, unless of course we feel like there's a good chance we'd change the `to_s` for any of these types before 2.0.

**Comment by mattrberry** [comment]
Is there interest in carrying this forward?

**Review by straight-shoota — APPROVED** [review]
I think this is fine.

There is a slight chance for surprising behaviour in very edgey cases. That shouldn't stand in the way.

**Comment by mattrberry** [comment]
No dice in 1.7.0 with https://github.com/crystal-lang/crystal/pull/12524?

**Comment by mattrberry** [comment]
@straight-shoota Was this forgotten or intentionally skipped?

**Comment by straight-shoota** [comment]
I think it just slipped. Core Team member availability is a limiting factor for merging PRs. Let's see if we can get someone to approve this.

**Review by beta-ziliani — APPROVED** [review]

**Comment by straight-shoota** [comment]
This was eventually reverted in #14155 due to #14150.

**Pull request merged**
