### PR TITLE
Adds an “if” method to Bool.

### PR DESCRIPTION
**Pull request by Lukc**

### CODE REVIEW

**Comment by RX14** [comment]
Thanks for the contribution, however I think this reads too much like postfix if to have the complete opposite meaning.

**Comment by kirbyfan64** [comment]
Is there a particular reason you can't just do:

```crystal
my_result = if xyz
  puts 123
end
```

**Comment by asterite** [comment]
@Lukc Thank you for this proposal, but using the `if` keyword is enough for your purposes and it's easier to read and write.

**Comment by Lukc** [comment]
There was no particular reason, I guess. Though one may argue that having conditions implemented as methods would make the language “purer” (from an OOP point of view), I was mostly interested in the community’s opinion on actually implementing and/or using it.

Thank you for the quick answer. :)

**Comment by asterite** [comment]
@Lukc I know Smalltalk is like that, but I don't think we can make everything pure, or if it's worth it. I prefer to sacrifice a bit of purity for the sake of readability.

**Pull request closed without merging**
