### PR TITLE
Add property `HTTP::Server::Response#status_message`

### PR DESCRIPTION
**Pull request by straight-shoota**
This makes `status_message` of `HTTP::Server::Response` writable to use a custom status message. Until now this was only possible with `respond_with_status` which doesn't allow a custom body or headers.

Resolves the main problem of #10038

### CODE REVIEW

**Comment by asterite** [comment]
Shouldn't the setter raise if the response headers were already written?

I don't understand why the status message is configurable, I thought these messages were pretty standard.

**Comment by straight-shoota** [comment]
> Shouldn't the setter raise if the response headers were already written?

No other setter does this, so I don't think it should. It doesn't directly cause new headers to be written, so it's not an immediate reason for an error. That's different with `respond_with_status` which is clearly an action that's supposed to send the response (and fail if it can't).

> I don't understand why the status message is configurable, I thought these messages were pretty standard.

They are pretty standard, yes. But not totally strict. Status codes are extensible. So you could a status code that is not represented in `HTTP::Status` and thus `#description` doesn't have a reason phrase associated with it. Or you might want to use localized or in some other way customized messages for standardized status codes.

**Comment by asterite** [comment]
> No other setter does this

Try doing `response.content_length = ...` after the headers were written. I'm almost sure that raises (because HTTP::Headers will raise in this case).

I think that the `version` setter should raise too.

**Comment by straight-shoota** [comment]
`content_length=` does not raise after the headers have been written. Same goes for `content_type=`, `version=`, `status=`, `status_code=`. It might be a good idea to change this, but it's a different issue.

**Comment by straight-shoota** [comment]
Since  #11253 added `check_headers` to other setters of `HTTP::Server::Response`, I added it to `#status_message=` as well.

**Review by beta-ziliani — APPROVED** [review]
:rocket:

**Pull request merged**
