### PR TITLE
Fixed #4278: String#underscore with digit

### LINKED ISSUE #4278: Strange output of String#underscore with strings of uppercased letters and numbers
I'm not really sure what the output of `String#underscore` should be with uppercased strings containing numbers, but I think that the current behavior is wrong:
```bash
$ crystal eval 'p "ABC123".underscore'
"ab_c123"

$ crystal --version
Crystal 0.21.1 [3c6c75e] (2017-03-06) LLVM 3.5.0
```

Here is how Rails [String#underscore](http://api.rubyonrails.org/classes/ActiveSupport/Inflector.html#method-i-underscore) behaves:
```bash
$ ruby -rrails -e 'p "ABC123".underscore'
"abc123"

$ ruby --version
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]
$ ruby -rrails -e 'puts Rails.version'
5.0.1
```

### PR DESCRIPTION
**Pull request by MakeNowJust**
Fixed #4278.

It treats digit characters as downcase characters. But in upcase characters it treats like upcase characters. It works fine.

```crystal
"CSS3".underscore     # => "css3"
"HTTP1.1".underscore  # => "http1.1"
"3.14IsPi".underscore # => "3.14_is_pi"
```

Thank you.

### CODE REVIEW

**Comment by MakeNowJust** [comment]
@bew Updated comments in 328d4ce26fb2a6ff763eac1aa01feffa887f9fb8. Thank you.

**Comment by MakeNowJust** [comment]
https://travis-ci.org/crystal-lang/crystal/jobs/221621776

Hmm... `openssl` spec depends on this strange behavior. I think we put `_` before `V` if we need to separate, like `NO_SSLV3` to `NO_SSL_V3`. For example, do you want to convert `WMV9` to `wm_v9`? I say of course 'no'.

NOTE: Original OpenSSL constant name is `NO_SSLv3`, not `NO_SSLV3`. `v` is just lower case letter. It is important thing that we don't respect original constant name already.

**Comment by asterite** [comment]
Let's rename openssl constants to match this new behaviour.

Since we are fixing this, what happens if you pass other characters like some of `!@#$%^&*()` to `underscore`? I'd include some tests for those edge cases too and make sure they behave like in Ruby's ActiveSupport.

**Comment by MakeNowJust** [comment]
@asterite Apologize for delay. I renamed OpenSSL constants for changes and updated this branch.

I know ActiveSupport's `String#underscore` converts `"::"` to `/` for Rails convention. However I think it is for Rails reason, so I don't implement it for now.

**Comment by akzhan** [comment]
I prefer to use ActiveSupport compatible behavior when it's OK.

**Comment by MakeNowJust** [comment]
I'm sure `String#underscore` is bad naming if it converts `"::"` to `"/"`.

**Comment by MakeNowJust** [comment]
@asterite ping

**Comment by mverzilli** [comment]
Thank you @MakeNowJust !!!

**Comment by MakeNowJust** [comment]
@mverzilli Can you close #4281?

**Pull request merged**
