### PR TITLE
Initial implmentation of Optional class.

### PR DESCRIPTION
**Pull request by jdantonio**
An implementation of an [option type](https://en.wikipedia.org/wiki/Option_type), based heavily on [std::optional](http://en.cppreference.com/w/cpp/utility/optional) from C++, with additional influence from [Functional Java](http://www.functionaljava.org/javadoc/4.6/functionaljava/fj/data/Option.html). If this isn't a good fit for the standard library I'd be happy to make this a shard instead.

Ruby overuses `nil`. Sometimes `nil` is a valid value, other times it represents the result of an operation that failed. This ambiguity can lead to difficult to understand and incorrect code. The [Null Object pattern](https://en.wikipedia.org/wiki/Null_Object_pattern) is one attempted solution, but it is overly complex. A new class or object must be defined for each class that may be null. When a Null Object is used the code generally just checks the type or identity, effectively just asking the object "did you succeed?" An `Optional` is a generic solution to this problem.

This implementation is an object with two states: `some` or `none`. When the object has a value it is a `some` and the value can be accessed via a getter. When the object has no value it is a `none` and it's lack of a value is explicit. The object has several methods for querying and changing its state.

This implementation is similar to my [Maybe](https://github.com/crystal-lang/crystal/pull/3371) PR, but with several key differences. `Optional` is a generic solution to the null-value problem whereas `Maybe` is highly specialized for use with error handling. `Optional` objects are mutable whereas `Maybe` is not. `Maybe` solves a narrow problem, `Optional` has a wider range of uses.

### CODE REVIEW

**Comment by RX14** [comment]
Can you expand on the advantages of using `Optional(T)` over `T | Nil`?

**Comment by jdantonio** [comment]
@RX14 


* More explicit intent
* Better compiler checks
* Simpler, less error-prone code
* Idiomatic way of handling "no valid value available" situations

This code snippet was presented by Ary and Brian in their [RubyConf Brazil](https://www.eventials.com/locaweb/crystal-para-rubistas-com-ary-borenszweig/) presentation at roughly 18:00 minutes:

```crystal
def foo(a)
  if a >= 0
    a
  else
    nil
  end
end

foo(rand()) + 1
```

Unfortunately, it doesn't compile. It raises a compile-time error "undefined method '+' for Nil (compile-time type is (Float64 | Nil))". The problem is that the return value of `foo` may be `nil`, hence the type `(Float64 | Nil))`. We can fix this by giving a hint to the compiler:

```
foo(rand()).not_nil! + 1
```

Unfortunately, this is a ticking :bomb:. We've just turned off compiler checking! It's OK in this particular instance because we can clearly see that `foo` will never return `nil`. But what happens if `foo` is updated later, and it exists in a different file from the line that uses it? In that case we'll have a runtime error that will crash the program.

Let's try this again with `Optional`:

```crystal
def optional_foo(a)
  if a >= 0
    Optional(Float64).some(a)
  else
    Optional(Float64).none
  end
end

optional_foo(rand()).if_value { |val| puts val + 1 }

puts optional_foo(rand()).value_or(0.0) + 1
```

This code compiles, runs, is bug-free, and is future-proof. The difference is that `Optional` handles all the nil/not logic for us. Each method of `Optional` is a contract that provides strong guarantees. The `foo` method returns a single type, `Optional(Float64)`, rather than a union type. All checks for `nil` are handled within the `Optional`. Our `Optional` is always valid, even when it _contains_ an invalid value. And most importantly, we're working *with* the compiler, not against it. Which is one of the main reasons to use a compiled, statically-typed language in the first place.

**Comment by lbguilherme** [comment]
`nil` means the lack of value. This implies `Optional(Nil)` doesn't make much sense semantically. `T | Nil` means exactly "a T or a lack of value", which is the same idiom as optionals, but with compiler support. Let's take a look at some code:

```cr
def foo(a)
  if a >= 0.5
    a
  else
    nil
  end
end

# puts optional_foo(rand()).value_or(0.0) + 1
puts (foo(rand()) || 0.0) + 1

# optional_foo(rand()).if_value { |val| puts val + 1 }
if x = foo(rand())
  puts x + 1
end
```

I find this way of writing code far more readable because it smaller and uses core language features such as `||` or `if` instead of methods, all while being checked by the compiler. `not_nil!` is a bomb waiting to explode and should be used as little as possible (this must be why it is so ugly to write!).

My point is that Crystal already uses the Optional idiom very heavily and has compiler support for it (you can even write `String?` as a contraction for `String | Nil`). I don't see advantage on a `Optional` class.

**Comment by RX14** [comment]
@jdantonio What about `foo(rand()).try { |x| x + 1 }` or `(foo(rand()) || 0.0) + 1`. Both compile, and have the same level of safety as `Optional`.

Using `Float64 | Nil` is much more compiler friendly, because the compiler can check normal code to ensure it's valid. For example:

```cr
ret = foo(rand())

if ret
  p ret
else
  # handle
end
```

Whereas with optional:
```cr
ret = foo(rand())

if ret.some?
  p ret.value.not_nil!
else
  # handle
end
```
It's just longer and more ugly for the same safety. You seem to have built something to handle what the compiler *already* does.

**Comment by ysbaddaden** [comment]
I can't help but reduce your example to `(foo || 0.0) + 1` or `if foo; foo + 1; end`. They're exactly the same to me, but less complex, and don't involve `not_nil!` which should be avoided unless a value can't be Nil in practice and it must be a fatal error when it happens.

**Comment by RX14** [comment]
The only tiny advantage to me seems to be that you can use nil to be a return value without it meaning "no value". This isn't an issue because the community has already decided that nil means no value in the same way as an empty optional, and any other meaning would be an overload and bad practice.

**Comment by asterite** [comment]
@jdantonio Hi!

Thank you for your PR. However, as in the comments above, `nil` is perfectly type-safe and it's pretty idiomatic and leads to very short code. The `not_nil!` example was just to show an example where in Ruby the program never raises, but in Crystal you have to somehow deal with it. One way is doing `not_nil!`, another way is:

```cr
if x = foo(rand())
  puts x + 1
else
  # This should really never happen
  raise "shouldn't happen!"
end
```

which is basically the same as `not_nil!`: it will raise. We can silently ignore the error if we don't provide an `else`, but it's better to know if we made a mistake.

The only problem with `nil` is the [Semipredicate problem](https://en.wikipedia.org/wiki/Semipredicate_problem), which right now happens if you have a `Hash` whose values can be `nil`.  So:

```cr
hash = {1 => nil, 2 => 3} of Int32 => (Int32 | Nil)
hash[1]? # => nil
hash[3]? # => nil

# But in one case the key is there and in the other the key is missing
```

This can happen, but it's not that frequent, and can be solved with other methods:

```cr
if hash.has_key?(1)
  # nil, but we know it's in the hash
  hash[1] # => nil
end
```

Another case is `Iterator`: it has a `next` method that must return the next value, or... well, we could use `nil` to mean "no more values", but then we couldn't distinguish that from an iterator whose values can be `nil`. For that reason "no more values" is signalled with a singleton type, `Iterator::Stop`, which never makes sense outside of an iterator (you wouldn't put it in an array, for example).

The [Nil](https://crystal-lang.org/api/0.19.3/Nil.html) docs show common idioms to deal with `nil`: many are the same as in Ruby, and then there's `try`, which in Ruby is present in ActiveSupport in a similar way (and now in Ruby there's the lonely operator, but we think `try` is good enough).

We *could* introduce `Optional` to deal with the semipredicate problem, but I feel that having two ways of doing more or less the same thing will bring more confusion to the language and libraries.

**Comment by jdantonio** [comment]
@RX14 "the community has already decided that nil means no value". That's pretty much my point. That's not a guarantee. That's not a formal contract. And that's one of the reasons nil handling in Ruby is such a mess. It's inconsistent, messy, error-prone, and a constant source of frustration for so many programmers. That's why idioms like optional and maybe are occurring with greater frequency in new languages and the latest versions of old languages.

@asterite "The Nil docs show common idioms to deal with nil: many are the same as in Ruby". This is pretty much my point, too. As you mentioned in Brazil, Crystal was inspired by Ruby but isn't intended to always be 100% compatible with Ruby. Ruby is a great language but not everything in Ruby is great. Crystal has an opportunity to critically evaluate Ruby and do things better. Nil handling and exceptions are two areas where I think Ruby isn't very good (recognizing that my opinion may be uncommon). Nil-handling is definitely better in Crystal, but there are other ideas from other languages worth exploring. I can absolutely understand why this and my other PR may not be a good fit for Crystal, but I felt it there was value in having a discussion.

The discussions regarding this PR and my other one were very informative and enjoyable. Hopefully others agree. :-)

**Comment by kirbyfan64** [comment]
I think you're just forgetting that, in Crystal, `nil` *isn't* error-prone and messy. `T | Nil` is basically the same thing as `Maybe t` (lower-case `t`, because my Haskell-ian self is screaming right now) in functionality; although the usage may look a bit different, the end result is the same. I think you should really try out using Crystal's handling of null values for a bit longer; you'll realize that it actually works really well.

**Comment by drosehn** [comment]
> The discussions regarding this PR and my other one were very informative and enjoyable. Hopefully others agree. :-)

I think this is interesting.  I don't have a strong opinion for or against it, but I do notice something similar in Swift (assuming I have the correct idea of features in Swift).  I need more experience with "the crystal way" of handling things with `Nil` vs optionals before I can decide which one seems the best fit to the way I think about programs.  I wouldn't race to add this as an official feature for the crystal language, but it might be interesting as a shard to experiment with.

**Comment by rmosolgo** [comment]
> in Crystal, `nil` _isn't_ error-prone and messy ... it actually works really well

I don't use Crystal for my day job, but in my personal projects, that's what I found. The compiler's warnings about `nil` forced me to be careful about the flow of types through the program, and often, that meant _skipping_ `nil` altogether. So nice!

>  interesting as a shard to experiment with

👏  👏

**Comment by ozra** [comment]
@jdantonio : My first thought: `(1 || nil).try? {|v| v + 1 }` - and then there are the `if` versions shown by others above.

`not_nil!` as already mentioned doesn't in any way reflect the behaviour of `if_value?`.

Make an alias `if_value?` to `try?` and you've got the same thing basically. But using the inbuilt type-flow-inference.

As - again - mentioned by others: Ruby != Crystal. In Ruby nils are as dangerous as in C(++)/Java/Go - but in Crystal nils are type safe.
A variable of type `Result` _can't_ have the value `nil`. Only something of type `Nil` can be `nil`.
Therefore: something of `Result|Nil` _can_ be nil - but thanks to type information and flow-inference it _must_ be handled. If you consider the nil-value to mean Nothing - _in you context_ - you simply elect handle it like that. That is pretty obvious from use-case to use-case, function to function.

I hardly think it's necessary to explicitly say "Hey user! Nil means Nothing when returned from _this_ function", officially to a user. _You decide_ what the impact of a nil-value means in your code, since the possibility of it's existence demands your attention and decision.

Maybes - now that's another thing - which has additional value ;-)

**Comment by trans** [comment]
I think Optional could be very useful for Crystal, **but** only if it works a bit differently than is does in say Swift. The problem with Optional in general is you always have to deal with it, wherever it may occur in the code (using `.some` or what have you) which is annoying. The same is true for nil to an extent, but nil is easier to use because it also functions as `false` in conditionals.

First, if an Optional could also function as false in conditionals when in none state, that would put it on par with nil. But we can go further and allow Optionals to "passthru" the call chain. Here's what I mean:

```ruby
    x = Optional("All is One")  # some state
    x.upcase.reverse
    => Optional("ENO SI LLA")

    x = Optional(nil)  # none state
    x.upcase.reverse
    => Optional(nil)
```

We can always make things explicit if we "unbox" the Optional.

```ruby
    x = Optional("All is One")  # some state
    x.unbox.upcase.reverse
    => "ENO SI LLA"

    x = Optional(nil)
    x.unbox.upcase.reverse
    => error NoMethodError `upcase` for Nil
```

And an immediate version,

```ruby
    x = Optional(nil) 
    x.unbox!.upcase
    => error UnwantedOptionalNilError
```

The upshot is, to paraphrase a famous movie, "Try? We don't need no stinking *try*."

The only exception to this passing-thru would be the few necessary methods the Optional class itself  must have, like the `unbox` methods mentioned and `class` and `object_id`.

**Comment by lbguilherme** [comment]
@trans But this is already implemented in the language as `String?`. Take a look:

```cr
a = rand < 0.5 ? "osudhs" : nil  # type of this is String?

a.try &.upcase.reverse  # type of this is String? Result is either "SHDUSO" or nil
a.try &.size  # type of this Int32? Result is either 6 or nil

a.not_nil!.upcase.reverse # type of this is String. Result is "SHDUSO".
# But this may raise "Nil assertion failed" at runtime.
```

`try` and `not_nil!` exactly maps to the operations you described with "Optional". Those are the same thing :)

**Comment by trans** [comment]
No. `String?` is exactly the same as `String | Nil`. With Optional "there is no try".

**Comment by trans** [comment]
I think another example would be helpful too,

    class This
        def that
          Optional(nil).new
        end
    end
    
    this = This.new 
    this.that.those
    => Option nil

Notice, even though `that` is in the middle of the call chain, it short-circuits the chain and returns the Optional nil.

P.S. I notice in my original examples that I forgot `new`. I fixed.

**Comment by asterite** [comment]
That's how Objective-C works and it's a mess.

I'm closing this issue. A shard with Optional and Maybe can be provided, but `T | Nil` is pretty much **the** idiom used to cover that, and in my experience it's working pretty well.

**Comment by RX14** [comment]
Your argument rests on the assertion that try is a bad thing, however I think it's quite nice. Its short (especially with `&.`), its explicit, and its not magic like optional would be. A little more typing for a little more clarity is never a bad thing.

**Pull request closed without merging**
