### PR TITLE
Fix each* methods to return only nil

### PR DESCRIPTION
**Pull request by MakeNowJust**
Related pull request: #3815 

In fact, I fixed only two ([1](https://github.com/MakeNowJust/crystal/blob/fix/each-return-nil/src/compiler/crystal/semantic/type_merge.cr#L126) and [2](https://github.com/MakeNowJust/crystal/blob/fix/each-return-nil/src/compiler/crystal/syntax/transformer.cr#L577)) by this change. This change has no effect for codes in many case.

### CODE REVIEW

**Comment by asterite** [comment]
@MakeNowJust Thank you!

There is an easy way to mark that a method always returns `nil`:

```cr
def each : Nil
  # ...
end
```

Then you don't have to use `nil` at the end of the method and also you don't have to remember to `return nil` in every branch. And this will show up in docs. What do you think?

**Comment by MakeNowJust** [comment]
@asterite Good. I'll rewrite it in this way.

**Comment by MakeNowJust** [comment]
@asterite Done.

And, I fixed `Int#times` and some methods to return `nil`.

**Comment by MakeNowJust** [comment]
[Hmm...](https://travis-ci.org/crystal-lang/crystal/jobs/188855754)

I think `to` of `Int#upto` and `Int#downto`'s arg is bad naming, `n` is better.

**Comment by Sija** [comment]
@MakeNowJust yep, one can use `def downto(to n)` keep the best from both worlds :)

**Comment by asterite** [comment]
@MakeNowJust I fixed the conflicts after I merged another PR but it seems I did it wrong in one place. Let's keep the name as `to` for now, later we can rename that to `n` for `to`, `upto` and `downto`

**Pull request merged**
