### PR TITLE
Remove obsolete TODOs

### PR DESCRIPTION
**Pull request by Sija**
SSIA

### CODE REVIEW

**Comment by Sija** [comment]
> I would prefer to keep the same style in the case statements. Full expression over the `when .< bound`

@bcardiff Addressed.

**Comment by straight-shoota** [comment]
Please leave the last commit off. It's not much of an improvement and unrelated to this change.

**Comment by Sija** [comment]
Seems like ready to merge?

**Comment by straight-shoota** [comment]
Thanks @Sija

**Pull request merged**
