### PR TITLE
Add #every top-level method

### PR DESCRIPTION
**Pull request by dscottboggs**
Just a suggestion, I just wrote this method in my code and thought it might be useful if it were in the stdlib.

Example run in the playground:

https://carc.in/#/r/8voj

### CODE REVIEW

**Comment by jhass** [comment]
Should this measure run time of the block and substract it from the sleep time?

**Comment by z64** [comment]
For reference, this was previously submitted here: https://github.com/crystal-lang/crystal/pull/4349

**Comment by dscottboggs** [comment]
> Should this measure run time of the block and substract it from the sleep time?

I thought of that, but there's the concern that the executed block would take longer than the given delay. I thought it better to keep things simple and make the delay constant. This way, you don't run the risk of turning a call to some method which also retries for the given delay into an infinite fast loop and stressing some other resource down the line.

I'm open to debate on the topic though, perhaps it should just fall back on being a fast loop if the block takes longer than the delay

**Comment by dscottboggs** [comment]
> For reference, this was previously submitted here: #4349

Thanks for pointing that out. To quote @asterite in that thread

> I don't think this belongs in the std.

I respectfully disagree -- it seems too common of a use case to leave to a 3rd party dependency. I don't really see the downside to including this four-liner alongside others like `loop`, `future` and `printf`

**Comment by z64** [comment]
Personally, I don't feel strongly about it. I think the argument over adding a small method to std goes both ways. That said, I believe the implementation from #4349 is preferable.

**Comment by straight-shoota** [comment]
Comparing both #4349 it should be evident that this is actually not a simple feature. There are even more variants to that pattern that just those two implementations. For example, what happens when the execution time of the block exceeds the time span? What happens if it raises? Is the scheduler supposed to be strictly based on elapsed time (`Time.monotonic`) or should it take wall clock into account (`Time.local`)?

I'd excpect many use cases would have different needs than others and each one requires some customizable or specialized solutions. This all seems to much for stdlib and is better solved in dedicated shards (such as [tasker](https://shardbox.org/shards/tasker) for example).

@dscottboggs Since the implementation proposed here is really trivial, it should be easy to just keep that method local to your app.

**Pull request closed without merging**
