### PR TITLE
Use `TypeNode#union_types` where possible

### PR DESCRIPTION
**Pull request by Sija**
Follow-up to #4995.

Meant to be merged after `v0.24.0` release.
~~All specs are passing on current `master`.~~

### CODE REVIEW

**Comment by bew** [comment]
Also in `primitives.cr`
https://github.com/crystal-lang/crystal/blob/b52b2f93dd037a12f33354b05fe26a61e1b33662/src/primitives.cr#L270-L272

**Comment by Sija** [comment]
@bew I thought it wouldn't compile, but it does, thanks for pointing out!

**Comment by bew** [comment]
@Sija did you see my edit about `io/byte_format.cr` ?

**Comment by Sija** [comment]
@bew `io/byte_format.cr` is required by `prelude` so can't do, or at least I dunno how.

**Comment by bew** [comment]
I don't see the possible issue with `prelude`, can you explain?

**Comment by Sija** [comment]
Compiler error will say more than me ;)

```
Using compiled compiler at `.build/crystal'
Error in line 1: while requiring "prelude"

in src/prelude.cr:19: while requiring "string"

require "string"
^

in src/string.cr:4235: while requiring "./string/builder"

require "./string/builder"
^

in src/string/builder.cr:1: while requiring "io"

require "io"
^

in src/io.cr:1142: while requiring "./io/*"

require "./io/*"
^

in src/io/byte_format.cr:123: expanding macro

  {% for mod in %w(LittleEndian BigEndian) %}
  ^

in src/io/byte_format.cr:125: undefined constant Int::Primitive

      {% for type, i in Int::Primitive.union_types %}
                        ^~~~~~~~~~~~~~
```

**Comment by bew** [comment]
It might work to move `require "int"` above `require "string"` in `prelude.cr`, but I'm not sure it's how we should do it..

**Comment by RX14** [comment]
This should be merged after the next release, as it depends on a new compiler feature.

**Comment by Sija** [comment]
I dunno how to fix it, I'll close it unless there's someone willing to help.

**Comment by bew** [comment]
Did you tried my suggestion?

**Comment by Sija** [comment]
@bew yes, it doesn't work.

**Comment by miketheman** [comment]
#codetriage 

Rebasing this PR on top of `master`:

```shellsession
$ bin/crystal --version
Using compiled compiler at `.build/crystal'
Crystal 0.26.1+36 [bc526468e] (2018-09-08)

LLVM: 6.0.1
Default target: x86_64-apple-macosx
```

Running `make std_spec` produces this output:

```
  1) JSON serialization from_json deserializes union with Int128 (fast path)
     Failure/Error: {% for type in Int::Primitive.union_types %}

       Expected: 170141183460469231731687303715884105727_i128
            got: -1_i128

     # spec/std/json/serialization_spec.cr:155
```

`make compiler_spec` fails a LOT, all around code generation. Example:

```
Codegen: super calls super with dispatch (#2318)

       while requiring "primitives" (Crystal::TypeException)
         from src/compiler/crystal/semantic/ast.cr:13:9 in 'raise'
         from src/compiler/crystal/semantic/ast.cr:12:5 in 'raise'
         from src/compiler/crystal/semantic/semantic_visitor.cr:72:5 in 'visit'
         from src/compiler/crystal/syntax/visitor.cr:27:12 in 'accept'
         from src/compiler/crystal/semantic/top_level_visitor.cr:707:9 in 'visit'
         from src/compiler/crystal/syntax/visitor.cr:27:12 in 'accept'
         from src/compiler/crystal/semantic.cr:62:7 in 'top_level_semantic'
         from src/compiler/crystal/semantic.cr:22:23 in 'semantic'
         from src/compiler/crystal/semantic.cr:21:3 in 'semantic'
         from src/compiler/crystal/codegen/codegen.cr:22:7 in 'run'
         from spec/spec_helper.cr:184:5 in 'run'
         from spec/spec_helper.cr:156:1 in 'run'
         from spec/compiler/codegen/super_spec.cr:396:5 in '->'
         from src/spec/methods.cr:255:3 in 'it'
         from spec/compiler/codegen/super_spec.cr:395:3 in '->'
         from src/spec/context.cr:255:3 in 'describe'
         from src/spec/methods.cr:16:5 in 'describe'
         from spec/compiler/codegen/thread_local_spec.cr:1:1 in '__crystal_main'
         from src/crystal/main.cr:97:5 in 'main_user_code'
         from src/crystal/main.cr:86:7 in 'main'
         from src/crystal/main.cr:106:3 in 'main'
```

I'm not entirely sure how to proceed here.

**Comment by HertzDevil** [comment]
This amounts to adding 128-bit integer support to the affected methods, so this cannot be done now. Specs however can opt in to `BUILTIN_INTEGER_TYPES` from `spec/support/number.cr`.

**Comment by Sija** [comment]
Closing in favor of #12636

**Pull request closed without merging**
