### PR TITLE
Update `shell.nix` for newer LLVM versions and aarch64-darwin

### PR DESCRIPTION
**Pull request by HertzDevil**

### CODE REVIEW

**Review by straight-shoota — APPROVED** [review]
Great, you got it working after I failed to upgrade to anything newer than LLVM 11 in #12498 😆

**Comment by HertzDevil** [comment]
Does `MACOSX_DEPLOYMENT_TARGET` also need to be updated?

**Comment by beta-ziliani** [comment]
> Does `MACOSX_DEPLOYMENT_TARGET` also need to be updated?

Sounds reasonable, although tbh I don't know what's a sensible X in 11.X

**Comment by will** [comment]
I've only been using nix for a day, decided to try not using homebrew on a new computer, but this PR worked for me first try

```
/t/crystal (feature/nix-shell)> nix-shell
these 2 derivations will be built:
  /nix/store/8c5yzvwwd0rz20qnzb8g3p7cxifr30v2-boehm-gc-8.2.0.drv
  /nix/store/a8ml099barsdjffjcxw87wfmqymf9hbk-crystal-binary.drv
these 128 paths will be fetched (168.57 MiB download, 1033.73 MiB unpacked):
...on and on and on....


[nix-shell:/tmp/crystal]$ crystal --version
Crystal 1.6.1 [fc61bd678] (2022-10-21)

LLVM: 10.0.0
Default target: aarch64-apple-darwin
```

**Comment by straight-shoota** [comment]
@HertzDevil @beta-ziliani What needs to be done with regards to `MACOSX_DEPLOYMENT_TARGET` to move this forward?

**Comment by beta-ziliani** [comment]
On a second thought, if we still can compile it in 10.11, I don't see the reason to change it.

**Pull request merged**
