### PR TITLE
Fix UNIXServer example in docs

### PR DESCRIPTION
**Pull request by petoem**
The example is essentially the same as the TCPServer one. I verified both UNIXServer and UNIXSocket examples, they work.

/cc @bew

### CODE REVIEW

**Comment by bew** [comment]
Agree @asterite 
```cr
require "socket"

def handle_client(client)
  message = client.gets
  client.puts message
end

server = UNIXServer.new("/tmp/myapp.sock")
while client = server.accept?
  spawn handle_client(client)
end
```
More sth like this then?

**Comment by asterite** [comment]
@bew I think so, yes :-)

**Comment by petoem** [comment]
@bew you are right, this is a more complete example. I change UNIXServer to it.
@asterite Can I fix TCPServer example in this PR too, or should I create a new/separate?

**Comment by asterite** [comment]
@petoem Sure! You can fix it in this PR :-)

**Pull request merged**
