### PR TITLE
Add Char methods and specs, include Comparable.

### PR DESCRIPTION
**Pull request by MaloJaffre**
~~There is a strange compiler side-effect bug with ```include Comparable(Char)```, see https://travis-ci.org/MaloJaffre/crystal/jobs/114014085 but I can compile and pass char specs.~~

### CODE REVIEW

**Comment by asterite** [comment]
Thanks! This looks really good.

After seeing this, I wonder if we should maybe remove the method `Comparable#between?`. My problem with it is that there are many ways "between" can be understood. If I say "a is bettwen b and c" I can understand:

```
b < a < c
b <= a <= c
```

In Ruby you can't do `b < a < c`, it's parsed as `(b < a) < c`, so having a `between?` method is somehow convenient. Crystal changes that, and we can also do `b < a <= c` and `b <= a < c` to be super clear about the meaning. So, my vote is to remove `Comparable#between?` and to use ordinary comparison operators. But all other changes (like adding `lowercase?`) look good, except that maybe I'd call them `upcase?` and `downcase?` to match the names in `String`).

The specs fail because in some compiler specs we just do `require "char"`, without the full prelude, and now they fail because it can't find `Comparable`. You can fix them by adding `require "comparable"` in the specs (or in `char.cr`).

**Comment by jhass** [comment]
I actually preferred `uppercase?` and `lowercase?`, `downcase` and `upcase` are the actions of converting from `lowercase` to `uppercase` or vice versa respectively: http://www.oxforddictionaries.com/de/definition/englisch/downcase

**Comment by MaloJaffre** [comment]
I've applied your suggestions.

**Comment by asterite** [comment]
@MaloJaffre Thanks!

Could you mention ASCII in the docs? For example:

```
Returns true if this char is a lowercase ASCII letter
```

All other methods explicitly say that they only deal with ASCII, so it's good to say this too in these new methods.

**Comment by MaloJaffre** [comment]
Done!

**Comment by MaloJaffre** [comment]
Done!

**Comment by asterite** [comment]
@MaloJaffre Awesome, thank you!! :heart:

**Pull request merged**
