### PR TITLE
Formatter: fixed private constants alignment

### LINKED ISSUE #4111: Formatter: private constants alignment does not working
For example:

```crystal
private Foo = 1
private Bar = 2
private FooBar = 3
```

Run `crystal format` against this file, but I got same file 😢 

I expected:

```crystal
private Foo    = 1
private Bar    = 2
private FooBar = 3
```

- - -

```console
$ crystal version
Crystal 0.21.0 (2017-02-21)
```

### PR DESCRIPTION
**Pull request by MakeNowJust**
Fixed #4111

But I appeared another problem. This file:

```crystal
private Foo 1
A = 1
```

is formatted as:

```crystal
private Foo = 1
A   = 1
```

I think it is too heavy to fix this problem, and we should not define mixed visibility constants in same segment in general. I will open a new issue for this problem.

### CODE REVIEW

**Comment by MakeNowJust** [comment]
The new issue is here: #4113

**Comment by bcardiff** [comment]
I agree with @bew 's https://github.com/crystal-lang/crystal/issues/4113#issuecomment-284150931

Let's add a blank line between different visibility constants. I can't think of a reason they should be visually together, and separating them seems to solve the alignment dilema in a trivial way.

@MakeNowJust if you are willing to implement it, should we hold this PR as in WIP until both #4111 and #4113 are fixed together?

**Comment by MakeNowJust** [comment]
@bcardiff See https://github.com/crystal-lang/crystal/issues/4113#issuecomment-285076965. If segments should be separated by visibility modifiers, I think this PR is independent from #4113 problem, so you can merge this PR without waiting. I'm working to implement @bew's idea now.

**Comment by bcardiff** [comment]
@MakeNowJust I rebase and apply the formatter to some additional files due to rebase. It should be ok to merge upon CI.

**Comment by bcardiff** [comment]
Thanks @MakeNowJust!

Although it does not apply to the cases handled in this PR, this PR make me think if it is ok to force the format with respect the formatter in master (current behavior) or with the released formatter. The reason is that editor's plugin will use the later and it could be uncomfortable to the user that the saved file will trigger some changes...

**Pull request merged**
