### PR TITLE
Compiler: fix proc of self causing multidispatch

### LINKED ISSUE #3822: 2 target defs compiler error
Code:
```crystal
class Foo
  def initialize(@proc : Proc(Bar, Nil))
  end
end

module Bar
end

class Baz
  include Bar
end

def test(bar : Bar)
  if bar.is_a? Baz
    test bar
  end
end

def test(baz : Baz)
end

Foo.new(->test(Bar))
```
Output:
```
2 target defs for test(arg0)
0x55694e: ??? at ??
0x11224cd: ??? at ??
0x11b0d81: ??? at ??
0x11e41e5: ??? at ??
0x11dc214: ??? at ??
0x11afa76: ??? at ??
0x11afef8: ??? at ??
0x115b42f: ??? at ??
0x18ece4d: ??? at ??
0x5ae16d: ??? at ??
0x57af0f: main at ??
0x7f4e755d1f45: __libc_start_main at ??
0x556281: ??? at ??

Error: you've found a bug in the Crystal compiler. Please open an issue, including source 
code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```

### LINKED ISSUE #9823: X target defs for method (Exception)
## Sample code to reproduce
```crystal
abstract struct Parent
  abstract def work(a : Int32, b : Int32)
  def get
    ->work(Int32,Int32)
  end
end
 
struct Child1 < Parent
    def work(a : Int32, b : Int32)
      a + b
    end
end
 
struct Child2 < Parent
  def work(a : Int32, b : Int32)
    a - b
  end
end
 
pp [Child1.new,Child2.new].map(&.get)
```

Above code triggers below Compiler exception

```
2 target defs for work(arg0, arg1) (Exception)
  from raise<Exception>:NoReturn
  from raise<String>:NoReturn
  from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil
  from Crystal::CodeGenVisitor#codegen_fun<String, Crystal::Def+, Crystal::Type+, Bool, Crystal::CodeGenVisitor::ModuleInfo, Bool, Bool>:LLVM::Function
  from Crystal::CodeGenVisitor#target_def_fun<Crystal::Def+, Crystal::Type+>:LLVM::Function
  from Crystal::CodeGenVisitor#visit<Crystal::Call>:Bool
  from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil
  from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil
  from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil
  from Crystal::CodeGenVisitor#prepare_call_args_non_external<Crystal::Call, Crystal::Def+, Crystal::Type+>:Tuple(Array(LLVM::Value), Bool)
  from Crystal::CodeGenVisitor#visit<Crystal::Call>:Bool
  from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil
  from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil
  from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil
  from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil
  from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil
  from Crystal::CodeGenVisitor#visit<Crystal::Call>:Bool
  from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil
  from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil
  from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil
  from Crystal::CodeGenVisitor#prepare_call_args_non_external<Crystal::Call, Crystal::Def+, Crystal::Type+>:Tuple(Array(LLVM::Value), Bool)
  from Crystal::CodeGenVisitor#visit<Crystal::Call>:Bool
  from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil
  from Crystal::CodeGenVisitor#prepare_call_args_non_external<Crystal::Call, Crystal::Def+, Crystal::Type+>:Tuple(Array(LLVM::Value), Bool)
  from Crystal::CodeGenVisitor#visit<Crystal::Call>:Bool
  from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil
  from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil
  from Crystal::CodeGenVisitor#visit<Crystal::Call>:Bool
  from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil
  from Crystal::CodeGenVisitor#visit<Crystal::Call>:Bool
  from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil
  from Crystal::CodeGenVisitor#visit<Crystal::Call>:Bool
  from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil
  from Crystal::CodeGenVisitor#prepare_call_args_non_external<Crystal::Call, Crystal::Def+, Crystal::Type+>:Tuple(Array(LLVM::Value), Bool)
  from Crystal::CodeGenVisitor#visit<Crystal::Call>:Bool
  from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil
  from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil
  from Crystal::Compiler#codegen<Crystal::Program, Crystal::ASTNode+, Array(Crystal::Compiler::Source), String>:(Tuple(Array(Crystal::Compiler::CompilationUnit), Array(String)) | Nil)
  from Crystal::Compiler#compile<Array(Crystal::Compiler::Source), String>:Crystal::Compiler::Result
  from Crystal::Command#run_command<Bool>:Nil
  from Crystal::Command#run:(Bool | Nil)
  from __crystal_main
  from main
Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```

### PR DESCRIPTION
**Pull request by asterite**
Fixes #9823
Fixes #3822

We rewrite `->foo(X)` to `->(x : X) { foo(x) }` in case `self` in that context could cause a multi-dispatch. This is similar to #9824

I believe with this, Procs don't have any more bugs (that **I** am aware of, so this is probably a lie 😛 )

### CODE REVIEW

**Review by bcardiff — APPROVED** [review]

**Comment by asterite** [comment]
Well, I lied. There's #3822 but I'll fix it in this PR too. We should always do the replacement if there's no `obj`.

**Comment by asterite** [comment]
Done! Ready for another review.

**Comment by asterite** [comment]
There's something wrong in what I did but I'll fix it in the next days

**Comment by asterite** [comment]
CI is green! Ready for another review.

**Review by bcardiff — APPROVED** [review]

**Comment by Blacksmoke16** [comment]
Just a heads up this PR broke some stuff in https://github.com/athena-framework/validator.  I'm working up a reduction and will create an issue when I got something reproducible.

**Pull request merged**
