### PR TITLE
Fix problem of XML parsing empty html string. Fixes #2752

### LINKED ISSUE #2752: XML.parse_html yield invalid memory access
Hi all,

I was running some test on the API I am working on and found the following issue. When I run `XML.parse_html()` with a empty string the program crashes and reports `Invalid memory access`

```
Invalid memory access (signal 11) at address 0x8
[4309874299] *CallStack::print_backtrace:Int32 +107
[4309833463] __crystal_sigfault_handler +55
[140735701570858] _sigtramp +26
[4309990313] *XML::Error::new<Pointer(LibXML::Error)>:XML::Error +9
[4310062567] *XML::from_ptr<Pointer(LibXML::Doc)>:XML::Node +39
[4310062516] *XML::parse_html<String>:XML::Node +68
[4309799127] __crystal_main +2199
[4309842264] main +40
```

I understand this is a edge case, but the error should be reported more gracefully which I understand as one of the main goals of crystal and on of the reasons I have been loving the language. You can check the code I used to replicate the error [here](https://gist.github.com/andremrsantos/f447a1bb73f3d1ccbad9e400b60bdc41).

I hope this can contribute to the language.

### PR DESCRIPTION
**Pull request by fernandes**
Raise an exception when XML.parse_html called with an empty string.

This is a small PR, probably self-explanatory. Please give any suggestion of better place to put the test or make the check.

Thank you!

### CODE REVIEW

**Comment by asterite** [comment]
Thanks! Can you add the same fix for `self.parse`? It happens there too.

**Comment by fernandes** [comment]
@asterite sure, doing right now! :)

ps: I didn't add because I thought was only on parse_html, my bad 😉

**Comment by fernandes** [comment]
@asterite the second test (for `parse`) I added on `xml_spec.cr` just because makes more sense to me once it's the library name, is it ok?

**Comment by asterite** [comment]
@fernandes Thank you! 🌟

**Pull request merged**
