### PR TITLE
Fix small stuffs

### PR DESCRIPTION
**Pull request by Sija**
This PR introduces couple of small, harmless tweaks/fixes as the title suggests.

### CODE REVIEW

**Comment by Sija** [comment]
Damn, I'm still capable of borking a PR, opening next one...

**Comment by RX14** [comment]
Why not update this PR with force push?

**Comment by Sija** [comment]
@RX14 I did. After that, commit 6026ccc unintentionally became part of it.

**Comment by RX14** [comment]
You should be able to rebase on master and then force push the results. If all else fails, you can always cherry pick your commits to a new branch and force push that to this PR instead.

**Pull request closed without merging**
