### PR TITLE
A method to escape a string into uri safe structure

### PR DESCRIPTION
**Pull request by tbrand**
Hi there,
There is a critical difference between Ruby and Crystal for an implementation of URI.escape.

```
require "uri"
p URI.escape("https://crystal-lang.org/")
```
Then,
```
$ ruby sample.cr
-> "https://crystal-lang.org/"
$ crystal sample.cr
-> "https%3A%2F%2Fcrystal-lang.org%2F"
```
So it is difficult to escape a String in uri-safe structure like as Ruby's behavior.
So I added a method to keep the String url structure.
```
require "uri"
p URI.escape_uri_safe(":/?#[]@!$&\'()*+,;= ")
p URI.escape_uri_safe("https://crystal-lang.org?test=あああ")
```
Then,
```
$ crystal sample.cr
-> ":/?#[]@!$&'()*+,;=%20"
   "https://crystal-lang.org?test=%E3%81%82%E3%81%82%E3%81%82"
```

May be [this](https://github.com/crystal-lang/crystal/issues/2098) issue is involved.

Thanks for your review.

### CODE REVIEW

**Comment by jazzonmymind** [comment]
it looks like Crystal URI.escape has the same behaviour as URI.encode_www_form_component in Ruby. why not copy Ruby? it has:
* URI.escape
* URI.encode_www_form_component
* URI.decode_www_form_component

**Comment by tbrand** [comment]
Ruby's `encode_www_form_component` replaces reserved character as well.

```
[Ruby]
URI.encode_www_form_component("https://crystal-lang.org") # => https%3A%2F%2Fcrystal-lang.org
URI.escape("https://crystal-lang.org") # => https://crystal-lang.org (I need this!)
```

```
[Crystal]
URI.escape("https://crystal-lang.org") # => https%3A%2F%2Fcrystal-lang.org
URI.escape_uri_safe("https://crystal-lang.org") # => https://crystal-lang.org (My implementation)
```

But I agree that the relation between Ruby's implementation and mine is very confusing.
So if it is ok, I want to rename the original 'escape' method to 'encode_www_form_component' and mine to 'escape'.
On the other hand, I need to keep the backward compatibility.
Any comments?

**Comment by kostya** [comment]
👍

**Comment by asterite** [comment]
I wouldn't mind keeping "Ruby compatibility". I'm not sure I understand why so many methods are needed. I see:

```rb
URI.escape("https://crystal-lang.org") # => https://crystal-lang.org (I need this!)
```

Isn't that just the original string? In which case it would make a difference?

**Comment by asterite** [comment]
Or, another question, when do you need the behaviour of Ruby's `URI.escape`?

**Comment by kostya** [comment]
parts of uri paths usually escaped like this:

ruby
```ruby
URI.escape '/bla-жж/'
=> "/bla-%D0%B6%D0%B6/"
```
ruby
```ruby
URI.escape '/bla-жж/'
=> %2Fbla-%D0%B6%D0%B6%2F"
```

**Comment by kostya** [comment]
right now crystal URI.escape = CGI.escape, and no method for URI parts escape

**Comment by 5t111111** [comment]
> I wouldn't mind keeping "Ruby compatibility". I'm not sure I understand why so many methods are needed. I see:

Although I'm quite aware of that and that there are some actual use-cases for `URI.escape`, I think you would better pay attention to that `URI.encode` had become obsolete in Ruby long years ago.

http://stackoverflow.com/questions/34274838/why-is-uri-escape-marked-as-obsolete-and-where-is-this-regexpunsafe-constant/34275499

**Comment by asterite** [comment]
@5t111111 Thank you for the link!

I was also having a hard time imagining a use case for this. For example:

* somebody gives me an URI: it is supposed to be escaped already, right? So nothing to do.
* I want to build an URI from components (host, schema, etc.): I use URI.new, optionally using URI.escape to escape each of the query params.
* Other scenario...?

**Comment by kostya** [comment]
when you parse uri from html, for example, need to normalize it (escape, and ...)

**Comment by straight-shoota** [comment]
Another scenario besides creating a URI from individual components is encoding a string which is not directly used in a URI. URI encoding is also relevant for other applications like sending HTTP POST data as `x-www-form-urlencoded`.

We need the following transformations for strings:
* `https://en.wikipedia.org/wiki/Crystal (programming language)` => `https://en.wikipedia.org/wiki/Crystal%20(programming%20language)` (reserved characters are not escaped)
* `foo=bar baz&hello/` => `foo%3Dbar+baz%26hello%2F` (reserved charachters are escaped)

These should be implement in two different methods called `encode` and `encode_www_form` (not `escape`: it is an [**encoding**](https://en.wikipedia.org/wiki/Percent-encoding)), as most other API's (except Ruby originally) do:

* Elixir: [`URI.encode`](https://hexdocs.pm/elixir/URI.html#encode/2), [`URI.encode_www_form`](https://hexdocs.pm/elixir/URI.html#encode_www_form/1)
* PHP: [`rawurlencode`](http://php.net/manual/de/function.rawurlencode.php)
* Ruby: [`CGI.escape`](https://ruby-doc.org/stdlib-2.4.1/libdoc/cgi/rdoc/CGI/Util.html#method-i-escape),  [`URI.encode_www_form_component`](https://ruby-doc.org/stdlib-2.4.1/libdoc/uri/rdoc/URI.html#method-c-encode_www_form_component)
* Javascript: [`encodeURI`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI), [`encodeURIComponent`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent)

Please note that there are different rules for URI encoding with slight differences. I think it is sufficient to  implement only the most recent [RFC 3986](https://tools.ietf.org/html/rfc3986) (but keep the option to encode space as `+`)

**Comment by asterite** [comment]
I think we should do something about this. We should have a distinction between encoding an URI (Ruby's `URI.encode`/`URI.escape`, which also exists in [Elixir](https://hexdocs.pm/elixir/URI.html#encode/2)) and encoding a query component (Ruby's `URI.encode_www_form_component`, Elixir's `URI.encode_www_form`) and we should probably use names similar to Ruby/Elixir.

Also worth noting is that in Ruby, `URI.escape`/`URI.encode` is deprecated, and they advise using `CGI.escape`, which works exactly like Crystal's `URI.escape`.

So... I guess I don't know. But following what Elixir does seems good and safe.

**Comment by straight-shoota** [comment]
IIRC I have a branch with a new implementation laying around. I think it was delayed because I did the URI normalize stuff first.

**Pull request closed without merging**
