### PR TITLE
Remove duplicated `sort` related specs

### PR DESCRIPTION
**Pull request by MakeNowJust**
See https://github.com/crystal-lang/crystal/pull/10163#issuecomment-754995318

@straight-shoota Could you merge this in 5 minutes? If it is possible, I will rebase #10163 soon.

### CODE REVIEW

**Comment by straight-shoota** [comment]
Could you please leave a simple positive spec for every method? Like `[2, 1, 3].sort.should eq [1, 2, 3]`.

**Comment by MakeNowJust** [comment]
@straight-shoota They are still in specs of course.

**Review by straight-shoota — APPROVED** [review]

**Comment by MakeNowJust** [comment]
ping. Please review this for #10163

**Review by bcardiff — APPROVED** [review]

**Comment by rdp** [comment]
Looks like it only lacks a `crystal format` to proceed?

**Comment by MakeNowJust** [comment]
@rdp CI error message is `formatting './src/compiler/crystal/syntax/parser.cr' produced changes`. However, this PR does not change such a file of course.

I will rebase this to re-run CI. I believe it makes CI green.

**Comment by MakeNowJust** [comment]
Please! #10163 is pending due to this.

**Comment by MakeNowJust** [comment]
Thank you @straight-shoota and @bcardiff.

**Pull request merged**
