### PR TITLE
Fix cookie expiration header (#2150)

### LINKED ISSUE #2150: Cookie#to_set_cookie_header ignores time zone
I noticed some weird behaviour when setting an expiration date for cookies:

```crystal
require "http"

now_local = Time.now
now_gmt   = Time.utc_now # GMT time is the same as UTC time

puts "Local time is \t#{now_local}"
puts "GMT time is \t#{now_gmt}"     # => 
```
Result:
```
Local time is 	2016-02-13 00:45:36 +0100
GMT time is 	2016-02-12 23:45:36 UTC
```
The notation is different but both mean the same point in time: right now. So if I create one cookie from now_local and one from now_gmt I would expect them to expire at the same time: now.

```crystal
# Creating cookies that both expire right now
cookie_local = HTTP::Cookie.new("name", "value", "/", now_local)
cookie_gmt   = HTTP::Cookie.new("name", "value", "/", now_gmt)

puts cookie_local.expires
puts cookie_gmt.expires
```
Result:
```
2016-02-13 00:45:36 +0100
2016-02-12 23:45:36 UTC
```
So far so good. But now:
```crystal
puts cookie_local.to_set_cookie_header
puts cookie_gmt.to_set_cookie_header
```
Result:
```
name=value; path=/; expires=Sat, 13 Feb 2016 00:45:36 GMT
name=value; path=/; expires=Fri, 12 Feb 2016 23:45:36 GMT
```
One expires at 00:45 GMT and the other one at 23:45 GMT. So when transforming the expiration date to the header it somehow just set ```+0100```to ```UTC``` (or GMT) without deducting the one hour difference.

### PR DESCRIPTION
**Pull request by Thyra**
fixes #2150

### CODE REVIEW

**Comment by jhass** [comment]
Looks good but please add a spec or two.

**Comment by Thyra** [comment]
I did. It's not optimal because it will pass for people whose local timezone is GMT even without the fix but I couldn't find a way to create a Time object with a specific timezone to make sure it is not GMT either.

**Comment by jhass** [comment]
Mh, does setting `ENV["TZ"]` influence anything for now?

**Comment by Thyra** [comment]
No, unfortunately not:
```crystal
puts Time.now

ENV["TZ"] = "America/New_York"
puts Time.now
ENV["TZ"] = "EST"
puts Time.now

ENV["TZ"] = "Africa/Tunis"
puts Time.now
ENV["TZ"] = "CET"
puts Time.now
```
Result:
```
2016-02-13 15:17:57 +0100
2016-02-13 15:17:57 +0100
2016-02-13 15:17:57 +0100
2016-02-13 15:17:57 +0100
2016-02-13 15:17:57 +0100
```

**Comment by jhass** [comment]
Looks like 33cf8121a1ccaee083f1bd75c88099ec421745df from #2124 fixes things here, the sequence of `ENV["TZ"] = "blabla"; LibC.tzset" does affect the local time generated then. Not a pretty interface yet, but good enough for these specs IMO.

@ysbaddaden @asterite would you be okay with cherry picking that commit to master already?

**Comment by ysbaddaden** [comment]
I'm OK with cherry picking it. I'm not sure whether using `LibC.timezone` that is specific to linux is a good idea or not, or if we should be using something else that would be more portable. I don't know if that variable reports DST...

BSD and Linux all deprecated gettimeofday and OSX is the only one to not have `clock_gettime`.

**Comment by asterite** [comment]
I guess it's fine to cherry pick that. But at least on mac setting TZ works with that patch, but if you change it in the code it has no effect. Not sure this is what you need for the spec.

**Comment by jhass** [comment]
@asterite even after calling `LibC.tzset` again?

**Comment by asterite** [comment]
@jhass Right, nothing changes

**Comment by jhass** [comment]
Bummer.

**Comment by jhass** [comment]
Let's continue this in #2682.

**Pull request closed without merging**
