### PR TITLE
Print build errors to stderr

### PR DESCRIPTION
**Pull request by bew**
This addresses #4451 

There are some cases which needs discussion about where to prints them:
- usages messages on missing CLI argument
- build errors when output format is JSON

### CODE REVIEW

**Comment by mverzilli** [comment]
LGTM! I think the two cases you mention should also print to stderr. Why would you send them to stdout?

**Comment by bew** [comment]
About the JSON formatted errors, I'm thinking about the use-case of using shell commands:
```sh
$ crystal build --format json file.cr | use_the_json_output
```
Once the JSON errors will be on stderr, they'll have a _hard time_ getting the correct stream to go in the pipe to `use_the_json_output` program.

But maybe it's not our business, and it should stay on stderr, as most users will use their language's stdlib to spawn a process and granuraly get it's stdout/stderr programmatically.

**Comment by bew** [comment]
I don't know why the build doesn't work, did I broke something?

**Comment by Sija** [comment]
@bew so far, so (green) good... :)

**Comment by RX14** [comment]
The travis build fails so often or osx, why don't we just disable it or ignore the results and use circleci only?

**Comment by bew** [comment]
Rebased, osx still failing, are we waiting for #4528 to be merged? Or could this be merged soon?

**Comment by Sija** [comment]
Looks like GTG, merge-time?

**Comment by akzhan** [comment]
I'm unsure to write errors to STDERR in JSON output case.

Better to choose output stream based on output format. Errors to JSON to STDOUT is ok. Isn't it?

**Comment by Sija** [comment]
@akzhan I'd expect to see errors on `STDERR` on non-success process exit...

**Comment by bew** [comment]
@akzhan I believe that an error message should always go to stderr, whatever the output format is.

**Comment by akzhan** [comment]
@Sija @bew Ok.

**Comment by RX14** [comment]
Looks good to me, would be nice if we could spec this behaviour but i'm not *really* opposed to landing this without specs.

**Comment by mverzilli** [comment]
Restarted the build (I know, I know, we'll tackle that soon :)).

**Comment by RX14** [comment]
@mverzilli this PR is from may so I guess it doesn't have the `.travis.yml` merged so that OSX is an allowed failure.

**Comment by bew** [comment]
@RX14 You're right, I've rebased the branch on current master it should be good now.

**Comment by bew** [comment]
I've found another place where output should go on STDERR:
```diff
diff --git a/src/spec.cr b/src/spec.cr
index 2c3c303a5..aa49cdbcf 100644
--- a/src/spec.cr
+++ b/src/spec.cr
@@ -83,8 +83,8 @@ OptionParser.parse! do |opts|
     if location =~ /\A(.+?)\:(\d+)\Z/
       Spec.add_location $1, $2.to_i
     else
-      puts "location #{location} must be file:line"
-      exit
+      STDERR.puts "location #{location} must be file:line"
+      exit 1
     end
   end
   opts.on("--junit_output OUTPUT_DIR", "generate JUnit XML output") do |output_dir|
@@ -106,7 +106,7 @@ OptionParser.parse! do |opts|
 end

 unless ARGV.empty?
-  puts "Error: unknown argument '#{ARGV.first}'"
+  STDERR.puts "Error: unknown argument '#{ARGV.first}'"
   exit 1
 end
```
Should I add this change in this PR ?

**Comment by Sija** [comment]
@bew IMHO it's an addition in line with this PR, so yes, I'd add it too.

**Comment by RX14** [comment]
@bew that's not actually build errors though is it? I'm fine with modifying the spec runner in this PR but the commit should be renamed to "Print build and spec errors to stderr".

**Comment by bew** [comment]
Indeed it's not a build error, that's why I asked first.

I'll make another PR later today (or someone else can if he wants to!) for the spec runners, as it was not in the scope of this PR to check every possible `print`/`puts`.

**Comment by RX14** [comment]
@bew so, is this ready to merge?

**Comment by bew** [comment]
If you all agree, yes I think so.

**Comment by mverzilli** [comment]
Great job @bew! Thank you ❤️

**Pull request merged**
