### PR TITLE
Remove shell script wrapper

### PR DESCRIPTION
**Pull request by j8r**
Resolves https://github.com/crystal-lang/crystal/issues/7391
To sumup the points:
- simplifies debugging
- removes any confusion about which crystal binary is used
- helps for Windows support (or one prefer writing a bat file? :smile: )

For now this is a quick dirty draft to ping core members before continuing.

Please, submit any opinion in the related issue: https://github.com/crystal-lang/crystal/issues/7391

### CODE REVIEW

**Comment by asterite** [comment]
Please explain how I can run a specific spec file without this wrapper.

Right now I do:

```
bin/crystal spec spec/std/array_spec.cr
```

the `bin/crystal` wrapper sets the value of `CRYSTAL_PATH` to use the standard library in my local copy rather than the one that comes with the crystal installation.

How do I do that without the wrapper?

**Comment by j8r** [comment]
Environment variable, a bit like `GOPATH`?
The Makefile is already capable of doing this.

**Comment by j8r** [comment]
By the way this is only needed when doing compiler development, not for common users.

`export CRYSTAL_PATH=$PWD/src` once doesn't seem too bad, versus having to learn why using `./bin/crystal` and not `.build/crystal`.

But either the script is kept or not, `which go`, `which rustc`, or whatever language directly returns a binary – it's also possible to do it for Crystal for the end user.

**Comment by ysbaddaden** [comment]
This patch makes it harder to use a custom built crystal (binary + its stdlib), since CRYSTAL_PATH must be exported manually (regression), with different compiler builds it becomes a nightmare (huge regression) or... requires to write wrapper scripts manually :confused:

We can't run some compiler/std specs (not all of them) quickly without analyzing Makefile beforehand (regression) or manually exporting CRYSTAL_PATH again.

We can talk about not requiring a wrapper script, having a compile time configurable default CRYSTAL_PATH when the envvar is unset —thought paths will be relative, which is tricky to resolve flawlessly across platforms (hence why we leverage bash).

> export CRYSTAL_PATH=$PWD/src once doesn't seem too bad, versus having to learn why using ./bin/crystal and not .build/crystal.

Please. Calling bin/crystal is easy; .build/crystal is hidden to plain sight, and it even comes with a warning when run directly; manually exporting CRYSTAL_PATH all the time is tedious, error prone, and unfriendly and unwelcomed behavior.

**Comment by j8r** [comment]
Let me try something, I've to look deeper how other languages do.
It's strange that only Crystal require this.

**Comment by asterite** [comment]
It's not that it's required. It's a compiler developer tool. Remove it and we have to do some things manually (like always passing the ENV var, or manually choosing a compiler compiler).

I'll close this and the related issue.

**Comment by j8r** [comment]
@asterite if it's a developer compiler tool, don't ship it to the user.
I think it's possible to directly use `.build/crystal` without having a wrapper or setting env variables.

**Pull request closed without merging**
