### PR TITLE
Add `Array#truncate`

### LINKED ISSUE #10665: [RFC] `Array#truncate`
Often times it is useful to keep only a subsequence of elements in an `Array` and remove all others. There are many ways to do this in the standard library, but not a single _fast_ way:

```crystal
arr = [0, 1, 4, 9, 16, 25, 36, 49]

# 1. delete_at
# creates two intermediate arrays
arr.delete_at(4 + 1..)
arr.delete_at(...2)
arr # => [4, 9, 16]

# 2. replace
# creates an intermediate array for the remaining elements
arr.replace(arr[2..4])
arr # => [4, 9, 16]

# 3. select!
# moves the remaining elements
i = 0
arr.select! { i.in?(2..4).tap { i += 1 } }
arr # => [4, 9, 16]

# 4. pop+shift loop
# calls `Intrinsics.memset` on each removed element individually, which can be slow
(arr.size - 4 - 1).times { arr.pop }
2.times { arr.shift }
arr # => [4, 9, 16]

# 5. pop(n)+shift(n)
# creates two intermediate arrays
arr.pop(arr.size - 4 - 1)
arr.shift(2)
```

I propose the following new API. These overloads mirror some other methods like `#[]`:

```crystal
class Array(T)
  # Removes all elements except the *count* or less (if there aren't enough)
  # elements starting at the given *start* index. Returns `self`.
  def truncate(start : Int, count : Int) : self
    raise ArgumentError.new "Negative count: #{count}" if count < 0
    count = {count, size - start}.min
    return clear if count == 0

    @buffer.clear(start)
    (@buffer + start + count).clear(size - start - count)
    @size = count
    shift_buffer_by(start)

    self
  end

  # Removes all elements except those within the given *range*. Returns `self`.
  def truncate(range : Range) : self
    truncate(*Indexable.range_to_index_and_count(range, size) || raise IndexError.new)
  end
end
```

Some basic [benchmarks](https://gist.github.com/HertzDevil/f86d1ba395613618603f47b700da64d8) indicate that this method is indeed faster than the others, since it groups all the pops / shifts and doesn't create any intermediate arrays. Compared to the delete-based approaches, there is also no need to calculate the number of popped elements ourselves, since the `Range` overload takes care of that (the end value of the range can be negative if a fixed number of trailing elements is to be removed).

This was brought up on Gitter a few months ago, and at that time the pop+shift loop was the suggested solution, which is in fact not very fast when the proportion of removed elements approaches 50%. Another alternative is to have the compiler avoid codegen'ing the intermediate array allocations by observing those return values are never used, but the compiler currently has no facilities for proving a piece of code has no side effects, and that is very hard to implement (besides, LLVM would have done the same anyway).

### PR DESCRIPTION
**Pull request by HertzDevil**
Closes #10665.

### CODE REVIEW

**Comment by wontruefree** [comment]
I am curious.  Why no negative numbers?  could negative numbers indicate direction?

**Comment by HertzDevil** [comment]
That convention has never been adopted by any other methods on `Indexable`:

```crystal
array = [1, 2, 3, 4, 5]

array[array.size - 1, -3] # Unhandled exception: Negative count: -3 (ArgumentError)
```

**Review by asterite — APPROVED** [review]
Looks great!

**Review by straight-shoota — APPROVED** [review]

**Comment by straight-shoota** [comment]
Thanks @HertzDevil

**Pull request merged**
