### PR TITLE
Codegen: use var pointer for `out` instead of an extra variable

### PR DESCRIPTION
**Pull request by asterite**
For some reason I decided to implement `out` C function arguments like this:

```crystal
LibC.call(out x)

# Would do something like this
x = uninitialized Sometype...
ptr = uninitialized Pointer(typeof(x))
LibC.call(ptr)
pointerof(x).value = ptr.value
```

That's what the codegen did. But we can actually just let `out` pass a pointer to the local variable (which is already declared by the codegen.) This pointer thing was already done for instance variables, I don't know why the same wasn't done for vars.

For comparison, we have this `YAML` method:

```crystal
module YAML
  def self.libyaml_version : SemanticVersion
    LibYAML.yaml_get_version(out major, out minor, out patch)

    SemanticVersion.new(major, minor, patch)
  end
end
```

Before this PR it would generate this LLVM code:

```llvm
; Function Attrs: uwtable
define internal %SemanticVersion @"*YAML::libyaml_version:SemanticVersion"() #0 !dbg !13411 {
alloca:
  %major = alloca i32, align 4, !dbg !13413
  %minor = alloca i32, align 4, !dbg !13413
  %patch = alloca i32, align 4, !dbg !13413
  %0 = alloca i32, align 4, !dbg !13413
  %1 = alloca i32, align 4, !dbg !13413
  %2 = alloca i32, align 4, !dbg !13413
  %3 = alloca %SemanticVersion, align 8, !dbg !13414
  br label %entry

entry:                                            ; preds = %alloca
  call void @yaml_get_version(i32* %0, i32* %1, i32* %2), !dbg !13415
  %4 = load i32, i32* %0, align 4, !dbg !13415
  store i32 %4, i32* %major, align 4, !dbg !13415
  %5 = load i32, i32* %1, align 4, !dbg !13415
  store i32 %5, i32* %minor, align 4, !dbg !13415
  %6 = load i32, i32* %2, align 4, !dbg !13415
  store i32 %6, i32* %patch, align 4, !dbg !13415
  %7 = load i32, i32* %major, align 4, !dbg !13415
  %8 = load i32, i32* %minor, align 4, !dbg !13415
  %9 = load i32, i32* %patch, align 4, !dbg !13415
  %10 = call %SemanticVersion @"*SemanticVersion::new<Int32, Int32, Int32>:SemanticVersion"(i32 %7, i32 %8, i32 %9), !dbg !13414
  store %SemanticVersion %10, %SemanticVersion* %3, align 8, !dbg !13414
  %11 = load %SemanticVersion, %SemanticVersion* %3, align 8, !dbg !13414
  ret %SemanticVersion %11, !dbg !13414
}
```

Now it generates this code:

```crystal
define internal %SemanticVersion @"*YAML::libyaml_version:SemanticVersion"() #0 !dbg !13337 {
alloca:
  %major = alloca i32, !dbg !13339
  %minor = alloca i32, !dbg !13339
  %patch = alloca i32, !dbg !13339
  %0 = alloca %SemanticVersion, !dbg !13340
  br label %entry

entry:                                            ; preds = %alloca
  call void @yaml_get_version(i32* %major, i32* %minor, i32* %patch), !dbg !13341
  %1 = load i32, i32* %major, !dbg !13341
  %2 = load i32, i32* %minor, !dbg !13341
  %3 = load i32, i32* %patch, !dbg !13341
  %4 = call %SemanticVersion @"*SemanticVersion::new<Int32, Int32, Int32>:SemanticVersion"(i32 %1, i32 %2, i32 %3), !dbg !13340
  store %SemanticVersion %4, %SemanticVersion* %0, !dbg !13340
  %5 = load %SemanticVersion, %SemanticVersion* %0, !dbg !13340
  ret %SemanticVersion %5, !dbg !13340
}
```

I don't expect this to generate more performant code because LLVM probably optimizes this anyway, but it's still simpler code, both in the compiler's source code and in the generated LLVM code.

### CODE REVIEW

**Comment by asterite** [comment]
I noticed this when implementing `out` for the interpreter... I looked at the codegen to compare, and saw this wasn't done in the best possible way.

**Review by straight-shoota — APPROVED** [review]

**Comment by straight-shoota** [comment]
The failing win32 and test_linux32 CI jobs seem to be introduced by this change.

**Comment by asterite** [comment]
Strange! Well, I guess for now we can avoid merging this...

**Comment by asterite** [comment]
Closing because I broke something and I won't have time to look into this.

**Comment by asterite** [comment]
I'd like to revive this because I think this is correct. We just need to figure out why the Windows build failed.

**Comment by oprypin** [comment]
Well it's not failing now 🙂

**Review by beta-ziliani — APPROVED** [review]

**Pull request merged**
