### PR TITLE
Add global annotation Property

### PR DESCRIPTION
**Pull request by kostya**
This usefull when you want to set meta data between shards (and dont want to create annotations for every shard).
Also fix bug with yaml and json umapped usage.

### CODE REVIEW

**Comment by kostya** [comment]
specs failed, i think in 0.25.1 add only line: `types["Property"] = AnnotationType.new self, self, "Property"`, what you think?

**Comment by bew** [comment]
It's a nice idea, but `Property` looks way too generic to me, maybe `Serialization(ignore: true)` ? This way I think it's easier to see what it is about, and how it relates to JSON/YAML/you-name-it (de)serialization.

**Comment by kostya** [comment]
this is need not only for serialization but for many other things.

**Comment by bew** [comment]
Can you give examples of non-serialization usecase?

**Comment by jhass** [comment]
I think we still haven't set in stone that we never will impose a specific interface on annotations. When we do decide this, this would backfire quite a bit, so I'm not sure I like it and be it for the reason that it makes it harder to later do enforce interfaces on annotations.

**Comment by asterite** [comment]
Just ignore for YAML, JSON, and any other format you want. Crystal should not become a "write less oriented" language.

**Comment by kostya** [comment]
### example: when you have many modules which generate methods based on instance_vars:

```crystal
# generate doc for class
module Doc
  def to_doc
     {% for ivar in @type.instance_vars %} ... {% end %}
  end
end

# Calculate md5 based of class fields
module Md5
  def to_md5
     {% for ivar in @type.instance_vars %} ... {% end %}
  end
end

# Generate methods to_named_tuple, to_hash, ...
module To
  def to_named_tuple
     {% for ivar in @type.instance_vars %} ... {% end %}
  end

  def to_hash
     {% for ivar in @type.instance_vars %} ... {% end %}
  end
end
```

and others.

And you want to use it like this:
```crystal
class A
   include JSON::Serializable
   include YAML::Serializable
   include MessagePack::Serializable
   include Doc
   include Md5
   include To

   @a : Int32

   @[Property(ignore: true)]
   @b : String?
end
```

instead of:
```crystal
@[JSON::Field(ignore: true)]
@[YAML::Field(ignore: true)]
@[MessagePack::Field(ignore: true)]
@[Doc::Field(ignore: true)]
@[Md5::Field(ignore: true)]
@[To::Field(ignore: true)]
@b : String?
```


### And another usage is modules which extend class with another variable:
```crystal
module Bla
   @[Property(ignore: true)]
   @some_storage = Hash(String, String).new
end

class A
  include JSON::Serializable
  include JSON::Serializable
  include Bla
end
```

you dont know where this module would be included, and what ignore it should add (JSON::Field, or others.)

So shared Property would be nice in all this examples:

**Comment by asterite** [comment]
@kostya The thing is, nobody will write such code (maybe only you?). When I write a REST API, I provide JSON output, not ten thousand kinds of outputs. When I parse a file with yaml configuration, I use YAML serialization. When I want to send something over a socket fast, maybe I'd use msgpack. But combining serialization just to be as generic as possible doesn't seem to have a good use case.

And even if there's a use case, just write all that code. You write a lot of code in C# and it's consistent. You write a lot of code in Elixir and it's consistent. The way to destroy consistency is by introducing hacks just because you don't want to write more.

**Pull request closed without merging**
