### PR TITLE
Update `shell.nix` to `nixpkgs-24.05` and LLVM 18

### PR DESCRIPTION
**Pull request by straight-shoota**
Updates nixpkgs in `shell.nix` to 24.05 release. This release also brings LLVM 18 (and drops LLVM 11) so we update LLVM as well.

Closes #14269, #14592

### CODE REVIEW

**Review by ysbaddaden — APPROVED** [review]

**Comment by straight-shoota** [comment]
Like in #14592 there are some spec failures in CI related to iconv.
Somebody should investigate that on a macOS machine.

**Comment by HertzDevil** [comment]
Apparently [Apple replaced the system iconv implementation from an old GNU libiconv to a FreeBSD-based one in 2023](https://lists.nongnu.org/archive/html/bug-gnulib/2024-02/msg00123.html), so this is why I recalled not seeing those spec failures on my M2 in the past?

**Comment by HertzDevil** [comment]
We should pass either `-Dwithout_encoding` or `-Duse_libiconv`. The latter requires `pkgs.libiconvReal` rather than `pkgs.libiconv`, but there isn't an associated pkg-config file and the linker flag is only available in `$NIX_LDFLAGS`?

**Comment by HertzDevil** [comment]
My bad, it's `-Dwithout_iconv` rather than `-Dwithout_encoding`

**Comment by straight-shoota** [comment]
Now for some reason CI on macOS doesn't even complete anymore. https://github.com/crystal-lang/crystal/actions/runs/11682308922/job/32535751549?pr=14651 is running for 4 hours now.

**Comment by HertzDevil** [comment]
I think I have seen that outside this PR (https://github.com/crystal-lang/crystal/actions/runs/11856091183/job/33041700399), so I think we're fine?

**Comment by straight-shoota** [comment]
Without completion of the CI job we cannot be sure the changes in this PR actually work as expected.
We can of course test it locally to give some confidence, but CI is a different environment.

Also the fact that this hangup reproduces consistently makes me think it is related to the change.

**Comment by HertzDevil** [comment]
I tried applying #15150 and I think CI is progressing now: https://github.com/HertzDevil/crystal/actions/runs/11893760288/job/33139453764

**Comment by straight-shoota** [comment]
@HertzDevil That seems to have resolved it. So this is ready for review now.

We can probably updated to nixpkgs 24.11 soon.

**Review by HertzDevil — APPROVED** [review]

**Pull request merged**
