### PR TITLE
Fixes specs broken on BSD

### PR DESCRIPTION
**Pull request by wmoxam**
Fixes: https://github.com/crystal-lang/crystal/issues/4780

### CODE REVIEW

**Comment by akzhan** [comment]
LGTM.

It follows code (hw.ncpu).

**Comment by ysbaddaden** [comment]
Thank you!

**Comment by straight-shoota** [comment]
I mean this looks fine and is simple enough, but what about the two man rule?
Apart from that, milestone and perhaps labels are missing.

**Comment by ysbaddaden** [comment]
I can't set milestones nor labels them on mobile :(

**Pull request merged**
