### PR TITLE
Support LLVM 5.0

### PR DESCRIPTION
**Pull request by ysbaddaden**
Adds support for LLVM 5.0 (rc2). They didn't introduce much breaking changes, for once.

Warning: builds on #4396 (drop LLVM 3.5 and 3.6 support) which should be merged beforehand, or merged directly with this pull request.

### CODE REVIEW

**Comment by ysbaddaden** [comment]
The LLVM5 release notes:
http://llvm.org/svn/llvm-project/llvm/branches/release_50/docs/ReleaseNotes.rst

**Comment by akzhan** [comment]
Just want to note that we must drop support for buggy LLVM <3.9. So please rebuild omnibuses and get LLVM 5 compatibility.

**Comment by sdogruyol** [comment]
LLVM 5.0 is just released http://releases.llvm.org/5.0.0/docs/ReleaseNotes.html :+1:  LGTM :smile: ?

**Comment by asterite** [comment]
CI failed. There's some bug in the LLVM bindings that I can't find... an LLVMContext is disposed but apparently the debug metadata associated with it was already disposed... but I don't know where...

**Comment by ysbaddaden** [comment]
I rebuilt on Circle and it passed this time. Random failures...

I'll be happy to merge. Omnibus should already be using LLVM 3.8 now, and if need be it may revert thus patch to reenable LLVM 3.5, but I doubt this is needed.

**Comment by Sija** [comment]
@RX14 what about #4396 mentioned in PR's description?

**Pull request merged**
