### PR TITLE
Fix `crystal tool unreachable` & co visiting circular hierarchies

### LINKED ISSUE #14034: `crystal tool unreachable` doesn't seem to work with a default Lucky app out of the box
When I generate a brand new Lucky app, then try to run this command, I get this error

```
❯ crystal tool unreachable -s src/app.cr 
Parse:                             00:00:00.000047490 (   0.76MB)
Semantic (top level):              00:00:00.676927559 ( 154.28MB)
Semantic (new):                    00:00:00.003794976 ( 154.28MB)
Semantic (type declarations):      00:00:00.041002824 ( 170.28MB)
Semantic (abstract def check):     00:00:00.022827716 ( 186.28MB)
Semantic (restrictions augmenter): 00:00:00.012279238 ( 186.28MB)
Semantic (ivars initializers):     00:00:00.339022827 ( 218.34MB)
Semantic (cvars initializers):     00:00:00.016675461 ( 218.34MB)
Semantic (main):                   00:00:00.584360733 ( 282.46MB)
Semantic (cleanup):                00:00:00.000670768 ( 282.46MB)
Semantic (recursive struct check): 00:00:00.001140204 ( 282.46MB)

Macro runs:
 - /home/jeremy/Sites/zzz_test/lib/lucky/src/run_macros/generate_asset_helpers.cr: reused previous compilation (00:00:00.003366501)
Invalid memory access (signal 11) at address 0x7ffd98cb8e98
[0xe83369] ???
[0xe8332a] ???
[0x3b7250a] ???

❯ crystal -v
Crystal 1.10.1 [c6f3552f5] (2023-10-13)

LLVM: 15.0.7
Default target: x86_64-unknown-linux-gnu
```

### PR DESCRIPTION
**Pull request by straight-shoota**
Resolves #14034

### CODE REVIEW

**Review by ysbaddaden — APPROVED** [review]

**Comment by Blacksmoke16** [comment]
Does this also fix the error with the `implementations` tool from the OP?

**Comment by straight-shoota** [comment]
Ah thanks for the reminder. That doesn't fix those issues, but it seems to be the same bug.

**Comment by straight-shoota** [comment]
And IMO the cause for this bug is that `AliasType#types?` implicitly delegates to `aliased_type.types?`. This leads to circular hierarchies and I believe it's wrong (though I don't know how this affects other parts of the compiler code).

**Comment by straight-shoota** [comment]
I added the same fix into `TypedDefProcessor` which is used by the `context`, `expand` and `implementations` tool.
There are good reasons for a more extensive refactoring, but this is a minimal bug fix for now.

**Pull request merged**
