### PR TITLE
Added count_lines function

### PR DESCRIPTION
**Pull request by puppetpies**
I believe this could be a useful.

### CODE REVIEW

**Comment by jhass** [comment]
How about a `File.each_line` overload that returns an `Iterator` instead? Then one could simply `File.each_line(filename).size`.

**Comment by puppetpies** [comment]
I've amended the code !

**Comment by jhass** [comment]
Sorry I wasn't talking about using one but implementing it. Your current implementation doesn't make sure to close the file on errors :/

**Comment by asterite** [comment]
I added a `File.each_line` that returns an iterator. With that you can do what @jhass said: `File.each_line(file).size`. A `count_lines` method isn't general enough to be included in the standard library.

**Pull request closed without merging**
