### PR TITLE
WIP: Remove init command

### PR DESCRIPTION
**Pull request by j8r**
This PR removes the `crystal init` command.

## Initial problem
Beginners probably wants an easy way to initialize a new *standard* Crystal project:

To do it, (s)he has to choose between two commands:
- `shards init`
- `crystal init`

The first issue with this is: which one to use?

## Design considerations

As said in https://github.com/crystal-lang/crystal/pull/7138#issuecomment-445372645 , there is an inter-dependency where it shouldn't have one:

- the Crystal compiler itself shall not know shards
- shards, of course, know and depends of Crystal

Other languages like Rust with Cargo, Nodejs with npm, Go with dep, ruby with gem/bundler have this separation design.
Usually when there are project initialization logic, it lives on the package manager, not in the compiler: `cargo new`, `npm init`, `dep init`, `bundle init`.

## Solution

I'm working on merging it to `shards init` in https://github.com/crystal-lang/shards/blob/master/src/commands/init.cr , unless @ysbaddaden has a better idea?

### CODE REVIEW

**Comment by asterite** [comment]
Note: Crystal does now about `shards`. The whole `require` logic is built around that. I personally think `crystal init` should stay.

**Comment by ysbaddaden** [comment]
Don't spend time on this. Shards isn't a Crystal project management tool, but a dependency manager *for* Crystal projects. The `shards init` command is only meant to quickly create a `shard.yml` file in an *existing* project, for people like me that just creates a `foo/src` folder and start hacking *then* need to add a dependency, and don't want to create the `shard.yml` by hand.

**Comment by j8r** [comment]
@ysbaddaden So shards is similar to gem, and potentially a new project would be similar to `bundler`?

**Comment by j8r** [comment]
Whats the `crystal` command supposed to be?

Is there a compiler that provides project management, in addition to source code management?
For example, for go:
```
$ go
Go is a tool for managing Go source code.
```
Project management isn't going to be light, people will want new features to better initialize/manage their projects, which would likely be refused:
- adding other [CVS than git](https://github.com/crystal-lang/crystal/issues/4165)
- adding [shards version integration](https://github.com/crystal-lang/crystal/pull/5428)

**Comment by asterite** [comment]
Yes, there is: Crystal

**Comment by straight-shoota** [comment]
@asterite 
> Note: Crystal does now about shards. The whole require logic is built around that.

For the record: That's is not entirely correct. The compiler expects dependencies in the `lib` folder and looks for them in specific locations. This has certainly be designed with shards in mind (or literally *with* shards), but Crystal does not care *how* dependencies get there.

On the matter: While I'm not strictly opposed to the idea, I don't think there is much benefit worth the hassle. Besides, this PR puts the cart before the horse.

**Comment by RX14** [comment]
Maybe in the future we will remove `crystal init` (unlikely, bikeshedding over clean separation of compiling code and dependency management and project management tools isn't productive), but this PR is not it. It will need far more discussion and a concrete plan, not just a PR to remove the code with no replacement.

**Comment by j8r** [comment]
I guess we need a RFC repo like in Rust for stuff like this - opening an issue.

**Pull request closed without merging**
