### PR TITLE
Allow OSX failures on Travis CI

### PR DESCRIPTION
**Pull request by Sija**
Refs #3721 and https://github.com/crystal-lang/crystal/pull/4494#issuecomment-306584176.

### CODE REVIEW

**Comment by matiasgarciaisaia** [comment]
There are two main reasons to **not** merge this _by now_.

1) We're testing if the CircleCI plan's limits are enough for us. There's a "build minutes per month" limit that we still don't know if are enough for us or not.
2) We're working with TravisCI _(really awesome)_ support to learn _why_ the Xcode 8.2 builds are randomly failing while trying to `brew install llvm`. I'm in contact with them, and hopefully will have an answer soon.

So I say we should wait 👍

**Comment by matiasgarciaisaia** [comment]
On second thought - we should allow failures for xcode 8.2 until it gets fixed.

**Comment by Sija** [comment]
[Build #8674](https://travis-ci.org/crystal-lang/crystal/builds/240556148) failed on _osx_ too.

**Comment by Sija** [comment]
We could add all *osx* section to `allow_failures` for now...

**Comment by matiasgarciaisaia** [comment]
Be my guest:

```
diff --git a/.travis.yml b/.travis.yml
index 55502d412..99495506c 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -3,6 +3,7 @@ sudo: required
 dist: trusty
 services:
   - docker
+os: # need to declare on top level for `allow_failures` to work
 matrix:
   include:
     - env: ARCH=i386 ARCH_CMD=linux32
@@ -12,6 +13,8 @@ matrix:
     - os: osx
     - os: osx
       osx_image: xcode8.2
+  allow_failures:
+    - os: osx
   fast_finish: true
 before_install:
   - bin/ci prepare_system
```

**Comment by Sija** [comment]
I'm wondering is `os` the proper top-level key? Documentation [states](https://docs.travis-ci.com/user/customizing-the-build#Rows-that-are-Allowed-to-Fail) mentions `env` key, but no `os`. Am I missing sth?

**Comment by Sija** [comment]
@matiasgarciaisaia I've pushed changes moving *osx* builds into `allowed_failures` section which seems to work (without adding `os` top-level key you suggested).

**Comment by Sija** [comment]
ping?

**Comment by sdogruyol** [comment]
Is there any blocker for this to be merged? @matiasgarciaisaia

**Comment by matiasgarciaisaia** [comment]
👍 LGTM. Thanks for the PR!

**Pull request merged**
