### PR TITLE
CHANGELOG: Add missing links to Github issues

### PR DESCRIPTION
**Pull request by straight-shoota**
**EDIT:** 
Sometimes people (at least me and occasionally somebody in chat) want to look up more details about a change even if it was introduced some time ago. Providing the ID of an issue/PR helps finding the relevant discussion. Turning that ID into a hyperlink makes it even easier accessible. This change is simple enough but can help to improve discoverability of previous decision making.

### CODE REVIEW

**Comment by straight-shoota** [comment]
Can this get a second approval? 👍

**Comment by luislavena** [comment]
What about using footer links instead?

```markdown
* Something ([#123])

[#123]: https://github.com/crystal-lang/crystal/issues/123
```

It does not require to change the entire changelog and also doesn't necessarily need to have all the links at the footer of the document, could be between releases and it will not show on the rendered markdown.

Cheers.

**Comment by straight-shoota** [comment]
What's the benefit? It still needs changes everywhere a link to an issue is referenced. And then again in the footer links section. I don't think there is any downside of having inline links. That's what's been used in the CHANGELOG in other places. Changing that would be out of scope.

**Comment by straight-shoota** [comment]
1. Yes, the purpose of this PR is to add the missing links, at least where specific issues are referenced.
2. Who cares?
3. Sometimes people (at least me and occasionally somebody in chat) want to look up more details about a change even if it was introduced some time ago. Providing the ID of an issue/PR helps finding the relevant discussion. Turning that ID into a hyperlink makes it even easier accessible. This change is simple enough but can help to improve discoverability of previous decision making.

**Comment by luislavena** [comment]
@straight-shoota I care, introducing a diff for the purpose of satisfy the rendered version of a document is a good one, which could have been explained in the first place by simply providing an initial description of the purpose.

Please don't get me wrong, I'm not against it, but explaining the real intention behind it _not just for the sake of adding links_ clears these doubts.

Thank you for taking the time explaining the reasoning. 👍

**Comment by straight-shoota** [comment]
@luislavena sorry for the confusion. I thought it was self-explanatory. Added the explanation in the OP.

**Pull request merged**
