### PR TITLE
[RFC] Ruby-like iterators

### PR DESCRIPTION
**Pull request by asterite**
This is an RFC in the form of a PR because this is a proof that it can be done.

# Rationale

Consider this code:

```crystal
a = [1, 2, 3, 4, 5]

it1 = a.each
it2 = it1.map { |x| x + 1 }
it3 = it2.map { |x| x + 10 }
it4 = it3.select { |x| x.even? }

p it1.to_a
p it2.to_a
p it3.to_a
p it4.to_a
```

What do you expect the output to be?

...

Well, the output before this PR is:

```
[1, 2, 3, 4, 5]
[]
[]
[]
```

The reason is that, once the first iterator is consumed, all other iterators just get "STOP" . They don't start from the beginnig.

If you run the same code in Ruby you get this:

```
[1, 2, 3, 4, 5]
[2, 3, 4, 5, 6]
[12, 13, 14, 15, 16]
[12, 14, 16]
```

I think this is more intuitive, and I hope you also consider it more intuitive too.

If you are familiar with Rails' ActiveRecord, this will look familiar too:

```ruby
all_users = User.all
users_with_an_email = all_users.where("email IS NOT NULL")
users_with_an_email_and_age = users_with_an_email.where("age IS NOT NULL")
```

Each "query" builds on top of the other, but they are all independent objects. If you call `to_a` on any of them, you get a result which doesn't affect results of queries based on those. And calling `to_a` multiple times gives you the same results over an over (well, ActiveRecord probably caches the result).

The point is, each query represents a query ready to be executed, and it can be executed as many times as you like it.

I think iterators should work like that in Crystal too. They already work like that in Ruby!

Now, what happens with `next`? In Ruby:

```ruby
a = [1, 2, 3, 4, 5]
it = a.each
p it.next # => 1
p it.to_a # => [1, 2, 3, 4, 5]
p it.next # => 2
p it.to_a # => [1, 2, 3, 4, 5]
p it.next # => 3
p it.to_a # => [1, 2, 3, 4, 5]
```

As you can see, the iterator keeps track of the current element, but calling `to_a` on it seems to read all elements from the beginning... BUT the state of the `next` iteration is preserved.

In real life, you would probably never mix `next` with other methods. You either want internal iteration (`each { ... }`, `to_a`, etc.) or external iteration (`next`). And `to_a` always represents all the iterated elements as an array.

If you run the above code with this PR, the output is the same as Ruby. Same for the output of the first snippet.

# Why?

In AoC (but it could be in any other scenario) I wanted to be able to have this. I formed an iterator over the chars of a string:

```crystal
each_char_with_index = string.each_char.with_index
```

Then I wanted to filter those chars with indexes in two different ways... and there's no way to easily do this. You just have to write `string.each_char.with_index` over and over again. I think this could be improved.

# How?

All methods that consume an iterator are based on `each` that receives a block. To make the above behavior work, we can:
1. Dup self. For this dup must dup any wrapped iterators.
2. Rewind the iterator
3. Iterate the rewinded iterator using `next`

So this relies on some new behavior, and some old behavior that was removed in #7440
1. The ability to `dup` an iterator. With this, you can capture the state of an iterator into a separate iterator, so calling `next` on the duped iterator doesn't affect the original one.
2. The ability to `rewind` an iterator.

I believe these two things can actually be useful outside of this PR. With all three things (`dup`, `rewind` and independently composing iterators) I think iterators become really powerful, but also more intuitive and composable.

Yes, it's a bit more tedious to implement an Iterator, but:
1. `dup` is generically defined here by copying all fields from the original iterator, and dupping any wrapped iterator (so for most iterators this will already work out of the box)
2. rewinding an iterator is usually easy. Take a look at the diff in #7440, it wasn't that much code!

I know I go forward and backwards with this subject, but I believe this is the ultimate and best solution to the problem.

This PR is WIP because I didn't implement `rewind` for all iterators, but if we all agree on moving forward with this I can continue working on it.

What do you think?

### CODE REVIEW

**Comment by asterite** [comment]
Another example:

```crystal
a = [1, 2, 3]
it = a.each
it.each do |x|
  it.each do |y|
    puts "#{x}, #{y}"
  end
end
```

What do you expect the output to be?

In Ruby:

```
1, 1
1, 2
1, 3
2, 1
2, 2
2, 3
3, 1
3, 2
3, 3
```

In Crystal before this PR:

```
1, 2
1, 3
```

After this PR it works exactly like in Ruby... which is pretty crazy!

**Review by grkek — APPROVED** [review]

**Comment by asterite** [comment]
Thinking a bit more, I made `Iterator` always define `rewind` but raise `NotImplementedError` by default. That is, `rewind` can be optionally defined. And `dup` will be already defined for all iterators and most probably in a correct way. So this change will work out of the box if `next` and is never combined with internal iteration. This will improve all iterators without users needing to change anything.

**Comment by wontruefree** [comment]
This is interesting.  I wonder if there are any examples in the stdlib that could benefit from this change.

**Comment by asterite** [comment]
The stdlib and the compiler don't use iterators because they are less efficient than not using them. But iterators are fine to use in other (higher level) situations.

**Comment by straight-shoota** [comment]
Looks great :+1: That's really how you would expect iterators to work.

Maybe the part about `next` could be postponed and discussed separately? Mixing internal and external iteration is expected to be be quirky. I'm not convinced of re-introducing `#rewind` with raise by default.

The major benefit is really the duping for internal iteration. That behaviour I'm sure we definitely want as it is implemented.

**Comment by asterite** [comment]
How would you do it without rewind? Or maybe we just make it clear that mixing internal and external iteration shouldn't be done and that's it. If you do it, then you will get mixed results too :-)

**Comment by straight-shoota** [comment]
Yes, it could just be accepted to be that way. In case of the path iterators it's actually expected to consume some elements with `next` and then the rest with `each`. I'm not saying that we should just leave it that way, but discuss it a distinct feature because that discussion may become more complex. And it shouldn't hinder the dup feature which works perfectly well by itself without `rewind` for most use cases.

**Comment by asterite** [comment]
I still think implementing `rewind` is very easy and we should do it.

**Comment by asterite** [comment]
Actually, maybe dropping `rewind` is fine. We dropped it because it's not always possible to rewind... for example if you are streaming values from a socket. There's also `Iterator.of { ... }` which is impossible to rewind (though it's also impossible to `dup`).

Another thing: in Ruby it's not always the case that `to_a` on an Enumerator will give the same values. For example:

```ruby
f = File.open(__FILE__)
e = f.each_line
p e.to_a # => ["f = File.open(__FILE__)\n", "e = f.each_line\n", "p e.to_a\n", "p e.to_a\n"]
p e.to_a # => []
```

In Ruby it's [documented](https://ruby-doc.org/core-2.6/Enumerator.html#method-i-next) that if `next` has side-effects, like advancing the read pointer of an IO, then it's not guaranteed that results will always be the same:

> Note that enumeration sequence by next does not affect other non-external enumeration methods, unless the underlying iteration methods itself has side-effect, e.g. `IO#each_line`.

Well, that's slightly different than what I wanted to say... I think that means that calling `next` doesn't affect the values returned by `to_a` and others.

In our case, we can document that `next` does affect the resulting values, but calling non-external methods that "fully consume" the iterator do not... so calling `to_a` doesn't affect the values returned by `next`. In that way you can actually skip a few values with `next` and then `to_a` will return the remaining values... though maybe that's a bit counter-intuitive, I don't know.

**Comment by HertzDevil** [comment]
Speaking of `dup`, it always confuses me that only some wrapper iterators are structs and others are classes.

**Comment by asterite** [comment]
The idea is that struct is used when the iterator is immutable, otherwise it's a class. Does that not hold in some cases?

**Comment by straight-shoota** [comment]
So, do we want to move forward with this?

**Comment by asterite** [comment]
Yes! What do we do? I can send a PR that just has `dup`, and then we can discuss `rewind` later on, maybe in a separate PR. What do you think? (I still think `rewind` is a nice thing to have, specially because it's usually easy to implement).

**Comment by asterite** [comment]
Actually... is there any harm in trying rewind? For example this code in Ruby:

```ruby
dir = Dir.open(__dir__)
e = dir.each
p e.to_a
p e.to_a
```

prints all the entries of the dir twice. In Crystal it would just print them once... making the result less idempotent and predicatble.

For some reason if you do this in Ruby it's not the same:

```ruby
file = File.open(__FILE__)
e = file.each_line
p e.to_a
p e.to_a
```

You only get the file lines once, then you get an empty array. However, if we `rewind` in Crystal it will work even better than Ruby.

Of course it won't work for all IOs because some are not rewindable... and that's fine! I'd say, if there's a way to rewind the iterator and that works, let's do it. Otherwise, it will work as it used to work before. But in most cases it will work better.

But, hmm... I guess we can separate this into two PRs so it's at least easier to review.

**Comment by asterite** [comment]
The code is updated! I removed `rewind` and only kept `dup`, and added it to a few missing iterators (well, just one: `Flatten`).

So at least if you don't mix `next` with `each` you'll get predictable results. And if you do, you still get predictable results, just not like in Ruby. And with `IO` things it won't be that predictable, but I'll leave that for a separate PR because it might not be accepted.

**Comment by straight-shoota** [comment]
Thank you, discussing rewind separately is good ❤️

There's still a merge conflict.

**Comment by asterite** [comment]
Conflict resolved!

**Comment by asterite** [comment]
Actually, this is missing a few more `dup`... I wonder if `Iterator#dup` should simply dup all objects, not just those fields with `Iterator`. That means that it would be more of a `clone`, but maybe it's fine.

For context, `each_permutation` doesn't always work well (isn't idempotent).

**Comment by asterite** [comment]
I changed `Iterator#dup` to dup all fields and that fixes it.

**Comment by asterite** [comment]
Hmm... dupping all the time is not good. I think we need to override `dup` for every iterator more or less. Right now a couple of tests are failing. For example if you do `[1, 2, 3].each.each { ... }` that will dup the original array which is not good for performance.

Let's close this for now, this needs a bit more thought.

**Pull request closed without merging**
