### PR TITLE
add Enumerable#pmap

### PR DESCRIPTION
**Pull request by kostya**
very useful from celluloid

### CODE REVIEW

**Comment by jhass** [comment]
Can we name this `con_map` or `spawn_map` perhaps? All parallel programs are concurrent, but not all concurrent programs are parallel.

**Comment by alex-fedorov** [comment]
What about `parallel_map` ?

**Comment by jhass** [comment]
My point is that, at least currently, it's not parallel at all, only concurrent.

**Comment by alex-fedorov** [comment]
Then `concurrent_map` :) Longer than `con_map` but not so cryptic.

**Comment by technorama** [comment]
@jhass `spawn` will be parallel soon.  `pmap` or `parallel_map` can be named for it's intent even if the current implementation isn't parallel yet.

**Comment by Nakilon** [comment]
I called this refinement `Array#parallel_map` in my Ruby programs. I'm ok with `pmap`.

**Comment by asterite** [comment]
@kostya Thanks!

But each `future` call creates a channel, so it's probably not very efficient. There's also a double `map` there.

I believe `parallel_map` can be implemented much more efficiently, maybe using a single channel, I don't know.

**Comment by ozra** [comment]
+1 for naming after what it _will_ be / intent, not current implementation status.
+1 for `pmap` - this is one of those cases where a short name will be nice, since one can expect a lot of methods being doubled up `pmethod` for parallell version.

**Comment by kostya** [comment]
with future it simple, but with channel it become little complex:
it looks like this, but not complete because this not catch exceptions correctly.
```ruby
  def parallel_map(&block : T -> U)
    ary = Array(U).new
    chan = Channel({Int32, U}).new
    c = 0
    each do |e|
      spawn { chan.send({c, block.call(e)}) }
      c += 1
    end

    ary = Array(U).new(c)
    c.times do
      id, e = chan.receive
      ary[id] = e
    end
    ary
  end
```

**Comment by asterite** [comment]
We (me and @waj) need to think this a bit more, so for now we won't add it so we don't have a method that starts to be used and then we might change or remove. Once we have parallelism support we can rethink this. You can off course define this in a shard or in your project until then :-)

**Pull request closed without merging**
