### PR TITLE
Avoid reallocation in `Enumerable#each_cons` and `Iterator#cons`'s default reused array

### PR DESCRIPTION
**Pull request by HertzDevil**
Implements https://github.com/crystal-lang/crystal/issues/7189#issuecomment-777147888 for the case of `Array`. (The original issue has been resolved so it can be closed regardless of this PR.)

Suppose we have

```crystal
(1..).each_cons(4, reuse: true) { |v| }
```

`v` has an initial capacity and size of 4, and `#each_cons` will push and shift `v` before the second iteration. This means `v`'s internal buffer must be reallocated to a new one that can store 8 elements, for any `Enumerable` whose `size > 4`. (It doesn't matter whether the push or the shift occurs first, since an `Array`'s elements are always laid out contiguously. No further reallocations are performed after this iteration.) We could reduce memory usage by ~33% if we use this capacity upfront. Here it is assumed that the case where `each_cons` yields more than once occurs much more frequently than where it yields 0 or 1 times.

The case for `reuse = false` is largely unaffected; every `v` is a `dup` so saving one reallocation doesn't help much.

`Iterator#cons` seems to benefit much more from this than `Enumerable#each_cons(&)`. I don't know why.

Also fixes the documentation so that `each_cons_pair` refers to the actual count parameter instead of `size`.

### CODE REVIEW

**Comment by straight-shoota** [comment]
I don't understand why "a second iteration would have reallocated the array to that capacity [=n * 2] anyway". The second iteration pushes an element at the end and shifts the first one, thus capacity is `n + 1`. And so forth for every following iteration.
If finally reaches `n * 2` as the maximum capacity before the array is resized.

But this maximum is never reached when `count` is bigger than `n / 2`. So I suppose the initial capacity could be further optimized for `n / count < 2`.

**Comment by asterite** [comment]
Instead of pushing an element and then shifting one, can the logic be changed to first shifting an element if we are at desired size, then pushing an element? That way we never exceed the requested size.

**Comment by HertzDevil** [comment]
It works for `Deque` but not `Array`. Remember that `Array` now adjusts the buffer pointer but keeps the root buffer, so after the first element is shifted there is still no space for the next element:

```crystal
x = [1, 2, 3, 4]
x.shift
# now x's root buffer looks like [_, 2, 3, 4], not [2, 3, 4, _]
```

Since `Array` reallocates its buffer following a geometric sequence, the next capacity is `2 * n`, not `n + 1`.

**Comment by straight-shoota** [comment]
> the next capacity is 2 * n, not n + 1.

Only if it needs to resize. It doesn't need to resize if we allocate a large enough buffer beforehand. And large enough can be smaller than 2 * n, depending on the ratio between n and count.

**Comment by HertzDevil** [comment]
There is no ratio between `n` and `count`, and there is no ratio between `n` and `size` either because we can't call `Enumerable#size` here.

**Comment by straight-shoota** [comment]
Okay, let's leave it like that then. Potential optimization could be implemented for Array/Indexable later.

Yet another reason for #10014

**Review by straight-shoota — APPROVED** [review]

**Review by oprypin — APPROVED** [review]

**Pull request merged**
