### PR TITLE
Implement StringLiteral#count

### PR DESCRIPTION
**Pull request by Blacksmoke16**
Implements StringLiteral#count.

### CODE REVIEW

**Comment by bcardiff** [comment]
I’m courious, was this feature needed in some use case?

**Comment by Blacksmoke16** [comment]
I needed it to count the number of placeholder values in a URL path, i.e. `"/users/:user_id/posts/:post_id".count (':')`.

Other way to do it would be like `"path".chars.select { |chr| chr == ':' }.size`

**Comment by j8r** [comment]
@Blacksmoke16 you can do `"/users/:user_id/posts/:post_id".split(':').size}}`

**Comment by straight-shoota** [comment]
At some point we need to establish some consistent policy how to decide which methods should be available in the macro language. We shouldn't port all of `String` to `StringLiteral`.

But I don't see a reason why not to merge this and it has a use case. There are workarounds, but they obscure meaning.

**Comment by asterite** [comment]
Yes, right now there's no clear policy about which macro methods should exit. However, we should probably have all methods from string and all non-mutating methods from array/hash to allow simpler macro code to be written.

**Pull request merged**
