### PR TITLE
Workaround llvm.powi.* intrinsics not available on win32

### PR DESCRIPTION
**Pull request by RX14**

### CODE REVIEW

**Comment by luislavena** [comment]
@RX14 wouldn't be better move the platform condition down to `LibM` and define those `func` replacements there instead?

Apologies if this was discussed elsewhere.

Thank you.

**Comment by RX14** [comment]
@luislavena I'm not sure what you mean...

**Comment by luislavena** [comment]
Apologies for the brevity of previous message.

I was thinking something similar to the approach taken in #5533 and reduce the number of places platform condition needs to be checked to only `LibM`.

Cheers.

**Comment by RX14** [comment]
@luislavena no, I did that because creating an entirely new function is the *only way* to create a new va_list.

**Comment by luislavena** [comment]
Thanks for the clarification. Was simply a thought.

Cheers.

**Pull request merged**
