### PR TITLE
Visual and structural improvements to docs generator HTML

### PR DESCRIPTION
**Pull request by straight-shoota**
This adds the following improvements to the docs generator:

**Structural**

* renamed partial templates with leading underscore to distinguish them from page templates
* combined shared code for `<head>` into partial `_head.html` partial (DRY up)
* combined shared code for sidebar into partial `_sidebar.html` (DRY up)
* replaced element IDs for CSS selectors with classes to reduce specifity in stylesheets (avoid specifity wars)
* replaced absolute position with flexbox
* added `.sidebar-header` element (which currently includes `.search-box`)

**Visual**

* added CSS class `.source-link` with improved visual style to source links
* <del>changed default font to [Roboto](https://fonts.google.com/specimen/Roboto)</del>
* <del>added [Montserrat](https://fonts.google.com/specimen/Montserrat) as accent font</del>
* added a:hover indicator
* increased border for h2
* limited width for content elements (`p`, `pre`) to `55 em` for improved legibility
* added a slight background and border for inline code elements
* added a slight visual separation between `.sidebar-header` and `.types-list`

## Fonts
*Font changes have been removed from this PR to be discussed in #5053*
<del>The API docs should use Crystal's CD font Roboto as specified on https://crystal-lang.org/media/ to have a similar visual style as other Crystal resources. The previous default Avenir is not openly available and fallbacks Tahoma, Lucida Sans and Lucida Grande don't look very nice.
Better alternative fonts are Muli and Lato whith a similar appearance to Avenir, so I added them as fallbacks, too.</del>

<del>Montserrat looks nice with Roboto for headlines and other accented styles.</del>

<del>All added fonts are available on Google Fonts, though only the defaults
Roboto and Montesrrat are loaded through the stylesheet.</del>

## Preview
**[LIVE PREVIEW](https://straight-shoota.github.io/crystal/doc-improvements/)**

README with fonts and h2 border-bottom:
image

Sample with fonts, code background and limited line length:
image

Sample with source link and limited line length:
image

### CODE REVIEW

**Comment by straight-shoota** [comment]
I've added a `.sidebar-header` element (which currently includes `.search-box`) which makes the search box stand out a bit from the results list. This would also be a good spot for name, version and date of the documented API as suggested in #4754 

The [live preview](https://straight-shoota.github.io/crystal/doc-improvements/) shows the current state.

There is also a [preview](https://straight-shoota.github.io/crystal/doc-search/) of an enhanced search interface based on this PR and #4746. I'd like to get this or the other merged so I can rebase accordingly and keep a simple commit history.

**Comment by oprypin** [comment]
Good job! Can't wait for this

> There is also an [enhanced search interface](https://straight-shoota.github.io/crystal/doc-search/) based on this PR and #4746. I'd like to get this or the other merged so I can rebase accordingly and keep a simple commit history.

---

I am against using web fonts. Keep it lightweight.

**Comment by oprypin** [comment]
Inline code looks weird.
Compare Overview in [old](https://crystal-lang.org/api/0.23.1/Benchmark/BM/Job.html)/[new](https://straight-shoota.github.io/crystal/doc-improvements/Benchmark/BM/Job.html)

**Comment by oprypin** [comment]
There is way too much spacing added in the sidebar, both regarding the width and line spacing. I'd say the spacing is too much even as it is right now.

**Comment by straight-shoota** [comment]
Thanks for your remarks @oprypin, I'll address your comments in one:

* Web fonts don't add much overhead, it just needs to be downloaded once. From a technical point this is negligible considering the API docs are usually browsed relatively frequently. It is rather a question of visual style: should there be a unique look everywhere (may or not be based on Crystal CI guidelines) or more variation and usage of system-specific fonts.
* I added a slight border around inline code to highlight it against regular text. In the current style it is not always easy to distinguish. Although I believe I added this before I changed the fonts, and Roboto and Consolas have a higher contrast than Avenir and Consolas. If we keep this fonts it might be okay to remove the border.
* The paddings there did not change. I think this entire type list needs some review in a dedicated topic, There are some usability issues in the way this is implemented and it might be worth rethinking navigation overall. There have been a few comments and ideas about that in the past.

**Comment by oprypin** [comment]
Here's what I see. 
image
Can't agree with "paddings there did not change". We don't need to discuss the sidebar's general problems to see that something is off.

**Comment by straight-shoota** [comment]
Tahoma on the left (which is the current default if Avenir is not available) has much bigger letters than Roboto on the right, even at the same font-size. The paddings are exactly the same, it's just that the letters on the right are smaller and therefore increase the impression of space around the text.

**Comment by oprypin** [comment]
Do you not see that the picture on the right has a wider sidebar and also fits in less text vertically? They are taken at the exact same scale and viewport size

**Comment by oprypin** [comment]
Mobile [before](https://user-images.githubusercontent.com/371383/29295670-f0ec6afc-8155-11e7-9907-7ebcadd45553.png)/[after](https://user-images.githubusercontent.com/371383/29295675-f5cd88b2-8155-11e7-9ba9-33a4072a8c14.png) ☹️

**Comment by RX14** [comment]
- You should set the list padding to `0` and use `line-height: 1.5` for the list.
- Web fonts are fine as long as there's a defined fallback which also looks good.
- Mobile in general needs the sidebar to be toggleable.

**Comment by straight-shoota** [comment]
@oprypin Oh yes, the width of the sidebar changed slightly but this has nothing to do with paddings. Before, it was a relative value (`20%` of viewport width) and I changed it to an absolute `30em` which makes more sense in general, considering that the viewport could be very large or very small but the sidebar should always be about the same width. This could be further improved by making the width slightly responsive.

Mobile sucks before and after. I have a few improvements for that (including toggleable sidebar) but I'd address this in another PR because this one is already quite extensive and tweaking a responsive layout can be challenging by itself. I'd prefer to get this merged as the *standard* layout for "normal size" screens and then work on improving other sizes.
I guess I should remove the `viewport` meta attribute until there is proper support for smaller screens.

@RX14 I don't see any benefit in using line-height over vertical padding. There shouldn't be any line breaks inside a type list item, so there shouldn't be any difference. But if there would be one by any chance, it's better to have the space between items defined as padding instead of line-height.

**Comment by RX14** [comment]
@straight-shoota the benefit of `line-height` is that it's relative to the font size. Just replacing `.types-list a` with `line-height: 1.5; padding-left: 30px` makes the left arrows *more* central. At least in firefox.

**Comment by straight-shoota** [comment]
@RX14 I guess that depends on your defaults. The triangle element `a::before` has a fixed height of `30px`. A font-size of `16px` (that's the default value in my Chrome installation) with `line-height: 1.5` results in the total height of the anchor element at `24px` - which means a misaligned triangle. With a default line-height of (usually) `1.2` the line height is `19.2px` and with two `5px` paddings it adds up to about `30px` total height - which makes the triangles fit.
So yes, this needs a big overhaul but also requires a discussion about the usability features.

**Comment by vladfaust** [comment]
I usually very tolerant to design updates if they aim to minimalism and efficiency. But in this case I strongly dislike new fonts. They are much harder to read. Regarding to headers, it feels like serif font. I vote for Roboto! :fist_oncoming:

**Comment by akzhan** [comment]
What about separate pull requests? 

I want all of this except fonts.

Fonts may be subject of another PR.

**Comment by straight-shoota** [comment]
Sure, I can easily extract the fonts to discuss them separately. Though I'd like to hear what others (especially core members) think first.

**Comment by ysbaddaden** [comment]
First of all, the structural changes are very welcome. It follows overall good practices and cleans things up :+1:

I'm not fond of visual changes. The bolder view-source link is attracting the attention too much and isn't very pretty. The new fonts may follow the Crystal branding, but this isn't a crystal branding website, this is a reference. We should focus on readability, try to fit better with the gitbook documentation maybe, not impose Crystal branding to the documentation of each and every project.

To be honest, I don't like the actual fonts either. I wish we used a mere `helvetica, sans-serif` and `consolas, monospace`, and improved typography with a `line-height: 1.4` —best rendering, best readability to my taste.

Also, the actual sidebar behaves better on smaller screen than yours. I'm not talking of smartphones screens, but half of my 15" laptop screen for example: yours takes too much space, at the expense of the documentation I'm looking for.

**Comment by straight-shoota** [comment]
Thanks for the feedback!

* I'll try modify the source links to make them stand out less. Maybe some lighter color and smaller font-size can do this or a lighter font size.
* I think it's best to discuss fonts in a separate issue. I was pretty confident that everyone would agree to follow the Crystal CI but obviously this is not the case ;)
* Half a 15" laptop screen is actually about the size of a smartphone and we need a solid solution for these sizes anyway: Neither the current nor my proposal are very usable. I'll add a `max-width: 20%` to reduce the width on smaller viewport sizes until there is a proper solution.

**Comment by ysbaddaden** [comment]
No. Half of my 15" inch laptop screen is bigger than my 9.7" iPad. It's a *lot* bigger than my 5" smartphone !

**Comment by straight-shoota** [comment]
@ysbaddaden I wasn't talking about physical dimensions but visually perceived size. A typical 15" laptop screen fits about 80 to 85em horizontal, a smartphone or tablet usually somewhere between 50 and 60em. So half a 15" screen actually fits less characters per line than a 5" smartphone in default font size.

I have removed the font changes from this PR and opened #5053
Small-screen display has been improved (basically to be similar as it was before this PR) and the source links have been downsized.
The [preview link](https://straight-shoota.github.io/crystal/doc-improvements/) now contains the updated changes.

**Comment by chances** [comment]
Is this PR dead in the water?

The search input's placeholder text is not accessible as-is, according to the W3C's [WCAG specification](https://www.w3.org/TR/WCAG21/):

Screenshot from 2021-12-15 18-21-12

**Comment by straight-shoota** [comment]
> Is this PR dead in the water?

Pretty much, yes. Most of the proposed changes have been applied in separate PRs. Not even sure what else is left to do. So I guess it's time to close this. We can alwas cherry pick items from here.

Please open a new PR for the placeholder text.

**Comment by chances** [comment]
Okay, I've opened #11604.

**Pull request closed without merging**
