### PR TITLE
Fix each* methods to return a receiver itself

### PR DESCRIPTION
**Pull request by MakeNowJust**
All `each` and methods like `each` should return a receiver itself. For example, current `Deque#each` returns `Range?`, it looks like a bug. (But `each_cons` and some `Enumerable` methods return `nil` same as Ruby)

### CODE REVIEW

**Comment by asterite** [comment]
Thank you!

We copied Ruby here when we made `each` return `self`. However, now I'm more inclined to make them return `nil`. I never understood why it's useful to return `self`. But I'd like others' opinion here :-)

**Comment by MakeNowJust** [comment]
@asterite I asked it to matz in twitter, and answered now. https://twitter.com/yukihiro_matz/status/815905904084197376

Matz says "To return `self` by `Array#each` and some methods is not big meaning. But it is better than to return `nil`."

**Comment by MakeNowJust** [comment]
@asterite My question: To return `self`, does it have effects for optimization? And if returning `nil`, does it have no effect?

**Comment by asterite** [comment]
Yes, of course :-)

If a method returns `nil` then for code generation it returns `void` in LLVM. Then if you have a method like:

```cr
def foo
  some_array.each do
  end
end
```

then `foo` now returns the array, but if `each` returns `nil` then `foo` will return `nil`. This can also prevent some union types.

But this is not the point. I never understood why `each` (or `p`, or `puts`) return something other than `nil`. This is kind of ugly:

```cr
obj.each do
  # ...
end.do_something_else
```

so maybe I'd like to remove that anti-feature from the standard library.

**Comment by ysbaddaden** [comment]
I think we can remove it. It's not such a big deal.

**Comment by asterite** [comment]
Closed in favor of #3826

**Pull request closed without merging**
