### PR TITLE
Drop `Crystal::FiberChannel`

### LINKED ISSUE #14222: `spec/std/channel_spec.cr` gets stuck on Windows with `-Dpreview_mt`
Running that spec file will block at the `raises if channel was closed` test. Increasing `CRYSTAL_WORKERS` from the default 4 makes two more specs run and pass, but after that the `awakes all waiting selects` test still blocks.

This reduction, probably the first Windows-specific one we have, similarly blocks at the `CRYSTAL_WORKERS + 1`-th loop:

```crystal
100.times do |i|
  p i

  x = Atomic(Int32).new(0)

  spawn do
    x.set(1)

    spawn(same_thread: true) do
      while true
        Fiber.yield
      end
    end
  end

  while x.get == 0
    Fiber.yield
  end
end
```

The snippet doesn't block if run without `-Dpreview_mt` or run on Linux.

### PR DESCRIPTION
**Pull request by HertzDevil**
Fixes #14222. This doesn't affect `IO.pipe`'s behavior on Windows.

### CODE REVIEW

**Review by ysbaddaden — COMMENTED** [review]
`Fiber.yield` enqueues a 0 second timer, so the next event loop wait won't block. Don't we enter a busy loop when there's nothing to do but wait on the event loop?

**Comment by HertzDevil** [comment]
I almost managed to replace it with `Fiber.suspend` / `reschedule` on Windows, but then the same code no longer works on WSL. I think this is because `fiber_channel.receive` implicitly tells Libevent to monitor the pipe, without which `Crystal::LibEvent::EventLoop#run` immediately returns. So I believe the use of `IO.pipe` is actually a Libevent-exclusive implementation detail, and it is fine if Windows does something else entirely.

**Comment by ysbaddaden** [comment]
Handling the parked/sleeping state is very tricky, especially in MT.

The IO pipe enables a double trick: it allows the run loop to enter the parked/sleeping state, while making sure that there's always something in the event loop.

For example libevent won't block if there are no registered event/timer (nothing to wait for) so with this change the thread will enter a busy-loop again when it happens —and won't our IOCP evloop do the same?

Note: the IO pipe would also work for Windows/IOCP _if_ reading from the reader was nonblocking.

Maybe we can find an alternative to FiberChannel on Windows, and keep it otherwise?

**Review by straight-shoota — APPROVED** [review]

**Comment by HertzDevil** [comment]
It looks like overlapped I/O operations don't always use events either; if they have no timeouts, then `Crystal::IOCP::OverlappedOperation#wait_for_completion` calls `Fiber.suspend`, in which case `Crystal::IOCP::EventLoop#@queue` only ever takes care of definite `sleep`s and timeout `select` actions.

**Comment by straight-shoota** [comment]
I'm not sure what's the status of this. Do we want to merge this change or leave it as is due to the upcoming changes with execution contexts?

**Comment by ysbaddaden** [comment]
**Today**: removing `FiberChannel` with the current schedulers means we assume a timer will _always_ be enqueued. This happens to be true thanks to the stack-pool-collector fibers that we happen to create on each thread (and thus on each event loop) and repeat a timer.

While the assumption is true, it's a bit fragile :face_with_diagonal_mouth: 

If we drop the stack-pool-collector fiber, then the `FiberChannel` becomes mandatory on UNIX again.

As stated by @HertzDevil: IOCP is broken because it only keeps track of timers and won't try to check for completion otherwise. It's only working thanks to the `stack-pool-collector` fiber.

**Near future**: the `ExecutionContext` schedulers don't need `FiberChannel` but they need the evloop to properly report whether it has pending operations, otherwise the schedulers assume the evloop is empty and will park the thread(s). Oops: infinite hang.

**Proposal**: Quinton's idea of the IOCP evloop assuming a +infinite timeout is a good idea, it would avoid having to keep track of operations. The Polling evloops already do that when blocking is true, and we could instruct libevent to do just the same (`EVLOOP_NO_EXIT_ON_EMPTY`) so all evloops would exhibit the same behavior :thinking:

**Comment by ysbaddaden** [comment]
As for this PR I'm not sure. I'd keep `FiberChannel` if `:unix` and `:preview_mt`, and on Windows I would call `EventLoop#interrupt` on win32 (always).

BTW: `PostQueuedCompletionStatus` is probably a better solution for interrupting `GetQueuedCompletionStatusEx` than an `UserAPC`.

**Comment by ysbaddaden** [comment]
**Alternative**: tell `libevent` to not exit even where there are no events.

That could become a requirement of evloop implementations. The polling eventloop already blocks forever, and so does the refactored IOCP evloop (#15238) 

We wouldn't need `FiberChannel` anymore and could just call `Crystal::EventLoop#interrupt` when the scheduler is sleeping (once). Since we must grab the lock anyway, it's simpler to just push the fiber to the runnables Deque than passing the pointer through a pipe.

**Pull request closed without merging**
