### PR TITLE
Add repology badge to README

### PR DESCRIPTION
**Pull request by Sija**
SSIA

### CODE REVIEW

**Comment by j8r** [comment]
Why the site says that Crystal is absent from the Alpine Linux Edge repository? This isn't the case.

**Comment by AMDmi3** [comment]
The package naming discrepancy has been sorted out - all relevant packages are now under `crystal-lang`

**Comment by RX14** [comment]
@Sija as a maintainer I have to think about the big picture. If we merge one badge for a service which is unused by crystal core devs, i.e. "unofficial", people will use this PR as an excuse to merge more badges like this in the future. I think the badges should stay minimal and be links to official channels or services.

This service is cool, but unlike all the other badges (except maybe the code triage one), it's not officially part of the crystal workflow. We use travis and circle for CI so they should be there, gitter and bountysource are official channels. Repology is something I've never even heard of before.

**Comment by AMDmi3** [comment]
I'd agree that the badges should stay minimal, however note that badges are not only useful to project developers but also to users and newcomers, so it makes sense to inform them that the project is well packaged in many distro repositories.

Honestly I don't find this particular type of badge too useful for this purpose, but somebody does as there was a request to add it to Repology. There are [other types of badges](https://repology.org/metapackage/crystal-lang/badges) too, maybe the big one could be more useful somewhere in the [installation](https://crystal-lang.org/docs/installation/index.html) documentation section.

**Comment by straight-shoota** [comment]
Installation instructions are provided in the docs. That's where people should be pointed for installing Crystal. Maybe it would make sense to include a link to Repology there, but a badge isn't too helpful, actually.

**Comment by AMDmi3** [comment]
> Installation instructions are provided in the docs. That's where people should be pointed for installing Crystal.

- It doesn't hive any hint on how recent version you will get
- It doesn't cover all the repositories

**Comment by straight-shoota** [comment]
@AMDmi3 Yes, the installation instructions are nowhere complete. But let's focus on fixing that instead of simply adding some batches to the readme.

**Comment by Sija** [comment]
Would GitHub release badge be regarded as useful?

GitHub release

**Comment by j8r** [comment]
More ideas taken from the [Nim's README](https://github.com/nim-lang/Nim/blob/devel/readme.md):
* Separate build status badges and community badges
* Build details on the right of the Crystal title, or in a section like in [Julia](https://github.com/JuliaLang/julia/blob/master/README.md), to see directly the status of Linux32, Linux64 and macOS builds.
* Add the official twitter account https://twitter.com/CrystalLanguage
* Use flat buttons, more modern and in line with the design of https://crystal-lang.org/ and https://crystal-lang.org/api/master/

The IRC channel can also be mentioned.

**Comment by jhass** [comment]
It seems like there's little to no interest to this from any core member. Let's close this :)

**Pull request closed without merging**
