### PR TITLE
Add WASD keys in 2048.cr

### PR DESCRIPTION
**Pull request by r00ster91**
So you can use WASD keys also if capital letters are enabled.

### CODE REVIEW

**Comment by bew** [comment]
Looks like there is already `wasd`, why add `WASD` ?

**Comment by r00ster91** [comment]
Look in **Files changed**. Now you can also use the wasd keys even if you have enabled caps lock.

**Comment by bew** [comment]
What if the user's keyboard is not qwerty (like me)? Should we handle all existing keyboard layout and combinations of caps locks, etc?

**Comment by r00ster91** [comment]
But whats with the Q key? Why is this supported then?

**Comment by bew** [comment]
I don't know, maybe the one who did this sample code has an habit for quitting a software with `Q`. I don't think that's because of caps lock.

**Comment by r00ster91** [comment]
Hm okay :/

**Pull request closed without merging**
