### PR TITLE
Do not collapse whitespaces in playground sidebar.

### PR DESCRIPTION
**Pull request by hugopl**
`"   3"` should be show as `"   3"`, not `" 3"`.

### CODE REVIEW

**Comment by asterite** [comment]
Hi! Could you provide a couple of before/after screenshots?

**Comment by hugopl** [comment]
Before
before
After
after

**Comment by hugopl** [comment]
No idea how to auto test this without the bloat used on normal web apps testing frameworks....

**Comment by asterite** [comment]
Oh, come on, testing this should be easy. You just need a couple of npm packages: https://twitter.com/thomasfuchs/status/1103700462107164672?s=20 ;-)

**Comment by asterite** [comment]
Just in case (because sometimes it's hard to tell when I'm saying something funny or serious): there's no need to write tests for this. Sorry if the above came harsh for some reason.

**Comment by hugopl** [comment]
nah, all good. :-)

**Pull request merged**
