### PR TITLE
Change racial undertone variable name

### PR DESCRIPTION
**Pull request by LesterCano**
Hello,

I modified some instances of the `firstNonWhite` variable, as it could possible have a racist undertone. "First non white person of whom?"

Also changed it to be more expressive for what that variable is actually doing (and less oppressive).

### CODE REVIEW

**Comment by j8r** [comment]
Why not, if it really bothers you – the variable is more descriptive. Do you mind to change to snake case, `first_non_white_space`?

**Comment by LesterCano** [comment]
Hi @j8r, good idea, done.

**Comment by groud** [comment]
Hello, just coming from the Godot community. We had to face a vague of trolls, apparently coming from 4chan requiring such changes (see https://boards.4chan.org/pol/thread/186588488#p186588488).

As all other troll, @LesterCano has a 1day old account and only opens issues about such topics.

**Comment by LesterCano** [comment]
@groud Not sure why you decided to come over here to spam my PR. Please mind your own business.

**Pull request closed without merging**
