### PR TITLE
Formatter: remove unnecessary escape sequences 

### PR DESCRIPTION
**Pull request by RX14**
After https://github.com/crystal-lang/crystal/issues/8459, I'd like to make invalid escape sequences a syntax error. The first step towards doing that is to introduce a warning, and to make the formatter automatically correct this mistake.

However, I found plumbing the warning apparatus (in `Program`, which is a hell class) through to the `Parser` painful, so I left it out for now.

I'd like feedback on whether a warning should necessarily be required before making this change, given that the formatter can fix it automatically. And if not, how is the best way to plumb this (duplicate the code, or pass the whole `Program` into the `Parser`?)

### CODE REVIEW

**Comment by RX14** [comment]
Anyone want to discuss whether a warning is required for this?

**Comment by bcardiff** [comment]
There is no context shared between parsing and compiling, where the deprecation.
Something like that might help to remove some duplicates between the cli and program.

Given the nature of this change, I say that emitting always the warnings to STDERR is enough.
And I can tolerate the breaking change without warning. The fix is syntactic, there is no documentation or semantic change. The fix should be able to be inferred locally:

`\" invalid escape sequence, did you mean "?`

seems helpful enough, plus applying the change today works on latest. So people can have a codebase working on latest+nightly.

**Comment by RX14** [comment]
Okay, so should we merge this formatter fix for next release, then make this a compile error a release after?

**Comment by straight-shoota** [comment]
@RX14 Needs a rebase.

**Comment by bcardiff** [comment]
I think that making an invalid char escape sequence a compiler error is an improvement. 
I'm not sure the formatter should automatically fix the code in this case though.

As of 0.32.1 `'\s'` is a parser error but `"\s"` is not (same with other invalid char escape sequence)

Wouldn't it be better to make `"\s"` a parser error? 
And keep the formatter away from changing the code?

**Comment by RX14** [comment]
@bcardiff you can see it's an existing error in the codebase, I really wanted a formatter release which allows people to easily fix all the occurences of this.

**Comment by bcardiff** [comment]
So on a future release, the invalid escape sequence within a string will cause a parser error and the formatter will stop correcting this. Right?

If so, this pr is fine as is, no need for a warning.

**Comment by RX14** [comment]
@bcardiff yeah that was my intention

This has been rebased and reformatted, so a quick merge would be nice

**Pull request merged**
