### PR TITLE
Rename `HTTP::Params` to `URI::Params`

### LINKED ISSUE #10052: Rename `HTTP::Params` to `URI::Params`
`HTTP::Params` is actually a pretty generic implementation of attribute-value pairs as they are used in different URI schemes, not only for HTTP.

It's used as return type of `URI#query_params` which supports the argument that it is not closely connected to HTTP since there's no other direct relation there.

### PR DESCRIPTION
**Pull request by straight-shoota**
Resolves #10052

There are a few additional commits with some cleanup and enabling the use of `URI::Params` in `URI.new` and `URI#query_params=`.

### CODE REVIEW

**Review by jhass — APPROVED** [review]

**Review by bcardiff — APPROVED** [review]
I agree the `URI::Params` name is better. I guess this will break `HTTP::Params` reopening.

The lack of support to detect deprecated aliases will make the alias definition stay a bit longer, I think.

If nobody thinks these reasons are not that important we can merge it.

**Comment by straight-shoota** [comment]
Reopening actually works with aliases 👍

**Comment by wontruefree** [comment]
Is there any deprecation or migration path we should provide people?

**Comment by Blacksmoke16** [comment]
Related https://github.com/crystal-lang/crystal/issues/10125.

**Pull request merged**
