### PR TITLE
Add MatchData#matches_full_string?

### PR DESCRIPTION
**Pull request by straight-shoota**
Adds a methd that tells whether a regex matched the entire string or not.
I found such a method useful, so maybe it would be good to have it by default.

### CODE REVIEW

**Comment by oprypin** [comment]
I feel like this could have edge cases. Would be nice to "fuzz" it against `matches? /\Apattern\Z/`

**Comment by oprypin** [comment]
Wish the name was shorter. Also probably good to clarify that it means **matched** full string, not that it could potentially match it, which the current name might be confused for.

**Comment by oprypin** [comment]
Ha, it might also be an important note (in docs?) that this is not equivalent to `\A\Z`. E.g. `foo+?` `matches_full_string` would give a different result from `\Afoo+?\Z`

**Comment by jhass** [comment]
Yeah, what's wrong with wrapping into `\A\z`?

**Comment by oprypin** [comment]
Uh I was just saying that it gives a different result

`\Afoo\z` matches "foo" but **not** "foooo".
`foo` matches "foo" or "foooo" but the latter match is not the full string.

And, more subtly and more importantly,

`\Afoo+?\z` matches "foo" or "foooo".
`foo+?` matches "foo" or "foooo" but the latter match is not the full string.

**Comment by jhass** [comment]
Ah sorry, I misunderstood the purpose of this. It's if you do want to match both, a partial or a full string but disambiguate the result. 

I think that's rare enough (I never once needed it) that I don't mind the long method name.

**Comment by straight-shoota** [comment]
> Yeah, what's wrong with wrapping into `\A\z`?

My use case is regular expressions that come frome user input but should only be matched fully. If you want partial matches, you need to add `.*` explicitly to the pattern.

Wrapping the user-supplied patterns in `\A#{pattern}\z` would also work, but it's an extra step.

**Comment by oprypin** [comment]
But @straight-shoota, as per my example, this implementation is not useful for your use case!

**Comment by oprypin** [comment]
The choice that you want only a full match needs to be known in advance to the regex engine. It should also be specified in advance in the API as most programming languages have. In Python there's `re.fullmatch`

**Comment by straight-shoota** [comment]
I honestly don't care about /foo+?/ not matching the entire string. 

> In Python there's re.fullmatch

That might be a better idea. There's already `String#starts_with?(regex : Regex)` and `String#ends_with?(regex : Regex)`, so this would seem to fit.

**Comment by straight-shoota** [comment]
Implemented fullmatch in #9312. If that gets merged, this one here is probably not that useful anymore.

**Pull request closed without merging**
