### PR TITLE
Allow leading and trailing whitespace in number strings

### PR DESCRIPTION
**Pull request by Sija**
Followup to #5589.

### CODE REVIEW

**Comment by RX14** [comment]
We typically have options for these, going from the `String#to_i` args.

**Comment by Sija** [comment]
@RX14 I know but decided against it, because `String#to_*`methods are implemented directly within `String`, and `Big*` classes are re-opening `String` with their own `#to_big_*` impl.

**Comment by ysbaddaden** [comment]
You do implement the skip, using `strip`, so you can implement the options to allow whitespace or not.

**Comment by bcardiff** [comment]
If we are relaxing the treating of whitespaces we should probably allow them between the sign and the number itself. Please ensure the same rules applies for non-big numbers. If custom logic is used to ignore whitspaces we should ensure (adding specs) that some other whitspace than 0x20 is treated as whitespace.

**Comment by RX14** [comment]
Plus, all these string copies are expensive.

**Comment by straight-shoota** [comment]
I see a valid use case for parsing numbers with stripping whitespace.

* But the implementation needs to be configurable. I'd be fine with making that behaviour default, but there should be an option to control it.
* The current implementation is not very performant because it creates string copies. Limiting the char array passed to the C function would avoid additional allocations.
* Non-Big number types should also be covered.
* In the current state, it's better to just call `strip` explicitly when you need this behaviour.

I propose to close this PR. If someone comes up with a new proposal, I'd be happy to accept it. But it's not a pressing issue, since the alternative is trivial.

**Pull request closed without merging**
