### PR TITLE
Add aarch64 support for macOS/darwin targets

### LINKED ISSUE #10066: Add Aarch64 support for macOS
Since Apple now ships ARM processors on their computers, it would be nice to have this platform supported by the Crystal compiler.

Crystal already supports AArch64 for Linux and Darwin on x86_64, so achieve Tier 3 support as a first step should be feasible ~~without too much work~~. 
EDIT: Actually, an ABI for Apple devices should be [adapted](https://developer.apple.com/documentation/xcode/writing_arm64_code_for_apple_platforms) from the [aarch64](https://github.com/crystal-lang/crystal/blob/master/src/llvm/abi/aarch64.cr) one.

A target triple such as `aarch64-apple-darwin` can already be provided to the `--target` argument, but the compiler will fail as C bindings for this target are missing.

This [commit](https://github.com/RomainFranceschini/crystal/commit/b416f5d8e157d071f7b582ce2d58f52c83faeeaa) adds the LibC bindings for the target. It is basically a copy-paste-modify from the `x86_64-darwin` target, where the modify part is inspired by what the rust team did ([rust-lang/libc#1817](https://github.com/rust-lang/libc/pull/1817)) for the same purpose.

It seems to be enough to produce simple binaries, maybe it could be the basis for a PR if you think it goes into the right direction.

### Cross-compiling

To test whether this slight change is enough for cross-compilation, you need (besides the hardware):

- [A side-by-side installation](https://soffes.blog/homebrew-on-apple-silicon) of homebrew (one for ARM, one for x86_64). I will refer to them as `brew` and `ibrew` respectively.
- Install Crystal runtime requirements for ARM `brew install gmp libevent libyaml openssl@1.1 pcre pkg-config bdw-gc`. While homebrew on ARM is not officially supported yet, those compiles fine from sources.
- Install the x86_64 official release of Crystal as well as LLVM 9 since Crystal does not support LLVM 11 yet. `ibrew install crystal-lang llvm@9`

The next step is to build the modified compiler for x86_64 first (using Homebrew's `crystal` running under Rosetta):
- `LLVM_CONFIG="$(ibrew --prefix)/opt/llvm@9/bin/llvm-config make"`

Now we can try to cross-compile programs to ARM using our built from source Crystal.

First, we need to build an ARM version of `libcrystal`:

- `cc -c -o sigfault.o src/ext/sigfault.c/sigfault.c`
- `ar -rcs libcrystal.a sigfault.o`

And finally:

- `./bin/crystal build samples/binary-trees.cr --cross-compile --target aarch64-apple-darwin --release`
- `cc binary-trees.o -o binary-trees -rdynamic -L$(brew --prefix)/opt/bdw-gc/lib -L$(brew --prefix)/opt/pcre/lib -lpcre -lgc -lpthread libcrystalarm.a -L$(brew --prefix)/opt/libevent/lib -levent -liconv -ldl`

We can check the architecture with `file ./binary-trees`. My console shows `./binary-trees: Mach-O 64-bit executable arm64`

The next step would be to cross compile the compiler itself, but it is more difficult as:

- I was not able to compile LLVM 9 for ARM.
- LLVM 11 for ARM compiles, but Crystal does not support this version yet (see [#9809](https://github.com/crystal-lang/crystal/issues/9809)).

### PR DESCRIPTION
**Pull request by maxfierke**
Resolves #10066

Work from @RomainFranceschini and I, this PR adds the libc bindings for `aarch64-apple-darwin` (thanks Romain!) and implements proper handling for the `arm64-apple-darwin` triple (which is a synonym, and presented by default via LLVM on Apple Silicon)

Compiling requires a working `x86_64` crystal compiler (via Brew for e.g.) that can be run via Rosetta 2. For working on this, we've installed ARM homebrew to  the `/opt/homebrew` prefix and Intel Homebrew to its usual `/usr/local` prefix. More info on that [here](https://soffes.blog/homebrew-on-apple-silicon).

As the Intel homebrew is installed to a default lookup path, `x86_64` libraries will be read first, so we need to do some overriding of environment variables to get the linker to look up arm64/aarch64 libraries correctly.

Cross-compilation instructions for the compiler:

### Environment

```
export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
alias ibrew="arch -x86_64 /usr/local/bin/brew"
export INTEL_BREW_PREFIX="$(ibrew --prefix)"
export INTEL_LLVM_ROOT="$INTEL_BREW_PREFIX/opt/llvm"
export INTEL_LLVM_CONFIG="$INTEL_LLVM_ROOT/bin/llvm-config"

export ARM_BREW_PREFIX="$(brew --prefix)"
export ARM_LLVM_ROOT="$ARM_BREW_PREFIX/opt/llvm"
export ARM_LLVM_CONFIG="$ARM_LLVM_ROOT/bin/llvm-config"
```

### Compiling libcrystal.a

```
cc -c -o sigfault.o src/ext/sigfault.c
ar -rcs libcrystal.a sigfault.o
```

### Compiling bdw-gc

```
$ git clone https://github.com/ivmai/bdwgc.git
$ cd bdwgc
$ git clone https://github.com/ivmai/libatomic_ops.git
$ autoreconf -vif
$ ./configure --enable-static --disable-shared
$ make -j
$ make check
```

Then copy `.libs/libgc.a` into the Crystal source root

(You can also `brew install --HEAD bdw-gc`, which has the MT patches too, and is effectively the same as doing the above.)

### Compiling Crystal for ARM

```
$ LLVM_CONFIG="$INTEL_LLVM_CONFIG" \
   LDFLAGS="-L$INTEL_LLVM_ROOT/lib" \
   CPPFLAGS="-I$INTEL_LLVM_ROOT/include" \
   CC="$INTEL_LLVM_ROOT/bin/clang" \
   AR="$INTEL_LLVM_ROOT/bin/llvm-ar" \
   arch -x86_64 make

$ LLVM_CONFIG="$INTEL_LLVM_CONFIG" \
   LDFLAGS="-L$INTEL_LLVM_ROOT/lib" \
   CRYSTAL_CONFIG_TARGET=aarch64-apple-darwin \
   CRYSTAL_CONFIG_LIBRARY_PATH="$ARM_BREW_PREFIX/lib" \
   arch -x86_64 ./bin/crystal build src/compiler/crystal.cr --cross-compile --target aarch64-apple-darwin -Dwithout_playground

$ LLVM_CONFIG="$ARM_LLVM_ROOT/bin/llvm-config" \
   LDFLAGS="-L$ARM_LLVM_ROOT/lib" \
   $ARM_LLVM_ROOT/bin/clang -I$ARM_LLVM_ROOT/include -c -o src/llvm/ext/llvm_ext.o src/llvm/ext/llvm_ext.cc

$ LLVM_CONFIG="$ARM_LLVM_ROOT/bin/llvm-config" \
   LDFLAGS="-L$ARM_LLVM_ROOT/lib" \
   CPPFLAGS="-I$ARM_LLVM_ROOT/include" \
   $ARM_LLVM_ROOT/bin/clang crystal.o -o .build/crystal  -rdynamic -L$ARM_BREW_PREFIX/lib src/llvm/ext/llvm_ext.o `"$ARM_LLVM_ROOT/bin/llvm-config" --libs --system-libs --ldflags 2> /dev/null` -lstdc++ -lpcre libgc.a -lpthread libcrystal.a -L$(brew --prefix libevent)/lib -levent -liconv -ldl

$ file .build/crystal
.build/crystal: Mach-O 64-bit executable arm64
```

### Compiling and running the compiler specs 

```
$ CRYSTAL_PATH=$(pwd)/src \
   CRYSTAL_LIBRARY_PATH=$ARM_BREW_PREFIX/lib \
   CC="$ARM_LLVM_ROOT/bin/clang" \
   LLVM_CONFIG="$ARM_LLVM_ROOT/bin/llvm-config" \
   LDFLAGS="-L$ARM_LLVM_ROOT/lib" \
   CPPFLAGS="-I$ARM_LLVM_ROOT/include" \
   PKG_CONFIG_PATH="$(brew --prefix openssl@1.1)/lib/pkgconfig" \
   ./bin/crystal build -o spec/compiler_spec spec/compiler_spec.cr --link-flags "$PWD/libcrystal.a" -Di_know_what_im_doing

$ CRYSTAL_PATH=$(pwd)/src \
   CRYSTAL_LIBRARY_PATH=$ARM_BREW_PREFIX/lib \
   CC="$ARM_LLVM_ROOT/bin/clang" \
   LLVM_CONFIG="$ARM_LLVM_ROOT/bin/llvm-config" \
   LDFLAGS="-L$ARM_LLVM_ROOT/lib $(pwd)/libgc.a $(pwd)/libcrystal.a" \
   CPPFLAGS="-I$ARM_LLVM_ROOT/include" \
   PKG_CONFIG_PATH="$(brew --prefix openssl@1.1)/lib/pkgconfig" \
   spec/compiler_spec
```

### Compiling and running the std library specs

```
$ CRYSTAL_PATH=$(pwd)/src \
  CRYSTAL_LIBRARY_PATH=$ARM_BREW_PREFIX/lib \
  CC="$ARM_LLVM_ROOT/bin/clang" \
  LLVM_CONFIG="$ARM_LLVM_ROOT/bin/llvm-config" \
  LDFLAGS="-L$ARM_LLVM_ROOT/lib" \
  CPPFLAGS="-I$ARM_LLVM_ROOT/include" \
  PKG_CONFIG_PATH="$(brew --prefix openssl@1.1)/lib/pkgconfig" \
  ./bin/crystal build -o spec/std_spec spec/std_spec.cr --target aarch64-apple-darwin --link-flags "$PWD/libcrystal.a" -Di_know_what_im_doing

$ CRYSTAL_PATH=$(pwd)/src \
   CRYSTAL_LIBRARY_PATH=$ARM_BREW_PREFIX/lib \
   CC="$ARM_LLVM_ROOT/bin/clang" \
   LLVM_CONFIG="$ARM_LLVM_ROOT/bin/llvm-config" \
   LDFLAGS="-L$ARM_LLVM_ROOT/lib $(pwd)/libgc.a $(pwd)/libcrystal.a" \
   CFLAGS="--target aarch-apple-darwin" \
   CPPFLAGS="-I$ARM_LLVM_ROOT/include" \
   PKG_CONFIG_PATH="$(brew --prefix openssl@1.1)/lib/pkgconfig"
   spec/std_spec
```

Both sets of specs have been validated as passing, but please also try on your own hardware too  if you cross-compile to validate.

The cross-compilation experience leaves a bit to be desired, unfortunately. I'm working on a separate PR to make it a bit nicer to cross-compile this all on one machine to avoid having to do so many gymnastics to compile for multiple targets.

Many thanks to @RomainFranceschini for kicking off this work and doing all the discovery, and @alin23 for validating it on their hardware as well

### CODE REVIEW

**Comment by maxfierke** [comment]
FWIW `Linux CI / test_alpine (push)` seems to be failing on master as well. This PR shouldn't have any had any effect on that.

**Comment by bcardiff** [comment]
Is there something that should be changed regarding https://github.com/crystal-lang/crystal/issues/10066#issuecomment-771149776 ? 

If I read things right `src/fiber/context/aarch64.cr` is in good shape regarding apple platform divergences, and the rest I guess are handled by llvm. Am I right?

**Comment by maxfierke** [comment]
> Is there something that should be changed regarding [#10066 (comment)](https://github.com/crystal-lang/crystal/issues/10066#issuecomment-771149776) ?
> 
> If I read things right `src/fiber/context/aarch64.cr` is in good shape regarding apple platform divergences, and the rest I guess are handled by llvm. Am I right?

Yeah, I think fiber switching is in good shape (we don't touch `x18` and we always populate `x29`). I would expect that LLVM handles much of the rest, though I'm not sure if there's anything we might need to do for the argument passing subtleties. I'll try to take a closer look tonight. FWIW all the tests pass, including for ABI, so I would expect that what's there is _mostly_ correct, at least for Crystal's purposes.

**Comment by maxfierke** [comment]
Looked into the details a bit more, and I think we're okay on the ABI: https://github.com/crystal-lang/crystal/issues/10066#issuecomment-772960191

Made one alteration to the type of LibC::VaList on `aarch64-darwin`, according to the Apple documentation

**Review by jhass — APPROVED** [review]
Looks good to me, we don't have first tier support on the first try :) 

Anyone already found a CI solution? Maybe there's a Linux distribution compiling against the Apple ABI that we can use for now on our AArch64 box or something like that?

**Comment by Sija** [comment]
Lil' bit more on the topic via GHA issue https://github.com/actions/runner/issues/805

**Review by bcardiff — APPROVED** [review]
👍

**Pull request merged**
