### PR TITLE
Don't use integer unions in the compiler when analyzing enum values

### PR DESCRIPTION
**Pull request by asterite**
This is a workaround for #10359

It seems there's a bug that is triggered when unions of integer types are involved.

There are already many bugs in the compiler which will eventually be fixed. The problem with #10359 is that the code that triggers the bug is also present in the compiler. And because of that, compiling a compiler in release mode produces a compiler that can no longer compile any program that depends on "prelude".

We have two choices:

1. We fix the bug. That means the bug will no longer be present in the compiler, or in any program.
2. We avoid using the code that triggers the bug in the compiler. That means that programs that include this code pattern might not behave well, but the compiler can continue to be compiled.

I think we can do point 2 to unblock the compiler, and to unblock the 1.0 release. Then we can do point 1 with time, similar to other bugs where we take our time to fix them in order to understand the problem.

There's another reason to prefer going with a workaround: I believe the bug is triggered when unions of multiple integer types, and `nil`, are involved. This should be pretty rare in most programs, because one doesn't need to work with multiple integer types (unlike the compiler). In fact the compiler could always do math using `Int64` and only go to perform math in other types to check for overflow errors, but then go back to `Int64`, maybe even disallowing `UInt64` values that don't fit into an `Int64`. But given that the language allows such union types, it was implemented like that.

This PR implements point 2: it avoids using integer union types when computing the value of enum members.

The workaround can be later undone once we actually fix the bug.

This PR also adds LLVM 11.1.0 support, which is just an entry in `llvm-versions.txt`. I needed that because I have LLVM 11.1.0 on my machine and without this change I couldn't work on the compiler.

# Steps for testing that this workaround is effective

1. Run `make clean crystal release=1`. Make sure you are using LLVM 11 or bigger.
2. Using `bin/crystal` compile the following program:

```crystal
enum Test : UInt32
  One   =  1
  Two   =  2
  Three =  3
  Four  =  4
  Five  =  5
  Six   =  6
  Seven =  7
  Eight =  8
  Nine  =  9
  Ten   = 10

  {% for member in @type.constants %}
    {% puts member, @type.constant(member) %}
  {% end %}
end
```

The output should be:

```
One
1_u32
Two
2_u32
Three
3_u32
Four
4_u32
Five
5_u32
Six
6_u32
Seven
7_u32
Eight
8_u32
Nine
9_u32
Ten
10_u32
```

Before this PR the output was:

```
One
1_u32
Two
8_u32
Three
9_u32
Four
0_u32
Five
1_u32
Six
2_u32
Seven
3_u32
Eight
4_u32
Nine
5_u32
Ten
4294967306_u32
```

### CODE REVIEW

**Comment by asterite** [comment]
In fact, I believe the bug is already present in the 0.36.1 compiler, and it triggers when you use an UInt32 enum. So the only way forward is to first workaround the bug so the compiler doesn't have the code that triggers the bug. Otherwise even if we fix the compiler to generate correct code the bug will manifest in the next compiled compiler.

**Comment by bcardiff** [comment]
I haven't been able to reproduce this when using LLVM 10. Even after many iterations. Since that is the most recent llvm version used in .tar.gz releases there is not blocking in the release process. Of course having a workaround is better.

What made you think it was something regarding unions of integer types?

**Comment by j8r** [comment]
I was not able to reproduce with LLVM 10 either. It may have nothing to do, but are you on Linux @bcardiff ?

**Comment by bcardiff** [comment]
No. I use Darwin mainly. Yet I use as a base compiler the .tar.gz binary via nix-shell. That way I can keep using llvm@10 and other versions. This is also more similar to the build process distribution-scripts and homebrew formula uses.

**Comment by j8r** [comment]
@asterite could you probably see by yourself if you use compile the compiler on Linux.
However, I doubt that the bug being triggered from LLVM 10 onwards or LLVM 11 onwards won't change much at this point.

**Comment by asterite** [comment]
Can you try with LLVM 11? I think I said it wrong that the bug happens with LLVM 10.

Also, in my case this is with a compiler from homebrew. I can try with the tar.gz one, I'm sure it will break too with LLVM 11 but I'll tell you later in the week.

**Comment by j8r** [comment]
Yeah it does happen on LLVM 11, already tried.

**Comment by asterite** [comment]
@j8r on Linux?

**Comment by asterite** [comment]
I guess that if 1.0 will be compiled with LLVM 10 or less then this is not a problem. Of course I don't think we can control what LLVM version other people use to distribute Crystal for platforms we don't officialy support...

**Comment by j8r** [comment]
Yes I'm on Linux, always been 😄

**Comment by asterite** [comment]
@j8r I see. I thought with those repro steps you got a segfault instead of wrong behavior

**Comment by j8r** [comment]
So, I run the tests again on GNU/Linux. Your steps described in this PR was not enough to reproduce, LLVM 10 or 11, ran with `--release` or not. I needed to compile the compiler before running the code snippet.

Indeed, any code I run sigfaults, including your snippet with LLVM 11. You're right, not wrong behavior.

On LLVM 10.0, no issues at all.

Trying this branch now.

**Comment by j8r** [comment]
Good news @asterite - no more segfaults with you PR on Linux with LLVM 11 :heart:

**Comment by bcardiff** [comment]
This is no longer needed 🧹

**Pull request closed without merging**
