### PR TITLE
Capitalized error messages

### PR DESCRIPTION
**Pull request by Sija**
This PR changes error messages according to #3944.

### CODE REVIEW

**Comment by Sija** [comment]
Hmm, CI fails at `IO#peek` related tests, dunno why...

**Comment by asterite** [comment]
Note that capitalizing error message given by the compiler is not correct. Right now with this code:

```crystal
def foo
  A = 1
end
```

we get this error:

```
Syntax error in qux.cr:2: dynamic constant assignment

  A = 1
     ^
```

With your PR we get:

```
Syntax error in qux.cr:2: Dynamic constant assignment

  A = 1
     ^
```

which doesn't read that well (capitalizing after ":" doesn't look good). Compiler message are always non-capitalized because of this reason (check for example errors produced by `clang`, `go` or `rustc`)

I do agree about capitalizing messages of exceptions thrown in the standard library.

**Comment by Sija** [comment]
@asterite Reverted changes made to compiler as requested. CI is hanging due to macOS problems on Travis, while Linux is all green-good.

**Comment by Sija** [comment]
@asterite ping? it's ready to 🚢 !

**Comment by Sija** [comment]
@asterite anything more to do here?

**Pull request merged**
