### PR TITLE
Make it possible to use all types of Int* with JSON/YAML mappings

### PR DESCRIPTION
**Pull request by marceloboeira**
Add Int8 and In16 initializer definitions in order to make possible to
use instead of Int32 or Int64 whenever necessary

Solve: #2301

### CODE REVIEW

**Comment by asterite** [comment]
I think for this it's better if we do something like this (here it's worth using a macro):

```crystal
{% for type in %w(Int8 Int16 Int32 Int64 UInt8 UInt16 UInt32 UInt64) %}
  def {{type.id}}.new(pull : JSON::PullParser)
    {{type.id}}.new(pull.read_int)
  end
{% end %}
```

to easily cover all cases.

**Comment by marceloboeira** [comment]
@asterite alright!

**Comment by marceloboeira** [comment]
@asterite I've made some changes, what do you think?

**Comment by asterite** [comment]
@marceloboeira Looks good, thanks!

**Comment by asterite** [comment]
Oh, well. Next time remind me to remind you to squash into a single commit :blush:

**Comment by marceloboeira** [comment]
@asterite I'll remember :+1:

**Comment by bcardiff** [comment]
@marceloboeira / @asterite Maybe I'm wrong, but since `PullParser#read_int` returns Int64, isn't the UInt64 support buggy while trying to parse upper values of UInt64?

Can some specs around this be added?

**Comment by asterite** [comment]
@bcardiff You are right, it's probably buggy. However, that would need a rewrite of the JSON lexer, because UInt64 isn't supported at that level.

**Pull request merged**
