### PR TITLE
Fix broken #10109 merge

### PR DESCRIPTION
**Pull request by Sija**
https://github.com/crystal-lang/crystal/pull/10109#issuecomment-860449057

### CODE REVIEW

**Review by straight-shoota — APPROVED** [review]

**Review by caspiano — APPROVED** [review]

**Review by jhass — APPROVED** [review]

**Comment by Sija** [comment]
@straight-shoota I don't think it's a regression (unless you mean that it in re: to the `master` ;))

**Comment by straight-shoota** [comment]
Yes, it's a regression in master. Not sure If thats supposed to bei tagged, but I figure it doesnt hurt.

**Comment by Sija** [comment]
IMO that's confusing/conflating terms - regression usually is compared to the previous release, not the `master`...

**Comment by wontruefree** [comment]
There are some doc generator specs.  Should a spec for this be added since it was a regression?

**Comment by Sija** [comment]
@wontruefree It **aint** a regression though.

**Comment by straight-shoota** [comment]
It broke master. No additional specs necessary.

**Pull request merged**
