### PR TITLE
RISC-V64 Support (WIP)

### PR DESCRIPTION
**Pull request by CoelacanthusHex**
RISC-V64 Support

### CODE REVIEW

**Comment by straight-shoota** [comment]
This is awesome! I'm very happy about getting RISC-V support.

Have you tested this on actual hardware?

**Comment by BlobCodes** [comment]
It looks like the workflows were suddenly un-approved (maybe because of the force-push/long time without commits?).
Re-approving them would maybe help the developer identify problems on other platforms? 

@straight-shoota

**Comment by straight-shoota** [comment]
Yeah, workflows need to be approved for every new commit. That gives a bad UX for first-time contributors working on drafts. But that's pretty rare.

However, I don't think running the full CI gives much in this case. The majority of the changes affect only RISC-V64 architecture which is not tested in CI. I don't expect this to have much effect for other targets.

I nevertheless approved the workflows to run again.

**Comment by isguarded** [comment]
I get this right, that this commit would/will be for cross-compiling to a risc-v target?

**Comment by CoelacanthusHex** [comment]
> I get this right, that this commit would/will be for cross-compiling to a risc-v target?

Both cross compile and native compile.

**Comment by CoelacanthusHex** [comment]
I'm sorry that I need to leave for a while, I need to prepare for NCEE (Gaokao).

**Comment by straight-shoota** [comment]
Thanks for your contribution, and don't worry about delays! It's your time and you can allot to Crystal as much as you like. Or none if you can't spare any. That's totally fine 🙇 
We appreciate any help, no matter how long it takes.

**Comment by CoelacanthusHex** [comment]
I'm so sorry that I no longer have enough time to continue this porting. So I'm giving up on this for now, maybe someone else will finish it, and maybe someday I'll have time to devote myself to it again. Regardless, I hope Crystal gets better and better.

**Pull request closed without merging**
