### PR TITLE
Integer exponentiation should avoid using floats

### PR DESCRIPTION
**Pull request by endSly**
Using float exponentiation generates error when working with long integers besides it's performance penalization.
Some examples:
```
61 ** 9 => 11694146092834141 # Expected 11694146092834140
126 ** 9 => 8004512848309156864 # Expected 8004512848309157376
```
Using [Exponentiation by squaring](https://en.wikipedia.org/wiki/Exponentiation_by_squaring) it gives  correct result.

### CODE REVIEW

**Comment by endSly** [comment]
It would be great to implement also [Modular exponentiation](https://en.wikipedia.org/wiki/Modular_exponentiation)

**Comment by ysbaddaden** [comment]
I understand this is accurate as well as faster now?

**Comment by endSly** [comment]
In my benchmarks I've not seen great differences in term of performance. It will be very dependent on the processor...

**Comment by asterite** [comment]
@endSly Thank you!!

**Pull request merged**
