### PR TITLE
Fix SDL samples on linux

### PR DESCRIPTION
**Pull request by rbviz**
None of them were working for me on debian. Works as intended with these changes.

### CODE REVIEW

**Comment by marcosdsanchez** [comment]
With your changes I'm able to run the examples, but running `fire.cr` in release mode doesn't work for me:

```
➜  crystal git:(bf33cea) bin/crystal samples/sdl/fire.cr --release       
Using compiled compiler at .build/crystal
Invalid memory access (signal 11) at address 0x4
[4283462] ???
[4278302] __crystal_sigfault_handler +30
[4283736] sigfault_handler +40
[139807178141824] ???
[4218555] ???
[4277579] main +43
[139807165575825] __libc_start_main +241
[4203226] _start +42
[0] ???

➜  crystal git:(bf33cea) llvm-config --version
3.9.0

➜  crystal git:(bf33cea) uname -a
Linux marcos-macbook-arch 4.4.38-1-lts #1 SMP Sat Dec 10 20:21:58 CET 2016 x86_64 GNU/Linux

➜  crystal git:(bf33cea) sdl2-config --version
2.0.5
```

**Comment by rbviz** [comment]
Interesting. All it did for me is add performance.


Testing on fresh VM install.
```
 $ lsb_release -d
 Description:	Ubuntu 16.04.1 LTS
 $ uname -a
 Linux ubuntu 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```


```
 $ bin/crystal samples/sdl/fire.cr 
 2132 frames in 6051 ms
 Average FPS: 352.33845645347873
```

```
 $ bin/crystal samples/sdl/fire.cr  --release
 16600 frames in 10221 ms
 Average FPS: 1624.107230212308
```

```
 $ llvm-config --version
 3.8.0
```

```
 $ sdl2-config --version
 2.0.4
```

Did these samples work for you without my changes? I have no way to test on a mac right now.

**Comment by marcosdsanchez** [comment]
> Did these samples work for you without my changes? I have no way to test on a mac right now.

No, they were not working. They are working with your changes in my linux machine (my mac runs linux) with the exception of `fire.cr` in release mode.

**Comment by rbviz** [comment]
Seems like you are using your locally compiled crystal, which seems to have some kind of problem.

`rm -r .build` and then retry, should work as i see no issues with the code right now or was able to replicate the issue.

**Comment by rbviz** [comment]
This is a small change, what is taking so long? Broken samples are rather discouraging for people new to crystal.

**Comment by asterite** [comment]
I think it's better if we remove these samples and move them to, maybe, https://github.com/ysbaddaden/sdl.cr

**Comment by ysbaddaden** [comment]
It's taking some time because:

- it used to work the way it is (at least for some people);
- I don't have to call `SDL_main` on Linux (as per documentation), but I know nothing about other platforms; I don't have a Mac at hand for example;
- it's not critical to Crystal (compiler, core/std lib).

Last but not least: the samples are for SDL 1.2, not SDL 2 as far as I know, and both versions sre quite different.

**Comment by drhuffman12** [comment]
I think the Crystal-lang team have done a great job and more than deserve some time off to spend w/ family this holiday season! Merry [belated] Christmas and Happy New Year!

**Comment by rbviz** [comment]
Indeed, happy new year!

**Comment by rbviz** [comment]
Closing this. Samples on master still exist and fail, but i see no interest in this PR.

**Pull request closed without merging**
