### PR TITLE
Allow a path to declare a constant

### LINKED ISSUE #5742: Can't use `AModule::AConst = 1` to declare a constant
```cr
ModuleFoo::Bar = 1

{% puts ModuleFoo.class_name %} # => NumberLiteral

puts ModuleFoo::Bar  # undefined constant ModuleFoo::Bar
```
https://carc.in/#/r/3mjb

I would expect it to create a module named `ModuleFoo` with a constant `Bar` inside it.
Instead, `ModuleFoo::Bar = 1` creates a constant `ModuleFoo` with value `1`, discarding `Bar` completely.

Apart from the fact that the current behavior is a bug, as we already have a few other places where we can use a module name in front of something, I think it would be consistent to allow this for constants too.

### PR DESCRIPTION
**Pull request by bew**
Allow `Foo::Bar = 1` to declare a constant `Bar` inside a module `Foo`.

Previously it was broken: it declared a constant `Foo`, discarding `Bar` completely.

Fixes #5742

### CODE REVIEW

**Comment by RX14** [comment]
@ysbaddaden it should have the same semantics as declaring `class Foo::Bar` when `Foo` doesn't exist - which is to create `Foo` as a module. If we want to change that semantic is a different discussion but this should be consistent with what we already have.

**Comment by bew** [comment]
I'm using the same method as in the class name resolution, so it should work the same. But I'm can add a test for it if you want!

**Comment by RX14** [comment]
Yes please.

**Comment by RX14** [comment]
@ysbaddaden I've never gotten that error, maybe you're misremembering? I'm pretty sure it's always worked.

**Pull request merged**
