### PR TITLE
Include Indexable into String

### PR DESCRIPTION
**Pull request by j8r**
Follow up of https://github.com/crystal-lang/crystal/issues/7619

The end goal is to remove duplication with the `Indexable` module, benefit from methods from the module and no longer use the `Indexable.self.range_to_index_and_count` [class method](https://github.com/crystal-lang/crystal/blob/master/src/indexable.cr#L622).

I had a hard time to figure out why I got `Error opening file '/app/s/r/c/c/o/m/p/i/l/e/r/c/r/y/s/t/a/l/c/r' with mode 'r': No such file or directory (Errno)`. That's because `String` was assumed not to be an `Enumerable`

I'm still worry about slower performance, for example with `String#size` and `String#each`.

Feedbacks welcome.

### CODE REVIEW

**Comment by oprypin** [comment]
You're going against a deliberate design decision that a string is not inherently iterable. At least it's relatively clear what the `chars` of a string are, and they are indeed what's iterable. But what does it really mean to iterate over, say, a poem? Over bytes, codepoints, visible characters, maybe even lines?

**Comment by asterite** [comment]
I guess one thing we can do is to have views. I think Swift does that. Do you could have `string.byte_view`, `string.char_view`, `string.codepoint_view`, etc. These would just be wrapper structs over string that could be `Indexable` and `Enumerable`. So you could do:

```crystal
"hello".char_view.map { |c| c + 1 } # => ['i', 'f', 'm', 'm', 'p']
```

That's basically the same than `"hello".chars.map ...` except that an intermediate array for `chars` is not needed. Same with `bytes`, `codepoints`, etc.

**Comment by bew** [comment]
@asterite About view, I have this in my wishlist for a loong time: StringView, for example you could do `some_string.view` (or `to_view`) and get a `StringView` object with all the (at least) lookup methods of `String`, but without the overhead of creating a `String` object each times..

For example for `String#split` instead of creating and returning new strings, you could do `my_string.view.split(' ', 2)` and get very lightweight StringView referencing the original `String`..

(_I should do a separate issue for this one day_)

**Comment by j8r** [comment]
Why not having then a `String::Chars` struct, that is returned for `String#chars`? Same for codepoints, bytes etc. To have an array, one can do `"mystring".chars.to_a` then.

**Comment by oprypin** [comment]
But that's exactly what @asterite said?

**Comment by j8r** [comment]
On the idea yes, on my side I was proposing to replace the existing `String#chars : Array(Char)` by `String#chars : String::Chars`  (not creating a new `String#chars_view`).
I said this because:
- `String#each_char` will be replaced by `String::Chars#each`
- `String#chars` by `String::Chars#to_a`
- `String#each_char_with_index` by `String::Chars#each_with_index`

**Comment by j8r** [comment]
Thanks for the feedbacks everyone, I wasn't sure it was a good idea to include Indexable into String.
We'll move this discussion to a proper issue about having indexable structs for chars, bytes and maybe even lines in the `String` namespace – I like the idea too.

**Comment by j8r** [comment]
Thanks for the feedbacks everyone, I wasn't sure it was a good idea to include Indexable into String.
We'll move this discussion to a proper issue about having indexable structs for chars, bytes and maybe even lines in the `String` namespace – I like the idea too.

**Pull request closed without merging**
