### PR TITLE
Make links of hyperlinks (documentation)

### PR DESCRIPTION
**Pull request by mjago**
Make documentation links `clickable'

### CODE REVIEW

**Comment by mjago** [comment]
@MakeNowJust Huh? So presumably [these links](https://crystal-lang.org/api/0.20.5/Debug/DWARF/LineNumbers.html) <i>shouldn't</i> be hyperlinks ? I would assume some amount of consistency is preferable.

**Comment by MakeNowJust** [comment]
@mjago Ah, yes. I wanted you to write description for explanation. And we may want to improve Markdown processor for such a style link.

In fact, I prefer `<http://...>` style link to `[...](http://...)` in this case because `[...]` content says little. I think the URL and the context describe themselves fully.

**Comment by mjago** [comment]
@MakeNowJust Ok sorry - added a description. My only issue was when I tried to follow the link I had to copy-and-paste. I assumed it was an oversight so I made the `tiny change' to the markup to be consistent with other linked references. I have no opinion on the link descriptions.

**Comment by MakeNowJust** [comment]
@mjago But this pull request improve document quality. Good job!

**Comment by MakeNowJust** [comment]
@mjago I think you missed fixing [links in `src/debug/mach_o.cr`](https://github.com/crystal-lang/crystal/blob/fcf294919c8637a7c4ddd2218f604051d8669254/src/debug/mach_o.cr#L5-L6).

**Comment by mjago** [comment]
@MakeNowJust Thanks - now formatted also.

**Comment by ysbaddaden** [comment]
The markdown processor should be enhanced to support direct links instead. See <http://spec.commonmark.org/0.27/#autolink>

**Pull request closed without merging**
