### PR TITLE
Format: indent multiline call chaining with 4 spaces

### PR DESCRIPTION
**Pull request by MakeNowJust**
Closes #5195 

See https://github.com/crystal-lang/crystal/pull/5195#issuecomment-340790563

### CODE REVIEW

**Comment by yxhuvud** [comment]
I just wonder how easy it will be to make this kind of exception in the editors. Not all use the builtin formatter by default.

**Comment by RX14** [comment]
@yxhuvud they should.

**Comment by MakeNowJust** [comment]
ping

**Comment by ysbaddaden** [comment]
I quote and support @asterite : "I think the formatter should always use 2 spaces to indent."

This is what I always use: 2 spaces.

- chained calls on multiple lines already have the leading '.' to give the chained information;
- 4 spaces disrupt the usual 2 spaces indentation, despite having nothing peculiar to outline;
- it eats 2 more chars on the line (which I keep under 80).

This is unwelcomed, and one more reason to not use the formatter.

**Comment by MakeNowJust** [comment]
Hm, @ysbaddaden's opinion makes sense. Do you have a counter, @RX14, @straight-shoota or any one?

**Comment by RX14** [comment]
@ysbaddaden it's not a big deal, but I outlined by argument [here](https://github.com/crystal-lang/crystal/pull/5195#issuecomment-340248685). If everyone else agrees that an indent of 2 is fine, let's merge this PR with that.

**Comment by MakeNowJust** [comment]
@RX14 changed indent size as 2 spaces.

**Comment by MakeNowJust** [comment]
ping

**Pull request merged**
