### PR TITLE
[doc] Remove superclass from ASTNode in API docs

### LINKED ISSUE #9932: the api documentation for the Macro "module" wrongly claims that Macro classes inherit from Object
the [api documentation](https://crystal-lang.org/api/0.35.1/Crystal/Macros/TypeNode.html) for Macro classes state that the classes inherit instance methods from `Object`, which is incorrect. i assume it's because Macro classes aren't actually real classes, but the documentation just assumes everything inherits from Object and Reference

it's not a huge issue, but definitely confusing trying to call `TypeNode#to_s` and having the compiler tell you that TypeNode doesn't have a to_s method

### PR DESCRIPTION
**Pull request by beta-ziliani**
Fixes #9932 by avoiding the inclusion of any superclass of ASTNode in the generation of docs.

Check the discussion in PR #9965 (if this is approved, said PR should be rejected).

### CODE REVIEW

**Review by straight-shoota — APPROVED** [review]
Congrats on your first PR to this repo! 🚀 😃 

The change looks good.
As a suggestion, you could check the individual namespace components directly, instead of constructing the full name, just for comparison. Crude example:

```cr
type.name == "ASTNode" && type.superclass.name == "Macros" && type.superclass.superclass.name == "Crystal" && type.superclass.superclass.superclass.nil?
```

And a spec would be great. The doc generator is notoriously underspecced (if that's a term).

**Comment by beta-ziliani** [comment]
OK about the spec.

I'm failing to see the advantages of comparing each module separately, care to explain? I also carefully avoided hardcoded constants on purpose.

**Comment by straight-shoota** [comment]
It's a minor thing, avoiding a couple of string allocations. We don't need the string in the end. 

`Crystal::Macros::ASTNode.name` *is* a hardcoded constant. There is no way around that because this special behaviour needs to be hardcoded to a specific path.

**Comment by asterite** [comment]
I think this is fine. The doc generator is already pretty fast, and a few allocations here and there shouldn't matter (unlike in the compiler)

**Comment by beta-ziliani** [comment]
@straight-shoota would love a comment on the added spec. If it's good, we can then merge this. Thx

**Review by straight-shoota — APPROVED** [review]

**Comment by straight-shoota** [comment]
Thanks @beta-ziliani

**Pull request merged**
