### PR TITLE
Remove `bin/crystal` usage for init tool specs

### PR DESCRIPTION
**Pull request by bew**
It feels ugly to pass `stderr` all over the place, but hey.. it works!

I think that the routines getting the correct fields from the given args being in the class is not correct, we should probably build a intermediate object (kind of factory which takes arguments and 'parse' them) that will create & return the `InitProject` object then execute it or sth like that.. Absolutely not sure about this..

Maybe we should just merge this to remove `bin/crystal` direct usage, and make another PR to refactor the init tool? (I think I would prefer that)

WDYT?

### CODE REVIEW

**Comment by asterite** [comment]
To avoid passing `stderr` everywhere, make `Init` a class, store it in an instance variable, and change class methods to instance methods.

**Comment by bew** [comment]
@asterite the specs fails weirdly because there are early exits in the init tool, so when the spec check a specific error, it exits after printing a little msg on stderr. (no idea how I got the specs to pass once on my computer...)

I'm going in another way, using expections instead of `STDERR.puts msg; exit 1`, it should be better!

**Comment by RX14** [comment]
circleci seems to be flakey downloading things from homebrew, i've had to restart a number of builds.

**Comment by bew** [comment]
@asterite I kept `Error` exception class only, should be GTG I think!

**Pull request merged**
