### PR TITLE
Add NamedTupleLiteral#map and HashLiteral#map

### LINKED ISSUE #2606: Possible to support map in NamedTupleLiteral?
Hello,

Wanted to start saying 0.17 is a awesome and unleashed a lot of power in relation to DSL building thanks to NamedTuple, splat and double splat support, thank you for all that!!! :tada: :smile: 

I was trying to implement a macro that uses named arguments for `initialize` and found that `.map` is not supported (simplified code):

```crystal
macro results(**properties)
  {% for key, value in properties %}
    {% properties[key] = {type: value} unless value.is_a?(HashLiteral) || value.is_a?(NamedTupleLiteral) %}
  {% end %}

  struct Results
    {% for key, value in properties %}
      getter {{key.id}} : {{value[:type]}}{{ (value[:nilable] ? "?" : "").id }}
    {% end %}

    def initialize(*, {{
                        *properties.map { |key, value|
                          if value[:nilable]
                            "@#{key.id} = nil".id
                          else
                            "@#{key.id}".id
                          end
                        }
                      }})
    end
  end
end

class Signup
  results(
    name: String,
    age: {type: Int32, nilable: true}
  )
end
```

```
undefined macro method 'NamedTupleLiteral#map'
```

I tried looking at how `TupleLiteral#map` is implemented, but since it shares it's behavior with ArrayLiteral for `map`, got lost there :confused: 

Perhaps there is another way that I'm missing? (most likely that, hehe).

Thank you in advance and once again, great release!

:heart: :heart: :heart:

### PR DESCRIPTION
**Pull request by jhass**
closes #2606

### CODE REVIEW

**Comment by asterite** [comment]
Awesome, thanks!

Care to add a couple of specs in macro_methods_spec.cr?

**Comment by asterite** [comment]
You can also add docs if you want, at `src/compiler/crystal/macros.cr`

**Comment by jhass** [comment]
Eh right, got late yesterday :D

**Comment by jhass** [comment]
Alright, updated.

**Comment by luislavena** [comment]
Awesome @jhass, thank you!!! :heart: :heart: :heart:

**Comment by asterite** [comment]
I cherry picked this to the release/0.17 branch, so this will be included in 0.17.1 :-)

**Pull request merged**
