### PR TITLE
Use markd for markdown rendering in the compiler

### LINKED ISSUE #4613: Improve Markdown implementation - Or: Should we separate compiler tools?
The Markdown parser and renderer is still very basic and misses important features like for example raw html.

I suggest to implement the [CommonMark](http://commonmark.org/) specification which is very reasonable and the de-facto standard reference for Markdown implementations. There is an entire test suite [jgm/CommonMark](https://github.com/jgm/CommonMark) to validate implementations. Currently `Markdown.to_html` passes only 137 of 621 (22 %).

It would also be nice if the Markdown parser/renderer can be easily extended to add support for more specialized features like Github Flavoured Markdown (e.g #2217)

### LINKED ISSUE #7009: Numbered list not rendered correctly in docs when using code block
This is how the current **Installation** section looks in the generated docs:
grafik
**1** and **1** instead of **1** and **2**.
Even if this is actually in the README:

`````md
## Installation

1. Add the dependency to your `shard.yml`:
```yaml
dependencies:
  library:
    github: user/library
```
2. Run `shards install`
``````

### LINKED ISSUE #7463: Markdown escapes HTML
Which is obviously incorrect, since Markdown is [allowed](https://daringfireball.net/projects/markdown/syntax#html) to contain HTML tags.

For an example of such erroneous behavior see
https://hanneskaeufler.github.io/crytic/api/ generated by `crystal doc` out of https://raw.githubusercontent.com/hanneskaeufler/crytic/eb13b67362fc6646f9278120ebe5ba0c9526e772/README.md

Refs #4613

### LINKED ISSUE #10058: Docs generator doesn't parse Markdown correctly when reading URLS that have parens in them.
When making a method definition in Crystal like:
```crystal
# Create a mask object and add it to this `Celestine::Meta::Context`
def filter(&block : Celestine::Filter -> Celestine::Filter)
end
```

`crystal docs` will make a method stub URL that is linked like:
```
https://docs.celestine.dev/Celestine/Meta/Context.html#filter(&block:Celestine::Filter-%3ECelestine::Filter)-instance-method
```

However, linking these in your README file causes the docs generator to not parse the URL correctly.

An Example for Comparison:

Using the following text in the README:

```
 * [Celestine::Filter](https://docs.celestine.dev/Celestine/Filter.html) -> [filter](https://docs.celestine.dev/Celestine/Meta/Context.html#filter(&block:Celestine::Filter-%3ECelestine::Filter)-instance-method)
```
You would expect that the link would be parsed into
```
Celestine::Filter -> filter
```

but instead parses as:
```
Celestine::Filter -> filter-instance-method)
```

A video to better illustrate: https://youtu.be/xD9zna2gJIA

Some Links to see for yourself. Check the `Usage` sections.
https://github.com/celestinecr/celestine (correct)
vs
https://docs.celestine.dev/ (broken)

### PR DESCRIPTION
**Pull request by straight-shoota**
This is a revival of #8174, pulling in https://github.com/icyleaf/markd/ and using it for markdown rendering in the docs generator and playground.

The markdown implementation we're currently using was previously part of the standard library but got yanked because it's broken. We still used it in the compiler. This finally replaces it with a dedicated library that is proven to work well.
To avoid external dependencies for the compiler, the markd shard is vendored into the Crystal repository using [`git subtree`](https://manpages.debian.org/testing/git-man/git-subtree.1.en.html). The entire code is embedded in the repository, but it's easy to pull in upstream changes using `git subtree pull`.
The first two commits are just git subtree pulling in the code from markd.

Only the third commit is interesting for review, integrates markd with the compiler and adds specs to make sure the output is as expected and the mentioned bugs are indeed fixed.

The generated docs HTML is mostly identical with the previous implementation, except for some insignificant white space changes and more encoded special characters. And of course, a lot of broken behaviour is fixed.

Resolves #4613
Fixes #7009
Fixes #7463
Fixes #10058

**NOTE:** This must not be squash merged to keep the commit information for git subtree.

### CODE REVIEW

**Review by asterite — APPROVED** [review]
This is great! And it's so much better than my headlong attempt. Thank you! ❤️

**Comment by j8r** [comment]
Glad the final chosen approach iswith `git subtree` at the end, some were not very keen to go this way at first.

Hopefully the Readme and License will remind us to submit patches upstream.

**Review by sdogruyol — APPROVED** [review]
Awesome 💯  Thank you @straight-shoota 🙏

**Comment by straight-shoota** [comment]
The newly generated docs are already live at https://crystal-lang.org/api/master/
A clear indicator of a working markdown implementation is that `<https://github.com/crystal-lang/crystal/fork>` in the README is properly rendered as a hyperlink.

Please let us know about any issues with the new renderer, discovered on https://crystal-lang.org/api/master/ or while building shards.

**Comment by icyleaf** [comment]
Good news! I am happy to make this happened 😄

**Pull request merged**
