### PR TITLE
Merge 0.36.1 to master

### PR DESCRIPTION
**Pull request by bcardiff**
Merges the changelog from the 0.36.1 release to master.
It also update the CI to use 0.36.1.

### CODE REVIEW

**Review by asterite — APPROVED** [review]

**Review by straight-shoota — APPROVED** [review]

**Comment by oprypin** [comment]
I hope *this* PR doesn't get squash-merged like others :o

**Comment by j8r** [comment]
Yeah @oprypin , but be careful - the master branch has been merged into this PR.

**Comment by straight-shoota** [comment]
Hm, not sure if that's really best. The changes from these commits are already in master because they were cherry-picked to the release branch. So they're just duplicates with a different hash.

**Comment by oprypin** [comment]
Oh, weird, maybe then squash it :/

**Comment by bcardiff** [comment]
My opinion is that it should have a merge commit :-).

Although the only difference is the changelog and the ci, I did the merge from master to solve conflicts first and in order to have in git commits the information that all changes from 0.36.1 are (or should be on master).

I don't like when tagged commits are leaves.

**Comment by oprypin** [comment]
If we're talking about perfection in the process, all of these commits could have gone only to a 0.36 branch and then merged to master.

I prefer a merge commit anyway, yes.

**Pull request merged**
