### PR TITLE
Add return type restrictions to methods of container types

### PR DESCRIPTION
**Pull request by oprypin**

### CODE REVIEW

**Comment by straight-shoota** [comment]
Is there a particular reason why there's sometimes `self` and sometimes `Array(T)` etc.?

**Comment by oprypin** [comment]
@straight-shoota "returns actually self" vs "returns another array"

**Review by straight-shoota — APPROVED** [review]

**Comment by oprypin** [comment]
> @straight-shoota "returns actually self" vs "returns another array"

On that topic... In https://github.com/crystal-lang/crystal/pull/10243 you added type annotations that totally clash with this idea. So I replace them back.

**Comment by straight-shoota** [comment]
Ooops, habits....

**Pull request merged**
