### PR TITLE
HTTP::Client spec: don't write server response if expecting read timeout

### LINKED ISSUE #7401: "Unhandled exception in spawn: Error writing to socket: Broken pipe (Errno)" in socket client specs
If you put a `1000.times do` around all socket client specs this is easy to reproduce. I won't have time these days to find out why it happens, but if somebody has the time, please investigate it.

With that and my other researches we should be reaching a point where no specs will fail on CI.

### PR DESCRIPTION
**Pull request by asterite**
Fixes #7401

I found out that the problem was in the ["tests read_timeout"](https://github.com/crystal-lang/crystal/blob/4e0f731a7314cf03a37f76453799e9de54f7a550/spec/std/http/client/client_spec.cr#L192) spec. This fixes it but I'm not _entirely_ sure why the exception happens.

What I think happens is:
- the client is set a read timeout, and it will timeout
- the server is said to wait for more time than that of the read timeout and then write a response
- by the time the server gets to write the response, the client's socket might be already closed because the GC already finalized it

At least I couldn't reproduce it with `GC_DONT_GC=1` (but then it failed because of too many open file requests), so I'm not sure. But I think my logic above is correct.

In this PR, when we expect a read timeout to happen we don't even bother instructing the server to write a response because that doesn't matter anymore.

However, this leads me to think... if I write an HTTP server and I accept a request and the client closes the socket before I get to write the response... an exception will be raised and it will be printed in the server's `spawn` handling that request. Is that OK? How do other languages handle this?

### CODE REVIEW

**Comment by bew** [comment]
> if I write an HTTP server and I accept a request and the client closes the socket before I get to write the response... an exception will be raised and it will be printed in the server's spawn handling that request. Is that OK?

That's what I would expect at least..

**Comment by asterite** [comment]
Ugh, that failure in darwin... come on, CI, I'm trying my best here, don't give me **new** errors...

**Comment by asterite** [comment]
For history purposes, this is the darwin build that failed: https://circleci.com/gh/crystal-lang/crystal/18231?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

I'll re-run it now.

**Comment by straight-shoota** [comment]
I'm pretty sure the immediate issue should be fixed by #7197.

**Comment by asterite** [comment]
Another one to investigate, a `Nil assertion failed` in `signal_spec.cr`: https://circleci.com/gh/crystal-lang/crystal/18298?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by straight-shoota** [comment]
That's already tracked in #7243

**Comment by asterite** [comment]
We can probably merge this PR first, which is really small, and then focus on reviewing #7197, which is much larger and also is currently failing on my machine.

**Pull request merged**
