### PR TITLE
Remove :nodoc: from singular method aliases, add Int#microsecond alias

### PR DESCRIPTION
**Pull request by Sija**
Refs #6273

### CODE REVIEW

**Comment by j8r** [comment]
@Sija do you realize this aliases are only one character different?

**Comment by asterite** [comment]
@j8r It's about being able to write `sleep 1.minute` instead of `sleep 1.minutes`.

**Comment by Sija** [comment]
@j8r yes, I do, see @asterite's comment.

**Comment by asterite** [comment]
@j8r `ditto` is processed on the semantic level. That the methods are sorted alphabetically doesn't mean the ditto will be applied like that.

**Comment by j8r** [comment]
Sorry @asterite this wasn't as clear as `:nodoc:`, wich has colons. Adding them around `:ditto:` will make more obvious that its a special semantic.

**Comment by RX14** [comment]
Yeah I considered that, but it's such a minor change that it's really not worth breaking.

**Comment by j8r** [comment]
@RX14 `:ditto:` seems to be already supported [here](https://github.com/crystal-lang/crystal/blob/master/src/compiler/crystal/semantic/top_level_visitor.cr#L1023), and also `nodoc` (without colons) [here](https://github.com/crystal-lang/crystal/blob/master/src/compiler/crystal/tools/doc/generator.cr#L166).
If yes, `ditto` can already be changed to `:ditto:`.
I can send a PR about removing the non-colons version of `ditto` and `nodoc`.

**Comment by RX14** [comment]
`:ditto:` and `nodoc` are unused in my experience, `ditto` and `:nodoc:` are what people tend to use. I'm not sure thats worth changing.

**Comment by straight-shoota** [comment]
@RX14 @j8r please discuss this in a separate issue. Thanks 👍

**Comment by RX14** [comment]
Just needs review

**Comment by j8r** [comment]
We can use a single macros to add all this non `s` variants:
```crystal
{% for time in %w(nanosecond microsecond millisecond second minute hour day week month year)  %}
 # Returns a `Time::Span` of `self` {{time.id}}s.
  def {{time.id}} : Time::Span
    {{time.id}}s
  end
{% end %}
```

**Comment by Sija** [comment]
Can this go forward?

**Comment by Sija** [comment]
2nd review, @bcardiff @asterite, anyone?

**Pull request merged**
