### PR TITLE
Fix Enum#to_s for flag enums to join with pipe

### PR DESCRIPTION
**Pull request by MakeNowJust**
See #3961

### CODE REVIEW

**Comment by bcardiff** [comment]
This overrides #3961, right? I don't know why there were commas in the first and i didn't stop in questioning them to avoid the ambiguity the parens solved.

**Comment by bcardiff** [comment]
I've just read the 3961 thread. Unless something comes up i would also go with pipes :-)

**Comment by sdogruyol** [comment]
Pipe wins 💯

**Comment by MakeNowJust** [comment]
NOTE: Comma separation is corresponding to `Enum.flag` macro argument. It may be important.

**Comment by ysbaddaden** [comment]
Good note. I believe `Enum.flag` to a macro to quickly a flags Enum, I'm not sure it should dictate an Enum representation.

**Comment by asterite** [comment]
Pipes are good for `to_s`. I originally copied the comma from `to_s` from how C# shows these enums, but using pipes is better.

**Pull request merged**
