### PR TITLE
Fix StringLiteral#!=, SymbolLiteral#!= and MacroId#!=

### PR DESCRIPTION
**Pull request by jhass**

### CODE REVIEW

**Comment by asterite** [comment]
Merge? :-)

**Comment by jhass** [comment]
Yup :)

**Comment by javajax** [comment]
Have you thought about using the original case statement to determine the decision tree?
It seems unintuitive to me to have a case statement on the "method" and then an additional case statement in the inner block.

I thought it might be easier to read if it was broken out into 2 conditionals.
So changing it from this.

```
      case method
      when "==", "!="
        case arg = args.first?
        when MacroId
          if method == "=="
            return BoolLiteral.new(@value == arg.value)
          else
            return BoolLiteral.new(@value != arg.value)
          end
        else
          return super
        end
```
to something like this
```
      case method
      when "=="
        if MacroId
          return BoolLiteral.new(@value == args.first.value)
        else
          return super
        end
      when "!="
        if MacroId
          return BoolLiteral.new(@value != args.first.value)
        else
          return super
        end
```

**Comment by jhass** [comment]
Looks like about the same amount of boilerplate  to me ;)

**Comment by javajax** [comment]
the lines of code are the same it was just about moving the check for the string "==" and "!=" to the outer cases statement so there are no inner checks.

Lines of code the same.

But I guess it made it easier for me to think about.

**Pull request merged**
