### PR TITLE
Add Doc struct to libXML

### PR DESCRIPTION
**Pull request by vonKingsley**
This will add access to some document specific attributes such as version, encoding, standalone, ids/refs, and charset to libXML.

### CODE REVIEW

**Comment by asterite** [comment]
Looks good, thanks. But unless we use those properties in some way I don't see a reason to add just this change.

**Comment by vonKingsley** [comment]
No Problems,  Would it be beneficial to bundle this with some of the other functionality i was building out?  Such abilities as add_child, add_sibling, new_doc, new_node, etc..?

**Comment by asterite** [comment]
Sure, I guess added functionality should be similar to that of [Nokogiri](http://www.rubydoc.info/github/sparklemotion/nokogiri).

**Comment by vonKingsley** [comment]
OK thanks, I'm familiar enough with Nokogiri. Go ahead and close this out and I'll see what I can do.

**Comment by asterite** [comment]
If you want we can keep this open and you can continue to push to this branch with `--amend` or with different commits if you provide different features.

**Comment by vonKingsley** [comment]
Sounds Good.  It'll be a little while till I can revisit this, but I can add new feature commits if you don't mind keeping it open.

**Pull request closed without merging**
