### PR TITLE
Fix `Compress::Gzip` extra field

### PR DESCRIPTION
**Pull request by kojix2**
Hi.
If a Gzip file had a extra field, it could not be opened with `Compress::Gzip::Reader`.
This is because the length of an extra field, XLEN, is 2 bytes (uint16), but was treated as 1 byte. 
This pull request aims to fix this issue. 
Thank you.

Reference: BGZF file specifications: https://samtools.github.io/hts-specs/SAMv1.pdf
image

Reference:  GZIP file format specification version 4.3
 https://www.rfc-editor.org/rfc/rfc1952
 
```

   2.1. Overall conventions

      In the diagrams below, a box like this:

         +---+
         |   | <-- the vertical bars might be missing
         +---+

      represents one byte; a box like this:

         +==============+
         |              |
         +==============+

      represents a variable number of bytes.
```

```
      Each member has the following structure:

         +---+---+---+---+---+---+---+---+---+---+
         |ID1|ID2|CM |FLG|     MTIME     |XFL|OS | (more-->)
         +---+---+---+---+---+---+---+---+---+---+

      (if FLG.FEXTRA set)

         +---+---+=================================+
         | XLEN  |...XLEN bytes of "extra field"...| (more-->)
         +---+---+=================================+
```

### CODE REVIEW

**Comment by Sija** [comment]
Spec would be nice :)

**Comment by kojix2** [comment]
Hi @Sija

The current test is the following link. It already contains tests on Extra field.

https://github.com/crystal-lang/crystal/blob/989b7fb31451951696ea8c2aaf3e6f0cc01d56f0/spec/std/gzip/gzip_spec.cr

Here we use `Gzip::Writer` to create a gzip stream with an Extra field.

```crystal
  Gzip::Writer.open(io) do |gzip|
    header = gzip.header
    header.modification_time = SAMPLE_TIME
    header.os = SAMPLE_OS
    header.extra = SAMPLE_EXTRA
    header.name = SAMPLE_NAME
    header.comment = SAMPLE_COMMENT

    io.bytesize.should eq(0)
    gzip.flush
    io.bytesize.should_not eq(0)

    gzip.print SAMPLE_CONTENTS
  end
```

The created gzip stream is then read using Gzip::Reader.

```crystal
    Gzip::Reader.open(io) do |gzip|
      header = gzip.header.not_nil!
      header.modification_time.should eq(SAMPLE_TIME)
      header.os.should eq(SAMPLE_OS)
      header.extra.should eq(SAMPLE_EXTRA)
      header.name.should eq(SAMPLE_NAME)
      header.comment.should eq(SAMPLE_COMMENT)

      # Reading zero bytes is OK
      gzip.read(Bytes.empty).should eq(0)

      gzip.gets_to_end.should eq(SAMPLE_CONTENTS)
    end
```

The original code passed the test. Because it created an incorrect stream with XLEN size of one byte instead of two bytes and read it the wrong way.

This pull request failed the test the first time because I was only correcting the reading XLEN. So I also corrected the writing XLEN as well and now it passes the test.

Even then, so, should we really add another test? If so, what kind of test should we add?

One idea might be to have a hard-coded slice and check that it can be read by `Gzip::Reader`.

@oprypin  Thanks for linking the issue. I think this also fixes the issue (https://github.com/crystal-lang/crystal/issues/8933)

**Comment by straight-shoota** [comment]
There should be at least one test that ensures correctly reading an extra field, and one for correctly writing an extra field.
Each test should fail without this patch, and succeed with it.
If the existing test succeeds with and without this patch, it's insufficient. It just test that reading and writing are implementing the same format, but not that this is correct.

So it's probably a good idea to include a gzipped file with extra field as a test fixture and make sure we can read it and produce the same file when writing.

**Comment by kojix2** [comment]
@straight-shoota 
Understood. Now I would like to add a test code that fails before the change and passes after the change.

(1) Add a small file `test.gz` with extra fields to `spec/std/data` .

https://github.com/crystal-lang/crystal/blob/master/spec/std/data

(2) Write some test code like the following

https://github.com/crystal-lang/crystal/blob/89f2e43e3a0672a40dd291364f41f2c1771403e0/spec/std/compress/zip/zip_file_spec.cr#L108-L114

Is my understanding correct?

**Comment by kojix2** [comment]
I created a draft Gzip file for testing.

C code to generate the Gzip file
https://gist.github.com/kojix2/bd9523fdd3c1e7f8be4ce2c91fd17435

Generated gzip file
[test.gz](https://github.com/crystal-lang/crystal/files/15244761/test.gz)

image

image

**Comment by kojix2** [comment]
A minimal test was written by adding the simple gzip file presented above. 
The modification time is the time of the first commit of Crystal, with the comment "happy birthday".

**Comment by kojix2** [comment]
Confirmed that the test fails when I Revert the fix commit.
https://github.com/kojix2/crystal/actions/runs/9803064446/job/27068655521#step:5:200

```
  Failures:
  
    1) Compress::Gzip reads file with extra fields from file system
       Failure/Error: header.extra.should eq(Bytes[1, 2, 3, 4, 5])
  
         Expected: Bytes[1, 2, 3, 4, 5]
              got: Bytes[0, 1, 2, 3, 4]
  
       # spec/std/compress/gzip/gzip_spec.cr:67
  
  Finished in 1:30 minutes
  17716 examples, 1 failures, 0 errors, 21 pending
```

```
           +---+---+
Expected:  | 5   0 | [1, 2, 3, 4, 5]
           +---+---+

           +---+
Got:       | 5 | [0, 1, 2, 3, 4], 5
           +---+
```

**Review by ysbaddaden — APPROVED** [review]

**Review by straight-shoota — APPROVED** [review]
Thanks @kojix2

**Pull request merged**
