### PR TITLE
Changed 2 lines in time/time.cr to calculate local time correctily wh…

### PR DESCRIPTION
**Pull request by joeydonuts**
…en DST is in effect.

### CODE REVIEW

**Comment by jhass** [comment]
We renamed `TimeSpan` to `Time::Span` recently.

I've been thinking, do you have an idea how to write a nice test for this? That is without reimplementing the function inside the test and ideally without shelling out to any coreutils.

**Comment by jhass** [comment]
Mmh, actually this doesn't seem to work for me, `Time.now` gives me `0001-01-01 00:00:00 +0000` now.

**Comment by jhass** [comment]
Also worth noting that my `gettimeofday` manpage says
> Applications should use the clock_gettime() function instead of the obsolescent gettimeofday() function.

**Comment by asterite** [comment]
And that my mac osx says:

```
$ man clock_gettime
No manual entry for clock_gettime
```

:-(

But yes, we can use an ifdef there. If somebody wants to make that change, please go ahead.

**Comment by jhass** [comment]
So `gettimeofday` as well as `clock_gettime` will always return UTC time. `localtime` will give us a local time (I think DST adjusted but there's no explicit mention of that), but neither the definition of the `tm` struct nor the attributes in it that tell us the timezone or even if it's a DST time seem to be portable. There's `tzset` which sets a couple of globals from which we can get the current timezone offset (not DST corrected), the short timezone names (both the non-DST and the DST name) and whether the timezone has DST (but not if it's active or not). The way to get an offset seems to be to obtain a `localtime`, a `gmtime` and the difference between the two. I guess then comparing that difference to the offset we get from `tzset` allows us to determine whether DST is active or not.

**Comment by jhass** [comment]
Alright, it looks like one can force `mktime` to set `isdst` to whether the current local time is DST adjusted or not. We can also get around allocating the `tm` struct ourselves, so we can get away with only specifying the portable fields to get to `isdst`.

So we can do the  following to find out the effective offset, the timezone name and thus the local DST adjusted ticks

```cr
lib LibC
  struct Tm
    sec   : Int # Seconds (0-60)
    min   : Int # Minutes (0-59)
    hour  : Int # Hours (0-23)
    mday  : Int # Day of the month (1-31)
    mon   : Int # Month (0-11)
    year  : Int # Year - 1900
    wday  : Int # Day of the week (0-6, Sunday = 0)
    yday  : Int # Day in the year (0-365, 1 Jan = 0)
    isdst : Int # Daylight saving time
  end

  fun tzset()
  fun mktime(tm : Tm*) : TimeT
  fun gmtime(time : TimeT*) : Tm*
  fun localtime(time : TimeT*) : Tm*

  $tzname   : Char*[2]
end

# ...
    compute_ticks do |ticks, tp, tzp|
      LibC.tzset

      time = LibC::TimeT.new((ticks - UnixEpoch) / Span::TicksPerSecond)

      tm     = LibC.gmtime(pointerof(time))
      utc    = LibC.mktime(tm)

      tm       = LibC.localtime(pointerof(time))
      tm.value.isdst = -1 # Force mktime to use the system timezone database
      local    = LibC.mktime(tm)

      dst    = tm.value.isdst != 0
      offset = local - utc
      offset += 3600 if dst
      name   = String.new(LibC.tzname[dst ? 1 : 0])

      ticks + (offset * Span::TicksPerSecond)
    end
````

That still requires proper integration into `Time`, for example just using it for `local_ticks` will report the correct local time, but display the offset as `+0000` still.

**Comment by asterite** [comment]
Any approach we take, it would be nice to find a way to test this. `Time.now` isn't tested either. Maybe using an alternative time provider (`date`, for example) isn't a bad idea :-)

**Comment by asterite** [comment]
I think we could make this testable if we honor the TZ environment variable, like in Ruby. For now I'll close this PR as it doesn't work and probably needs a lot more code to make it work.

**Pull request closed without merging**
