### PR TITLE
Minor Range improvements

### PR DESCRIPTION
**Pull request by omninonsense**
- Adds `Range(B,E)#reverse_each : ReverseIterator(B,E)`
- ~~Update method signatures for documentation purposes to
include `&block` where a method `yield`s.~~

### CODE REVIEW

**Comment by MaloJaffre** [comment]
The second part or the PR is not needed because the block argument is auto-generated in the docs:
http://crystal-lang.org/api/Range.html#step%28n%3D%3Cspanclass%3D%22n%22%3E1%3C%2Fspan%3E%2C%26block%29-instance-method

**Comment by omninonsense** [comment]
@MaloJaffre That *is* why I added it in the first place; so the code is self-documenting, but I can remove it, if people don't like it.

**Comment by MaloJaffre** [comment]
IMO this part can be removed because the ```yield``` is easily spottable in these short methods, and the doc above mentions and shows examples of blocks.

**Comment by asterite** [comment]
We could add this, but in a different PR

**Comment by omninonsense** [comment]
Removed the stylistic changes! :smile:

**Comment by asterite** [comment]
Thank you!

**Pull request merged**
