### PR TITLE
Drop deprecated JSON.mapping

### PR DESCRIPTION
**Pull request by bcardiff**
Use [github:crystal-lang/json_mapping.cr](https://github.com/crystal-lang/json_mapping.cr) as a drop-in replacement.

### CODE REVIEW

**Comment by bcardiff** [comment]
The `JSON::MappingError` was shared between Mapping and Serializable.

Should I create a `JSON::SerializableError` or keep the old name?

**Comment by asterite** [comment]
I think `JSON::SerializableError` is fine.

**Comment by Sija** [comment]
I'd suggest scoping that to `JSON::Serializable::Error`.

**Comment by straight-shoota** [comment]
Changing the name of the exception would introduce a breaking change. `JSON::MappingError` wasn't deprecated in 0.35.0, so I suppose it should be in 1.0.

Looking at YAML, there's just `YAML::ParseException`. But I suppose having a dedicated serialization exception woudl be a good idea for each, JSON and YAML.

**Comment by asterite** [comment]
Nah, after a few months after 1.0.0 nobody will care about that small breaking change.

Plus the 1.0.0 release will break all shards so they will have to upgrade anyway.

**Comment by bcardiff** [comment]
Names are not that tidy. The following exists `[YAML|JSON]::ParseException` and `[YAML|JSON]::Error`.

I would prefer to avoid using `JSON::Serializable::Error` and keep `JSON::SerializableError`

**Pull request merged**
