### PR TITLE
CI: Migrate `::set-env` -> `$GITHUB_ENV`

### LINKED ISSUE #9785: Prepare Windows GitHub Action for upcoming deprecations
Ref: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

`::set-env` is used https://github.com/crystal-lang/crystal/blob/master/.github/workflows/win.yml#L149-L155

### PR DESCRIPTION
**Pull request by oprypin**
Fixes #9785

### CODE REVIEW

**Review by jhass — APPROVED** [review]

**Comment by bcardiff** [comment]
@oprypin would you know why windows builds on fork fails? https://github.com/bcardiff/crystal/runs/1333647009?check_suite_focus=true it seems the timeout in my fork due to llvm build, is that expected? 

This is not new to this PR, I think my fork just never succeeded on a windows build. Which is unfortunate because I discover missing bits when submitting PRs only.

**Comment by oprypin** [comment]
@bcardiff The only reasonable explanation I can see is that at some point the environment of GitHub Actions changed so that this build always breaks, but the cache never expired in the main repo so it still appears OK. I have noticed this problem but have not figured out a solution (although I haven't dug deep at all).
It is definitely suspicious that the build seems to break around a 1 hour mark without any relevant output.

**Comment by oprypin** [comment]
Ah don't mind the last remark. It's not a timeout and there *is* relevant output after all.

https://github.com/bcardiff/crystal/runs/1333355667?check_suite_focus=true#step:20:1623
```
D:\a\crystal\crystal\llvm-src\include\llvm/ADT/SmallVector.h(315,32): error C2976: 'llvm::SmallVectorTemplateBase': too few template arguments (compiling source file D:\a\crystal\crystal\llvm-src\lib\ExecutionEngine\RuntimeDyld\RTDyldMemoryManager.cpp) [D:\a\crystal\crystal\llvm-src\lib\ExecutionEngine\RuntimeDyld\LLVMRuntimeDyld.vcxproj]
D:\a\crystal\crystal\llvm-src\include\llvm/ADT/SmallVector.h(179): message : see declaration of 'llvm::SmallVectorTemplateBase' (compiling source file D:\a\crystal\crystal\llvm-src\lib\ExecutionEngine\RuntimeDyld\RTDyldMemoryManager.cpp) [D:\a\crystal\crystal\llvm-src\lib\ExecutionEngine\RuntimeDyld\LLVMRuntimeDyld.vcxproj]
```

Must have been a compiler update.

**Comment by oprypin** [comment]
Tried to bump LLVM minor version, that didn't help
https://github.com/oprypin/crystal/actions/runs/339148829

**Pull request merged**
