### PR TITLE
Remove leftover debug messages in raise.cr

### PR DESCRIPTION
**Pull request by hugoabonizio**
SSIA

### CODE REVIEW

**Comment by wontruefree** [comment]
what about wrapping them in a debug conditional?

**Comment by ysbaddaden** [comment]
I struggled with exceptions on ARM and damn, they helped a lot. Keep 'em in, commented, because they're useless to 99.99% of users they'd just clutter the compiler with macros for each and every compilation.

**Comment by RX14** [comment]
I think this is fine as-is

**Comment by hugoabonizio** [comment]
@ysbaddaden makes sense, just one question: why they are more useful on `raise.cr` than on other files?

**Comment by RX14** [comment]
Because when raise breaks it's harder to debug.

**Comment by hugoabonizio** [comment]
Thanks for clarifying!

**Pull request closed without merging**
