### PR TITLE
Remove the adler32/ and crc32/ directories

### PR DESCRIPTION
**Pull request by r00ster91**
This removes the directories `adler32` and `crc32` and puts the files directly in `src/`. It's unnecessary to have them in directories, it's just one file.

### CODE REVIEW

**Comment by j8r** [comment]
For those wondering what are `adler32` and `crc32`:
- [Adler32](https://en.wikipedia.org/wiki/Adler-32)
- [CRC-32](https://en.wikipedia.org/wiki/Cyclic_redundancy_check)

**Comment by asterite** [comment]
I actually want all libs to be inside directories.

**Comment by asterite** [comment]
And probably move these under a namespace.

**Comment by j8r** [comment]
@asterite you moving mean under `Crypto`? There are already `Crypto::Blowfish`, and `Crypto::Subtle`. We can have `Crypto::Adler32` and `Crypto::CRC32`

**Comment by j8r** [comment]
@asterite you mean moving under `Crypto`? There are already `Crypto::Blowfish`, and `Crypto::Subtle`. We can have `Crypto::Adler32` and `Crypto::CRC32`

**Comment by asterite** [comment]
I think so. But please let's not design using PRs. We can open issues to discuss these things.

**Comment by straight-shoota** [comment]
Closing. We don't want to go in this direction.

Let's please discuss these refactorings first, thanks :+1:

**Pull request closed without merging**
