### PR TITLE
Make the Windows compiler artifact more portable

### PR DESCRIPTION
**Pull request by HertzDevil**
This PR sets the `CRYSTAL_CONFIG_PATH` and `CRYSTAL_CONFIG_LIBRARY_PATH` variables when building the Crystal compiler on Windows<strike>, and arranges the directory structure so that it mirrors that of the other portable packages we release</strike>.

The resulting compiler no longer needs the `LIB` and `CRYSTAL_PATH` environment variables configured prior to running, nor fetch the standard library from elsewhere. All it needs now is:

* Add the root directory to `PATH`;
* Enable the MSVC developer command prompt; (not anymore after #11495 or #11496)
* Set `CRYSTAL_OPENSSL_VERSION=3.0.0` to enable OpenSSL support.

Note that the CI still overrides `CRYSTAL_PATH` and `CRYSTAL_LIBRARY_PATH` because they are needed for the development compiler to run properly. The `bin/crystal` wrapper script for non-Windows systems also does that when running `.build/crystal`.

### CODE REVIEW

**Comment by straight-shoota** [comment]
I was planning to look into doing exactly that today. You just beat me to it 👍 

I'm wondering if we should flatten the `crystal` sub directories in `share` and `lib`. On POSIX systems the tree is intended to be merged with global path in `/usr/` or similar. I don't think we expect that on windows. So these sub directories are technically unnecessary. Only reason to keep them would be to keep the structure similar to the POSIX packages.

**Comment by oprypin** [comment]
I would also prefer plain src/ and lib/ subdirectories. Never seen "share" in Windows-targeted packages

**Comment by HertzDevil** [comment]
The structure is now:

```crystal
crystal
- crystal.exe
- lib
  - (.lib files)
- src
  - (standard library)
```

For a release package `shards.exe`, the readme, and the license would also belong to the root.

`lib` technically conflicts with `lib/markd`, but this is a common problem for all platforms and the development compiler is assumed to be distinct from the "existing" compiler, so `lib` is probably fine.

**Review by straight-shoota — APPROVED** [review]

**Review by oprypin — APPROVED** [review]
@straight-shoota Could you ping me ~2 hours before merging this, so I'm ready to follow up on possible issues with install-crystal GitHub Action

**Comment by straight-shoota** [comment]
You should probably have time until the next nightly release, right?

**Comment by oprypin** [comment]
@straight-shoota There are no nightly releases for this, just as soon as the GHA run completes

**Comment by oprypin** [comment]
I have tried out this PR with install-crystal.

It is backwards-compatible, won't break anything there. I don't need notice now :)
https://github.com/crystal-lang/install-crystal/commit/254601fe575f24fb323b47fa1d59eeb44bd9e37e


And after landing this, I will be able to greatly simplify the code indeed
https://github.com/crystal-lang/install-crystal/commit/5f7f9ea0a30d8a5d00273e3baff5fd6869734a60?w=1#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346

**Comment by oprypin** [comment]
This PR and the [addition of `$ORIGIN`](https://github.com/crystal-lang/crystal/pull/11030) are pure awesomeness! :green_heart: 
Already enjoying it.

**Pull request merged**
