### PR TITLE
update manual installation ubuntu and debian [ci skip]

### PR DESCRIPTION
**Pull request by theodelaune**
Add sudo to commands, add apt-get update to re-synchronize the package index files with crystal package.  Also update sources.list addition command with sudo because actually it fails with permission denied.

### CODE REVIEW

**Comment by ysbaddaden** [comment]
Maybe we could just state "execute the following commands as **root**"?

**Comment by theodelaune** [comment]
Ok, should I keep the *apt-get update* in the command list ?

**Comment by jhass** [comment]
Yes, the `apt-get update` is a good addition.

**Comment by theodelaune** [comment]
Updated with your suggestions, thanks !

**Comment by jhass** [comment]
Thank you!

**Pull request merged**
