### PR TITLE
Adds docs for `Complex.zero`

### PR DESCRIPTION
**Pull request by wontruefree**

### CODE REVIEW

**Review by straight-shoota — APPROVED** [review]

**Comment by Sija** [comment]
Is this really worth an example? I do applaud the initiative of enhancing the stdlib docs, yet in the same time I'd imagine it should take a _quality over quantity_ approach.

**Comment by straight-shoota** [comment]
That's a valid point. I'm tempted to agree on that. The example really doesn't add much. On the other hand, it also doesn't hurt. So 🤷  IDK

**Comment by wontruefree** [comment]
I think examples are a great addition.  It is helpful to see how to interact with something as well as a description as what it does.  I would like to see an example of almost everyhing.  It really helps when searching for something and getting a working state and integrate it with code around it.

**Comment by Sija** [comment]
Yes, I agree on the usefulness of the examples **that are actually showing sth**. Addind examples for the examples sake is just bloating the docs for no reason other than your personal preference to state the obvious. Documentation's role is to explain, not the be redundant piece of bloat.

**Comment by wontruefree** [comment]
@Sija I agree with limiting bloat.  I think docs like this can be useful but am open to closing this doc PR if it is considered bloat.

**Comment by HertzDevil** [comment]
The example is misguided because it appears to demonstrate the properties of `#zero?` rather than `.zero`. The simplest documentation is just:

> Returns `(0.0 + 0.0i)`.

No example is needed. But this actually carries more information than just checking `#zero?`, because signed zeroes exist:

```crystal
Complex.zero.phase            # => 0.0
Complex.new(0.0, 0.0).phase   # => 0.0
Complex.new(0.0, -0.0).phase  # => -0.0
Complex.new(-0.0, 0.0).phase  # => 3.141592653589793
Complex.new(-0.0, -0.0).phase # => -3.141592653589793
```

**Pull request closed without merging**
