### PR TITLE
Update doc for `IO#read_bytes`.

### PR DESCRIPTION
**Pull request by mirek**

### CODE REVIEW

**Comment by jhass** [comment]
It looks like there's a conflict, could you please rebase?

**Comment by mirek** [comment]
Ok, after a bit of juggling I think it's ok.

**Comment by jhass** [comment]
Cool, what about keeping `write_bytes` in line actually?

**Comment by jhass** [comment]
Merged as e105bc50c73152d7b2caa362f59060c4f547bad2

Thanks!

**Pull request closed without merging**
