### PR TITLE
Allow underscore in block return type even if the type can't be computed

### LINKED ISSUE #10932: Underscore return type in non-captured block doesn't work when the type can't be inferred
See https://forum.crystal-lang.org/t/difference-between-underscore-and-empty-as-block-return-value/2998

This code should compile but it doesn't:

```crystal
def foo(& : -> _)
  yield
end

def recursive
  if false
    foo { recursive } # Error: can't infer block return type, try to cast the block body with `as`.
  end
end

recursive
```

The problem is that if there's a block return type, even if it's an underscore, the block type is computed and then matched against the return type. However, when the return type is an underscore there's nothing to match against.

### PR DESCRIPTION
**Pull request by asterite**
Fixes #10932

Alternative to #10929

### CODE REVIEW

**Comment by straight-shoota** [comment]
I'm a bit hesitant about merging such a compiler change last minute. But I suppose we might just postpone the release for another day or so to see if it creates any smoke 🤷 

I can confirm this fixes the issue discovered in crinja (https://github.com/crystal-lang/crystal/pull/10905#issuecomment-878905574), so this fix is also an alternative to #10928.

**Review by straight-shoota — APPROVED** [review]

**Comment by asterite** [comment]
This fix makes the compiler not check a type where it previously did. Types are eventually checked when needed, anyway. So I'm 100% confident that this won't break anything.

**Comment by beta-ziliani** [comment]
Either case we might break things (adding annotations, removing or changing them), so I say let's go with this better approach.

**Comment by straight-shoota** [comment]
test-ecosystem is green: https://github.com/crystal-lang/test-ecosystem/actions/runs/1026623854  👌

**Pull request merged**
