### PR TITLE
Add WeakRef to docs_main

### PR DESCRIPTION
**Pull request by RX14**
`WeakRef` wasn't showing up in the documentation, but it's not `:nodoc:` so I assume this is not intended.

### CODE REVIEW

**Comment by luislavena** [comment]
@RX14 there isn't much documentation defined in `WeakRef` currently to make it worth of addition.

Perhaps adding an example on usage to the docs will make it better?

Thank you.

**Comment by RX14** [comment]
I've added some docs to `WeakRef`, although I wasn't sure exactly how to document `WeakRef.allocate`. It seems to be for structs, using `malloc_atomic` to ensure that any pointers in the struct are "weak references", but as it doesn't change the type of the members that would be pretty unsafe. Should it be `:nodoc:`?

**Comment by bcardiff** [comment]
@RX14 yes, `:nodoc:` seems fine for `.allocate`

**Comment by bcardiff** [comment]
@RX14 I include manually these changes updating them w.r.t #4293.

**Comment by RX14** [comment]
Thanks!

**Pull request closed without merging**
