### PR TITLE
Add docs for `Enum#value`

### PR DESCRIPTION
**Pull request by lbguilherme**
I noticed this method wasn't really documented, although it is used in a doc example.

### CODE REVIEW

**Review by beta-ziliani — APPROVED** [review]
Thanks!

**Comment by asterite** [comment]
I _think_ this could be put in `struct Enum` in primitives.cr. It's an actual method, not a pseudo-method.

**Comment by beta-ziliani** [comment]
@asterite help me here, if it isn't listed in `enum.cr` nor `primitive.cr`, and it's not a pseudo method, what is it? 👻

**Comment by lbguilherme** [comment]
> I _think_ this could be put in `struct Enum` in primitives.cr. It's an actual method, not a pseudo-method.

I couldn't find a `def value` anywhere for Enum. primitives.cr doesn't define it. So I assumed it was a pseudo-method.

**Comment by beta-ziliani** [comment]
Nice! But then, since it's a primitive, it might make sense to move it to `primitive.cr` like Ary said.

**Comment by asterite** [comment]
Actually it's impossible to do because value's type depends on the enum type. Enum should somehow be generic, but currently it's not.

**Comment by asterite** [comment]
With that in mind, maybe doing nothing for now I'd better

**Comment by beta-ziliani** [comment]
We need
```crystal
struct Enum(T) where T < Int
```
Ref #934, which even has a proposed implemented according to https://github.com/crystal-lang/crystal/issues/934#issuecomment-504766096

**Comment by straight-shoota** [comment]
Yes, it's a regular method and can be overriden by implementing types. It's definitely not *pseudo*.

The docs are fine. I think we could just move them to `enum.cr` and simply define `#value` delegating to `previous_def`.

**Pull request merged**
