### PR TITLE
add more GC.stats

### PR DESCRIPTION
**Pull request by kostya**

### CODE REVIEW

**Comment by asterite** [comment]
Thanks! I wanted to this a couple of times but always forgot to do it... :-)

**Comment by RX14** [comment]
This seems to have broken my build on arch linux:
```
G-C-.o: In function `*GC::stats:GC::Stats':
GC:(.text+0x419): undefined reference to `GC_bytes_found'
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc -o "/data/programming/crystal/.build/std_spec" "${@}"  -rdynamic  -lyaml `/usr/bin/llvm-config --libs --system-libs --ldflags 2> /dev/null` -lstdc++ `command -v pkg-config > /dev/null && pkg-config --libs libssl || printf %s '-lssl -lcrypto'` `command -v pkg-config > /dev/null && pkg-config --libs libcrypto || printf %s '-lcrypto'` -lz -lreadline -lgmp -lxml2 -lpcre -lm -lgc -lpthread /data/programming/crystal/src/ext/libcrystal.a -levent -lrt -ldl -L/usr/lib -L/usr/local/lib`
```

It seems from the source as if `GC_bytes_found` is a private variable inside bdwgc, so i'm not sure if we should reply on it being present.

**Comment by RX14** [comment]
Seems as if the core issue is that the arch package is built with `--disable-static`, which hides private symbols, of which GC_bytes_found is one. So I don't think it's appropriate to use.

**Comment by kostya** [comment]
`bytes_found` was before this commit, and also this is strange value not showing anything, i think need to delete it.

**Comment by RX14** [comment]
@kostya but it didn't have a spec before this commit, so `.stats` was never called, and so the symbol didn't make it into the binary for the linker to error at.

**Comment by RX14** [comment]
This is #837 again, but with a different symbol from LibGC.

**Comment by asterite** [comment]
Don't worry, we'll eventually provide our own LibGC fork because we already made some changes to it to support multiple threads, so these functions will be available everywhere.

**Comment by RX14** [comment]
@asterite how am I meant to contribute to crystal in the meantime? Revert the commit every time I need to run specs, and unrevert every time I need to push? The point is that you're using LibGC's internal API, and that's not portable.

**Comment by asterite** [comment]
I see. We can probably remove stats then and someone can provide it as a temporary shard.

**Comment by asterite** [comment]
@RX14 Let me know if it compiles now. I think `GC_get_heap_usage_safe` is exposed, and that's the only thing used now.

**Pull request merged**
