### PR TITLE
added factorial function to int and float 

### PR DESCRIPTION
**Pull request by dylandy**
This method can behave better than Range#product method which can get value up to 170, the same  behaviour as R lang does.

Also I added float number factorial calculation using gamma function.

### CODE REVIEW

**Comment by david50407** [comment]
Actually, you can melt these commits together before you create pull request.
and why re-format some files which are irrelevant to this change?

**Comment by dylandy** [comment]
@david50407 @Sija  I just rebased those commits and recovered the other files that I accidentally formatted.

**Comment by dylandy** [comment]
fixed the format issue in int.cr.

**Comment by asterite** [comment]
Thank you!

But... I never used factorial in my life, and never saw it used except for code samples and blog posts. What's a real use case for factorial other than that? Also, factorial gets big pretty quickly, which means that using limited integers like `Int32` isn't very good.

**Comment by BlaXpirit** [comment]
If someone needs factorial, they can decide for themselves what number type they want to work with and (very easily) implement factorial accordingly. `Int` is not always a good fit because it overflows quickly, and `Float` just doesn't feel right.

I think that this should not be a method on the number data types. Might be OK for the `Math` module, but still...

There's probably a good reason that Ruby doesn't have factorial.

**Comment by ysbaddaden** [comment]
I follow up on what @asterite said. I'm not sure this is any common to be included in the standard library. It may prove to be more useful in an `algebra` shard, along with many more mathematical algorithms.

**Comment by dylandy** [comment]
Thanks for reply, I'm working on some machine learning projects which needs a lots of performance and I was really upset about how slow Python and R did so I decided to move on to Crystal. But some of the basic and most use functions have missed here, so I just give it a try though.

**Comment by mverzilli** [comment]
Closing. There's consensus this doesn't need to be in the stdlib.

**Pull request closed without merging**
