### PR TITLE
Replace PNG icon with optimized SVG for playground

### PR DESCRIPTION
**Pull request by straight-shoota**
Closes #6768

### CODE REVIEW

**Review by bcardiff — DISMISSED** [review]
🐛 The `` ends with size 0x0 (tested in Chrome and Firefox)

**Comment by wontruefree** [comment]
Does this change the Browsers that can run this?
I would imagine we are targeting Firefox, Chrome, Safari and Opera right?

**Comment by straight-shoota** [comment]
SVG support has been in all relevant browsers for 10 years or so.

**Comment by wontruefree** [comment]
I thought so but I was not sure and thought I would ask.

**Review by oprypin — APPROVED** [review]

**Pull request merged**
