### PR TITLE
Fix FFI bindings for libffi >= 3.4

### LINKED ISSUE #11802: Segfault from FFI closure function in interpreter
There is a bug causing a segmentation fault when using FFI closured function pointers in the interpreter.

A triggering example is `XML.parse("<foo>")`. The setup for `libxml2` configures some function pointers for memory management via [`LibXML.xmlGcMemSetup`](https://github.com/crystal-lang/crystal/blob/37497c9ef2bbfd552e53f1a8463f70a421c4b50d/src/xml/libxml2.cr#L317-L328).
These function pointers are then used from within libxml2 when it needs to allocate memory, for example. This happens when parsing an XML document. Apparently, the closured function that's supposed to be called from the closure wrapper is broken: The `user_data` pointer (which holds a reference to the interpreter and context instances) points to a very low address like `0x43` (c.f. [`Context.ffi_closure_fun`](https://github.com/crystal-lang/crystal/blob/37497c9ef2bbfd552e53f1a8463f70a421c4b50d/src/compiler/crystal/interpreter/context.cr#L266)).

I have been able to reproduce what looks like the same bug without libxml:
```c
// libclosure.c
// build: gcc -shared -fPIC .test/lib_closure.c -o libclosure.so
int (*foo_ptr)(int);

void set_foo(int (*f)(int)) {
  foo_ptr = f;
}
```

```cr
#! bin/crystal i
@[Link("./libclosure.so")]
lib LibClosure
  fun set_foo(fun_ptr : LibC::Int -> LibC::Int) : Void

  $foo_ptr : LibC::Int -> LibC::Int
end

LibClosure.set_foo -> (i : LibC::Int) { i * 100 }
LibClosure.foo_ptr.pointer # => Pointer(Void)@0x7f1ad3d98f40
LibClosure.foo_ptr.call(4) # Error: Invalid memory access (signal 11) at address 0x0
```

It seems to be working fine when the function pointer in a global variable is called from another C function like this:
```c
int call_foo_ptr() {
  (*foo_ptr)(42);
}
```

When the value of the global variable is assigned from Crystal, it can be called from Crystal. But now it errors when called from C:
```cr
LibClosure.foo_ptr = -> (i : LibC::Int) { i * 100 }
LibClosure.foo_ptr.call(4) # => 400
LibClosure.foo_ptr.pointer # => Pointer(Void)@0x7fd71f787180
LibClosure.call_foo_ptr # Error: Invalid memory access (signal 11) at address 0x7fd71f787180
```
Note that here the address of the function pointer triggers the invalid access.

### PR DESCRIPTION
**Pull request by straight-shoota**
Resolves #11802

https://github.com/libffi/libffi/pull/540 changed the memory layout of `ffi_closure` (`LibFFI::Closure`) between libffi 3.3 and 3.4 (which equates to libffi7 and libffi8 packages).
When linking against libffi 3.4 the constant `FFI_TRAMPOLINE_SIZE` is 32 instead of 24 (16 instead of 12 on 32-bit).

### CODE REVIEW

**Comment by Sija** [comment]
`SemanticVersion` doesn't handle version strings without the _patch_ part :(

```
Error: Not a semantic version: "3.3"
```

**Comment by cyangle** [comment]
Confirmed, this patch fixed the segfault issue on Ubuntu 22.04 for me.
It would be nice to have this in the 1.5 release.

**Comment by asterite** [comment]
> SemanticVersion doesn't handle version strings without the patch part :(

It's true, I get "3.4-rc1" on my end, and it fails to compile. I think we'll need to do some preprocessing before passing that to `compare_versions`.

**Comment by asterite** [comment]
> SemanticVersion doesn't handle version strings without the patch part :(

It's true, I get "3.4-rc1" on my end, and it fails to compile. I think we'll need to do some preprocessing before passing that to `compare_versions`.

**Comment by Sija** [comment]
@asterite I'd rather refactor `SemanticVersion` to handle such cases, since they're not uncommon.

**Comment by asterite** [comment]
But then it's not a semantic version 🤔

**Comment by straight-shoota** [comment]
Oh, that's a good note. So `LibFFI::Closure` is actually just used within this method and even there it's really just a handle.
https://github.com/crystal-lang/crystal/blob/8eb1413aa8d750d41b3ccfb9ee48cd2a757be169/src/compiler/crystal/ffi/closure.cr#L5-L15

I don't think there should be any harm from over-allocating a couple of bytes. Since we really only need the memory size and not the internal layout, we could just use the biggest size (from 3.4) always.

**Comment by asterite** [comment]
Right. In that case I would also make Closure an opaque type.

**Comment by HertzDevil** [comment]
We still need to hard-code the value of `sizeof(LibFFI::Closure)` somewhere. The [official documentation](https://github.com/libffi/libffi/blob/ddc6764386b29449d941b2b18d000f2987a9d848/doc/libffi.texi#L815) suggests the `size` argument to `ffi_closure_alloc` only needs to be "sufficient to hold a `ffi_closure` object", so over-allocation is probably fine.

**Review by asterite — APPROVED** [review]
Looks good!

**Comment by zw963** [comment]
Fixed on my arch linux

```
 ╰─ $ cr i
icr:1:0> Time.local
=> 2022-07-06 02:54:45.607922055 +08:00 Asia/Shanghai
icr:2:0> 
 ╰─ $ cr version
Crystal 1.5.0-dev [e9d223a67] (2022-07-05)

LLVM: 14.0.6
Default target: x86_64-pc-linux-gnu
``

**Pull request merged**
