### PR TITLE
Basic support for Win64 C lib ABI

### PR DESCRIPTION
**Pull request by oprypin**
Also un-does #5851

Based on

```bash
rust$ git checkout 29ac04402d53d358a1f6200bea45a301ff05b2d1
rust/src/librustc_trans/trans$ git diff cabi_x86.rs cabi_x86_win64.rs -w --no-index
```

<details>
<summary><b>See diff</b> (and actually all but the last hunk are no-ops!)</summary>

```patch
diff --git a/cabi_x86.rs b/cabi_x86_win64.rs
index 028d20f30..9b34c3bf2 100644
--- a/cabi_x86.rs
+++ b/cabi_x86_win64.rs
@@ -8,14 +8,14 @@
 // option. This file may not be copied, modified, or distributed
 // except according to those terms.
 
-use self::Strategy::*;
 use llvm::*;
-use trans::cabi::{ArgType, FnType};
-use trans::type_::Type;
 use super::common::*;
 use super::machine::*;
+use trans::cabi::{ArgType, FnType};
+use trans::type_::Type;
+
+// Win64 ABI: http://msdn.microsoft.com/en-us/library/zthk2dkh.aspx
 
-enum Strategy { RetValue(Type), RetPointer }
 pub fn compute_abi_info(ccx: &CrateContext,
                           atys: &[Type],
                           rty: Type,
@@ -26,35 +26,13 @@ pub fn compute_abi_info(ccx: &CrateContext,
     if !ret_def {
         ret_ty = ArgType::direct(Type::void(ccx), None, None, None);
     } else if rty.kind() == Struct {
-        // Returning a structure. Most often, this will use
-        // a hidden first argument. On some platforms, though,
-        // small structs are returned as integers.
-        //
-        // Some links:
-        // http://www.angelcode.com/dev/callconv/callconv.html
-        // Clang's ABI handling is in lib/CodeGen/TargetInfo.cpp
-
-        let t = &ccx.sess().target.target;
-        let strategy = if t.options.is_like_osx || t.options.is_like_windows {
-            match llsize_of_alloc(ccx, rty) {
-                1 => RetValue(Type::i8(ccx)),
-                2 => RetValue(Type::i16(ccx)),
-                4 => RetValue(Type::i32(ccx)),
-                8 => RetValue(Type::i64(ccx)),
-                _ => RetPointer
-            }
-        } else {
-            RetPointer
+        ret_ty = match llsize_of_alloc(ccx, rty) {
+            1 => ArgType::direct(rty, Some(Type::i8(ccx)), None, None),
+            2 => ArgType::direct(rty, Some(Type::i16(ccx)), None, None),
+            4 => ArgType::direct(rty, Some(Type::i32(ccx)), None, None),
+            8 => ArgType::direct(rty, Some(Type::i64(ccx)), None, None),
+            _ => ArgType::indirect(rty, Some(StructRetAttribute))
         };
-
-        match strategy {
-            RetValue(t) => {
-                ret_ty = ArgType::direct(rty, Some(t), None, None);
-            }
-            RetPointer => {
-                ret_ty = ArgType::indirect(rty, Some(StructRetAttribute));
-            }
-        }
     } else {
         let attr = if rty == Type::i1(ccx) { Some(ZExtAttribute) } else { None };
         ret_ty = ArgType::direct(rty, None, None, attr);
@@ -63,11 +41,12 @@ pub fn compute_abi_info(ccx: &CrateContext,
     for &t in atys {
         let ty = match t.kind() {
             Struct => {
-                let size = llsize_of_alloc(ccx, t);
-                if size == 0 {
-                    ArgType::ignore(t)
-                } else {
-                    ArgType::indirect(t, Some(ByValAttribute))
+                match llsize_of_alloc(ccx, t) {
+                    1 => ArgType::direct(rty, Some(Type::i8(ccx)), None, None),
+                    2 => ArgType::direct(rty, Some(Type::i16(ccx)), None, None),
+                    4 => ArgType::direct(rty, Some(Type::i32(ccx)), None, None),
+                    8 => ArgType::direct(rty, Some(Type::i64(ccx)), None, None),
+                    _ => ArgType::indirect(t, Some(ByValAttribute))
                 }
             }
             _ => {
```

</details>

Currently depends on #9384, so skip the first commit in this review.

### CODE REVIEW

**Comment by oprypin** [comment]
Umm woops, the ability to write `pending_win32 "works with C code"` in compiler specs depends on #9351. Shouldn't be a problem otherwise

**Comment by RX14** [comment]
How was this working with C libs before then?

**Comment by oprypin** [comment]
Passing structs and return values never worked. Just that CrSFML never uses either of those so it happened to work, almost everything else doesn't

**Comment by oprypin** [comment]
Wait hold on, I didn't realize that Crystal stdlib itself already has many dependencies on external libs so how do they work?

I only saw that libchipmunk didn't work at all without this change and now it does

**Comment by oprypin** [comment]
It could be that all those libs never require passing structs directly (not through a pointer)

**Comment by jhass** [comment]
Passing a full struct isn't the most common C API indeed IME. Usually you want your caller to allocate them and give you a reference to fill for them.

**Pull request merged**
