### PR TITLE
Run GHA CI only on push or pull request, but not both

### PR DESCRIPTION
**Pull request by Sija**
Solution taken from https://github.community/t/how-to-trigger-an-action-on-push-or-pull-request-but-not-both/16662

### CODE REVIEW

**Comment by j8r** [comment]
Why not just on push?

**Comment by Sija** [comment]
@j8r Did you read the referenced article?

**Comment by oprypin** [comment]
This makes it impossible to try CI without creating a pull request, so it's not good.

**Comment by Sija** [comment]
Why it's not good? It's dead simple and clear what's going on. I'd say it's better than having duplicate ci jobs on every push or pull request.

**Comment by j8r** [comment]
@Sija `on: [push]` will be enough, because the action will have already been ran on the fork.

**Comment by oprypin** [comment]
@Sija I can tell you more clearly what's not good, with an example. If you're working on some code, the first possible moment for you to find out that it doesn't work at all on another OS is some time after creating a pull request. Which I guess isn't *that* horrible (mostly just embarrassing..?), but why have that limitation?

I have heard that core team members sometimes rely on CI of pushed branches to the main repo, and also each contributor's fork will be unable to run CI with this.

Now, the fact that Windows builds break on forks currently is another matter. If that prompted your PR, well, instead that should just be fixed.

**Comment by Sija** [comment]
> @Sija I can tell you more clearly what's not good, with an example. If you're working on some code, the first possible moment for you to find out that it doesn't work at all on another OS is some time after creating a pull request. Which I guess isn't _that_ horrible (mostly just embarrassing..?), but why have that limitation?

@oprypin It's not a bug (limitation), it's a feature! (; Opening PRs gives more visibility and IMO there's nothing embarrassing in having failing specs in the early stage of the PR (could be a draft - they're here for a reason).

> I have heard that core team members sometimes rely on CI of pushed branches to the main repo, and also each contributor's fork will be unable to run CI with this.

It will run on every push to the `master` - addressing first part of your issue, re: the forks - we're again back to the PR.

> Now, the fact that Windows builds break on forks currently is another matter. If that prompted your PR, well, instead that should just be fixed.

No, it didn't.

I'd also add, that throughout my history as a OSS contributor I rarely used CI as primary spec runner - instead I'd run (selected) specs locally before pushing changes to the upstream.

OTOH what makes me itch is duplicated CI jobs on EVERY push OR pull request, resulting in:

1. visual noise
2. 200% increased CI times
3. confusion about the quality of tooling configuration resulting in such a mess

Btw, [default crystal GHA template](https://github.com/actions/starter-workflows/blob/main/ci/crystal.yml) uses exactly this pattern.

**Comment by lbguilherme** [comment]
@Sija There is a workaround suggested by piersy in the thread you linked: https://github.community/t/how-to-trigger-an-action-on-push-or-pull-request-but-not-both/16662/10

```
on:
  push:
  pull_request:
    branches:
      # Branches from forks have the form 'user:branch-name' so we only run
      # this job on pull_request events for branches that look like fork
      # branches. Without this we would end up running this job twice for non
      # forked PRs, once for the push and then once for opening the PR.
    - '**:**'
```

This seems to run the CI on any push from the current repo and on PRs from forks only. Seems to solve it all.

**Comment by Sija** [comment]
@lbguilherme Thanks for the tip! 🙏  I've force-pushed mentioned changes.

**Review by bcardiff — APPROVED** [review]

**Comment by lbguilherme** [comment]
I did the exact same change on a project of mine and it seems to be working just fine: https://github.com/sdkgen/sdkgen/commit/e3c2573ec7bfb6b972ed0a80918c0e4ad0ccb921

I have no idea what is going on here.

**Pull request closed without merging**
