### PR TITLE
Optimize Char#to_s

### PR DESCRIPTION
**Pull request by r00ster91**
This optimizes [`Char#to_s`](https://crystal-lang.org/api/0.27.2/Char.html#to_s-instance-method) by passing the exact amount of bytes to [`String.new`](https://crystal-lang.org/api/0.27.2/String.html#new%28capacity%3AInt%2C%26block%29-class-method) so if a character has less than 4 bytes (which is very commonly the case), less memory will be allocated by [`GC.malloc_atomic`](https://crystal-lang.org/api/0.27.2/GC.html#malloc_atomic(size:Int)-class-method) which is faster.
1 byte character:
```
new to_s  64.32M ( 15.55ns) (±14.73%)  16 B/op        fastest
old to_s  23.16M ( 43.18ns) (±21.06%)  48 B/op   2.78× slower
```
2 byte character:
```
new to_s  47.31M ( 21.14ns) (±20.04%)  16 B/op        fastest
old to_s  22.29M ( 44.86ns) (±22.60%)  48 B/op   2.12× slower
```
3 byte character:
```
new to_s  47.76M ( 20.94ns) (±10.11%)  32 B/op        fastest
old to_s  31.36M ( 31.89ns) (± 8.03%)  32 B/op   1.52× slower
```
4 byte character, the new `to_s` is slightly slower than the old `to_s`:
```
new to_s  45.33M ( 22.06ns) (±12.35%)  32 B/op   1.10× slower
old to_s  49.89M ( 20.05ns) (± 7.99%)  32 B/op        fastest
```
I believe that is because in the new `to_s` the `4` needs to be computed first using [`Char#bytesize`](https://crystal-lang.org/api/0.27.2/Char.html#bytesize-instance-method) while the old `to_s` has the `4` already.
But I think it's worth it.

This also fixes two dead links.

### CODE REVIEW

**Comment by asterite** [comment]
@r00ster91 Thank you! This is a good idea. However, calling `bytesize` and then `each_byte` effectively decodes the char twice, that's why with 1 byte it's a bit slower.

Using your initial idea of avoiding allocating more memory than needed, I ended up with this implementation:

```crystal
def new_to_s
  chars = uninitialized UInt8[4]
  i = 0
  each_byte do |byte|
    chars[i] = byte
    i += 1
  end
  String.new(i) do |buffer|
    buffer.copy_from(chars.to_unsafe, i)
    {i, 1}
  end
end
```

Using this benchmark:

```crystal
require "benchmark"

Benchmark.ips do |x|
  x.report("1 (old)") do
    'a'.to_s
  end
  x.report("1 (new)") do
    'a'.new_to_s
  end
end

Benchmark.ips do |x|
  x.report("2 (old)") do
    'ߣ'.to_s
  end
  x.report("2 (new)") do
    'ߣ'.new_to_s
  end
end

Benchmark.ips do |x|
  x.report("3 (old)") do
    '勞'.to_s
  end
  x.report("3 (new)") do
    '勞'.new_to_s
  end
end

Benchmark.ips do |x|
  x.report("4 (old)") do
    '䈽'.to_s
  end
  x.report("4 (new)") do
    '䈽'.new_to_s
  end
end
```

I got these results:

```
1 (old)  19.64M ( 50.91ns) (± 1.84%)  48 B/op   1.89× slower
1 (new)  37.07M ( 26.98ns) (± 1.72%)  16 B/op        fastest
2 (old)  19.76M (  50.6ns) (± 2.96%)  48 B/op   1.99× slower
2 (new)  39.26M ( 25.47ns) (± 3.33%)  16 B/op        fastest
3 (old)  17.45M ( 57.31ns) (± 3.39%)  33 B/op   1.46× slower
3 (new)  25.56M ( 39.12ns) (± 2.62%)  32 B/op        fastest
4 (old)  17.27M ( 57.89ns) (± 4.55%)  33 B/op   1.45× slower
4 (new)   25.0M ( 39.99ns) (± 6.45%)  32 B/op        fastest
```

(always faster than before)

Can you run this benchmark in your machine to check it's also always faster?

**Comment by r00ster91** [comment]
Oh so in your implementation you avoid some of these checks: `elsif c <= 0xffff` by not calling both `bytesize` and `each_byte` like in the implementation of this PR, that's a good idea.

> that's why with 1 byte it's a bit slower.

I think you mean 4 bytes, right?

In your last benchmark the `䈽` isn't 4 bytes, it's 3 bytes. When I replace it with `􏾛` which has 4 bytes, these are my results:
```
1 (old)  20.95M ( 47.73ns) (±21.06%)  48 B/op   3.33× slower
1 (new)  69.83M ( 14.32ns) (±13.88%)  16 B/op        fastest
2 (old)  19.95M ( 50.13ns) (±21.08%)  48 B/op   2.88× slower
2 (new)  57.51M ( 17.39ns) (±19.27%)  16 B/op        fastest
3 (old)  24.89M ( 40.18ns) (±14.46%)  32 B/op   2.09× slower
3 (new)  52.07M ( 19.21ns) (± 8.31%)  32 B/op        fastest
4 (old)  50.25M (  19.9ns) (± 8.13%)  32 B/op        fastest
4 (new)  50.12M ( 19.95ns) (± 7.47%)  32 B/op   1.00× slower
```
So in the last benchmark the new implementation is at least not slower.

But now when I also benchmark with the `to_s` of this PR:
```crystal
require "benchmark"

struct Char
  def new_to_s
    chars = uninitialized UInt8[4]
    i = 0
    each_byte do |byte|
      chars[i] = byte
      i += 1
    end
    String.new(i) do |buffer|
      buffer.copy_from(chars.to_unsafe, i)
      {i, 1}
    end
  end
  def pr_to_s
    String.new(bytesize) do |buffer|
      appender = buffer.appender
      each_byte { |byte| appender << byte }
      {appender.size, 1}
    end
  end
end

Benchmark.ips do |x|
  x.report("1 (old)") do
    'a'.to_s
  end
  x.report("1 (new)") do
    'a'.new_to_s
  end
  x.report("1 (pr)") do
    'a'.pr_to_s
  end
end
Benchmark.ips do |x|
  x.report("2 (old)") do
    'ߣ'.to_s
  end
  x.report("2 (new)") do
    'ߣ'.new_to_s
  end
  x.report("2 (pr)") do
    'ߣ'.pr_to_s
  end
end
Benchmark.ips do |x|
  x.report("3 (old)") do
    '勞'.to_s
  end
  x.report("3 (new)") do
    '勞'.new_to_s
  end
  x.report("3 (pr)") do
    '勞'.pr_to_s
  end
end
Benchmark.ips do |x|
  x.report("4 (old)") do
    '􏾛'.to_s
  end
  x.report("4 (new)") do
    '􏾛'.new_to_s
  end
  x.report("4 (pr)") do
    '􏾛'.pr_to_s
  end
end
```
I get this where the PR implementation is a tiny bit faster than your implementation for some reason:
```
1 (old)  17.03M ( 58.72ns) (±20.07%)  48 B/op   4.08× slower
1 (new)  68.56M ( 14.58ns) (±12.98%)  16 B/op   1.01× slower
 1 (pr)  69.44M (  14.4ns) (±11.49%)  16 B/op        fastest
2 (old)  22.14M ( 45.16ns) (±22.05%)  48 B/op   3.07× slower
2 (new)  65.38M (  15.3ns) (±12.42%)  16 B/op   1.04× slower
 2 (pr)  67.88M ( 14.73ns) (±13.54%)  16 B/op        fastest
3 (old)  29.58M ( 33.81ns) (± 8.87%)  32 B/op   1.80× slower
3 (new)  52.56M ( 19.02ns) (± 7.47%)  32 B/op   1.01× slower
 3 (pr)  53.34M ( 18.75ns) (± 7.06%)  32 B/op        fastest
4 (old)  28.27M ( 35.37ns) (±12.94%)  32 B/op   1.87× slower
4 (new)  52.58M ( 19.02ns) (± 7.87%)  32 B/op   1.01× slower
 4 (pr)  52.93M ( 18.89ns) (± 7.48%)  32 B/op        fastest
```
Hmm but I'm not sure if there is actually really a difference.
Now only comparing those 3:
```crystal
Benchmark.ips do |x|
  x.report("4 (old)") do
    Char::MAX.to_s
  end
  x.report("4 (new)") do
    Char::MAX.new_to_s
  end
  x.report("4 (pr)") do
    Char::MAX.pr_to_s
  end
end
```
```
4 (old)  45.47M ( 21.99ns) (±12.17%)  32 B/op   1.10× slower
4 (new)   49.9M ( 20.04ns) (± 8.18%)  32 B/op        fastest
 4 (pr)  49.23M ( 20.31ns) (± 8.60%)  32 B/op   1.01× slower
```
Yes it looks like they are relatively the same.

**Comment by r00ster91** [comment]
In the 4 byte character benchmark in the description of this PR it was just a coincidence I think. I was just sure the new implementation was slower in this case because I've ran it multiple times in a row and it was always shown as 'slower'. But now I also got a case where the old one was 'slower':
```shell
$ crystal benchmark.cr --release
4 (pr)   44.4M ( 22.52ns) (±14.21%)  32 B/op   1.13× slower
4 (old)  50.39M ( 19.85ns) (± 8.81%)  32 B/op        fastest
$ crystal benchmark.cr --release
4 (pr)   23.81M ( 41.99ns) (±14.00%)  32 B/op   1.94× slower
4 (old)  46.09M (  21.7ns) (±20.27%)  32 B/op        fastest
$ crystal benchmark.cr --release
4 (pr)   47.82M ( 20.91ns) (±12.49%)  32 B/op        fastest
4 (old)  41.89M ( 23.87ns) (±23.95%)  32 B/op   1.14× slower
```

**Comment by r00ster91** [comment]
I resolved the conflicts.

**Comment by straight-shoota** [comment]
I think the implementation should be changed to @asterite's proposal in https://github.com/crystal-lang/crystal/pull/7393#issuecomment-461575678

It seems a bit weird that in your benchmark, it was en par with the `bytesize` implementation, but in theory it should be more performant.

**Comment by r00ster91** [comment]
@straight-shoota Here's another benchmark.
```cr
struct Char
  def new_to_s
    chars = uninitialized UInt8[4]
    i = 0
    each_byte do |byte|
      chars[i] = byte
      i += 1
    end
    String.new(i) do |buffer|
      buffer.copy_from(chars.to_unsafe, i)
      {i, 1}
    end
  end
end

require "benchmark"

Benchmark.ips do |benchmark|
  benchmark.report("to_s") { 'あ'.to_s(); 'a'.to_s(); }
  benchmark.report("new_to_s") { 'あ'.new_to_s(); 'a'.new_to_s(); }
end
```
```
    to_s  14.87M ( 67.25ns) (±16.56%)  80.0B/op   2.91× slower
new_to_s  43.29M ( 23.10ns) (±22.26%)  48.0B/op        fastest
```
`new_to_s` is still consistently faster for me and allocates less memory. Same for the benchmark @asterite provided above.
Is anything blocking this?

**Review by straight-shoota — APPROVED** [review]

**Comment by BlobCodes** [comment]
@r00ster91 

I have tried improving the performance even further.
I came up with this (method blobcodes_to_s):

<details>
<summary>Benchmark code</summary>
<p>

```crystal
require "benchmark"

struct Char
  # Mostly copied from the each_char implementation (just replaced the yields with String creation)
  def blobcodes_to_s : String
    c = ord
    if c < 0x80
      # 0xxxxxxx
      String.new(1) do |pointer|
        pointer[0] = c.to_u8
        {1, 1}
      end
    elsif c <= 0x7ff
      # 110xxxxx  10xxxxxx
      String.new(2) do |pointer|
        pointer[0] = (0xc0 | c >> 6).to_u8
        pointer[1] = (0x80 | c & 0x3f).to_u8
        {2, 1}
      end
    elsif c <= 0xffff
      # 1110xxxx  10xxxxxx  10xxxxxx
      String.new(3) do |pointer|
        pointer[0] = (0xe0 | (c >> 12)).to_u8
        pointer[1] = (0x80 | ((c >> 6) & 0x3f)).to_u8
        pointer[2] = (0x80 | (c & 0x3f)).to_u8
        {3, 1}
      end
    elsif c <= MAX_CODEPOINT
      # 11110xxx  10xxxxxx  10xxxxxx  10xxxxxx
      String.new(4) do |pointer|
        pointer[0] = (0xf0 | (c >> 18)).to_u8
        pointer[1] = (0x80 | ((c >> 12) & 0x3f)).to_u8
        pointer[2] = (0x80 | ((c >> 6) & 0x3f)).to_u8
        pointer[3] = (0x80 | (c & 0x3f)).to_u8
        {4, 1}
      end
    else
      raise InvalidByteSequenceError.new("Invalid char value #{dump}")
    end
  end

  def r00ster91_to_s
    chars = uninitialized UInt8[4]
    i = 0
    each_byte do |byte|
      chars[i] = byte
      i += 1
    end
    String.new(i) do |buffer|
      buffer.copy_from(chars.to_unsafe, i)
      {i, 1}
    end
  end
end

char = '😎'
Benchmark.ips do |x|
  x.report("old") { char.to_s }
  x.report("roo") { char.r00ster91_to_s }
  x.report("blo") { char.blobcodes_to_s }
end

char = 'a'
Benchmark.ips do |x|
  x.report("old") { char.to_s }
  x.report("roo") { char.r00ster91_to_s }
  x.report("blo") { char.blobcodes_to_s }
end
```

</p>
</details>

Results:
```
Char: '😎'
old  76.12M ( 13.14ns) (± 1.60%)  32.0B/op   1.02× slower
roo  65.47M ( 15.28ns) (± 1.68%)  32.0B/op   1.18× slower
blo  77.37M ( 12.92ns) (± 1.67%)  32.0B/op        fastest

Char: 'a'
old  38.66M ( 25.87ns) (± 3.17%)  48.0B/op   3.02× slower
roo  96.35M ( 10.38ns) (± 1.78%)  16.0B/op   1.21× slower
blo 116.76M (  8.56ns) (± 2.57%)  16.0B/op        fastest
```

It definitely looks worse than the other method (because it is so big), but I think it could be considered.

**Comment by HertzDevil** [comment]
If #10451 is merged then it is safe to assume that `!(0xD800 <= ord <= 0xDFFF) && ord <= MAX_CODEPOINT` for any `Char`. In that case what happens if range checking is removed from all 3 implementations as much as possible? (Most notably `InvalidByteSequenceError` would not be raised at all.)

**Comment by BlobCodes** [comment]
> If #10451 is merged then it is safe to assume that `!(0xD800 <= ord <= 0xDFFF) && ord <= MAX_CODEPOINT` for any `Char`. In that case what happens if range checking is removed from all 3 implementations as much as possible? (Most notably `InvalidByteSequenceError` would not be raised at all.)

<details>
<summary>Code</summary>
<p>

```crystal
require "benchmark"

struct Char
  # Mostly copied from the each_char implementation
  def blobcodes_to_s : String
    c = ord
    if c < 0x80
      # 0xxxxxxx
      String.new(1) do |pointer|
        pointer[0] = c.to_u8
        {1, 1}
      end
    elsif c <= 0x7ff
      # 110xxxxx  10xxxxxx
      String.new(2) do |pointer|
        pointer[0] = (0xc0 | c >> 6).to_u8
        pointer[1] = (0x80 | c & 0x3f).to_u8
        {2, 1}
      end
    elsif c <= 0xffff
      # 1110xxxx  10xxxxxx  10xxxxxx
      String.new(3) do |pointer|
        pointer[0] = (0xe0 | (c >> 12)).to_u8
        pointer[1] = (0x80 | ((c >> 6) & 0x3f)).to_u8
        pointer[2] = (0x80 | (c & 0x3f)).to_u8
        {3, 1}
      end
    elsif c <= MAX_CODEPOINT
      # 11110xxx  10xxxxxx  10xxxxxx  10xxxxxx
      String.new(4) do |pointer|
        pointer[0] = (0xf0 | (c >> 18)).to_u8
        pointer[1] = (0x80 | ((c >> 12) & 0x3f)).to_u8
        pointer[2] = (0x80 | ((c >> 6) & 0x3f)).to_u8
        pointer[3] = (0x80 | (c & 0x3f)).to_u8
        {4, 1}
      end
    else
      raise InvalidByteSequenceError.new("Invalid char value #{dump}")
    end
  end

  def blobcodes_to_s_stripped
    c = ord
    if c < 0x80
      # 0xxxxxxx
      String.new(1) do |pointer|
        pointer[0] = c.to_u8
        {1, 1}
      end
    elsif c <= 0x7ff
      # 110xxxxx  10xxxxxx
      String.new(2) do |pointer|
        pointer[0] = (0xc0 | c >> 6).to_u8
        pointer[1] = (0x80 | c & 0x3f).to_u8
        {2, 1}
      end
    elsif c <= 0xffff
      # 1110xxxx  10xxxxxx  10xxxxxx
      String.new(3) do |pointer|
        pointer[0] = (0xe0 | (c >> 12)).to_u8
        pointer[1] = (0x80 | ((c >> 6) & 0x3f)).to_u8
        pointer[2] = (0x80 | (c & 0x3f)).to_u8
        {3, 1}
      end
    else
      # 11110xxx  10xxxxxx  10xxxxxx  10xxxxxx
      String.new(4) do |pointer|
        pointer[0] = (0xf0 | (c >> 18)).to_u8
        pointer[1] = (0x80 | ((c >> 12) & 0x3f)).to_u8
        pointer[2] = (0x80 | ((c >> 6) & 0x3f)).to_u8
        pointer[3] = (0x80 | (c & 0x3f)).to_u8
        {4, 1}
      end
    end
  end

  def r00ster91_to_s
    chars = uninitialized UInt8[4]
    i = 0
    each_byte do |byte|
      chars[i] = byte
      i += 1
    end
    String.new(i) do |buffer|
      buffer.copy_from(chars.to_unsafe, i)
      {i, 1}
    end
  end

  def r00ster91_to_s_stripped
    chars = uninitialized UInt8[4]
    i = 0
    each_byte_stripped do |byte|
      chars[i] = byte
      i += 1
    end
    String.new(i) do |buffer|
      buffer.copy_from(chars.to_unsafe, i)
      {i, 1}
    end
  end

  def each_byte_stripped
    c = ord
    if c < 0x80
      # 0xxxxxxx
      yield c.to_u8
    elsif c <= 0x7ff
      # 110xxxxx  10xxxxxx
      yield (0xc0 | c >> 6).to_u8
      yield (0x80 | c & 0x3f).to_u8
    elsif c <= 0xffff
      # 1110xxxx  10xxxxxx  10xxxxxx
      yield (0xe0 | (c >> 12)).to_u8
      yield (0x80 | ((c >> 6) & 0x3f)).to_u8
      yield (0x80 | (c & 0x3f)).to_u8
    else
      # 11110xxx  10xxxxxx  10xxxxxx  10xxxxxx
      yield (0xf0 | (c >> 18)).to_u8
      yield (0x80 | ((c >> 12) & 0x3f)).to_u8
      yield (0x80 | ((c >> 6) & 0x3f)).to_u8
      yield (0x80 | (c & 0x3f)).to_u8
    end
  end

  def to_s_stripped : String
    String.new(4) do |buffer|
      appender = buffer.appender
      each_byte_stripped { |byte| appender << byte }
      {appender.size, 1}
    end
  end
end

{'a', '😎'}.each do |char|
  puts "Char: #{char}"
  Benchmark.ips do |x|
    x.report("blo stripped") { char.blobcodes_to_s_stripped }
    x.report("blo normal") { char.blobcodes_to_s }
    x.report("roo stripped") { char.r00ster91_to_s_stripped }
    x.report("roo normal") { char.r00ster91_to_s }
    x.report("old stripped") { char.to_s_stripped }
    x.report("old normal") { char.to_s }
  end
  puts
end
```

</p>
</details>

<details>

<summary>Results</summary>

<p>

```
Char: a
blo stripped 106.16M (  9.42ns) (± 4.76%)  16.0B/op   1.01× slower
  blo normal 106.82M (  9.36ns) (± 3.32%)  16.0B/op        fastest
roo stripped  90.53M ( 11.05ns) (± 2.45%)  16.0B/op   1.18× slower
  roo normal  89.65M ( 11.15ns) (± 2.45%)  16.0B/op   1.19× slower
old stripped  42.67M ( 23.43ns) (± 1.95%)  48.0B/op   2.50× slower
  old normal  42.11M ( 23.75ns) (± 1.55%)  48.0B/op   2.54× slower

Char: 😎
blo stripped  75.98M ( 13.16ns) (± 5.39%)  32.0B/op        fastest
  blo normal  73.18M ( 13.67ns) (± 5.54%)  32.0B/op   1.04× slower
roo stripped  63.33M ( 15.79ns) (± 3.74%)  32.0B/op   1.20× slower
  roo normal  62.46M ( 16.01ns) (± 4.56%)  32.0B/op   1.22× slower
old stripped  72.26M ( 13.84ns) (± 3.78%)  32.0B/op   1.05× slower
  old normal  75.84M ( 13.19ns) (± 2.56%)  32.0B/op   1.00× slower
```

</p>

</details>

There does seem to be a little improvement.

**Comment by r00ster91** [comment]
Closing in favor of #11593

**Pull request closed without merging**
