### PR TITLE
Feature/dig method

### PR DESCRIPTION
**Pull request by werner**
Dig method for Hash, like Ruby: http://ruby-doc.org/core-2.3.0_preview1/Hash.html#method-i-dig

### CODE REVIEW

**Comment by asterite** [comment]
I though about this, but I think in Crystal it's not very useful because:

1. The resulting type will be a union of all types that are in all hashes (recursively)
2. Those nested hashes are not very common. Proper types (classes) are more common and easier to deal with.

However, maybe `dig` for `JSON::Any` (and eventually a `YAML::Any` could be useful.

**Comment by waj** [comment]
The union result type could be avoided if `dig` is defined in this way:

```crystal
class Hash
  def dig(key)
    self[key]
  end

  def dig(key, *keys)
    self[key].dig(*keys)
  end
end

h = {foo: {bar: {baz: 5}}}
puts h.dig(:foo, :bar, :baz).class # => Int32
```

And it will also give compile errors if the passed keys are invalid for the hash type. However this error is quite hard to read, so I'm still unsure about adding this to the std library.Thoughts?

**Comment by werner** [comment]
Hi, I was thinking in include this method in a shard. So, can I close it?

**Comment by jhass** [comment]
Ping.

**Pull request closed without merging**
