### PR TITLE
Fix parsing of '!=' after an identifier

### LINKED ISSUE #4815: Behavior of obj.prop!= value
I had the following code:

```
if( obj.prop!= 1)
```

This resulted in the error "undefined method 'prop!=' for ObjClass".

The error happened because there is no space between "prop" and "!=".
It appears that without a space inserted, Crystal parses the syntax as invoking the method "prop!=" on object "obj".

I am wondering if there was a purpose behind it? One would generally expect the != to be a negation of ==, not to be treated as part of method name.

In Ruby, "obj.prop!= value" is parsed as "obj.prop not-equal value" as expected.

Example on Play: https://play.crystal-lang.org/#/r/2i55

### PR DESCRIPTION
**Pull request by oprypin**
Fixes #4815

### CODE REVIEW

**Comment by MakeNowJust** [comment]
I think it is breaking change.

**Comment by RX14** [comment]
Maybe it is a breaking change but the behaviour before was certainly a bug.

**Comment by oprypin** [comment]
I just made a mistake in the spec (or more likely pushed before saving that file). All good now.

**Comment by bew** [comment]
So a method named `method!=` shouldn't work?

This PR breaks the following code:
```cr
class C
  def method!=(var)
    puts "assigning #{var}"
  end
end

C.new.method! = 4
```
Error:
```
Using compiled compiler at `.build/crystal'
Syntax error in test.cr:2: unexpected token: !=

  def method!=(var)
            ^
```

**Comment by RX14** [comment]
No, I don't think that code should work.

**Comment by ysbaddaden** [comment]
Merging. What do bang (`foo.bar! = 1`) or question (`foo.bar? = 2`) setters bring to the language? IMHO only weirdness, if not confusion.

**Comment by bew** [comment]
@RX14 @ysbaddaden I agree, it's just confusing. I just wanted to point it out, as it wasn't mentionned anywhere and this PR is breaking it.

**Comment by RX14** [comment]
@bew Thanks for mentioning it, i'm sure it'll make it into the changelog.

**Pull request merged**
