### PR TITLE
Docs cleanup

### PR DESCRIPTION
**Pull request by Sija**
Every commit fixes different, albeit small issue, I've found with docs :)

### CODE REVIEW

**Comment by BlaXpirit** [comment]
I'd rather see "consistently use indented code blocks". It's a waste of 2 lines every time otherwise :/

**Comment by Sija** [comment]
@BlaXpirit indented code block are not being processed by formatter tool.

**Comment by Sija** [comment]
I think I've also found a bug in markdown parser. It's visible in the docs for [String#new](https://crystal-lang.org/api/0.20.3/String.html#new%28bytes%3ABytes%2Cencoding%3AString%2Cinvalid%3ASymbol%3F%3Dnil%29%3AString-class-method) method, where final code block is being chopped.

**Comment by Sija** [comment]
@asterite WDYT about it?

**Comment by asterite** [comment]
@Sija This is **huge**, and excellent! I liked it so much the first time I saw it that I thought I already merged this... sorry! 😊

**Comment by Sija** [comment]
@asterite I was wondering wouldn't it be nice to have dedicated flag for _see also_ notes? Maybe `SEE` to stay coherent with the rest of 'em (like `NOTE` or `FIXME`)?

**Pull request merged**
