### PR TITLE
Fix Slice#clone for non-primitive types and deep copy

### LINKED ISSUE #7590: possible issue with Slice#clone
Code source:
https://carc.in/#/r/6l2p
```
slice = Slice["abc", "a"]

slice.clone
```
```
Error in line 3: instantiating 'Slice(String)#clone()'

in /usr/lib/crystal/slice.cr:125: Can only use primitive integers and floats with Slice.new(size), not String

    copy = self.class.new(size)
```

It's strange how Slice was created with String elements but it fails to clone the instance.
Is this an intended behavior?

### PR DESCRIPTION
**Pull request by straight-shoota**
Fixes `Slice#clone` for non-primitive types (#7590) and fixes `Sice#clone` to perform a deep copy, `Slice#dup` a memory copy.

### CODE REVIEW

**Comment by asterite** [comment]
I think it's still wrong. `clone` should perform a deep copy, so the elements inside the slice must be `clone`d too.

**Comment by straight-shoota** [comment]
You're right. That was already broken before #3624 was fixed.

**Comment by straight-shoota** [comment]
So, we have three levels of copy:

1. struct copy: duplicates the ivar values pointer and size (current `#dup`).
2. buffer copy: the data is duplicated to a new memory location (current `#clone`).
3. deep copy: calls `#clone` on each item and stores the results in newly allocated memory (new `#clone`).

When fixing `#clone`, we're missing a method for buffer copy. Should we maybe rename the current behaviour to `#dup`? It would be different from other struct's default `#dup` method, but that should be fine. Struct copy is always implicit when passed as value.

**Comment by bcardiff** [comment]
I don't see it as three levels. 
When cloning a container structure you want to avoid aliasing of values (deep copy)
When dupping a container structure you want to have aliasing of values. (shallow copy)

**Comment by asterite** [comment]
I think for 2 he means allocating a new buffer for the data, but use the same data. If you move the struct around (struct copy) it will be the same pointer/buffer. So I think yes, 2 is missing and we could use `#dup` for that.

**Comment by straight-shoota** [comment]
Exactly. I've implemented my suggestion and provided specs to demonstrate the behaviour.

**Comment by kematy** [comment]
How can this ruby language like code be simplified when deep cloning?
class Object
      def dclone
        case self
          when Fixnum,Bignum,Float,NilClass,
               FalseClass,TrueClass
            klone = self
          when Hash
            klone = self.clone
            self.each{|k,v| klone[k] = v.dclone}
          when Array
            klone = self.clone
            klone.clear
            self.each{|v| klone << v.dclone}
          else
            klone = self.clone
        end
        klone.instance_variables.each {|v|
          klone.instance_variable_set(v,
            klone.instance_variable_get(v).dclone)
        }
        klone
      end
    end

**Comment by Sija** [comment]
@kematy Please use the forum for questions like that.

**Pull request merged**
