### PR TITLE
Fix the scope to look-up the constant as the receiver type of the macro

### LINKED ISSUE #5343: Bytes[1, 2] is broken when used in a class
https://carc.in/#/r/36qg
```cr
STDOUT.write Bytes[1, 2] # works OK

class Foo
  def self.bytes
    Bytes['a'.ord, 97]
  end
end

STDOUT.write Foo.bytes   # compile error
```
Gives:
```
Error in bytes_slice.cr:9: instantiating 'Foo:Class#bytes()'

STDOUT.write Foo.bytes
                 ^~~~~

in bytes_slice.cr:5: expanding macro

    Bytes['a'.ord, 97]
         ^

in /usr/lib/crystal/slice.cr:34: undefined constant T

    {% if @type.name != "Slice(T)" && T < Number %}
                                      ^
```
The macro expansion is looking for a `T` in Foo.

This is visible with this example (https://carc.in/#/r/36qi):
```cr
class Bar(T) # Here is a T !
  def self.bytes
    Bytes['a'.ord, 97]
  end
end

STDOUT.write Bar(UInt8).bytes # compiles OK, but this is wrong!
```
Going back in time with carc.in, it seems to break on 0.19.0 release.

### PR DESCRIPTION
**Pull request by MakeNowJust**
Fixed #5343. It is another solution than #5349. I believe this PR is better than #5349.

Currently the constant in expansion inside macro is resolved by caller-scope, for example:

```crystal
class Foo
  macro foo
    {{Baz}}
  end
end

class Bar
  class Baz
  end

  def self.foo
    Foo.foo
  end
end

p Bar.foo # => Bar::Baz
```

It is unexpected because the constant inside method is of course resolved by the receiver type of the method. And so, [the second example](https://carc.in/#/r/36qi) in #5343 is caused.

This PR fixed scope to look-up the constant as the receiver type of the macro.

### CODE REVIEW

**Comment by RX14** [comment]
@MakeNowJust say in that example the macro did want to access `Baz`, how would that be done?

**Comment by MakeNowJust** [comment]
@RX14 Using `Bar::Baz` is the right way.

**Comment by MakeNowJust** [comment]
It does not make a sense that this example works only if `Foo.foo` is called from the scope having `Bar`.

```crystal
class Foo
  macro foo
    {{Baz}}
  end

  class Baz
  end
end

class Bar
  class Baz
  end

  def self.foo
    Foo.foo
  end
end

class FooBar
  def self.foo
    Foo.foo
  end
end

p Bar.foo # => Bar::Baz
p FooBar.foo # compilation error: undefined constant 'Baz'
```

Isn't it?

**Comment by RX14** [comment]
@MakeNowJust but now you have to pass in the outer scope somehow? Macros can reference local variables and local methods, why not local types too.

**Comment by MakeNowJust** [comment]
This example works. What is problem?

```crystal
class Foo
  macro foo(x)
    {{x}}
  end

  macro bar
    Baz
  end
end

class Bar
  class Baz
  end

  def self.foo
    Foo.foo Baz
  end

  def self.bar
    Foo.bar
  end
end

p Bar.foo # => Bar::Baz
p Bar.bar # => Bar::Baz
```

This PR fixes the semantic in only **macro expansion inside macro**.

**Comment by RX14** [comment]
@MakeNowJust ah yes never mind me I was just confused.

**Comment by bew** [comment]
I think what @RX14 fears is that we may not be able to access a 'local' type from the macro system, as `{% SomeType %}`

```cr
module IncludeMe
  macro included
    STORAGE = [] of _ # Create a 'local' Type in the caller's (includer) scope
  end

  macro add(node)
    {% STORAGE << node %} # Access a 'local' type in the caller's scope, from the macro system
  end
end

class Foo
  include IncludeMe

  # Add some stuff from macros to a 'local' type
  add a + b
  add :bla
end
```

But it seems to still work, so :+1:

**Comment by bew** [comment]
Can this go forward?

**Comment by asterite** [comment]
This fix is correct 👍

**Comment by RX14** [comment]
needs a rebase, sorry for the delay merging

**Comment by MakeNowJust** [comment]
I merged master into this on GitHub Web UI. Please do squash merge.

**Pull request merged**
