### PR TITLE
Remove `spec/win32_std_spec.cr`

### PR DESCRIPTION
**Pull request by HertzDevil**
With just 8 out of 259 spec files failing to compile on Windows, there is no longer a dire need to keep a list of the spec files that do build. This PR makes the remaining specs use `skip_file` instead, similar to the Unix domain socket ones. It looks like this enables 3 new examples somewhere.

The script that generates `spec/win32_std_spec.cr` remains intact in case we want to reuse it for some other completely new system.

### CODE REVIEW

**Review by sdogruyol — APPROVED** [review]
Thank you @HertzDevil 🙏

**Review by straight-shoota — APPROVED** [review]

**Comment by straight-shoota** [comment]
👀 
```
1) HTTP::Client tests write_timeout
     Failure/Error: expect_raises(IO::TimeoutError, {% if flag?(:win32) %} "WSASend timed out" {% else %} "Write timed out" {% end %}) do
       Expected IO::TimeoutError, got #<Socket::ConnectError: Error connecting to 'localhost:64862': Overlapped I/O event is not in a signaled state.> with backtrace:
         # src\socket\addrinfo.cr:67 in 'initialize'
         # src\socket\tcp_socket.cr:27 in 'initialize'
         # src\socket\tcp_socket.cr:27 in 'new'
         # src\http\client.cr:789 in 'io'
         # src\http\client.cr:671 in 'send_request'
         # src\http\client.cr:603 in 'exec_internal_single'
         # src\http\client.cr:596 in 'exec_internal'
         # src\http\client.cr:581 in 'exec'
         # src\http\client.cr:713 in 'exec'
         # src\http\client.cr:406 in 'post:body'
         # spec\std\http\client\client_spec.cr:296 in '->'
         # src\spec\example.cr:45 in 'internal_run'
         # src\spec\example.cr:33 in 'run'
         # src\spec\context.cr:18 in 'internal_run'
         # src\spec\context.cr:339 in 'run'
         # src\spec\context.cr:18 in 'internal_run'
         # src\spec\context.cr:156 in 'run'
         # src\spec\dsl.cr:220 in '->'
         # src\crystal\at_exit_handlers.cr:14 in 'run'
         # src\crystal\main.cr:50 in 'exit'
         # src\crystal\main.cr:45 in 'main'
         # src\crystal\main.cr:127 in 'main'
         # src\crystal\system\win32\wmain.cr:35 in 'wmain'
         # D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288 in '__scrt_common_main_seh'
         # C:\Windows\System32\KERNEL32.DLL +85712 in 'BaseThreadInitThunk'
         # C:\Windows\SYSTEM32\ntdll.dll +517019 in 'RtlUserThreadStart'
```

**Comment by straight-shoota** [comment]
This looks very much like a flaw in the event loop.

**Comment by HertzDevil** [comment]
The three new examples introduced in this PR are `spec/std/crystal/compiler_rt/{ashlti3,ashrti3,lshrti3}_spec.cr`. It is rather unlikely they would break the concurrency-related specs.

I am wondering if the failures can also be reproduced by simply rearranging the `require`s in `win32_std_spec.cr`.

**Comment by straight-shoota** [comment]
CI is green consistently, so I think this should be good to merge.
If the failure shows up again, it's probably not related to this change.

**Pull request merged**
