### PR TITLE
Add `Indexable#index!` overloads with `offset` parameter

### PR DESCRIPTION
**Pull request by HertzDevil**
Follow-up to #11566. `Indexable#index` overrides `Enumerable#index` and has an extra parameter, so it makes sense the raising variant should be overridden in a similar way. (There are further overrides in `Indexable`'s including types, but they do not introduce any new signatures, so this PR will suffice.)

### CODE REVIEW

**Review by straight-shoota — COMMENTED** [review]
There is a discrepancy between the parameter name in code (`object`) and in the docs (`value`). `#index` uses `object`, so that seems to be the natural choice.

**Comment by straight-shoota** [comment]
I'd prefer `object` over `obj` and I'd rather standardize on that.

**Comment by HertzDevil** [comment]
No other methods in `Enumerable` or `Indexable` use `object` as a parameter name. On the other hand, `obj` also shows up in `Enumerable#includes?` and `#each_with_object` (plus similar ones in `Iterator` and `Iterable`).

**Comment by HertzDevil** [comment]
I don't think it would be wise to do any renamings on the whole standard library in here, so to move forward I suggest using `obj` here, since that's what the parameter is called in `Enumerable#index!`, and revert everything else.

**Review by straight-shoota — APPROVED** [review]

**Pull request merged**
