### PR TITLE
Fix example of hexadecimal sequence

### LINKED ISSUE #5030: Possible typo in src/string.cr
On line 124: [https://github.com/crystal-lang/crystal/blob/master/src/string.cr#L124](https://github.com/crystal-lang/crystal/blob/master/src/string.cr#L124)

```crystal


# Hexadecimal escape sequences
"\x45" # # => "A"
````
But this is what I get in the Crystal playground: https://play.crystal-lang.org/#/r/2sep
"\x45" prints "E", not "A":
screenshot from 2017-09-24 12-21-04

### PR DESCRIPTION
**Pull request by faustinoaq**
Fix example of hexadecimal sequence

Fixes #5030

### CODE REVIEW

**Comment by oprypin** [comment]
Please use the opposite ordering of lines in the commit message. Ideal example:

```
Fix example of hexadecimal sequence

Fixes #5030
```

The exact same goes for pull request title vs content. They should be swapped. `Fix #5030` is not even clickable in the title, and you must open it to have any idea of what's going on.

**Comment by faustinoaq** [comment]
@oprypin Ok, Thanks for the advice, Should I open a new PR ?

**Comment by oprypin** [comment]
There's never a need to make a new PR. `git commit --amend; git push -f` can fix it.
But maybe you don't have to do anything because the person who clicks merge can edit the message, IIRC.

**Comment by faustinoaq** [comment]
> But maybe you don't have to do anything because the person who clicks merge can edit the message

So, is this ready to merge?

**Pull request merged**
