### PR TITLE
Spec: bump and document timeouts in interpreted mode

### PR DESCRIPTION
**Pull request by asterite**

### CODE REVIEW

**Review by sdogruyol — APPROVED** [review]
Thank you @asterite 🙏

**Comment by HertzDevil** [comment]
The master CI run for this very PR times out despite the increased `schedule_timeout` duration: https://github.com/crystal-lang/crystal/runs/8117747560?check_suite_focus=true

**Comment by asterite** [comment]
Interesting! Then probably there's a something wrong with the interpreter that makes a fiber get stuck or something. It's also interesting to that other specs continue to run fine.

**Comment by asterite** [comment]
Is there a way to make CI not consider interepeter spec failures as failing the entire PR? That is, I think the interpreter is a "nice to have" at this point, not something that required to work on releases.

**Comment by straight-shoota** [comment]
No. GitHub Actions can't to that.

**Pull request merged**
