### PR TITLE
 StaticArray/Array improvements (map_with_index!) 2

### PR DESCRIPTION
**Pull request by Nephos**
cf: #3356 
(misusage of git on my side, I had to recreate a new PR, my bad)

Aims: have map_with_index! in the StaticArray

### CODE REVIEW

**Comment by oprypin** [comment]
I don't understand, why is `StaticArray` so special that you're making it the only class that has `map_with_index!`?

**Comment by mverzilli** [comment]
It should be `map_with_index` (without `!`), right?

**Comment by mverzilli** [comment]
Nevermind, I got confused. It's with `!` because it ends up calling `to_unsafe.map!`, which mutates. @oprypin  are you objecting against this PR not including a `map_with_index!` for the common `Array`?

**Comment by Nephos** [comment]
It would be cool to have map_with_index! in the Array too

**Comment by mverzilli** [comment]
Cool! Would you add `map_with_index!` to `Array` then?

**Comment by Nephos** [comment]
Anything else that should be added / changed ?

**Comment by mverzilli** [comment]
No, looks good to me! Thank you!

**Comment by bcardiff** [comment]
Since map! is actually implemented in Pointer, why not implement there the logic and let StaticArray forward the call as in map!

Also, in Array#map_with_index! I think there should be no U, just T, since it is an inplace replacement. Forcing a T in the block will give a different and clearer error message.

**Comment by Nephos** [comment]
You're right ! I fix that.

**Comment by bew** [comment]
In `StaticArray#map_with_index!`, `Pointer#map_with_index!` & `Array#map_with_index!` the `yield` keywork should be replaced by `block.call` IMO.
Or remove the `block` parameter, and use only `yield` ?

We shouldn't mix named block & yield.

**Comment by RX14** [comment]
The block parameter is only used as documentation for the block types. Using block.call instead of yield will be uglier and perform much much worse.

**Comment by bew** [comment]
I see, for `Pointer#map_with_index!` the `block` argument has no documentation, but is still there though.

**Pull request merged**
