### PR TITLE
Add support for max + min intrinsics

### PR DESCRIPTION
**Pull request by wmoxam**
LLVM support is now sufficiently updated to support these.

### CODE REVIEW

**Comment by wmoxam** [comment]
The LLVM [binary operations](https://github.com/wmoxam/crystal/blob/04e8bcf9c20dc4bfb47a0c7847e56e79a1fa1033/src/math/libm.cr#L6-L13) should be usable now too but commented out code for them seems invalid. I don't understand how they can be called.

**Comment by RX14** [comment]
This depends on https://github.com/crystal-lang/crystal/pull/4396, and this change was also discussed there.

**Comment by wmoxam** [comment]
@RX14 Oh, I was totally under the impression that was done a while back 😅

**Comment by wmoxam** [comment]
#4396 was merged as part of #4821, should be safe to merge this now

**Comment by RX14** [comment]
@wmoxam thanks for the ping!

**Pull request merged**
