### PR TITLE
Crypto::MD5 also allow Slice(UInt8)

### PR DESCRIPTION
**Pull request by will**
I was also thinking of a 

```cr
MD5.hex_digest do |c|
  c << "data"
  c << "more data"
end
```

form, but since the context is a struct that doesn't work, and it's probably not worth making classes.

### CODE REVIEW

**Comment by asterite** [comment]
I think we could allow the block form by having a Context class that would wrap the Context struct, to allow mutation.

**Comment by will** [comment]
Since blocks with yield are inlined, I was actually a bit surprised that it didn't just work. Do you do something special to keep the cant-mutate-structs semantics consistent?

**Comment by asterite** [comment]
The problem is that when you yield the context, it's passed by value, so a copy is passed. The copy is accessible via the block argument. You mutate the block argument (invoking methods on a struct mutate it, they are only copied when passed around) but those mutations are not seen in the original struct:

```crystal
ctx = Context.new
yield ctx # here we are passing a copy
ctx # the original was never modified
```

The compiler doesn't keep track of this, the only thing the codegen does is to copy a struct's value when you pass it around (pass to a call, assign to a variable, return from a function, yielded).

**Comment by will** [comment]
I understand that from how if it was calling other code it'd be a copy, but on  http://crystal-lang.org/docs/syntax_and_semantics/blocks_and_procs.html#performance it says that
```
def twice
  yield 1
  yield 2
end

twice do |i|
  puts "Got: #{i}"
end
```
is exactly the same as
```
i = 1
puts "Got: #{i}"
i = 2
puts "Got: #{i}"
```

so wouldn’t
```
def md5
ctx = Context.new
yield ctx # here we are passing a copy
ctx # the original was never modified
end

md5 do |ctx|
  ctx << data
end
```

be exactly the same as
```
ctx = Context.new
ctx < data
ctx 
end
```

**Comment by asterite** [comment]
Oh, I see. Maybe the docs should change or should mention that a copy is actually made. For ints this is transparent so the problem can't be seen.

In any case, even if we improve this, someone might do:

```crystal
md5 do |ctx|
  helper(ctx)
end
```

and then a copy will be made, and it will be very unintuitive. That's why maybe a class in this case would be much better and will never fail.

**Comment by asterite** [comment]
@will I just see that you updated the PR. I'll merge this. Thanks! :-)

**Pull request merged**
