### PR TITLE
Add .editorconfig template on crystal init command.

### PR DESCRIPTION
**Pull request by akzhan**
Settings based on https://github.com/crystal-lang/crystal/blob/master/.editorconfig.

Refs #297.

### CODE REVIEW

**Comment by asterite** [comment]
This project (Crystal) uses this editor configuration, but other Crystal projects are free to use whatever configuration they want. I don't think this should be included in every Crystal project.

**Comment by oprypin** [comment]
Are other Crystal projects not free to use a different license?

**Comment by akzhan** [comment]
@asterite this .editorconfig just follow crystal language convention at all. Like `crystal tool format` one.

No one requires to use it, but it is fine defaults.

**Comment by RX14** [comment]
I think including an editorconfig file is a good default, just like the gitignore and license we include.

**Comment by asterite** [comment]
OK, sorry, I shouldn't have closed this. Have someone else decide :-)

**Comment by mverzilli** [comment]
Thanks!

**Pull request merged**
