### PR TITLE
Optimize BitArray#fill

### PR DESCRIPTION
**Pull request by RespiteSage**
## Purpose
This PR optimizes `BitArray#fill` by adding a specialized method in `bit_array.cr` that fills the `@bits` pointer directly instead of changing every bit individually like the `Indexable::Mutable#fill` implementation does. I also added a spec for the specialized method.

## Performance
I've benchmarked this on my own machine, using [this code](https://gist.github.com/RespiteSage/95b0182a9fa6d9961766faa6ef8faf4a), and in all my tests this method was ~300 times faster than the existing implementation (which makes sense, really).

## Notes
I suspect that there may be a bit of room for improvement but that I'm missing some information that would show me how to reach it. I did test whether replacing `(value ? ~0u8 : 0u8)` with `(value.to_unsafe << 8)` would make any difference, but they came out to about the same speed on average, so I went with the solution I thought was more readable.

### CODE REVIEW

**Comment by Blacksmoke16** [comment]
Duplicate of https://github.com/crystal-lang/crystal/pull/11450?

**Comment by RespiteSage** [comment]
Ah... Darnit. I thought I'd searched sufficiently before making a PR.

That said, in my testing my solution was about twice as fast as the solution in #11450, which I tried. So maybe the solution is to close this PR and speed up #11450 using `Intrinsics.memset`? @HertzDevil, what do you think?

**Comment by HertzDevil** [comment]
This one is incorrect. If `value` is true and `size` is not a multiple of 8 then the trailing bits _must_ be cleared. This explains the performance difference between the two implementations.

Also the `#fill(value, start, count)` and `#fill(value, range)` overloads are not optimized here.

**Comment by RespiteSage** [comment]
Okay, I see. I hadn't seen that `BitArray#to_slice` makes a `Slice(UInt8)`. Also, the clearing makes sense as the cause of the time difference. I look forward to having #11450 in a release.

**Pull request closed without merging**
