### PR TITLE
Restore []? as a valid macro name

### PR DESCRIPTION
**Pull request by xxkb**
Restores the ability to define `[]?` as a macro. Support appears to have been dropped via https://github.com/crystal-lang/crystal/pull/10069.

No strong argument exsists for why this operator should be disallowed in either that PR, or the issue it addressed (#10022). Unfortunately GitHub code search does not allow searching for those characters so it's hard to gauge impact elsewhere, however as an immediate example: https://github.com/spider-gazelle/secrets-env/issues/3.

### CODE REVIEW

**Review by straight-shoota — APPROVED** [review]

**Comment by asterite** [comment]
In fact, I would revert the entirety of #10069

You can always do `Foo.+(...)` or `Foo.<<(...)` to call a macro named that way.

Why are we restricting these things? Is there any harm in allowing the above?

**Comment by straight-shoota** [comment]
Not entirely. #10022 has some examples that really shouldn't be allowed.

**Comment by bcardiff** [comment]
The rejection of a receiver on #10069 make sense to me. Regarding the macro names for setters-like the issue was described in #10022. The operators and `[]?` macro names I think can be restored, yes.

**Comment by bcardiff** [comment]
@KimBurgess do you want to handle the restoration of the other operators as macro names in this PR to revert  #10069 partially? cc: @HertzDevil because maybe we are missing something else from that change.

**Comment by KimBurgess** [comment]
Sure thing. If I don't get a chance today (AU time), I'll amend early next week.

If there's time sensitivity related to the 0.36.1 release, let me know and I'll take a look a little sooner.

**Comment by bcardiff** [comment]
I think this is good enough for 0.36.1. But if we get the operators would be great. Otherwise those will come later. I would expect 0.36.1 to me closed by mon/tue. But again, i think this is enough for it.

**Comment by asterite** [comment]
I can also try to send a PR this weekend

**Comment by asterite** [comment]
Closed in favor of #10338

**Pull request closed without merging**
