### PR TITLE
Docs: Fix matching nested type references in markdown renderer

### LINKED ISSUE #5293: Definitions in docs not linked properly
`Iterator::Stop::INSTANCE` gets incorrectly linked to `Iterator::Stop`, as seen
for instance in https://crystal-lang.org/api/0.23.1/Iterator.html#stop-instance-method.

### PR DESCRIPTION
**Pull request by straight-shoota**
Closes #5293

### CODE REVIEW

**Comment by RX14** [comment]
Is there a spece where this could be specced?

**Comment by straight-shoota** [comment]
Unfortunately not, at least I couldn't find any. That's why I created #5309

**Comment by RX14** [comment]
@straight-shoota yeah I saw that right after this issue. Why not just create a place?

**Comment by straight-shoota** [comment]
I couldn't see an easy way to test just that change so I figured it would be to much to bootstrap a docs generator test setup just for this small fix.
Maybe it could also help to put some thought into how these specs should be laid out.

**Comment by RX14** [comment]
Hmm, ok.

**Comment by Sija** [comment]
Will it merge?

**Comment by RX14** [comment]
@Sija hopefully, although I do need someone to agree with me.

**Pull request merged**
