### PR TITLE
Changed IO.read_line to return String rather than String?

### LINKED ISSUE #4920: Shouldn't IO.read_line return "String" rather than "String?"
The function either returns string read from input or throws, so most probably the result cannot contain nil.

Current implementation from Crystal 0.23.1:
```
  def read_line(*args, **options) : String?
    gets(*args, **options) || raise EOFError.new
  end

```

### PR DESCRIPTION
**Pull request by Sija**
Fixes #4920

### CODE REVIEW

**Comment by RX14** [comment]
Just an entirely offtopic comment: I don't think forwarding argument using `*args, **options` is a good pattern because it makes the documentation suck. Perhaps we should try to remove this all over the stdlib?

**Comment by bew** [comment]
RX14 I don't agree, I think that forwarding arguments is good, what needs a fix is the documentation generation.
Maybe the `crystal doc` could detect the arguments forwarding? Or we could add a mention about it in the docs, like `:arg_forwarding: gets`, to mark the method as forwarding its arguments to `gets`, and allow `crystal doc` to generate the proper documentation?

**Comment by asterite** [comment]
@RX14 I also agree with you regarding the ugly docs, but `gets` has several overloads.

**Comment by jhass** [comment]
Thanks!

**Comment by oprypin** [comment]
@jhass Please note that you seem to be the only one who creates merge commits when merging pull requests. Maybe worth switching to the squash/rebase kind of merge in the UI, just for consistency's sake.

**Comment by jhass** [comment]
Oh sorry, I didn't notice we switched to that here, will make sure in the future. Personally I like the merge commit for a pull request though, as it keeps an easy reference to it.

**Comment by RX14** [comment]
@jhass Github's UI will usually show the PR a commit arrived in regardless of how it was merged.

**Comment by jhass** [comment]
Yes, if you're on Github, which is not always the case ☺

**Pull request merged**
