### PR TITLE
Openssl updates

### PR DESCRIPTION
**Pull request by plukevdh**
Opening this up to give some visibility.

@datanoise this is mostly code from you, I'm just turning it into a more up-to-date PR that matches current progress in the stdlib. A :+1: or :-1: would be awesome.

All others, feel free to help or give feedback. Slow in coming as I've hit a few oddities with OpenSSL (which oddly enough also exist in the Ruby OpenSSL stdlib). At least it's consistent :grimacing:

### CODE REVIEW

**Comment by ysbaddaden** [comment]
If I recall correctly we weren't sure about adding those classes, because there are lots of digest methods; they may not all be available in the compiled OpenSSL; why have some classes for some digests but not others; ... Having a single interface for all digests sounded better.

**Comment by plukevdh** [comment]
@ysbaddaden I can get behind that.

**Comment by plukevdh** [comment]
I guess a question here, what min-version of OpenSSL are we looking to support?

**Comment by plukevdh** [comment]
This is ready to go with the exception of the build failure due to out of date OpenSSL on the "no arch" build. I'd appreciate feedback and some guidance on the `require` convention for these kinds of libraries. Lots of things requiring similar things. Not sure how to approach it in the sense of whether to push people to just `require "openssl"` or be able to piecemeal it.

**Comment by plukevdh** [comment]
This was tested locally against `OpenSSL 1.0.2f  28 Jan 2016`. Not sure what CI is running.

**Comment by plukevdh** [comment]
Also, unrelated (but maybe related?) `make spec` fails for me with:

```
make spec
./bin/crystal build  -o .build/all_spec spec/all_spec.cr
Using compiled compiler at .build/crystal
Error: execution of command failed with code: 127: `cc -o ".build/all_spec" "${@}"  -rdynamic  -lxml2 -lssl -lz -lcrypto -lreadline -lgmp -lyaml /Users/plukevdh/src/Articulate/tooling/vendor/crystal/src/llvm/ext/llvm_ext.o `(llvm-config-3.6 --libs --system-libs --ldflags 2> /dev/null) || (llvm-config-3.5 --libs --system-libs --ldflags 2> /dev/null) || (llvm-config --libs --system-libs --ldflags 2>/dev/null)` -lstdc++ /Users/plukevdh/src/Articulate/tooling/vendor/crystal/src/ext/libcrystal.a -levent -lpcre -liconv -lgc -lpthread -ldl`
make: *** [.build/all_spec] Error 127
```

I can successfully run `./bin/crystal spec` though.

**Comment by ysbaddaden** [comment]
I believe TravisCI uses Ubuntu Precise. Only the upcoming Xenial supports OpenSSL 1.0.2f. Trusty only has 1.0.1f and I don't know for Precise.

**Comment by ysbaddaden** [comment]
Errata: the build fails on OSX. I believe this is Maverick, I don't know which OpenSSL version is installed.

**Comment by plukevdh** [comment]
From my install, it's definitely an old one. Not sure how old off hand though I can check this tomorrow. Are we wanting to support vanilla install or push for adoption of newer OpenSSL?

**Comment by plukevdh** [comment]
After unlinking homebrew's verison, the default OSX install is `OpenSSL 0.9.8zg 14 July 2015`

**Comment by jeromegn** [comment]
I was about to send in a PR with less OpenSSL ported from @datanoise and added ssl methods on HTTP::Client. But now that I see this, it looks far more complete.

Should I wait until we fix this or send in my smaller PR? (mine just adds 2 LibSSL functions and 2 SSL methods: `TLSv1` and `SSLv3`, but it does add some stuff to HTTP::Client.)

**Comment by asterite** [comment]
@jeromegn I would send multiple small PRs (or: I would start with one, wait for it to be merged, send another one, etc.). Huge PRs like this are very hard to review and take a lot of time. If the PR is small and focused it has many more changes to be merged. Thank you! :-)

**Comment by miketheman** [comment]
#triage 
This appears to have stalled, CI failed, and is no longer mergable.
The efforts undertaken in previously linked PRs, and @ysbaddaden appears to have become the defacto leader on OpenSSL-in-Crystal.

Should this PR remain open? Is there any value?

**Comment by ysbaddaden** [comment]
This PR still does a lot more than we integrated with @jhass, most notably generate/sign/validate with DSA/RSA keys. Right now we mostly only have what was required for a (hopefully) secure TLS communication (sockets, contexts) and validation (SNI, hostname).

It needs a rebase and clean commits. If someone is courageous enough to work on this.

**Comment by vegai** [comment]
Headsup.

I merged this to my branch and rebased it against master. See https://github.com/crystal-lang/crystal/compare/master...discord-tech:openssl-updates-from-2180

Needs a bit of work still, all the merged specs don't work anymore. I'll make a PR a bit later if I get things to work at least a bit. I don't have extensive openssl knowledge, so any PR I make needs to be scrutinized rather well.

**Comment by akzhan** [comment]
Will glad to see updated PR from you @vegai

**Comment by asterite** [comment]
Closing because it's not mergeable. Please send small individual PRs so we can more easily review them.

**Pull request closed without merging**
