### PR TITLE
 Don't merge proc types but allow assigning them if they are compatible

### LINKED ISSUE #9935: segmentation fault using procs in crystal 0.35.1
Rather interestingly, deleting some of the code here (block for bug0, bug1) will cause the crash to disappear.

```
Crystal 0.35.1 [5999ae29b] (2020-06-19)

LLVM: 8.0.0
Default target: x86_64-unknown-linux-gnu
```
Fedora 33

```crystal
require "option_parser"

thunk = nil
parser = OptionParser.new do |parser|
  parser.on("bug0", "") do
    parser.unknown_args do |args|
      thunk = ->do
        Process::Status.new(0)
      end
    end
  end

  parser.on("bug1", "") do
    parser.unknown_args do |args|
      thunk = ->do
      end
    end
  end

  parser.on("bug", "") do
    parser.unknown_args do |_, after_dash|
      thunk = ->do
        Process.exec("ls", after_dash)
      end
      puts thunk
      puts "never get here"
    end
  end
end

parser.parse
```

```
$ crystal run bug.cr -- bug -- hi
Invalid memory access (signal 11) at address 0x39a00000001
[0x4614e6] *Exception::CallStack::print_backtrace:Int32 +118
[0x4543c5] __crystal_sigfault_handler +341
```

### PR DESCRIPTION
**Pull request by asterite**
Fixes #9935

The idea is that if we have two variables, one of type `Proc(T, U)` and another one of type `Proc(T, NoReturn)` we **don't** merge them to be of type `Proc(T, U)`. It will always form a union now.

However, assigning a Proc that returns `NoReturn` to a Proc that returns a value is valid:

```crystal
class Foo
  @x : -> Int32

  def initialize
    @x = ->{ raise "OH NO" } # This compiles just fine. Value can't be extracted anyway...
  end
end

Foo.new.x
```

We are already doing something similar with `Proc(T, Nil)` and `Proc(T, U)`:

```crystal
class Foo
  @block : -> Nil

  def initialize
    @block = ->{ 1 } # This is fine! Value is ignored.
  end

  def block
    @block
  end
end

Foo.new.block
```

I also changed the code for the latter case to be a bit more explicit.

### CODE REVIEW

**Review by straight-shoota — APPROVED** [review]

**Comment by bcardiff** [comment]
I don't get the difference between disallowing the union between two values but allowing the asignment of a `Proc(T, NoReturn)` value to a `Proc(T, R)`. Or the assignment only works for literal proc, and the literal is treated as a `Proc(T, R)` instead of a `Proc(T, NoReturn)`?

Since this is semantic change, I think specs should be added 🙈

**Comment by asterite** [comment]
> Since this is semantic change, I think specs should be added

Good point. There's a spec that said that assigning a Proc that returns NoReturn to a Proc that returns U compiles and runs fine. That spec still passes. That was the original idea when I merged the proc types to avoid forming a union. I'll add a spec, though, to verify that a union is indeed formed.

**Comment by asterite** [comment]
> I don't get the difference between disallowing the union between two values but allowing the asignment of a Proc(T, NoReturn) value to a Proc(T, R)

Avoiding forming a union (merging the types into one) is problematic when there are more types involved. See https://github.com/crystal-lang/crystal/issues/9935#issuecomment-731078855

**Comment by asterite** [comment]
Just added a spec.

**Comment by asterite** [comment]
And this is the spec that we care about:

https://github.com/crystal-lang/crystal/blob/219e1a871916c4dca4ee9be02f085d4d8344ac9a/spec/compiler/semantic/proc_spec.cr#L862-L882

**Comment by bcardiff** [comment]
I'm still hesitant with this change. 

It makes total sense that `Proc(T, NoReturn) < Proc(T, R)`. And `Union(NoReturn, R) = R` is sound also.

I think it will introduce noise to allow values of type `Union(Proc(T, NoReturn), Proc(T, R))`. 

All procs can raise when executing. If the problem is memory representation, the fix should affect only the memory representation, not the typing rules. 

Any `Proc(T, NoReturn)` value should be assignable to a `Proc(T, R)`. Maybe what we are missing a conversion when that assignment happens.

**Comment by asterite** [comment]
@bcardiff say you have an array with three elements: a proc that returns Int32, a proc that returns Float64, and a proc that returns NoReturn. If you ask for the third elements in the array and print it's `class`, what output do you expect?

**Comment by bcardiff** [comment]
I would expect the `class` to be `Proc(T, NoReturn)` but the typeof to be `Proc(T, Int32) | Proc(T, Float32)` due to the context.

**Comment by asterite** [comment]
Well, that's the problem. When `Proc(T, Int32)` is merged with `Proc(T, NoReturn)` into `Proc(T, Int32)`, you are left with a value that doesn't know which type it is: a `Proc` doesn't know what type it is (similar to structs, and unlike classes who do have their type ID behind the pointer).

That's why I think merging two types into a single type and losing that type information is a big NO.

Could you try this patch in the ecosystem? I feel like nothing will break, and this PR actually fixes an existing issue.

**Comment by bcardiff** [comment]
I see, the lack of runtime type information is preventing us to implement a subtyping rule while preserving the original type then.

I think I prefer almost any other path:

* return `Proc(T, Int32)` or `Proc(T, Float32)` as `.class` result
* add type_id to proc representation 🙊 .

I feel we are loosing formality with this change. Or maybe I need to adjust my mental model to cover this case.

I will validate the PR with test-ecosystem once the github action outage is over probably.

**Comment by asterite** [comment]
I just don't think there's any use case in merging the types. And, as I said, I made this rule to allow assigning or passing a NoReturn proc to a T proc, and that's still possible with this PR. The gain (if any) of doing it another way isn't matched by the effort required to do so.

**Comment by bcardiff** [comment]
> The gain (if any) of doing it another way isn't matched by the effort required to do so.

I think this argument is a slippery slope.

---

With struct, we have that concrete types don't have type_id, but when assigning them to an (abstract) base class it is treated as a union and type id appears.

But this is possible because only abstract structs can be extended, which is not the case for Proc. That is where it gets more complicated.

---

test-ecosystem didn't complain, and neither some convoluted experiments I tried.

Feel free to merge if nobody else shares my discomfort 😅.

**Comment by asterite** [comment]
Let's merge it. We can always improve it later without a breaking change.

**Pull request merged**
