### PR TITLE
AArch64 support (ARMv8-A)

### PR DESCRIPTION
**Pull request by ysbaddaden**
Initial AArch64 port, aka ARM64, aka ARMv8-A.

- [x] ABI: please review, it's based on [rust](https://github.com/rust-lang/rust/blob/master/src/librustc_trans/cabi_aarch64.rs)
- [x] fiber context switch, based on [d runtime](https://github.com/ldc-developers/druntime/blob/ldc/src/core/threadasm.S)
- [x] unwind support (damn easy this time)
  - [x] can raise in `spawn` (fiber context switch corrupts the callstack)
- [x] libxml2: failed to raise (missing unwind tables)
- [x] `llvm.readcyclecounter` segfaults on Cortex A53/A57 CPUs as [previously reported](https://github.com/crystal-lang/crystal/pull/3424#issuecomment-256329740) —maybe we'd like to seed `Random` from `/dev/urandom`?
- [x] C bindings for `aarch64-unknown-linux-gnu` target
- [x] green std specs:
  - [x] BigFloat specs segfault or hang forever
  - [x] segfault (gc -> yaml_delete -> segfault)
  - [x] 1 failure: `HTTP generates RFC1123 with local time zone` ~~(certainly a VM misconfiguration)~~ DST issue.

~~Note: I can't link my [posix](https://github.com/ysbaddaden/) project in my QEMU machine because `ld` segfaults... I'll investigate later. In the meantime it's probable the C bindings aren't exact, which may explain some crashes, or maybe the ABI is faulty.~~ ABI fixed, libyaml bindings fixed, but it segfaults because of infinite `clang_visitChildren` recursive calls. Not investigated.

Please review!

### CODE REVIEW

**Comment by ysbaddaden** [comment]
Down to a single bug! and most certainly because of a VM time misconfiguration.

```
$ ./std_spec

Finished in 2:18 minutes
3474 examples, 1 failures, 0 errors, 1 pending

  1) HTTP generates RFC1123 with local time zone

       expected: "Sun, 06 Nov 1994 06:49:37 GMT"
            got: "Sun, 06 Nov 1994 07:49:37 GMT"
```
@asterite merge?

**Comment by keplersj** [comment]
@ysbaddaden That bug was happening on Travis a few days ago as well. I wouldn't worry about it.

**Comment by asterite** [comment]
I already fixed that bug in master, the spec was buggy (it broke because of DST changes)

**Comment by ysbaddaden** [comment]
What the hell? Homebrew is distributing LLVM *without* the AArch64 target :sob: 

https://github.com/Homebrew/homebrew-core/blob/master/Formula/llvm.rb#L139

**Comment by ysbaddaden** [comment]
@asterite since LLVM targets can be missing, I made them optional in Crystal, too. We now have a `LLVM::BUILT_TARGETS` constant, run target ABI specs only when the target is available, and raise an exception at runtime when trying to use a target that isn't available. It fixed the Travis issue.

**Comment by asterite** [comment]
@ysbaddaden Nice! I'm happy to see that you was able to solve this with a macro :-)

**Comment by ysbaddaden** [comment]
So, merge?

**Comment by asterite** [comment]
@ysbaddaden Whenever you are ready :-)

**Pull request merged**
