### PR TITLE
Support to_yaml in YAML.mapping generated classes

### PR DESCRIPTION
**Pull request by maxpowa**
Allows `to_yaml` on classes generated through `YAML.mapping`, prior to this patch you'd get an error as demonstrated [here](https://carc.in/#/r/1ecy).

### CODE REVIEW

**Comment by asterite** [comment]
@maxpowa Looks good, thank you! Do you want to add a spec too?

**Comment by RX14** [comment]
AFAIK @maxpowa is currently working on specs and supporting converters etc.

**Comment by maxpowa** [comment]
@RX14 is correct, I'm working on converters/emit_null etc - essentially to support what JSON supports.

**Comment by maxpowa** [comment]
Added support for converters, `emit_null` will take a bit more work - I'm going to put it in another PR since it also requires support from the parser, right now the parser doesn't appear to support YAML's null (`null | ~`).

**Pull request merged**
