### PR TITLE
Compiler: add a few missing `expanded.transform self`

### LINKED ISSUE #9439: $? $~ don't seem to work on Windows
Following from #9348, which exposes the fact that some language constructs don't codegen correctly on Windows, one can see that usages of "special vars" `$?` `$~` fail to compile.

This is a minimal code sample that, like the specs, also produces the error below:

```crystal
def foo(z)
  $~ = 1
end
foo(2)
p $~
```

If someone wants to look into this, the starting point (also assumes that you have #9348 merged / checked out) would be this diff:
*(certainly wasn't easy to find even this, because normally the nil assertion gives you no info whatsoever where it's coming from without stack traces)*

<details><summary>Click to see <b>diff</b></summary>

```patch
diff --git a/src/compiler/crystal/codegen/codegen.cr b/src/compiler/crystal/codegen/codegen.cr
index 09eef8806..d19c0d42d 100644
--- a/src/compiler/crystal/codegen/codegen.cr
+++ b/src/compiler/crystal/codegen/codegen.cr
@@ -1342,7 +1342,7 @@ module Crystal
       obj_type = node.obj.type
 
       type_id = type_id @last, obj_type
-      filtered_type = yield(obj_type).not_nil!
+      filtered_type = yield(obj_type) || raise "BUG: filtering #{obj_type} #{node} produced nil"
 
       @last = match_type_id obj_type, filtered_type, type_id
 
diff --git a/spec/compiler/codegen/special_vars_spec.cr b/spec/compiler/codegen/special_vars_spec.cr
index 14323c96d..280da6caa 100644
--- a/spec/compiler/codegen/special_vars_spec.cr
+++ b/spec/compiler/codegen/special_vars_spec.cr
@@ -2,7 +2,7 @@ require "../../spec_helper"
 
 describe "Codegen: special vars" do
   ["$~", "$?"].each do |name|
-    pending_win32 "codegens #{name}" do
+    it "codegens #{name}" do
       run(%(
         class Object; def not_nil!; self; end; end
 
@@ -15,7 +15,7 @@ describe "Codegen: special vars" do
         )).to_string.should eq("hey")
     end
 
-    pending_win32 "codegens #{name} with nilable (1)" do
+    it "codegens #{name} with nilable (1)" do
       run(%(
         require "prelude"
 
@@ -35,7 +35,7 @@ describe "Codegen: special vars" do
         )).to_string.should eq("ouch")
     end
 
-    pending_win32 "codegens #{name} with nilable (2)" do
+    it "codegens #{name} with nilable (2)" do
       run(%(
         require "prelude"
 
@@ -74,7 +74,7 @@ describe "Codegen: special vars" do
       )).to_string.should eq("hey")
   end
 
-  pending_win32 "works lazily" do
+  it "works lazily" do
     run(%(
       require "prelude"
 
@@ -145,7 +145,7 @@ describe "Codegen: special vars" do
       )).to_string.should eq("hey")
   end
 
-  pending_win32 "codegens after block" do
+  it "codegens after block" do
     run(%(
       require "prelude"
 
```

</details>

```cmd
> crystal spec spec\compiler\codegen\special_vars_spec.cr -Di_know_what_im_doing -Dwithout_playground
...
BUG: filtering NilAssertionError _.responds_to?(:finalize) produced nil (Exception)
...
```

### PR DESCRIPTION
**Pull request by asterite**
Fixes #9439

Sorry that there are no tests, I couldn't find an easy way to make a test that exposes these missing things.

@oprypin Can you confirm that this actually fixes the issue?

### CODE REVIEW

**Comment by jhass** [comment]
Mmh, actually it seems to break everything? 😅

**Comment by asterite** [comment]
I should have only done it for Global.

**Comment by asterite** [comment]
I was in a rush and I added an extra `transform self` that was needed 😊 

I think this should work.

By the way, I'm doing these almost blindly because when I compile the compiler and then try to compile anything I get "illegal instruction". Probably something related to my set-up.

**Comment by oprypin** [comment]
Thanks, yes, I confirm this fixes #9439, and makes that example pass on Windows, and also fixes corresponding specs.
https://github.com/oprypin/crystal/commits/bda74c7bb909f991ac0cc3f10c977c7cacfbf630
(the specs can't be "enabled" as part of this PR yet because they haven't been declared to be pending yet, in #9348).
But I'm having some trouble getting CI to pass as well -- some new unrelated problem in GH Actions build environment.

**Comment by oprypin** [comment]
*Now* it is possible to enable those specs, by merging master and cherry-picking b91a3e5f77506762a44dd7d26b421a5cfdb17bf3. E.g.

```shell
git pull origin master
git fetch https://github.com/oprypin/crystal b91a3e5f77506762a44dd7d26b421a5cfdb17bf3
git cherry-pick FETCH_HEAD
```

**Pull request merged**
