### PR TITLE
Set the Content-length when HTTP body is IO::Memory

### PR DESCRIPTION
**Pull request by carlhoerberg**

### CODE REVIEW

**Comment by straight-shoota** [comment]
Can you please give some context for this change? Doesn't this already work? `HTTP.serialize_headers_and_body` should take care of setting an approriate header.

I doubt this implementation is good. If I assign an empty IO and later append to it, the content length is incorrect.

**Comment by bcardiff** [comment]
@carlhoerberg are you trying to prevent the chunked encoding when a `IO::Memory` has the payload?

As @straight-shoota mentioned if this PR would lead to invalid content-length. So far setting the body with `String` or `Bytes`/`Slice` has the semantics that the body is all set. While setting an `IO` leads to chunked encoding.

If we set the content-length during `serialize_headers_and_body` to allow a chance to fill the IO, then we will need to introduce some way to state that chunked encoded is preferred if possible. (See the current logic in `serialize_headers_and_body`)

If in your usecase the `IO::Memory` is already filled, `req.body = io.to_slice` can be used and will set the content-length without duplicating memory. The underlying buffer of the `IO::Memory` will be reused.

Unfortunately the `IO::Memory` has not notion of closed for writtes, if that would be so, then we could safely choose if it's possible to set the content-length from the current buffer content.

**Comment by asterite** [comment]
What if in `serialize_headers_and_body`, if we have an IO and that IO is `IO::Memory` we just take a slice of it and write that to the underlying IO? But note that we have to be careful to do this correctly: the `IO::Memory` might have a `pos` different than zero (maybe).

**Comment by asterite** [comment]
I'm thinking that a lot of operations could "peek" into the underlying IO. For example `IO.copy` could check if the src is an IO::Memory, then write all the slice directly in one go.

**Comment by bcardiff** [comment]
IO are streams. Probably any intent to use them as a whole value will lead to confusion. Since String and Bytes are values defined as a whole, and the IO created there are owned by the request the api make sense to me.

I don't think is right to read the whole buffer to `IO::Memory`. Its current position should be used (and advanced) if there are optimization for `IO.copy`.

**Comment by carlhoerberg** [comment]
Ok, when's `HTTP.serialize_headers_and_body` run, after the `before_request` callback?  because this code: 
```crystal
require "http/client"
body = IO::Memory.new("aaaa")
http = HTTP::Client.new "localhost", 80
http.before_request do |r|
  pp r
end
http.post "/", body: body
```

outputs:
```
#<HTTP::Request:0x7f7137b4bf00
 @body=
  #<IO::Memory:0x7f7137b48ea0
   @buffer=Pointer(UInt8)@0x6639bc,
   @bytesize=4,
   @capacity=4,
   @closed=false,
   @decoder=nil,
   @encoder=nil,
   @encoding=nil,
   @pos=0,
   @resizeable=false,
   @writeable=false>,
 @cookies=nil,
 @headers=
  HTTP::Headers{"Accept-Encoding" => "gzip, deflate",
   "Host" => "localhost",
   "User-Agent" => "Crystal"},
 @method="POST",
 @query_params=nil,
 @remote_address=nil,
 @resource="/",
 @uri=nil,
 @version="HTTP/1.1">
```

**Comment by asterite** [comment]
`before_request` runs before `HTTP.serialize_headers_and_body` because that's when the request is actually "executed".

Maybe you could describe what you are trying to do and why the current code doesn't work for you?

For reference: https://en.wikipedia.org/wiki/XY_problem

**Comment by carlhoerberg** [comment]
You're right, pos has to be take in consideration, and yes, the IO::Memory can change between it's assigned and it's being sent. But at the time of serialization chunked encoding shouldn't be needed for IO::Memory, the size should be known at constant at that stage.

**Comment by bcardiff** [comment]
If you use `body.to_slice` you will have the content-length set and the buffer is not duplicated on runtime.

```cr
require "http/client"
body = IO::Memory.new("aaaa")
http = HTTP::Client.new "localhost", 80
http.before_request do |r|
  pp r
end
http.post "/", body: body.to_slice # <- here
```

**Comment by carlhoerberg** [comment]
Was posting to webserver (a AWS API) that didn't support keepalive when transfer encoding chunked was used, so pulled this one fast. But yes, it got several flaws in its current form. Don't know if it's worth working on, even though it can be done.

**Comment by carlhoerberg** [comment]
But then that slice will be wrapped in another io::memory, right? not optimal but i guess it's cheap enough.

**Comment by carlhoerberg** [comment]
With the latest commit problem is that the content-length still isn't available at `before_request`, which some middlewares, that eg. calculate authentication depeding on request headers, require. So nevermind, closing this

**Comment by bcardiff** [comment]
> But then that slice will be wrapped in another io::memory, right? not optimal but i guess it's cheap enough. 

I think it's cheap enough. Another alternative would be to allow the body to be directly IO | String | Slice. That would reduce allocating the intermediate IO::Memory. Maybe it would be worth in super heavy load, I'm not sure.

**Pull request closed without merging**
