### PR TITLE
Improve the syntax of some if blocks to one line

### PR DESCRIPTION
**Pull request by j8r**
Change some if blocks to one-liners and other minor syntax improvements.

### CODE REVIEW

**Comment by straight-shoota** [comment]
If these edits are really an improvement is highly questionable. Some perhaps, others probably not.

Many changes are purely about style and most of the trailing ifs don't improve readability at all. Neither are early returns always useful.
I don't think it makes any sense to merge this until there is a proper style guide.

**Comment by j8r** [comment]
We don't have to keep all this modiifcations, but some obsiously improve the readability, like replacing

```crystal
if true
  this
else
  that
end
```

by
```crystal
return this if true
that
```

and 

```crystal
if true
  this
end
```
by

```crystal
this if true
```

**Comment by straight-shoota** [comment]
No, I don't think these replacements are particularly improving readability. In some places, maybe. But not in general.

**Comment by Sija** [comment]
Like @straight-shoota said, many even exceed standard line width of 80 characters.

**Comment by j8r** [comment]
80 characters like PEP8?

If everyone agrees, I will start playing with the formatter to change little conditions blocks that have less than 80 characters to to one-liners.

**Comment by j8r** [comment]
Can we consider at least to transform little conditions to one-liners? This is of course not possible when we do variable affectations inside the condition. Maybe it is possible to do it with the formatter.

**Comment by j8r** [comment]
Ok LGTM I will look at the formatter to improve it. By the way I think there should have a rule for this.

**Comment by asterite** [comment]
Please let's not add a width limit to the formatter. It's not useful to me. Monitors are bigger now.

**Comment by Sija** [comment]
@asterite It's not just about the monitors, our brains are not rly suited for reading such long lines either (at least mine 😉).

**Comment by asterite** [comment]
If it's a long line, put a line break where you think it's convenient. The problem is that a formatter puts the end of line where it can, not where it's nice. I'm against that and I won't change my mind, sorry. `gofmt` doesn't do it either.

**Comment by Sija** [comment]
I don't think it's a formatter's job either, yet keeping 80 character line width as reference point is imho a good thing to have.

**Comment by RX14** [comment]
@Sija but 80 characters is a guideline. I super often break past 80 characters. We're not going to implement any kind of length metrics in the formatter, that's something for humans to think about.

**Comment by j8r** [comment]
Without having the 80 characters limit globally, I was just underlining the fact that some conditions can be better written.
Long lines are a thing, but long chaining conditions are sometimes quite hard to read, or the contrary lots of little conditions blcoks inside each others.
A formatter that can smartly change the condition line may be good. I don't know, maybe splitting to multi-lines according `&&` and `||` when we have more than 3 of them, or put it in one line when there is a single condition.

**Comment by j8r** [comment]
The only way to know this is to experiment with the formatter to see if the result is nice to be kept or not 😄 
I will play with lt when some other work will be finished.

I exagerate a bit, but looking a this make me sad. I can't believe there is nothing to do to beautify this:
```crystal
if true
 if true
   if true
     puts "hello"
   end
  end
end
```

**Comment by Sija** [comment]
@RX14 that's what I meant writing about a _reference point_, and so I'd leave it as is (a guideline).

**Comment by hugoabonizio** [comment]
@j8r Instead of a formatter's job, it'd fit better on an [Ameba](https://github.com/veelenga/ameba) rule :grin:

**Pull request closed without merging**
