### PR TITLE
Add parenthesis to all occurences of expect_raises

### PR DESCRIPTION
**Pull request by straight-shoota**
Spin-off from #5096

### CODE REVIEW

**Comment by asterite** [comment]
Why only to `expect_raises`? Why not add parentheses to every call in the compiler and std?

**Comment by asterite** [comment]
Sorry for the sarcastic reply above (which I just deleted), but I don't see the point of adding parentheses to these calls.

**Comment by straight-shoota** [comment]
I was reacting to a comment on my pull request [#5096](https://github.com/crystal-lang/crystal/pull/5096#discussion_r143771864) where it was suggested for the new code to have parenthesis. While obviously it's not required, it would at least make sense to use a coherent style throughout the stdlib.
But of course, this is just about calls to *one* single method.

So well, I don't really care either way. But maybe there are some other thoughts about this?

**Comment by asterite** [comment]
I don't think every comment out there needs to be turned into a PR. In fact, I'd advise against that given that without first discussing it (preferably in the mailing list)

**Comment by asterite** [comment]
I think we can close this. There's no 👍  yet. I understand that sometimes parentheses are used and sometimes not, many times I thought maybe we should just force parentheses so it's all consistent, but then we'd have to write `property(:x)` and such. So in the end it's a matter of style, and sometimes using parentheses and sometimes not is OK, it's just a small syntax detail.

**Pull request closed without merging**
