### PR TITLE
Let crystal play server print a hyperlink.

### PR DESCRIPTION
**Pull request by hugopl**
More info about hyperlinks in terminals at
https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda

### CODE REVIEW

**Comment by oprypin** [comment]
It should already work as a link though 👀

**Comment by Sija** [comment]
iTerm on macOS highlights the links automatically, many other apps I'd guess do the same.

**Comment by straight-shoota** [comment]
Most modern terminal emulators recognizes plain URLs and turns them into clickable links.
I doubt that the OSC 8 sequence has more support than plain URL matching.

As far as I understand, OSC 8 is useful when you want a different label for the link then the URL itself. This is not the case here. The URL is explicitly the link label.

So I don't think this change adds anything.

**Comment by hugopl** [comment]
In fact I wrote this 1 line patch because my terminal wasn't letting the link be clickable... but I checked now and was just an option turned off in vte.

I'm closing this ticket, it would be useful only if the text and URL were different.

**Pull request closed without merging**
