### PR TITLE
Win CI: Fix and enable compiler specs

### PR DESCRIPTION
**Pull request by oprypin**

### CODE REVIEW

**Comment by oprypin** [comment]
This now depends on #9346 and #9351.

**Review only the commit** "Win CI: Fix and enable compiler specs" d6016be

**Comment by oprypin** [comment]
Finally, now that there are no dependencies on other PRs, I squashed all that merge-mess :>

**Comment by RX14** [comment]
I'm a bit confused as to the reason for many of these failing specs.

I'd rather not make specs pending if we don't understand why they're broken, so could you give some details?

**Comment by oprypin** [comment]
Currently *all* of the specs are effectively pending, I just reduce that to a dozen.

I really just don't know why these things don't work. There are no stack traces. I'm tired.
So no, I don't want to look for an explanation.

Where I *did* know, I already fixed them. Many of them.

Now I just want to stop the ~~bleeding~~ addition of [more failing specs](https://github.com/crystal-lang/crystal/pull/9171/files#diff-5ddabb407742c04080113fa9fc3464d5).

**Additionally**, I consider merging fixes to these specs *before* enabling specs as strictly worse; then the fix PRs have no representation in specs even if something happens to be fixed (while with *this* in you just flip it back from pending). Showing the specs as what they are is *good*.

Best (bad) example: [#9387](https://github.com/crystal-lang/crystal/pull/9387/files) changes specs for seemingly no reason, but actually they were failing before, *if* they were to run. Then it even marks a related spec as pending, as if the commit breaks that spec???

**Comment by oprypin** [comment]
For the record, this PR is inconsequential for the 0.35.0 release (changes only specs), so definitely feel free to postpone it to after that

**Comment by straight-shoota** [comment]
> I'd rather not make specs pending if we don't understand why they're broken

They've essentially been pending all the time because they're not included in `win32_std_spec.cr`. So this doesn't change anything for those specs that are now `pending_win32`. But it does change the specs that are no longer pending, because they work.

Thanks for your efforts @oprypin

**Comment by jhass** [comment]
🎉

**Pull request merged**
