### PR TITLE
fix BigDecimal operations with floats

### PR DESCRIPTION
**Pull request by stakach**
previously limited to Ints

### CODE REVIEW

**Review by straight-shoota — COMMENTED** [review]
LGTM. I'm only wondering if we could do that in a more generalized way. Perhaps just remove the type restriction or make it `Number`? Let the `BigDecimal` constructor handle what types it supports. 
I think `Number` would be appropriate. It does cover all matching types from stdlib.  If third party number types don't define a `BigDecimal` constructor, it would break on the constructor call instead of `+`, but I think that's okay.

**Comment by stakach** [comment]
The only reason I didn't use Number is BigDecimal is a Number and wasn't sure what overloaded function the compiler would select.
Probably not the place to ask but how does that work, if I have `do_a_thing(with : Number)` and `do_a_thing(wth : Int64)` does it always select the closest match if I pass it an Int64

**Comment by straight-shoota** [comment]
Yes, the most restrictive overload is chosen.

This is easy to verify:
```cr
def do_a_thing(w : Int64)
  puts "Int64"
end
def do_a_thing(w : Number)
  puts "Number"
end

do_a_thing 0_i64
```

**Comment by stakach** [comment]
makes sense, thanks for the explanation.

**Review by straight-shoota — APPROVED** [review]

**Comment by stakach** [comment]
@straight-shoota will this make the 1.1.0 cut?

**Review by sdogruyol — APPROVED** [review]
Thank you @stakach 🙏 Maybe we can get this to 1.2.0 @beta-ziliani @straight-shoota ?

**Pull request merged**
