### PR TITLE
correct and use simple sample in FormData::Builder doc

### PR DESCRIPTION
**Pull request by icyleaf**
No details

### CODE REVIEW

**Comment by RX14** [comment]
Why?

**Comment by icyleaf** [comment]
It used wrong variable in second param,

```
file = IO::Memory.new "file contents"
# it be file not io
builder.file("upload", io, FileMetadata.new(filename: "test.txt"))
```

**Comment by RX14** [comment]
I'd prefer it if you simply fixed the variable name, instead of changing the example. Using `IO::Memory` is easier to understand here, I think.

**Comment by icyleaf** [comment]
In my option, the plain text/binary file often to be use in most of usage, suck like archive file, image file etc. No one will use a `IO::Memory`.

**Comment by RX14** [comment]
It's an example. `IO::Memory` will be rare in practice but using a file makes the example not be self-contained.

**Comment by jhass** [comment]
We shouldn't suggest to use the block-less variant of `File.open` where we can avoid it.

**Comment by icyleaf** [comment]
Updated.

**Comment by exts** [comment]
`In my option, the plain text/binary file often to be use in most of usage, suck like archive file, image file etc. No one will use a IO::Memory.`

@icyleaf I disagree, I needed to use IO::Memory to upload an image to a 3rd party api and unless there's an alternative to sending multipart/form-data this was the best solution that I've found so far.

**Pull request merged**
