### PR TITLE
Spec: allow --link-flags to be used

### LINKED ISSUE #6231: crystal spec doesn't support --link-flags
Hi, I'm trying to run specs for Amber on macOS (https://github.com/amberframework/amber/pull/879) and looks like brew openssl needs to be linked directly in the compiler, so I tried this: (suggested by @bcardiff )

```
crystal spec --link-flags -L/usr/local/opt/openssl/lib
```

And I got this:

```
Unhandled exception: Invalid option: --link-flags (OptionParser::InvalidOption)
  from /usr/local/Cellar/crystal-lang/0.25.0_1/src/option_parser.cr:79:45 in '->'
  from /usr/local/Cellar/crystal-lang/0.25.0_1/src/option_parser.cr:255:3 in 'check_invalid_options'
  from /usr/local/Cellar/crystal-lang/0.25.0_1/src/option_parser.cr:228:7 in 'parse'
  from /usr/local/Cellar/crystal-lang/0.25.0_1/src/option_parser.cr:184:5 in 'parse'
  from /usr/local/Cellar/crystal-lang/0.25.0_1/src/spec.cr:109:1 in '__crystal_main'
  from /usr/local/Cellar/crystal-lang/0.25.0_1/src/crystal/main.cr:104:5 in 'main_user_code'
  from /usr/local/Cellar/crystal-lang/0.25.0_1/src/crystal/main.cr:93:7 in 'main'
  from /usr/local/Cellar/crystal-lang/0.25.0_1/src/crystal/main.cr:133:3 in 'main'
```

I looked into the compiler source code and I found that `crystal spec` is using `setup_simple_compiler_options`, so, it doesn't support all flags.

https://github.com/crystal-lang/crystal/blob/9da2831aa12827601ff414b4685dcf0327ddc69b/src/compiler/crystal/command.cr#L484

https://github.com/crystal-lang/crystal/blob/430fea3aaf3e9b7d6d84e4ebb5f5e20415e2c226/src/compiler/crystal/command/spec.cr#L14-L17

### PR DESCRIPTION
**Pull request by bcardiff**
Fix #6231 .

The `--link-flags` is not added in the `setup_simple_compiler_options` because setting the `compiler.link_flags` is done after the `OptionParser.parse`.

Nevertheless the `setup_simple_compiler_options` is used for `crystal eval` and `crystal spec` only.
I don't think `--link-flags` are needed for `eval`

### CODE REVIEW

**Comment by RX14** [comment]
`--link-flags` does make sense for `eval`, because the resulting executable is linked and executed normally.

**Comment by bcardiff** [comment]
they make sense yes, but is there a use case for that?

**Comment by RX14** [comment]
@bcardiff when you need extra link flags to make an executable run at all? Perhaps you just want to run a quick snippet like `require "myshard"; MyShard.foo`, but you want to test the snippet against two seperately installed versions of a C library.

Why *not* allow it, if it's pretty much easier to allow it by placing the option where the rest of the compiler flags are anyway?

**Comment by RX14** [comment]
Oh, I misread the OP. I thought you were keeping `--link-flags` out of `setup_simple_compiler_options` because you specifically didn't want it on `eval`. Surely we could do something like `compiler.link_flags += " #{link_flag}" in the handler and put it in `setup_simple_compiler_options`...

**Review by straight-shoota — APPROVED** [review]

**Pull request merged**
