### PR TITLE
Add specs for debug info output

### PR DESCRIPTION
**Pull request by ggiraldez**
Code originally taken from
https://github.com/waj/crystal/commit/da7e88b7a00f5b03e8bfb61f46716a00da052a00
and modified to compile with the current version and improve failure
messages.

### CODE REVIEW

**Comment by RX14** [comment]
Would be super cool to start running tests on debug output, could we get this PR updated?

**Comment by ysbaddaden** [comment]
I had forgotten this pull request. It's great! If someone can fix the failing tests, we should merge this!

**Comment by sdogruyol** [comment]
This is a great low hanging fruit :open_mouth:

**Comment by RX14** [comment]
@sdogruyol I continuted this in #4718.

**Pull request closed without merging**
