### PR TITLE
Fix PCRE2 implementation and tests

### LINKED ISSUE #13103: Aftermath of making PCRE2 the default
When we merged the change to use PCRE2 by default in (https://github.com/crystal-lang/crystal/pull/12978), several things broke.
For some reason, the CI builds on the PR were all green. Only later we started so say failing builds.
Some of that can be attributed to the docker build images, which originally lacked `libpcre2`, which we have since added. But I have no idea how the tests  in environments that *don't* use the docker build images and clearly need fixes for PCRE2 support could've possibly succeeded.

The failures are cause by a couple of different bugs, either in the infrastructure setup or with portability of the `libpcre2` bindings.
Fixes are in these PRs:

* #13088 
* #13089 
* #13090
* #13100
* #13102

Since they fix independent bugs, each of them is only a partial contribution to make CI green again, but every single one still has failing jobs.
I've merged them all together into a CI test branch to make sure we're good when all are merged.
https://github.com/crystal-lang/crystal/tree/ci/test-pcre2-fixes
CI is all green, except for the release workflow (which is expected; I just included this test for informational purposes) and the occasional interpreter test failure (re-running that again, but this doesn't seem to be related to PCRE2).

So all looks good with these PRs and I'm gonna start merging them (as far as they are approved).

### PR DESCRIPTION
**Pull request by straight-shoota**
Resolves #13103

### CODE REVIEW

**Comment by beta-ziliani** [comment]
Odd, aarch60-musl-test-stdlib is failing without any useful information 🤔

**Comment by straight-shoota** [comment]
Yeah, that's odd. Will need to investigate further. I think we should merge this regardless (it's broken without this PR also).
`aarch64-musl-test-stdlib` succeeded in #13088 (https://github.com/crystal-lang/crystal/actions/runs/4213098782/jobs/7312598177) and on https://github.com/crystal-lang/crystal/tree/ci/test-pcre2-fixes (https://github.com/crystal-lang/crystal/actions/runs/4234860564/jobs/7357786827).

**Comment by beta-ziliani** [comment]
Thanks a bunch Johannes! 🙇

**Comment by straight-shoota** [comment]
I checked std_spec on aarch64_linux-musl manually and it runs fine. So that's good.
No idea why it's failing in CI.

**Comment by straight-shoota** [comment]
Since this was merged, `aarch64_linux-musl` succeeded in the latest CI builds on master. I guess it was a fluke then (although it  appeared repeatedly, so let's keep our eyes open).

**Pull request merged**
