### PR TITLE
Enumerable improvements

### PR DESCRIPTION
**Pull request by omninonsense**
- add `#first(n)` and `#first?(n)`
- add `#last`, `#last?`, `#last(n)` and `#last?(n)`

### CODE REVIEW

**Comment by kostya** [comment]
first(n) is a take(n)

**Comment by omninonsense** [comment]
Oh, good catch! Although, I suppose you meant `#first?(n)`? Should `#first?(n)` just call `#take(n)`, then, or should `#first?(n)` be removed? I kinda like that it's there, because it's symmetrical to `#last?(n)`.

**Comment by omninonsense** [comment]
Or `#take(n)` could call `#first?(n)`, since they are interchangeable. I think if `#take(n)` called `#first?(n)`, the intention of the code might be cleaner?

**Comment by omninonsense** [comment]
A few remarks

Ruby's `Range#last` behaves differently,

It will always returns the end of the range:
~~~ruby
(1..100).last # => 100
(1...100).last # => 100
~~~

However in Crystal it will return the last element of the *collection* (which I personally think is what one would *expect* from a method named `#last`):

~~~crystal
(1..100).last # => 100
(1...100).last # => 99
~~~

---

Methods  `#first(n)` and `#last(n)` raise if the collection is empty, but `#first?(n)` and `#last?(n)` return an empty array. They will also raise if `n = 0`; should this remain, or not?).

**Comment by asterite** [comment]
Hi,

`take(n)` already does what you propose: http://play.crystal-lang.org/#/r/mqr

`last` doesn't make much sense for `Enumerable`, as an enumerable goes forward, and asking it to go backwards is against its philosophy. Ruby has it, but it says "Builds a temporary array and traverses that array in reverse order". I prefer to make the performance penalty explicit by having to invoke `to_a` if you need it. That's also why we don't have `Enumerable#sort`.

About `Range#last`, I think Ruby's behaviour is odd and unintuitive. Ruby has many corner cases that it changes to do "the right thing", but it's not very clear from the documentation and it can lead to surprises.

**Comment by omninonsense** [comment]
Adding  `#last`s is for the purpose of completeness, but I can imagine some cases where you'd need the last few values of a collection. Also I don't understand why there *must* be a performance penalty?

**Comment by omninonsense** [comment]
Oh and I didn't realise `take` did the same thing as `last? n`, that's why I changed it. To expand a but on why I added last: if there's a `first` I would expect there's a matching  `last` available,  and I also feel like `first? n` might be a more intuitive name than `take n`?

**Comment by omninonsense** [comment]
@asterite Hi! What's the status of this?

`Range#last` is "fixed" (to be more intuitive than Ruby's), but I am still feeling strongly about renaming `take` to `first` and adding `last` to match it.

Also, I don't agree that adding an explicit performance penalty is necessary and that an enumerable's only direction is forward. Often, going from the end of the set is just as useful. Why do you believe otherwise?

**Comment by PragTob** [comment]
Hi there,

take as much more intuitive (and also wildly used especially together with laziness and in functional languages) so take over first (imo)

For last, the reason is to get to the last element of a normal Enumerable you have to create the WHOLE enumerable which is not really enumerableish. When you look at `last` you expect it to be O(1) not O(n), it is Crystal's philosophy (as I understand it) to make these penalties obvious so in this case you'd have to do `to_a.last`. A similar case exists with `sort` which is also missing from Enumerable as compared to Ruby for the very same reason - it creates an intermediate Array.

Also an Enumerable is defined "forward" as each always returns the next element until finished. So it is defined as from first to last, not the other way around.

Hope that sort of explains (at least my understanding of why we don't need first(n) and last).

Tobi

**Comment by omninonsense** [comment]
> take as much more intuitive (and also wildly used especially together with laziness and in functional languages) so take over first (imo)

Okay I agree that is is indeed more intuitive than`first`. The only reason why I thought `first` would be more intuitive is because `first` and `last` were opposites. Maybe rename `last` to `take_last`?

> For last, the reason is to get to the last element of a normal Enumerable you have to create the WHOLE enumerable which is not really enumerableish. When you look at last you expect it to be O(1) not O(n), it is Crystal's philosophy (as I understand it) to make these penalties obvious so in this case you'd have to do to_a.last. A similar case exists with sort which is also missing from Enumerable as compared to Ruby for the very same reason - it creates an intermediate Array.

The current implementation here *is* O(1). It will call `reverse_each`, if available and return the number of elements requested (or just 1) and then call `reverse!` before returning the collection; in case `reverse_each` is unavailable an error is raised. This allows for types that don't support `reverse_each` to have the explicit performance overhead by using `#to_a` and then `Array#last`. I felt like it was a nice balance.

> Also an Enumerable is defined "forward" as each always returns the next element until finished. So it is defined as from first to last, not the other way around.

I understand what you mean, but at the same time I don't think like it needs to go only forward. It's just a "map" of integers mapped to objects (I know this sounds like an Array, but an Array *is* an Enumerable).

If everyone agrees this is a bad idea, or if this proves to be too controversial, I don't mind closing the PR.

**Comment by omninonsense** [comment]
@asterite: Sorry for being a slow poke, but just noticed this got referenced in #2281. Should I close this, seeing as #2281 adds some of the things recommended here (at least to `Array`)?

Also, this PR seems kind of dead anyway… :confused:

**Comment by asterite** [comment]
Yes, let's close this. As `Array` is probably the most common data structure, having `first(n)` and `last(n)` in it is enough for most cases. I'm not sure about `last` for Enumerable, but we could eventually add it (but it needs a separate discussion).

**Pull request closed without merging**
