### PR TITLE
YAML: parse quoted empty string as string, never as nil

### LINKED ISSUE #10606: Object.from_yaml does not handle explicit empty strings correctly
## Bug Report

It is not possible to set a string value to an empty string when using `Object.from_yaml`, if the property has a default value and is not nillabe the default value is used, if it is nillable `nil` is used.

```crystal
require "yaml"

class TestClass
    include YAML::Serializable

    property string_property : String = "default"
end

test = TestClass.from_yaml(%(string_property: ""))
puts typeof(test)
puts typeof(test.string_property)

if test.string_property.nil?
    puts "test.string_property is nil"
else
    puts test.string_property
end

puts

class TestClassNillable
    include YAML::Serializable

    property string_property : String? = "default"
end

test = TestClassNillable.from_yaml(%(string_property: ""))
puts typeof(test)
puts typeof(test.string_property)

if test.string_property.nil?
    puts "test.string_property is nil"
else
    puts test.string_property
end
```
```
TestClass
String
default

TestClassNillable
(String | Nil)
test.string_property is nil
```

### PR DESCRIPTION
**Pull request by asterite**
Fixes #10606

### CODE REVIEW

**Comment by straight-shoota** [comment]
Haha, you beat me to it 😆 
I think #10608 might be a bit more elegant? Definitely better specs.

**Comment by asterite** [comment]
I don't know. You test an implementation detail, I end the overall expectation. If for some reason we stop using that underlying method and use something else, this might break again and we won't know.

**Comment by asterite** [comment]
But yes, feel free to work on this. I just had some spare minutes, now I don't anymore :-)

**Comment by straight-shoota** [comment]
There are also tests for integration with `YAML::Serializable` in https://github.com/crystal-lang/crystal/pull/10608/files#diff-8f5fd064de683a361badba03eeadc02d43c912eb880400e4aa632c8797c903d0R739-R744

**Comment by asterite** [comment]
Oh, sorry, I missed it.

**Pull request closed without merging**
