### PR TITLE
Remove _invariant macro from Float::Printer::* modules

### PR DESCRIPTION
**Pull request by Sija**
As per https://github.com/crystal-lang/crystal/pull/5065#issuecomment-353392651.

### CODE REVIEW

**Comment by bew** [comment]
The thing is: were they here for debug only, during dev phase of the float printer? or do they need a replacement for normal use?

**Comment by Sija** [comment]
Asserts are supposed to run only in debug mode, so I'd assume they should be safe to remove.

**Comment by Sija** [comment]
🏓

**Comment by RX14** [comment]
These exact asserts actually found #5518, but so would running the spec suite, so I guess they're fine to remove.

**Pull request merged**
