### PR TITLE
Release 1.0.0-pre1

### PR DESCRIPTION
**Pull request by bcardiff**
Preview at https://github.com/bcardiff/crystal/blob/changelog/1.0.0-pre1/CHANGELOG.md

There are a couple of more PRs that will land in 1.0.0-pre1, no worries :-)

The 1.0.0-pre1 will be the first unstable release as stated in https://crystal-lang.org/2020/08/24/announcing-new-apt-and-rpm-repositories.html

### CODE REVIEW

**Comment by j8r** [comment]
Is it planned to have both Logger and Log for the 1.0? I find it quite confusing, last day I used Logger by mistake.

**Comment by Sija** [comment]
@j8r Isn't `Logger` out already?

**Comment by j8r** [comment]
Ho right @Sija , I didn't noticed it, being "still" in 0.35.1. Great then :+1:

**Comment by asterite** [comment]
This is totally optional and my personal opinion, but...

I think the Changelog should be more oriented toward a user of the language reading it. Right now it contains things like "Fixed example code" or "Fix typos and misspelling" or "Make socket a bit more type friendly" (this is an internal refactor not visible to users). That probably has no impact on users. I mean, they are good things, but they are not actionable. With an item like "Change method X to do Y" the user will think "Oh, I need to update this code" or "Oh, now I can use this method for this different thing", but with "Fixed typos" or "Internal refactor" they can't do anything about it.
 
If users want that level of details they can go to the commit log. In the past I kept the Changelog user-oriented.

**Comment by straight-shoota** [comment]
@asterite I agree that the changelog is probably not that useful to users of the language. The question is: should it be? Yes, users need to get the information about changes to the language / stdlib that affect them. But that doesn't need to be in the changelog of this repository, which is just an internal tool. So documentation of changes is focused on internal view. 
I'd keep the changelog format as is and instead provide a separate changelog targeted for language users.
Internal and external concerns differ and both have their values. The git commit history could serve as an internal changelog. This may work well in smaller projects but in my opinion our repository and the activity is too much for that simple solution.
So my proposal would be more detailed release notes. Probably published on the website. It settles somewhere in between the changelog (internal records) and the current release note format (https://crystal-lang.org/2020/06/09/crystal-0.35.0-released.html) which focuses on major changes but in great detail.

**Comment by oprypin** [comment]
@straight-shoota I don't understand. If the changelog is just an internal tool, and a commit log fulfills that need just as well, then what's the point?

**Comment by straight-shoota** [comment]
I don't think the commit log fulfills that purpose well at all. It's noisy, unstructured, immutable, [etc.](https://keepachangelog.com/en/1.0.0/#log-diffs)

**Comment by hugopl** [comment]
IMO the changelog is for people that want to know details of the project development but not too many details/noise as a git log. Language users usually read the official blog post that describe the language changes with examples and a better explanations longer than a single line. So IMO the current format is ok.

**Comment by bcardiff** [comment]
I will reopen it again as 0.36 later

**Pull request closed without merging**
