### PR TITLE
Implement Pipe |> operator

### PR DESCRIPTION
**Pull request by S-YOU**
```
% .build/crystal eval '"Hello World!" |> puts'
Hello World!
```

What do you think?

### CODE REVIEW

**Comment by ysbaddaden** [comment]
That it was already refused a long time ago #1388 as "doesn't fit the language".

Crystal uses chaining instead. See https://github.com/crystal-lang/crystal/issues/1388#issuecomment-138083911

**Comment by asterite** [comment]
Note that pipe in Ruby 2.7 is equal to a dot. It's different from your implementation. I don't think it's worth adding it like Ruby. Maybe like Elixir and Elm yes, but it's already been discussed in the past and rejected.

**Comment by asterite** [comment]
See https://github.com/ruby/ruby/commit/f169043d81524b5b529f2c1e9c35437ba5bc3a7a and all the comments against it.

**Comment by S-YOU** [comment]
> See ruby/ruby@f169043 and all the comments against it.

That's because of Ruby implementation is very similar to dot and not much meaning. My Implementation is similar to Elixir I believe.

**Comment by asterite** [comment]
@S-YOU That's fine, but we never agreed that a pipeline operator for a non-functional language was a good idea.

**Comment by shuya-takano** [comment]
I doubt that too. Let’s see how it is going on with Ruby.

**Comment by absolutejam** [comment]
Is it possible to achieve this in a shard?

**Comment by ShalokShalom** [comment]
Ruins the whole language for me. I wonder why people, who have never coded proficiency in F#, the language it comes from, make remarks on how useful it is.

**Pull request closed without merging**
