### PR TITLE
Implement compiler-rt's 128-bit integer conversions to/from floats

### PR DESCRIPTION
**Pull request by HertzDevil**
This PR provides Crystal ports for these compiler-rt functions:

* `__floattidf` (`Int128#to_f64!`)
* `__floattisf` (`Int128#to_f32!`)
* `__floatuntidf` (`UInt128#to_f64!`)
* `__floatuntisf` (`UInt128#to_f32!`)
* `__fixdfti` (`Float64#to_i128!`)
* `__fixsfti` (`Float32#to_i128!`)
* `__fixunsdfti` (`Float64#to_u128!`)
* `__fixunssfti` (`Float32#to_u128!`)

This allows those conversions to be done on Windows.

### CODE REVIEW

**Review by straight-shoota — APPROVED** [review]

**Comment by BlobCodes** [comment]
https://github.com/crystal-lang/crystal/blob/b06c7b25241add5bd30de6a94f90ef1d25aa945d/spec/compiler/codegen/arithmetics_spec.cr#L3-L16

Does this still apply with the PR?

**Comment by HertzDevil** [comment]
The functions themselves work as intended but the ABI issue probably remains (same as `__divti3`).

**Review by beta-ziliani — APPROVED** [review]
🚀

**Comment by straight-shoota** [comment]
Regarding @BlobCodes' comment: The float to uint conversions in arithmetics_specs should be expected to work with this spec. See  https://github.com/straight-shoota/crystal/runs/4356998682?check_suite_focus=true:

```diff
--- c/spec/compiler/codegen/arithmetics_spec.cr
+++ w/spec/compiler/codegen/arithmetics_spec.cr
@@ -3,18 +3,15 @@ require "../../spec_helper"
 # Int128 and UInt128 specs do not pass on win32 because of missing compiler-rt symbols
 {% unless flag?(:win32) %}
   SupportedInts            = [UInt8, UInt16, UInt32, UInt64, UInt128, Int8, Int16, Int32, Int64, Int128]
-  SupportedIntsConversions = {
-    to_i8: Int8, to_i16: Int16, to_i32: Int32, to_i64: Int64, to_i128: Int128,
-    to_u8: UInt8, to_u16: UInt16, to_u32: UInt32, to_u64: UInt64, to_u128: UInt128,
-  }
 {% else %}
   SupportedInts            = [UInt8, UInt16, UInt32, UInt64, Int8, Int16, Int32, Int64]
-  SupportedIntsConversions = {
-    to_i8: Int8, to_i16: Int16, to_i32: Int32, to_i64: Int64,
-    to_u8: UInt8, to_u16: UInt16, to_u32: UInt32, to_u64: UInt64,
-  }
 {% end %}

+SupportedIntsConversions = {
+  to_i8: Int8, to_i16: Int16, to_i32: Int32, to_i64: Int64, to_i128: Int128,
+  to_u8: UInt8, to_u16: UInt16, to_u32: UInt32, to_u64: UInt64, to_u128: UInt128,
+}
+
 describe "Code gen: arithmetic primitives" do
   describe "&+ addition" do
     {% for type in SupportedInts %}
```

**Comment by beta-ziliani** [comment]
@HertzDevil can you make the proposed changes? 🙇

**Review by straight-shoota — APPROVED** [review]

**Pull request merged**
