### PR TITLE
Improve File.utime precision to nanosecond on Unix

### LINKED ISSUE #9345: Improve File.utime precision by using utimensat() on Unix
On Unix, [`File.utime`][] is implemented by [`utimes`][], whose time precision is microsecond. The least three digits of nanosecond part of `atime` and `mtime` are zeroed. [`utimensat`][], whose time precision is nanosecond, is usable instead of `utimes` when the special value `AT_FDCWD` is passed in the fd parameter.

`utimensat` is supported on the following platforms:

* Linux kernel >= 2.6.22 and glibc >= 2.6 (see [here](http://man7.org/linux/man-pages/man2/utimensat.2.html))
* Linux kernel >= 2.6.22 and musl libc >= 0.7.0
* macOS >= 10.13, High Sierra (see [here](https://bugs.python.org/msg303098))
* OpenBSD >= 5.0 (see [here](https://man.openbsd.org/utimensat.2))
* FreeBSD >= 10.3 (see [here](https://www.freebsd.org/cgi/man.cgi?query=utimensat))
* DragonFly BSD >= 4.1 (see [here](https://www.dragonflybsd.org/cgi/web-man?command=utimensat&section=2))

On the other hand, crystal's [supported platforms](https://github.com/crystal-lang/crystal/wiki/Platform-Support) are:

* Linux kernel >= 2.6.18
* macOS >= 10.7, Lion
* OpenBSD 6.x
* FreeBSD 11.x

I came up with four options:

1. Use `utimensat` on all Unix platforms and drop support for Linux kernel < 2.6.22 and macOS < 10.13.
2. Use `utimensat` when `LibC.dlsym(LibC::RTLD_DEFAULT, "utimensat")` returns non-null. Otherwise use `utimes`.
3. Use `utimensat` on BSD platforms. Use `utimes` on Linux and macOS while Linux kernel < 2.6.22 and macOS < 10.13 are supported.
4. Keep using `utimes` on all Unix paltforms while Linux kernel < 2.6.22 and macOS < 10.13 are supported.

Which is better?

[`File.utime`]: https://crystal-lang.org/api/File.html#utime(atime:Time,mtime:Time,filename:String):Nil-class-method
[`utimes`]: http://man7.org/linux/man-pages/man2/utimes.2.html
[`utimensat`]: https://pubs.opengroup.org/onlinepubs/9699919799.2008edition/functions/utimensat.html

### PR DESCRIPTION
**Pull request by kubo**
Closes #9345.

This PR makes the following distributions unsupported:
* Red Hat Enterprise Linux 5.x  
  The maintenance support ended at 31 March 2017. The extended lifecycle support, providing critical and security fixes to payed customers, ends at 30 November 2020. (see [here](https://en.wikipedia.org/wiki/Red_Hat_Enterprise_Linux#Product_life_cycle))
* Ubuntu 7.04 feisty  
  The support ended at 18 April 2009. (see [here](https://en.wikipedia.org/wiki/Ubuntu_version_history#Table_of_versions))
* macOS < 10.13, High Sierra

I think that almost people don't make new products for such old distributions.

This was tested on the following platforms.
* i386-linux-gnu ([circle ci][])
* x86_64-darwin (on my local machine)
* x86_64-linux-gnu ([circle ci][])
* x86_64-linux-musl ([circle ci][])
* x86_64-windows-msvc ([github actions][])

This was not tested on the following platforms. I hope it works on them.
* aarch64-linux-gnu
* aarch64-linux-musl
* arm-linux-gnueabihf
* x86_64-dragonfly
* x86_64-freebsd
* x86_64-openbsd

**Note:** This PR is incompatible with #9360. If this is merged before #9360, the following files in #9360 must be changed as in this PR. If #9360 is merged before this, I'll add a new commit.
* src/lib_c/x86_64-netbsd/c/fcntl.cr
* src/lib_c/x86_64-netbsd/c/sys/stat.cr
* src/lib_c/x86_64-netbsd/c/sys/time.cr

**Memo:**
| platform | AT_FDCWD |
| --- | --- |
| DragonFly BSD | [0xFFFAFDCD](https://github.com/DragonFlyBSD/DragonFlyBSD/blob/v5.9.0/sys/sys/fcntl.h#L178) |
| FreeBSD | [-100](https://github.com/freebsd/freebsd/blob/11e74d9/sys/sys/fcntl.h#L207) |
| Linux | [-100](https://github.com/torvalds/linux/blob/v5.6/include/uapi/linux/fcntl.h#L87) |
| macOS | [-2](https://github.com/apple/darwin-xnu/blob/a449c6a/bsd/sys/fcntl.h#L140) |
| NetBSD | [-100](https://github.com/NetBSD/src/blob/c4f624f/sys/sys/fcntl.h#L303) |
| OpenBSD | [-100](https://github.com/openbsd/src/blob/6bd4f7c/sys/sys/fcntl.h#L198) |

[circle ci]: https://app.circleci.com/pipelines/github/kubo/crystal/18/workflows/996282e1-311d-4343-b348-697a7d7698bc
[github actions]: https://github.com/kubo/crystal/actions/runs/120499355

### CODE REVIEW

**Comment by straight-shoota** [comment]
Maybe we should keep the current implementation as default and only use `utimensat` on platforms that have been tested to work. As far as we know, the current implementation works on all platforms Crystal currently supports. And it probably works on most POSIX platforms that will be supported in the future. So it seems like a good idea do keep this as the default implementation and only use the improved one when it's sure that it works.

Having no nanosecond support in utime is not a huge issue for most use cases. But broken utime is an issue for all use cases.

**Comment by kubo** [comment]
closed because of https://github.com/crystal-lang/crystal/issues/9345#issuecomment-636505222

**Comment by RX14** [comment]
please don't take one comment and take it as the entire core team's opinion...

**Comment by RX14** [comment]
Why are you using `utimensat` instead of `utimens` though...

**Comment by straight-shoota** [comment]
@kubo This is not rejected. I just made a suggestion, open for discussion. According to https://github.com/crystal-lang/crystal/issues/9345#issuecomment-636883216 it seems not necessary.
Would you mind restoring your branch? Then this PR can be reopened. You can also open a new one if you like.

**Comment by kubo** [comment]
Sorry, I tend to avoid discussion in English especially on weekdays. It needs ten times more time to write English compared with Japanese. If it were Japanese, I would post my opinion instead of closing this.

**Comment by bcardiff** [comment]
We target macOS, at least for now, 10.11 el capitan. 
So, we would need a fallback for macOS < 10.13 to merge this PR

**Comment by RX14** [comment]
> We target macOS, at least for now, 10.11 el capitan.
> So, we would need a fallback for macOS < 10.13 to merge this PR

That version has been unsupported for ages, if we need to support it we need a good reason why.

macos is not like linux distros where old versions stick around for ages

**Comment by kubo** [comment]
@bcardiff
macOS < 10.13 has been unsupported by Apple as @RX14 commented.
Who has the right to decide target OS versions? Should I revert macOS-specific code?

I made the list of release dates of macOS security updates from this [document](https://support.apple.com/en-us/HT201222).
Apple maintains only the last three versions.
   &nbsp;     | 10.11 | 10.12 | 10.13 | 10.14 | 10.15 |
------------|-------|-------|-------|-------|-------|
1 June 2020 |&nbsp; |&nbsp; |&check;|&nbsp; |&check;|
26 May 2020 |&nbsp; |&nbsp; |&check;|&check;|&check;|
24 Mar 2020 |&nbsp; |&nbsp; |&check;|&check;|&check;|
28 Jan 2020 |&nbsp; |&nbsp; |&check;|&check;|&check;|
10 Dec 2019 |&nbsp; |&nbsp; |&check;|&check;|&check;|
29 Oct 2019 |&nbsp; |&nbsp; |&check;|&check;|&check;|
26 Sep 2019 |&nbsp; |&check;|&check;|&check;|&nbsp; |
22 Jul 2019 |&nbsp; |&check;|&check;|&check;|&nbsp; |
13 May 2019 |&nbsp; |&check;|&check;|&check;|&nbsp; |
29 Mar 2019 |&nbsp; |&check;|&check;|&nbsp; |&nbsp; |
25 Mar 2019 |&nbsp; |&check;|&check;|&check;|&nbsp; |
22 Jan 2019 |&nbsp; |&check;|&check;|&check;|&nbsp; |
05 Dec 2018 |&nbsp; |&check;|&check;|&check;|&nbsp; |
30 Oct 2018 |&nbsp; |&check;|&check;|&check;|&nbsp; |
09 Jul 2018 |&check;|&check;|&check;|&nbsp; |&nbsp; |
01 Jun 2018 |&check;|&check;|&check;|&nbsp; |&nbsp; |
29 Mar 2018 |&check;|&check;|&check;|&nbsp; |&nbsp; |

**Comment by bcardiff** [comment]
Time fly. My concern for dropping 10.11 and 10.12 is that I remembered why we put `MACOSX_DEPLOYMENT_TARGET=10.11` in https://github.com/crystal-lang/distribution-scripts/pull/15 . At that time, homebrew used to build bottles for 10.11 and 10.12.

I'll double check if it's safe to drop those releases.

No further action is needed for now.

**Comment by straight-shoota** [comment]
It seems macOS 10.11 and 10.12 is already unsupported: #9476

/cf crystal-lang/crystal-website#111

**Comment by bcardiff** [comment]
FYI I need confirmation from someone in homebrew regarding https://github.com/Homebrew/homebrew-core/pull/56013#issuecomment-642056938 to avoid running again in https://github.com/Homebrew/homebrew-core/pull/29527 before effectively dropping 10.11 / 10.12 support.

**Comment by kubo** [comment]
Sorry, I closed this unintentionally. I removed my fork of the crystal repository.

**Comment by Sija** [comment]
Should this be revived?

**Pull request closed without merging**
