### PR TITLE
Introduce Math.frexp method.

### PR DESCRIPTION
**Pull request by akzhan**
PS: It may be used by Float64.hash (to solve #3932).

### CODE REVIEW

**Comment by Sija** [comment]
@akzhan 32-bit on linux [failed](https://travis-ci.org/crystal-lang/crystal/jobs/242405467) with `Invalid memory access (signal 11) at address 0x1f8dbcf8`, just FYI.

**Comment by asterite** [comment]
@Sija It's a bug because of LLVM 3.5

**Comment by Sija** [comment]
@asterite [`Using /usr/bin/llvm-config-3.8 [version=3.8.0]`](https://travis-ci.org/crystal-lang/crystal/jobs/242405467#L120) - is it rly?

**Comment by asterite** [comment]
Ah, well. Then there's something wrong with how we are using LLVM but unfortunately I have no idea why. Probably something gets disposed and still being used.

**Comment by RX14** [comment]
Doesn't mean the compiler was compiled using LLVM 3.8 @Sija.

**Comment by asterite** [comment]
@RX14 Ah, that's probably it. At least on my machine, where I have the compiler compiled with 4.0, I never got that error. In any case it's a minor issue because it only affects the compiler, randomly, but not the executables produced by the compiler.

**Comment by akzhan** [comment]
@asterite Compiler works fine on LLVM 3.9 and 4.0. Looks like it failed or earlier LLVMs.

**Pull request merged**
