### PR TITLE
[WIP] Implement ASTPrinter

### PR DESCRIPTION
**Pull request by yui-knk**
This is the tool mainly for debug usage.
For example `bin/crystal ast samples/matmul.cr`,
and shows the AST.

I am now implementing, reviews are welcome :)

### CODE REVIEW

**Comment by asterite** [comment]
Thanks! But why is this useful?

**Comment by vendethiel** [comment]
AST introspection, while working on the compiler or doing tricky macro stuff I guess?

**Comment by yui-knk** [comment]
AST inspection :)
Yes this is useful when some developer debug AST.
For example I am not familiar with `&.method` syntax (because this is not same as Ruby's).

Dumping to there code as AST give me some knowledges.

```
["a", "b", "c"].try &.map &.upcase
```

**Comment by asterite** [comment]
I'm still unsure about the use cases of this. One thing that I'm more sure about is that the output should be something that a program can handle, probably JSON.

But for learning the language there are (incomplete :blush:) docs, I don't think this is a valid use case.

**Comment by kirbyfan64** [comment]
I personally like this idea. They do say an example speaks a thousand words! My version of writing macros in Lisps is writing a model of what the end result shouls look like and dumping the AST; that's also how I work with Python ASTs. Yeah, there're docs, but it takes longer to put two and two together.

**Comment by asterite** [comment]
I think this *might* make sense as a tool, maybe `crystal tool ast`, but the output should be JSON or similar. Maybe a tool could you that. It's not clear if the dumped AST should be that of the compiled file, or the whole program once `require` are resolved. So for now maybe you could open an issue to discuss this.

**Pull request closed without merging**
