### PR TITLE
(WIP) Crystal 0.24.2

### PR DESCRIPTION
**Pull request by matiasgarciaisaia**
See #5358 for context on why we have this PR going :)

We're still missing a couple of changes on the release process before actually releasing this - please **don't merge yet**.

### CODE REVIEW

**Comment by RX14** [comment]
Shouldn't this be PRing the changelog into `release/0.24`?

**Comment by RX14** [comment]
All the commits in `release/0.24` should have been cherry-picked into master (or vice-versa) so this PR looks incorrect...

**Comment by Sija** [comment]
Why this release contains only cherry-picked commits/PRs, instead (like it was before) including all since the previous release?

**Comment by matiasgarciaisaia** [comment]
The idea is to have point-releases as bugfix-only. We would have wanted this to be released shortly after 0.24.1, but we didn't do that on time.

SemVer allows us to do whatever we want before 1.0, but we should at some point start to practice following it as if we were 1.0. So 0.24.2 would be a bugfix release - no new features.

There are also some specific reasons to have a new 0.24.2 release before releasing 0.25 with all the new features that are ready (namely, an issue with libgc that prevents us from building 32 bits on Docker).

So we can expect 0.25 to come "soon" after 0.24.2 (for really relaxed values of "soon").

**Comment by RX14** [comment]
Next time, can we agree to commit everything to master and then cherry-pick those commits onto branches?

**Comment by bcardiff** [comment]
@Sija it's more a manner on how to to implement git-flow. If when more that one version is been developed at the same time (like a maintenance release branch vs master) at manas we find easier to track to fix things in one place an then merge into master once release is done (or even regularly). The merge commit serves as the intention to include all the fixes. We found cherrypicking harder to track and to check. For sure the merge commit can get wrong, but at least the intention is clear and serves as a point of discussion. We usually work using a slight modification of http://nvie.com/posts/a-successful-git-branching-model/ .

**Comment by jhass** [comment]
IME git-flow is good for a company internal workflow but falls apart if applied without modifications in a OSS context, mainly due awareness issues but also longer development cycles.

**Comment by RX14** [comment]
Nah, git flow is just terrible in any context.

**Comment by Sija** [comment]
`(WIP)` still there (after merge)?

**Pull request merged**
