### PR TITLE
Introduce Byte, Bytes, and Chars aliases

### LINKED ISSUE #1348: [RFC] Alias for Slice(UInt8)
Can an alias of Slice(UInt8) be added to reduce carpel tunnel?

Suggestions:
* Bytes
* Buffer

### PR DESCRIPTION
**Pull request by keplersj**
Fixes #1348

### CODE REVIEW

**Comment by asterite** [comment]
Thanks!

We can maybe start with just `Bytes`, I'm not sure `Byte` would be used (typing `UInt8` is almost as easy) and `Chars` has no use case right now. I just mentioned those other in a theoretical way.

**Comment by ozra** [comment]
`Byte` feels nice for working with "binary buffers" rather than UInt8 which could be seen as more ambiguous. Obviously would go along well with `Bytes`.
Chars would be better off as `CString` or so for use cases I'd think of, no?

**Comment by asterite** [comment]
The use of `Slice(Char)` is for `IO`, when you'd want to read a few chars instead of bytes with some encoding. For example:

```crystal
io = ...

bytes = UInt8[1024]
io.read(bytes.to_slice)

chars = Char[1024]
io.read(chars.to_slice)
```

This would be similar to [C#](https://msdn.microsoft.com/en-us/library/97e90x91(v=vs.110).aspx) (read chars from a text reader, or [read bytes](https://msdn.microsoft.com/en-us/library/system.io.stream.read(v=vs.110).aspx) from a binary stream). However, we haven't found a real use case for that yet, so for now I wouldn't introduce a `Chars` alias.

**Comment by ozra** [comment]
Ah, right, Char = 32bit, my mind was in C-world X-|

**Pull request closed without merging**
