### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by kianmeng**

### CODE REVIEW

**Comment by straight-shoota** [comment]
Thanks! 

Could you perhaps make the changes in `lib/markd` directly to https://github.com/icyleaf/markd/ ? That folder is just vendored in. It's easier to fix upstream and we can just pull from there afterwards. It's more complicated to push changes from here back to upstream.

**Comment by kianmeng** [comment]
Should I reverted the changes made to `lib/markd` for this PR?

**Comment by straight-shoota** [comment]
Yes, please

**Comment by kianmeng** [comment]
@straight-shoota Done. Please check.

**Review by oprypin — APPROVED** [review]

**Review by straight-shoota — APPROVED** [review]

**Comment by kianmeng** [comment]
:tada: :tada: :tada: :tada: :tada:

**Pull request merged**
