### PR TITLE
Remove outdated TODOS

### PR DESCRIPTION
**Pull request by Sija**

### CODE REVIEW

**Comment by Sija** [comment]
@asterite GTG?

**Comment by asterite** [comment]
@Sija Depends, some crystal binaries for 0.20.3 weren't available at the time of the PR

**Comment by Sija** [comment]
@asterite builds on `x86_64` are still failing, all others should be green 👍

**Comment by asterite** [comment]
@Sija Yeah, then we basically can't merge this because all next commits will always fail and we won't immediately know if it's because of this or something else. Let's wait until all builds are green.

**Comment by Sija** [comment]
@asterite CI just turned green :)

**Comment by asterite** [comment]
Great! It seems the rebuild triggered by @jhass did work :-)

**Comment by Sija** [comment]
@asterite ping?

**Pull request merged**
