### PR TITLE
Add `WaitGroup.wait` and `WaitGroup#spawn`

### LINKED ISSUE #14820: Streamlining the `WaitGroup` API
## Feature Request

- Is your feature request related to a problem? Please describe clearly and concisely what is it.

Less of a problem, more of an itch I'd like to scratch. `WaitGroup` is something I've been wanting in Crystal for years, but the API is a bit Golang-like.

```crystal
wg = WaitGroup.new(2)
spawn do
  http.get "/foo"
ensure
  wg.done
end
spawn do
  http.get "/bar"
ensure
  wg.done
end
wg.wait
```

- Describe the feature you would like, optionally illustrated by examples, and how it will solve the above problem.

I've been experimenting with an API that looks like this and it works really nicely so far.

```crystal
WaitGroup.wait do |wg|
  wg.spawn { http.get "/foo" }
  wg.spawn { http.get "/bar" }
end
```

It's got the same feel as [Redis pipelines](https://jgaskins.dev/redis/index.html#pipelined-queries):

```crystal
redis.pipeline do |pipe|
  pipe.get "foo"
  pipe.get "bar"
end
```

- Describe considered alternative solutions, and the reasons why you have not proposed them as a solution here.

I don't have any alternatives at the moment, but it's perfectly understandable if the method names change.

- Does it break backward compatibility, if yes then what's the migration path?

Nope, the idea builds on top of the existing `WaitGroup` API.

### PR DESCRIPTION
**Pull request by jgaskins**
Fixes #14820

### CODE REVIEW

**Comment by stakach** [comment]
I definitely think this should be included as part of the std lib
super simple and easy to maintain

**Review by straight-shoota — APPROVED** [review]

**Review by straight-shoota — CHANGES_REQUESTED** [review]
Would you please add some doc comments (ideally with usage examples)?

**Comment by jgaskins** [comment]
Added

**Review by straight-shoota — APPROVED** [review]

**Review by ysbaddaden — APPROVED** [review]

**Comment by zw963** [comment]
I consider this new usage is really nice.

**Pull request merged**
