### PR TITLE
Finish the \a escape sequence

### PR DESCRIPTION
**Pull request by r00ster91**
This finishes the \a escape sequence.

### CODE REVIEW

**Comment by r00ster91** [comment]
Huh? It failed again? I thought CI is using 0.25.0 now.

**Comment by z64** [comment]
You didn't rebase onto a branch that includes the CI script fix.  You have to update your local master branch first, then rebase this branch on top of it, then force push it.

**Comment by r00ster91** [comment]
Sorry I can't access the finishescapesequence branch anymore... I already tried a lot of things.
It says `unknown repository` on the top now. I deleted my fork and forked again so I have the CI script fix in it. But that was dumb I know.
CI fails just because of this one space at the end of the `'\a'.ord.should eq(7)` line in [spec/std/char_spec.cr](https://github.com/crystal-lang/crystal/pull/6176/files#diff-52698489c143c0550d821160744cedcb). :/

**Comment by straight-shoota** [comment]
You'll have to create a new PR for your branch.

**Pull request closed without merging**
