### PR TITLE
Remove SimpleHash

### LINKED ISSUE #2331: Drop SimpleHash (Was: SimpleHash and other hashes)
In the compiler we used to use [SimpleHash](https://github.com/crystal-lang/crystal/blob/master/src/simple_hash.cr) (a hash built on top of an array of pairs) for some paths where the hash would end up with a few elements. However, we don't use that anymore because the performance difference was negligible.

The problem is, it's kind of public API now, and others want to use it, like [here](https://github.com/kostya/benchmarks/pull/84), but I'm not sure I want to stick with that type in the standard library. Or, if we stick with it, it's better if we change its name and clearly state its use case.

The questions are:
- Should we keep it in the std? If so, what name do we use? Since it's a Hash backed by an array, maybe `ArrayHash` would be an appropriate name, although it sounds confusing.
- Should we also add a class similar to Hash but without maintaining order? Right now `Hash` has a doubly linked list that allows maintaining insertion sorter, but this needs more allocated memory to work, so not having this functionality will speed up things in some cases. If so, what name should we use? Or maybe we can swap things, and maybe Hash dumber and add a [LinkedHash](https://docs.oracle.com/javase/7/docs/api/java/util/LinkedHashMap.html).

### PR DESCRIPTION
**Pull request by sdogruyol**
This fixes #2331. 

As @asterite already mentioned it leads to confusion and there's no use case for this since the performance difference is negligible.

### CODE REVIEW

**Comment by Sija** [comment]
There's stray `require` left in `src/docs_main.cr`.

**Comment by sdogruyol** [comment]
Fixed. Thanks @Sija

**Comment by asterite** [comment]
@sdogruyol Good idea! Yes, SimpleHash doesn't have a clear use case, Hash is usually faster. Thank you!

**Comment by sdogruyol** [comment]
Thank you ❤️

**Pull request merged**
