### PR TITLE
run standard library specs in release mode on travis

### PR DESCRIPTION
**Pull request by jhass**
This should catch codegen bugs that only appear after LLVM optimizations.

### CODE REVIEW

**Comment by jhass** [comment]
Looks like it actually exposes a bug: https://travis-ci.org/crystal-lang/crystal/jobs/151792684

**Comment by asterite** [comment]
On my machine `digest/sha1` specs fail with --release, I have no idea why

**Comment by asterite** [comment]
Actually, they fail with the current compiler, but not in the next one. I'll later try to see if it's an LLVM bug or there's a bug in the codegen.

**Comment by RX14** [comment]
When I discovered this on `0.18.7`, `digest/sha1` and one `process` spec were failing. The sha1 spec failing is quite concerning to me...

**Comment by RX14** [comment]
Bump on this, sha1 specs still fail in release mode on master which is super concerning to me.

Some of the bytes still get corrupted, for example:
```
  4) Digest::SHA1 does digest for "The quick brown fox jumps over the lazy dog"
     Failure/Error: bytes.to_slice.hexstring.should eq(hexdigest)

       expected: "2fd4e1c67a2d28fced849ee1bb76e7391b93eb12"
            got: "2fd480c67a2d28fced842be1bb76e7391b931212"
```

**Comment by miketheman** [comment]
#triage
@jhass Is it worth rebasing this against `master` and having Travis try again? I tried today with `Crystal 0.23.0+35 [890ab45bf] (2017-08-04) LLVM 4.0.1` - and it passed locally.

**Comment by jhass** [comment]
Sure why not, I hope memory consumption is low enough still.

**Comment by RX14** [comment]
Release mode doesn't pass for me, i'm trying to work out why right now. First guess from gdb is codegen is somehow passing uninitialized memory as the closure to a proc.

**Comment by RX14** [comment]
If this is rebased on master it should pass travis.

**Comment by straight-shoota** [comment]
@jhass is this PR still relevant?

**Comment by ysbaddaden** [comment]
Closing. We moved to Circle.

**Pull request closed without merging**
