### PR TITLE
Use `#trailing_zeros_count` in `Int#gcd`

### PR DESCRIPTION
**Pull request by HertzDevil**

### CODE REVIEW

**Review by straight-shoota — APPROVED** [review]

**Comment by yxhuvud** [comment]
I *tried* to use tzc when implementing it the first time, but got a whole lot of wrong results when I ran my benchmark suite over a bunch of inputs. Lets hope this is more correct than when I tried it :sweat:

**Comment by straight-shoota** [comment]
For reference, I tested the new implementation against the old one for a couple million random numbers from all primitive number types and both methods always returned the same value. So this change looks good 👍

**Comment by jzakiya** [comment]
I did a short|quick benchmark to see the performance difference, and for it they were essentially the same.

```
struct Int

  def gcd1(other : self) : self
    u = self.abs
    v = other.abs
    return v if u == 0
    return u if v == 0

    shift = (u | v).trailing_zeros_count
    u = u.unsafe_shr(u.trailing_zeros_count)

    loop do
      v = v.unsafe_shr(v.trailing_zeros_count)
      u, v = v, u if u > v
      v &-= u
      break if v.zero?
    end

    u.unsafe_shl shift
  end

  def gcd2(other : self) : self
    u = self.abs
    v = other.abs
    return v if u == 0
    return u if v == 0

    shift = self.class.zero
    while (u | v) & 1 == 0
      shift &+= 1
      u = u.unsafe_shr 1
      v = v.unsafe_shr 1
    end
    while u & 1 == 0
      u = u.unsafe_shr 1
    end

    loop do
      while v & 1 == 0
        v = v.unsafe_shr 1
      end
      u, v = v, u if u > v
      v &-= u
      break if v.zero?
    end

    u.unsafe_shl shift
  end
end

def test
  x = (1..1_000_000).to_a.shuffle
  y = (1_000_0001..2_000_000).to_a.shuffle
  x.each do |u|
    y.each do |v|
      return "bad" unless u.gcd1(v) == u.gcd2(v)
    end
  end
  puts "all good"
end

test

Benchmark.ips do |b|
  x = (1..1_000_000).to_a.shuffle
  y = (1_000_0001..2_000_000).to_a.shuffle
  b.report("gcd1") { x.each { |u| y.each { |v| u.gcd1(v) } } }
  b.report("gcd2") { x.each { |u| y.each { |v| u.gcd2(v) } } }
end

------------------------------------
➜  crystal run --release gcd-benchmarks.cr
all good
gcd1 738.48M (  1.35ns) (± 2.52%)  0.0B/op        fastest
gcd2 737.69M (  1.36ns) (± 2.55%)  0.0B/op   1.00× slower


```

**Comment by yxhuvud** [comment]
You might have to enable arch specific optimizations for it to actually
make a difference

**Comment by jzakiya** [comment]
I ran this on a Linux based AMD Ryzen 9 5900HX, 4.5GHz, 8C|16T laptop.
What special things need to be enabled to compile it more optimally?

**Pull request merged**
