### PR TITLE
Interpreter: handle yield with splat combined with tuple unpacking

### LINKED ISSUE #12227: Interpreter: Error: BUG: missing upcast_distinct from Tuple(String, String) to String (Crystal::TupleInstanceType to Crystal::NonGenericClassType)
Example code:
```crystal
class A
  private getter flashes = {} of String => String

  delegate each, to: flashes
end

a = A.new

a.each do |k, v|
  puts k
  puts v
end
```

Interpreter error:
```
$ cr i local/bugs/delegate_bug.cr 
Using compiled compiler at /home/chao/git/personal/crystal/.build/crystal
In local/bugs/delegate_bug.cr:9:3

 9 | a.each do |k, v|
       ^---



In local/bugs/delegate_bug.cr:9:3

 9 | a.each do |k, v|
       ^---
Error: compiling a.each do |k, v|

  puts(k)
  puts(v)
end


In local/bugs/delegate_bug.cr:4:3

 4 | delegate each, to: flashes
     ^
Error: expanding macro


There was a problem expanding macro 'delegate'

Called macro defined in /home/chao/git/personal/crystal/src/object.cr:1292:3

 1292 | macro delegate(*methods, to object)

Which expanded to:

 >  1 |     
 >  2 |       
 >  3 |         def each(*args, **options)
 >  4 |           flashes.each(*args, **options)
 >  5 |         end
 >  6 | 
 >  7 |         
 >  8 |           def each(*args, **options)
 >  9 |             flashes.each(*args, **options) do |*yield_args|
 > 10 |               yield *yield_args
 > 11 |             end
 > 12 |           end
 > 13 |         
 > 14 |       
 > 15 |     
 > 16 |   



In local/bugs/delegate_bug.cr:4:3

 4 | delegate each, to: flashes
     ^
Error: expanding macro


There was a problem expanding macro 'delegate'

Called macro defined in /home/chao/git/personal/crystal/src/object.cr:1292:3

 1292 | macro delegate(*methods, to object)

Which expanded to:

 >  1 |     
 >  2 |       
 >  3 |         def each(*args, **options)
 >  4 |           flashes.each(*args, **options)
 >  5 |         end
 >  6 | 
 >  7 |         
 >  8 |           def each(*args, **options)
 >  9 |             flashes.each(*args, **options) do |*yield_args|
 > 10 |               yield *yield_args
 > 11 |             end
 > 12 |           end
 > 13 |         
 > 14 |       
 > 15 |     
 > 16 |   
Error: BUG: missing upcast_distinct from Tuple(String, String) to String (Crystal::TupleInstanceType to Crystal::NonGenericClassType)
```

### PR DESCRIPTION
**Pull request by asterite**
Fixes #12227

### CODE REVIEW

**Comment by cyangle** [comment]
@asterite This PR breaks the existing interpreter tests.

**Comment by asterite** [comment]
Thanks! I pushed a commit that should fix things.

**Review by straight-shoota — APPROVED** [review]

**Comment by asterite** [comment]
@straight-shoota thank you for the marathon review!

**Comment by straight-shoota** [comment]
Thanks for your marathon patches 🙇
I just try to help you keep rolling 😉

**Pull request merged**
