### PR TITLE
Documentation for HTTP.rfc1123_date.

### PR DESCRIPTION
**Pull request by akzhan**
Heavily inspired by http://ruby-doc.org/stdlib-2.0.0/libdoc/cgi/rdoc/CGI.html#method-c-rfc1123_date

### CODE REVIEW

**Comment by akzhan** [comment]
@bew it's not true. A lot of documentation has same output without any `puts`.

Simply look for `#.+# =>` regular expression in src folder.

**Comment by Sija** [comment]
`string = ` part is IMO redundant since there's return type annotation.

**Comment by akzhan** [comment]
@Sija,@bew thanks, assignment removed.

**Comment by Sija** [comment]
btw, thanks for filling gaps in documentation, much appreciated! 👍

**Comment by Sija** [comment]
@akzhan `string = ` assignment is still there.

**Comment by akzhan** [comment]
@Sija Fixed.

P.S.: I will commit code without force updates due to keep comments history.

**Comment by Sija** [comment]
@akzhan no need to, they'll probably be squashed anyway.

**Comment by RX14** [comment]
@Sija Keeping commit/comment history is useful for the duration of the PR, even if they will be squashed and not preserved when merged into master.

**Comment by bcardiff** [comment]
Thanks again @akzhan ! As @Sija said, contributions to docs are important 👍

**Pull request merged**
