### PR TITLE
Wrap GenericInstanceType in link if type vars don't have link

### PR DESCRIPTION
**Pull request by MakeNowJust**
See [`Hash(K, V)` doc](https://crystal-lang.org/api/0.20.1/Hash.html):

This pull request makes `Enumerable({K, V})` wrap in link.

### CODE REVIEW

**Comment by asterite** [comment]
Awesome, thank you!! ❤️ 

It's so nice to see that you and others are starting to send PRs to the compiler's code, doc generator, etc. :-)

**Comment by RX14** [comment]
@asterite I should learn compiler internals... Maybe I'll try and find some easy PRs over the holidays.

**Comment by asterite** [comment]
@RX14 I plan to give a talk at Manas about how the compiler works, so more people there could start collaborating on the compiler. The talk will be in Spanish, but I'll take notes in English to prepare it, maybe do some slides. Once I do that I'll share it so others can jump into the compiler too. I believe there's a lot of room for improvements to the compiler, both in terms of code organization, readablity and performance.

**Comment by samueleaton** [comment]
@asterite que bueno que hablo español, jaja. pero en verdad eso sería bien chévere. Por favor, hagalo 👍

**Comment by Sija** [comment]
This PR broke links rendering, see below:

image

**Pull request merged**
