### PR TITLE
Deny invalid project name chars '\' & '/''

### LINKED ISSUE #4817: Bad fs structure with `crystal init lib /path/to/project`
While working on #4691 I've found a weird behavior of some specs:
https://github.com/crystal-lang/crystal/blob/b5dd948dfb74e883e64156a121f3f1d871cd2c3e/spec/compiler/crystal/tools/init_spec.cr#L166

As an example it'll generate the following project structure:
```
$ crystal init lib /tmp/path/to/my_lib
      create  /tmp/path/to/my_lib/.gitignore
      create  /tmp/path/to/my_lib/.editorconfig
      create  /tmp/path/to/my_lib/LICENSE
      create  /tmp/path/to/my_lib/README.md
      create  /tmp/path/to/my_lib/.travis.yml
      create  /tmp/path/to/my_lib/shard.yml
      create  /tmp/path/to/my_lib/src//tmp/path/to/my_lib.cr
      create  /tmp/path/to/my_lib/src//tmp/path/to/my_lib/version.cr
      create  /tmp/path/to/my_lib/spec/spec_helper.cr
      create  /tmp/path/to/my_lib/spec//tmp/path/to/my_lib_spec.cr
Initialized empty Git repository in /tmp/path/to/my_lib/.git/
$ tree /tmp/path/to/my_lib
/tmp/path/to/my_lib/
├── spec/
│   ├── tmp/
│   │   └── path/
│   │       └── to/
│   │           └── my_lib_spec.cr
│   └── spec_helper.cr
├── src/
│   └── tmp/
│       └── path/
│           └── to/
│               ├── my_lib/
│               │   └── version.cr
│               └── my_lib.cr
├── LICENSE
├── README.md
└── shard.yml
```
We can see that there are some files with incorrect path, like `/tmp/path/to/my_lib/src//tmp/path/to/my_lib.cr`.

Here using `/tmp/path/to/my_lib` will use `/tmp/path/to/` as the path, and `/tmp/path/to/my_lib` as the project name, and some files are generated as `<path>/src/<project_name>/file.cr`.

---

I think this is an unwanted behavior, there are multiple things we could do to prevent it:

1. **Prevent the use of `/` in the project name**: we ensure the following usage `crystal init lib|app <project_name> <path>`. An example would be `crystal init lib my_lib /tmp/path/to/my_lib`. The only drawback I see is that we need to write the project name twice, if we want it to be in a specific path.

2. **Extract the project name from the given path**: `/tmp/path/to/my_lib` will give `/tmp/path/to/` as path, and `my_lib` as the project name. The example `crystal init lib /tmp/path/to/my_lib` would then work as expected.

What do you think?

### PR DESCRIPTION
**Pull request by bew**
Fixes #4817

### CODE REVIEW

**Comment by straight-shoota** [comment]
There are other characters that can't appear in a file name (differs slightly depending on OS). I suggest to have a method in `File` (or later `Path`) to check if a string is a valid path component.

This SO answer looks quite comprehensive: https://stackoverflow.com/a/31976060/7401689

**Comment by bew** [comment]
Also, instead of having a blacklist, we could go the other way and have a whitelist?
This is the project name, this name will be used (with some modifications) for the module name in the generated code

**Comment by bew** [comment]
Thinking more about this, the whitelist solution will never be complete, as almost any unicode char is allowed in a module name (like `A€あ`).

So either:
- the tool only handles a subset of what's possible, by allowing only alphanumeric + dash & underscore
- we try to list all the unsupported chars (like `>`, `:`, `/`, `{`, `}`, ....) and test each of them to make sure the name is fully correct.

**Comment by straight-shoota** [comment]
I don't see a reason to artificially restrict the usage of arbitrary unicode characters in file names. So it should  only check against a blacklist of (potentially) invalid characters.

**Comment by petoem** [comment]
@straight-shoota Nice idea! We can add a list of invalid chars to `File` or later `Path` and have a method check if a string is valid.
dotnet has `GetInvalidFileNameChars` and `GetInvalidPathChars`, both for [unix](https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/IO/Path.Unix.cs#L13-L15) and [windows](https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/IO/Path.Windows.cs#L12-L28).

**Comment by straight-shoota** [comment]
Closing in favor of #8737
Thank you nevertheless @bew

**Pull request closed without merging**
