### PR TITLE
Disable double write buffering in OpenSSL sockets

### LINKED ISSUE #7458: Double buffering in OpenSSL::SSL::Socket
This seems like a contradiction: 

https://github.com/crystal-lang/crystal/blob/c9d1eef8fde5c7a03a029d64c8483ed7b4f2fe86/src/openssl/ssl/socket.cr#L87-L92

I suspect it should be `io.sync = true`?

### PR DESCRIPTION
**Pull request by carlhoerberg**
This fixes #7458 and #7456

### CODE REVIEW

**Comment by asterite** [comment]
I approve this because:
- it apparently fixes two issues
- I'm almost sure the code was supposed to match the comment, but it wasn't the case

@carlhoerberg Thank you!

**Comment by asterite** [comment]
I wonder if tests can be included for this. That way this stays working forever.

**Comment by asterite** [comment]
At least by including some manual specs (which are run before releasing, I think). This is in `spec/manual`

**Comment by carlhoerberg** [comment]
I don't know if it's reliable for all kind of things related to OpenSSL buffering, but for this case this code triggered it every time: https://github.com/crystal-lang/crystal/issues/7456#issuecomment-465319901

**Pull request merged**
