### PR TITLE
Add `CrystalPath.expand_paths`, expand relative to compiler path

### LINKED ISSUE #7391: Merge the /bin/crystal Shell script in the compiler?
The [/bin/crystal](https://github.com/crystal-lang/crystal/blob/master/bin/crystal) script is setting environment variables, then calling the compiler.

The questions are:
- is it a limitation of the language to not be able to write this script directly in Crystal?
- can't this environment variables like our other ones in our `.bashrc` or `.zshrc`?
- How about Windows, would it be in Powershell?

Issues:
- As noted by jemc on Gitter/IRC, this complicates compiler debugging with tools like lldb.
- This also render counter-intuitive to have multiple crystal - one may think to copy the shell script, which isn't going to work.

I think exposing `CRYSTAL_PATH=$CRYSTAL_ROOT/src:lib`, and potentially other variables, through an API that can be used by `shards` and other projects (ameba?)  would be a nice plus, instead of assuming the library path in each project and hard-coding it.

### PR DESCRIPTION
**Pull request by straight-shoota**
This patch adds support for runtime expansion of `CRYSTAL_PATH` and `CRYSTAL_LIBRARY_PATH`. It allows resolving the path to source file locations (such as the standard library) and binary libraries (such as bundled libraries) relative to the compiler location at runtime. This avoids the need to bake absolute paths into the compiler and using a wrapper script for distribution (https://github.com/crystal-lang/distribution-scripts/blob/8bc01e26291dc518390129e15df8f757d687871c/linux/files/crystal-wrapper). In fact, this essentially replicates the behaviour of the wrapper script, just embedded in the compiler directly.

It integrates perfectly with all existing usage. The new behaviour only becomes active when `CRYSTAL_PATH` or `CRYSTAL_LIBRARY_PATH` includes the pattern `$ORIGIN`. Existing use cases such as the wrapper script or bakinging absolute paths continue to work and will continue to do so.

The real value comes when this is baked in via `CRYSTAL_CONFIG_PATH` and `CRYSTAL_CONFIG_LIBRARY_PATH` because that makes the compiler binary work standalone, as long as it finds the standard library and bundles libraries in the designated paths relative to its location.
The defaults in the `Makefile` are:

* `CRYSTAL_PATH="$ORIGIN/../share/crystal/src"`
* `CRYSTAL_CONFIG_LIBRARY_PATH="$ORIGIN/../lib/crystal"`

These location fit the typical install paths `/usr/share/crystal/src` and `/usr/lib/crystal` relative to the compiler location at `/usr/bin/crystal`. This will become even more useful with `make install` (#10702) and adaptation in distribution-scripts.

This PR succeeds #10877 and should be more complete and easier to review, with a couple of refactors upfront.

Resolves #7391

### CODE REVIEW

**Review by beta-ziliani — APPROVED** [review]
LGTM 👍

**Comment by straight-shoota** [comment]
I had to fiddle with the `Makefile` configuration, but it looks good now.

Setting `CRYSTAL_CONFIG_LIBRARY_PATH` in the `Makefile` is actually not necessary, because the `bin/crystal` wrapper already sets it correctly when missing (that's been the case since #9423).

Only the build recipe (`$(O)/crystal`) needs `CRYSTAL_CONFIG_LIBRARY_PATH` configured. The compiler binary should have that installation path baked in, even if it's only used in development. In that case it's invoked through the wrapper, which sets `CRYSTAL_LIBRARY_PATH` to the installed libraries path.

**Comment by straight-shoota** [comment]
@jhass I'd be happy if you can take a look at this.

**Review by jhass — APPROVED** [review]
I'm still not entirely convinced we need this, but I guess there's no harm either.

**Pull request merged**
