### PR TITLE
Disallow negative enum flag values

### LINKED ISSUE #5955: What to do with negative enum flags values
While doing #5954 I noticed this behavior:
```cr
@[Flags]
enum Foo
  Bar = -2
  Baz
end

pp Foo::Bar.value # -2
pp Foo::Baz.value # -4
```
Is it intended? Or should this be an error (for flag enum at least) ?

If it should be an error, maybe we should also restrict enum flags to unsiged integer type (e.g: default to `UInt32` instead of `Int32`)

### PR DESCRIPTION
**Pull request by bew**
Closes #5955

### CODE REVIEW

**Comment by bew** [comment]
The failing test is: (introduced in 0eb47f52d4b0115ef107859597070bd711c4f406)
```cr
  it "casts All value to base type" do
    run(%(
      @[Flags]
      enum Foo
        A = 1 << 30
        B = 1 << 31
      end

      Foo::All.value
      )).to_i.should eq(-1073741824)
  end
```
I'm not sure how to understand it and make the proper change if needed.
@asterite any idea? Ty

**Comment by mjago** [comment]
Unsigned I agree ~ for flags. Signed doesn't make sense :+1:

**Comment by bew** [comment]
Any opinions from core devs?

**Comment by asterite** [comment]
C# allows negative enums just fine. Is there a bug related to this, or it's just something that we are considering we could change? Because if there's no bug, and everything is working fine, I'd rather not touch the language, specially if there's a new failing spec because of this (I understand it gives a negative value, but bitwise for flags it makes sense, even if it overflows).

**Comment by RX14** [comment]
@asterite does C# have flags enums?

**Comment by asterite** [comment]
@RX14 Yes. That's where we got the inspiration from ;-)

And flags enum just add `+1` to enum values, just like non-flags enums. In C# you are supposed to explicitly list flags enum members values: 1, 2, 4, 8, etc. So Crystal is (maybe) a bit better. I don't know if I'd bother with doing something with negative values... just my personal opinion, though.

**Comment by bew** [comment]
It turns out negative **enum flags** are quite buggy: https://play.crystal-lang.org/#/r/4rde
I'm not even sure it should work if we want to make that work, as from my understanding negative **enum flags** makes no sense.

**Comment by bew** [comment]
@asterite (and core team) as showed in previous comment, flags enums with negative values are quite buggy from user-point-of-view, I'd suggest we make enum flags _always_ unsigned, wdt?

**Comment by bcardiff** [comment]
@bew the sample you show as buggy is not because the enums can be negative but because you can define overlapping values. 

It is not obvious what is the value assigned to the next member when overriding one value, that could be improved/reviewed maybe.

The bug I am aware of is that if the enum base is changed to a 64 bits integer then the internal counter is not using all the available range of values, hence 64 bits integer enum needs to be explicitly defined.

**Comment by straight-shoota** [comment]
Seems this can be closed.

**Pull request closed without merging**
