### PR TITLE
Allows passing flags to disable linking of openssl and zlib

### PR DESCRIPTION
**Pull request by asterite**
This is a **temporary** solution for the upcoming release of the compiler. We might want to include an HTTP::Server in the compiler but without linking against openssl and zlib. For example we removed the browser tool because of this, and we might want to bring it back.

So, omnibus would build Crystal with `-D without_openssl -D without_zlib` but still be able to include an HTTP::Server.

This also affects the HTTP::Client (basically passing `-D without_zlib` doesn't add an "Accept-Encoding: gzip deflate" header).

This also allows creating any Crystal app that includes an HTTP::Server but, again, without linking against openssl, although we might change this "disabling" mechanism in the future.

### CODE REVIEW

**Comment by ysbaddaden** [comment]
Is it really required? Both zlib and openssl are very likely to be installed, thus available.

**Comment by waterlink** [comment]
The less dependencies compiler has - the better.

Imagine scenario, when a programmer has bleeding edge versions (or too old) of `zlib` and/or `openssl` installed. This will result in all sorts of weird bugs.

Additionally, it adds more dependencies for all packages for different distributions. And they need to be maintained.

**Comment by luislavena** [comment]
@asterite can I ask about the need for this temporary solution? While you might not need openssl or zlib for the compiler, most likely you will still require them when building things, so these dependencies will still be required.

Is this in response to an specific issue?

Cheers.

**Comment by asterite** [comment]
@luislavena We can't make omnibus build crystal if it links against openssl. But I guess we'll just try harder next time instead of adding these ifdefs.

**Comment by ysbaddaden** [comment]
Maybe `dlopen` could help, but that's the hard way.

**Comment by asterite** [comment]
@luislavena If you don't pass `-D without_openssl` (or zlib), everything still works as it's working now. We want these flags so we can build the compiler with an HTTP::Server inside it but without linking against openssl nor zlib, that's all. It doesn't affect any other application that doesn't pass those flags.

**Comment by luislavena** [comment]
I see, thank you for the details @asterite :smile:

**Pull request merged**
