### PR TITLE
Add String#center

### PR DESCRIPTION
**Pull request by ilja**
This adds String#center: `"hello".center(9, '-')` => `--hello--`

### CODE REVIEW

**Comment by asterite** [comment]
I agree with @bcardiff , it's better to keep the code clean and separate from the other methods

**Comment by straight-shoota** [comment]
@ilja Are you still interested in meeting the requested changes?

**Comment by hutou** [comment]
A String.center method would be useful for me. 
Is there any chance to see this PR validated ?

**Comment by straight-shoota** [comment]
The author hasn't responded in two years, so I expect this PR to be stalled. An implementation as suggested above would be very welcome. Feel free to submit a new PR for adding this!

**Comment by hutou** [comment]
Ok, I'll submit a PR soon.

**Comment by bcardiff** [comment]
Closed by #8557

**Pull request closed without merging**
