### PR TITLE
Let ZeroOneOrMany be mutable

### PR DESCRIPTION
**Pull request by asterite**
@straight-shoota Here's with ZeroOneOrMany as a mutable type.

I personally don't like mutable structs, but 🤷 

(I know the old way also mutated a value pointed by the struct, but that's different)

### CODE REVIEW

**Comment by asterite** [comment]
What I don't like about this struct being mutable is that the natural names to mutate things would be `push` and `concat`. And that means that if we replace an `Array(T)` with `ZeroOneOrMany(T)` things might still compile but work in a wrong way.

**Comment by yxhuvud** [comment]
The vast majority of these have 0 or 1 elements, right? Perhaps a singly-linked list could do well? It would be slightly worse in cases with many elements, but that case may not be common enough to matter?

**Comment by asterite** [comment]
The main issue with a singly-linked list is that even if it just has one element I believe you need to allocate memory for that node, right?

**Comment by yxhuvud** [comment]
Well you need to allocate memory for the zero one or many struct as well, but i suppose it would be too intrusive to embed next-pointers into the `T` elements themselves, adding indirection. :(

**Comment by asterite** [comment]
> Well you need to allocate memory for the zero one or many struct as well

This is relative: if the zero-one-or-many is held by another type, its memory is already there in the other type.

**Comment by straight-shoota** [comment]
Yeah, no I don't think this is the way to go.

**Pull request closed without merging**
