### PR TITLE
OpenSSL server socket fixes

### PR DESCRIPTION
**Pull request by ysbaddaden**
1. Close underlying IO on SSL accept errors.
2. Report EOF instead of raising SSL_ERROR_ZERO_RETURN (the socket was normally closed). This happens to me all the time with cURL making requests to `HTTP::Server` that waits for another request (keepalive).

### CODE REVIEW

**Comment by denysvitali** [comment]
@sdogruyol It seems that this is the fix we're looking for. Can you try it?

**Comment by denysvitali** [comment]
cc @rdp

**Comment by ysbaddaden** [comment]
Not exactly. There is another fix: ensure to close the underlying socket, whatever if it failed to flush pending data.

**Comment by sdogruyol** [comment]
Related to https://github.com/crystal-lang/crystal/issues/4003

**Comment by ysbaddaden** [comment]
Now with a fix for #4003.

**Pull request merged**
