### PR TITLE
Set default host in HTTP::Client#exec

### LINKED ISSUE #6480: HTTP::Client#exec causing some "400 Bad Request" response when using it with HTTP::Request object.
The following code triggers a 400 response from example.com:

```crystal
require "http/client"

client = HTTP::Client.new "www.example.com"
req = HTTP::Request.new("GET", "/")
resp = client.exec HTTP::Request.new("GET", "/")
puts resp.status_code # 400
```

Note that `HTTP::Client#exec` seems to be generating an HTTP request without the `Host` header.  Adding the missing header will trigger expected 200 response.

```crystal
req2 = HTTP::Request.new("GET", "/", HTTP::Headers.new.tap{|h| h["Host"] = "example.com"})
resp2 = client.exec req2
puts resp2.status_code # 200
```

Class method is working as expected:
```crystal
puts HTTP::Client.exec("GET", "http://www.example.com/").status_code # 200
```

I also noticed that this didn't seem to be a problem on google.com
```crystal
client2 = HTTP::Client.new "www.google.com"
resp3 = client2.exec(req)
puts resp3.status_code # 200
```

The reason I ran into this problem was because I was trying to send the same `Request` object to multiple Hosts.  I expect I should be able to reuse the same request object cross multiple client / hosts.  Is this an acceptable usage pattern of the HTTP::Client API? 

```
crystal -v
Crystal 0.25.1 (2018-06-30)

LLVM: 5.0.2
Default target: x86_64-apple-macosx
```

### PR DESCRIPTION
**Pull request by straight-shoota**
Fixes #6480

### CODE REVIEW

**Comment by asterite** [comment]
Just note that even though this is a good change, the original issue is not solved: the use case was to send a request to multiple hosts by reusing the request instance. Because the host is only set if it's not set already, that won't work.

Maybe we should remove the exec methods from being public. I don't think there's a sane way to reuse request objects, unless we dup/clone them in exec, but that's of course not ideal.

**Comment by straight-shoota** [comment]
Yeah, I figured as much. But the original issue can be solved by dup-ing the request when providing it to `exec`: `client.exec(request.dup)`.

Obviously, this is not ideal, but it works fine for that use case. I'd suggest to merge this fix and continue with #6011 to redesign HTTP client.

**Comment by asterite** [comment]
I would recommend then documenting this behavior, mentioning that reusing an `HTTP::Request` shouldn't be done because the `Host` header is set once per request. That's why I would maybe prefer to hide the `exec` method, and so there's no way to misuse the API.

**Comment by straight-shoota** [comment]
An alternative solution would be to modify `HTTP.serialize_headers_and_body` to insert default `host` argument provided as argument if it is missing from headers.

**Comment by z64** [comment]
@asterite re: removing `exec(request : HTTP::Request)`

For what it's worth, I've made good use of this method in libs. It's been helpful to construct a namespace of `HTTP::Request` factory methods that my own `Client` implements in order to spec/unit test the requests nicely against API documentation without having to actually execute them,  and where building a mock API service would be much more expensive (as in time consuming) task, and this is just as likely to ensure I've written working runtime code.

Basically:
```cr
# requests.cr
module Request
  extend self

  def get_resource(id : ID)
    HTTP::Request.new("GET", "/resource?id=#{id}")
  end
end

# client.cr
class Client
  @http_client : HTTP::Client

  def exec(request : HTTP::Request)
    @http_client.exec(request)
  end

  def get_resource(id : ID)
    response = Request.get_resource(id)
    Resource.from_json(response.body)
  end
end

# request_spec.cr
it "#get_resource" do
  request = Request.get_resource(1)
  request.method.should eq "GET"
  request.path.should eq "/resource"
  request.query.should eq "id=1"
end
```
I could replace this with my own types if removed with a slightly more complicated interface, but having `exec(request : HTTP::Request)` has been helpful in this regard, where things like rspecs `expect(api_client).to receive(:get_resource).with(resource_id)` doesn't exist in crystal

Maybe mock connections via #6011 would provide a equally simple solution, but that's still an abstract bullet point on the list, so I don't know

**Comment by newtonapple** [comment]
Correct me if I'm wrong, by removing `HTTP::Client#exec(request : HTTP::Request)` from the public API, it will effectively eliminate all public use cases / needs for `HTTP::Request`, correct?  I personally think having a reusable `HTTP::Request` can be quite useful a number of scenarios.

**Comment by RX14** [comment]
A reusable `HTTP::Request` doesn't make sense because the body should be an `IO`, which is consumed on use.

**Pull request merged**
