### PR TITLE
Fix warning on using Channel.select

### PR DESCRIPTION
**Pull request by asterite**
https://github.com/crystal-lang/crystal/issues/8409#issuecomment-548513517

### CODE REVIEW

**Comment by wontruefree** [comment]
should there be a test for this?

**Comment by bcardiff** [comment]
If deprecated code is not tested it is not guaranteed to stay working. 

I prefer a CI with warnings rather than untested deprecated methods. But If I'm the only one who thinks that way, we can go ahead.

**Comment by asterite** [comment]
> If deprecated code is not tested it is not guaranteed to stay working

Oh, I didn't know that was the reason it was kept.

**Comment by straight-shoota** [comment]
Maybe we could consider adding comments for such specs that are explicitly meant to test deprecated behaviour. Otherwise I expect we will eventually get more "fix warning" PRs in the future.

**Comment by straight-shoota** [comment]
I'll award bonus points for having a mechanism for designating a spec as testing a specific deprecated method and disabling deprecation warnings for this method inside the specs body.

**Comment by bcardiff** [comment]
Definitely. But is either be 

* a new keyword to be applied in a given lexical scope (as `checked` in https://github.com/crystal-lang/crystal/pull/6223) or
* an annotation that could express only for the whole method level. (not useful in specs)
* magic comments (I don't like it)

So, something like this?

```cr
pragma(allow_deprecated: true) { expr }
```

**Comment by asterite** [comment]
I don't think this is worth our efforts. After all it's just a warning.

**Comment by straight-shoota** [comment]
I agree. It was just an idea that popped into my head but should be filed under "in case you're bored and have nothing else to do".

**Comment by straight-shoota** [comment]
I don't know why I kept thinking about this. But it bugged me. And I think this could actually be very simple to implement. Because this really only affects specs and deprecated methods should only be called *directly* in the spec body, a naive static filter should be enough.

```cr
require "spec"

@[Deprecated]
def deprecated
end

it "test deprecated method" do
  deprecated
end
```
This is the warning:
```
In deprecation_spec.cr:8:3

 8 | deprecated
     ^---------
Warning: Deprecated top-level deprecated.
```

`crystal spec`, after compiling the program reports the warnings. These could simply be filtered based on file and line number. If it's in a spec file and maybe has some kind of annotation naming the deprecated method that should be suppressed.

Obviously this won't work if the deprecated method is called indirectly. But that should be avoided anyway because it would mean the deprecated method is used in some code other than specs.

**Comment by asterite** [comment]
The warnings are reported during compilation, not at runtime. I don't know if you took that into account.

**Comment by straight-shoota** [comment]
Yes. Runtime doesn't matter. The `spec` command knows about the warnings an has the source code. So it can easily lookup the warning location in the source and check whether there is for example a comment designating this spec as testing a deprecated method.

**Comment by RX14** [comment]
The warnings code already has a check for which directories to ignore warnings in (`lib`). It would be trivial to expose that on the crystal commandline, and add `spec`.

**Comment by straight-shoota** [comment]
This off-topic discussion should be continued in #8477

**Pull request closed without merging**
