### PR TITLE
Refactor `EventLoop` interface for sleeps & select timeouts

### PR DESCRIPTION
**Pull request by ysbaddaden**
A couple refactors related to select timeout and the signature of Crystal::EventLoop::Event#add that only needs to handle a nilable for libevent (because it caches events); other loop don't need that.

Extracted from #14959

### CODE REVIEW

**Comment by ysbaddaden** [comment]
Argh, it doesn't work on its own because IO::Evented isn't isolated to the libevent event loop (yet).

**Review by straight-shoota — APPROVED** [review]

**Comment by jkthorne** [comment]
This PR actually changes the API.  you have to pass 2 args to Fiber#timeout() and nil is no longer an option.

I am not saying this is the wrong choice but it did break a library.  Should there be a PR to add a deprecation warning or something?

**Comment by ysbaddaden** [comment]
That method should actually be nodoc (like the related methods): there's no way to create a `Channel::SelectAction` that is a private type.

**Comment by straight-shoota** [comment]
Yeah, this is technically a breaking change because the method was part of the public API. But I suppose it wont't be feasible to uphold this signature in a deprecated state because of the internal changes requiring a `timeout_select_action` for a timeout.

@jkthorne Could you tell a bit more about how/where this is used? Does it also cancel the timeout, and if so, how? `Fiber.cancel_timeout` is only available for the current fiber, so a suspended fiber needs to resume somehow in order to cancel a timeout.

**Pull request merged**
