### PR TITLE
number: Add `#positive?` and `#negative?`

### PR DESCRIPTION
**Pull request by woodruffw**
Adds `#positive?` and `#negative?` to Crystal's `Number`.

~Will add unit tests in a moment.~ Done.

### CODE REVIEW

**Comment by j8r** [comment]
Duplicate of https://github.com/crystal-lang/crystal/pull/6552

**Comment by woodruffw** [comment]
To summarize my argument for this (on Gitter):

1. Crystal's `Number` represents real numbers, and the definitions of "positive" and "negative" are settled for real numbers.
2. `positive?` and `negative?` make for much nicer reading in conditions and blocks and are consistent with "say what you mean" semantics (one of the things that makes writing Crystal from a background in Ruby so pleasant)
3. `Number` already defines both `sign` and `zero?`, accepting the settled definition of `sgn(R)`. The addition of `positive?` and `negative?` is consistent with the current semantics.

**Comment by j8r** [comment]
This isn't really the same as `#zero?`, because it isn't only defined in `Number`:
- [Complex#zero?](https://crystal-lang.org/api/master/Complex.html#zero%3F%3ABool-instance-method)
- [Time::Span#zero?](https://crystal-lang.org/api/master/Time/Span.html#zero?:Bool-instance-method)

Even if `Number#zero?` isn't that necessary, it's an already known method name.

**Comment by asterite** [comment]
Sorry, duplicate of something we rejected in the past.

**Pull request closed without merging**
