### PR TITLE
.downcase(Unicode::CaseOptions::Fold) without char ranges

### PR DESCRIPTION
**Pull request by akzhan**
The Fold option is required for correct Unicode string comparison using fold case.

It consumes more memory than #4512.

### CODE REVIEW

**Comment by sdogruyol** [comment]
Thank you @akzhan 💯

**Comment by akzhan** [comment]
Looks like we need an option for `downcase` to fold instead of proposed casefold method.

Will rework.

**Comment by akzhan** [comment]
Just for information - trying to extract case fold information using CaseRange:

* Number of records decreased twice approx. 600.

So there is no actual reason to save this information with ranges.

**Comment by akzhan** [comment]
There can be only one.

**Pull request closed without merging**
