### PR TITLE
Address FIXME

### PR DESCRIPTION
**Pull request by vlazar**
I've noticed a FIXME comment intended to be addressed once the issue #8015 is fixed. It is fixed now by #8019.

### CODE REVIEW

**Comment by Blacksmoke16** [comment]
Wouldn't this break with `Nil` since there isn't any logic handling it now?  The FIXME said to merge it with the previous conditional, not to remove it entirely.

**Comment by vlazar** [comment]
@Blacksmoke16 These are the cases I've checked locally:

```crystal
p! Pointer(Void).null.as(Nil) # => nil
p! nil.as(Void*).as(Nil) # => nil
a = 1_i64
p! pointerof(a).as(Nil).nil? ? 3 : 7 # => 3
```

First two from https://github.com/crystal-lang/crystal/issues/8015#issue-474832454
The third one from this spec https://github.com/crystal-lang/crystal/pull/8019/files#diff-c4efe0ebc6736f5e9dc5804721a547f6R68

**Comment by Blacksmoke16** [comment]
I don't know enough about this to know if its an issue or not.  I was just pointing out that `Nil` gets handled by the else block now, versus the if block.

https://play.crystal-lang.org/#/r/7uyr

**Comment by vlazar** [comment]
@Blacksmoke16 Thank you for pointing this out! I think there is a tiny chance (99.999...%) you are right and I should have did this instead:

```crystal
  def self.unbox(pointer : Void*) : T
     {% if T <= Reference || T == Nil %}
       pointer.as(T)
     {% else %}
       pointer.as(self).object
     {% end %}
  end
```

**Pull request merged**
