### PR TITLE
Print original exception after failing to raise it

### PR DESCRIPTION
**Pull request by jhass**

### CODE REVIEW

**Comment by jhass** [comment]
Well, unfortunately that was too easy. It seems to break CI

**Comment by jhass** [comment]
Well, looks like I fixed it!

**Comment by waj** [comment]
@jhass, this looks good, but is that `rescue nil` really necessary?

**Comment by jhass** [comment]
Probably not, it's admittedly defensive. I just figured given we're already in a weird state, we don't need to confuse users with any potential more weird error messages they cannot do anything about.

**Comment by waj** [comment]
Yes, I understand. `print_exception` is actually quite defensive already 🙂 https://github.com/crystal-lang/crystal/blob/master/src/crystal/system/print_error.cr#L26

If you don't mind, I would remove that. Actually there are still many `rescue nil` in the std that I want to get rid of (and after that I would like to remove that feature completely 😝)

**Pull request merged**
