### PR TITLE
Add support to jquery version 3

### PR DESCRIPTION
**Pull request by deiv**
Change some envents handlers, to use the 'on' method

### CODE REVIEW

**Comment by RX14** [comment]
But why? We use jquery 2.2.1?

**Comment by asterite** [comment]
Thank you! 

Is there something broken that this fixes?

**Comment by deiv** [comment]
Not, it not fixes something, it onlys allows to run the play server, with jQuery >= 3.

Use case:
For package in Debian, we drop the javascript libraries distributed inside the crystal source code (jquery, codemirror, etc). The current jQuery version in Debian is 3, so I use it in the play server.

**Comment by asterite** [comment]
Did anyone try this? If it works, I see no reason not to merge it.

**Comment by Sija** [comment]
Would it make sense to update vendored jQuery to v3 then?

**Comment by straight-shoota** [comment]
Thanks @deiv 

@Sija jQuery could be updated, but I don't think it's a pressing matter. The playground is only intended for local use anyways, and as longs as it works...
But if someone feels like doing that, please provide a PR.

**Pull request merged**
