### PR TITLE
OpenBSD Improvements

### PR DESCRIPTION
**Pull request by chris-huxtable**
- Improves readability of arguments
- Improves similarity to referenced c headers
- Expands several sets of constants, functions, and function like macros

### CODE REVIEW

**Comment by ysbaddaden** [comment]
I'm sorry you took so much time to update C bindings for OpenBSD. They were automatically generated, and OpenBSD C headers don't set names for function arguments, hence the placeholder. Hence absense of comments, ...

We aim to eventually generate bindings on-the-fly, so any manual work in C bindings is superfluous.

**Comment by jhass** [comment]
Maybe we should add some comment at the top of these files that they're generated and manual changes might get overwritten? Ideally the generator would add such.

**Comment by RX14** [comment]
It's my opinion that saying "these C bindings are automatically generated" doesn't make any sense when we don't even have up-to-date manifests equivalent to all the manual definitions that have accumulated since these were automatically bootstrapped. We can't (without work) generate the equivalent set of C bindings in the stdlib today, so how can we say they're automatically generated? To me it's a double standard (we accept some manual edits but not others) which must be rectified by re-generating the bindings from scratch and not accepting any more edits which aren't generated by the generator.

**Comment by chris-huxtable** [comment]
- The man pages contain function arg names.
- If they are automatically generated there are a few type related errors that got through.

Why would we discard manually built documents if they were superior to ones auto-generated? That artificially keeps the base only as good as it can be auto-generated which has pretty big limitations without arg names and type errors. 

The end goal may be to auto-generate bindings on-the-fly but useful information is missed or doesn't make its way through. Shouldn't these files be as human friendly as possible?

Wouldn't a better and easier solution be a checker then a generator? Something that picks up on differences between the crystal and c headers and flags discrepancies rather then writing over everything wholesale? This would allow the best of both worlds.

**Comment by asterite** [comment]
@chris-huxtable I believe all the docs about this is in `man` pages already, or in openbsd somewhere. The bindings are just bindings to existing things which already exist and are documented, they aren't something new that needs a documentation to be understood. Plus most of it was generated automatically and never used by crystal users, only in some parts of the standard library, so it's internal. It doesn't matter if it's not sorted or undocumented because you can either way find references to them here, the internet, etc.

**Pull request closed without merging**
