### PR TITLE
Add reallocation and concatenation methods for slice

### PR DESCRIPTION
**Pull request by jreinert**

### CODE REVIEW

**Comment by technorama** [comment]
Does this work when another slice references the first?
```
slice1 = Slice.new(x)
slice2 = slice1[2, 3]

# memory in slice2 is invalid
slice1.truncate_to(0)

# memory was reallocated and slice2 is invalid
slice1.extend_by(x * 2) 
```

**Comment by jreinert** [comment]
@technorama i'd say the behavior would be undefined. `slice2` will have the old pointer of `slice1` with an offset of 2 as its pointer. So if the pointer of `slice1` is reallocated it can be any address. It _can_ be the same address too. that's why it's undefined.

**Comment by asterite** [comment]
For rellocation I'd use an array, not a slice.

**Comment by jreinert** [comment]
@asterite Hmm I see. Don't you think theres any performance difference in using slice with reallocation vs array? In Slice I would have more control over when it's reallocated and could so optimize it to my needs.

**Comment by jreinert** [comment]
@asterite I'd close this if it's not needed. I already have 7 branches and several more dependent ones lying around waiting for merging or closing. The less there are, the less I need to worry about them diverging.

**Comment by asterite** [comment]
I think array should be used as a higher-level abstraction for a growable thing that can also be shared. The problem with rellocating a slice, same as with a pointer, is that you can end up with old pointers. But maybe slice could also be used as a non-shared rellocatable thing. For example `Array` right now used a raw pointer and a capacity, but it could perfectly be a rellocatable slice.

Give us some time to review this :-)

**Comment by asterite** [comment]
I'll close this. For now I like the idea of Slice being immutable: simpler to understand. There's also the thing that a Slice would have to know if it owns the pointer (it was allocated by it) or not, so for example `realloc` would raise if the slice doesn't own the pointer. But for this it's better to use a raw pointer.

I also think back then we didn't have MemoryIO backed by a resizable slice (pointer), so maybe that was missing and this was more needed.

**Pull request closed without merging**
