### PR TITLE
Compiler: consider free vars in return type in abstract def check

### LINKED ISSUE #8766: AbstractDefChecker don't resolve free variables in return type
When declaring an abstract method that has a self-referencing outer type, but free inner such as:
```crystal
module Functor(T)
  abstract def fmap(&block : T -> U) : Functor(U) forall U
end
```
A compiler warning - `Warning: can't resolve return type Functor(U)` - is generated.

It appears that an additional resolution step may be required for free variables before flagging issues.

### PR DESCRIPTION
**Pull request by asterite**
Fixes #8766

Free variables will probably have to be considered in #9585 but it can be done in a later PR.

### CODE REVIEW

**Comment by jhass** [comment]
Why is this a warning instead of an error?

**Comment by asterite** [comment]
Because I didn't want to error in case there was a bug in the compiler. And in fact there was ;-)

Eventually it should probably be an error.

**Comment by bcardiff** [comment]
Why we need a new type type for this? `TypeParameter` has an owner which I get it does not apply on the type variables introduced by `forall`, but we already represent those with another entity, right? Or they are never something else than a Path instance?

It bugs me that there are two entities for type varriables with this PR.

**Comment by asterite** [comment]
Yes, I wanted to reuse that but, as you noted, it's bound to a generic.

After thinking a bit more, a fee variable named U is the same as one named X, or anything else, as you can see in one of the specs. However, in the spec there's also T and it would be right to consider that the same as U or X. That is, a type parameter isn't equal to a free variable introduced by a forall. That's why I decided that two types are needed.

**Comment by asterite** [comment]
Actually, it's a bit more complex. If there are two free vars X and Y, doing Foo(X, X) vs Foo(X, Y) will match now, when it shouldn't. Maybe we can close this PR until we figure out how all of this should be represented.

**Comment by bcardiff** [comment]
I don't follow the `Foo(X, X) vs Foo(X, Y)` issue.

In general knowing if a expression can be matched to another one is solved by a mgu algorithm: find if there is a substitution among free variables that will make the expression equals. 

In some sense we are doing that, but I think we are missing a couple of cases. Since the current code differs from the usual encoding of Martelli and Montanari algorithm, I always had this thought there where some uncover cases.

**Comment by asterite** [comment]
I think right now for generic types, they match if they are exactly equal. But since there's no concept for free vars yet it doesn't work.

**Pull request closed without merging**
