### PR TITLE
Add support for concurrency safe file operations.

### PR DESCRIPTION
**Pull request by technorama**
The purpose of the openat() function is to enable opening files in directories other than the current working directory without exposure to race conditions. Any part of the path of a file could be changed in parallel to a call to open(), resulting in unspecified behavior. By opening a file descriptor for the target directory and using the openat() function it can be guaranteed that the opened file is located relative to the desired directory.

openat() is part of POSIX.1-2008.

New Dir methods:
  open, open_file, exists?, stat, lstat, mkdir, rmdir, rename, delete

### CODE REVIEW

**Comment by technorama** [comment]
The build failure is from OS/X 10.9.  Is there any way to upgrade to 10.10?

**Comment by jhass** [comment]
No, there's no way to upgrade, Travis only offers this version: http://docs.travis-ci.com/user/osx-ci-environment/

**Comment by jhass** [comment]
http://blog.travis-ci.com/2015-09-09-xcode7-gm/

But then do we want to ditch 10.9 support?

**Comment by waj** [comment]
Can't we fallback to combining the dir path with the file path if `openat` is not available?

**Comment by technorama** [comment]
@waj falling back to full paths is almost the same unless chdir is performed.  I have a compatible module that does that (for ruby).  The only issue is checking if openat is available.  How do I do that without autoconf?

**Comment by waj** [comment]
> almost the same unless chdir is performed

You mean the behaviour would be different if we fallback to joining the dir path and the file path? How?

> The only issue is checking if openat is available. How do I do that without autoconf?

No! No autoconf!!.... :-P We've been thinking about this for https://github.com/manastech/crystal_lib and we'll probably come up with a better solution. But in the meantime I think the `HAVE_OPENAT` works just fine.

**Comment by asterite** [comment]
We can probably do this in the future, once we have a way to detect, at compile time, if a certain C function is present. So for now I'll close this (won't be merged any time soon).

**Comment by myfreeweb** [comment]
Can we resurrect this now? 10.10 is the *minimum* macOS on Travis now, so it should be safe to assume that there are no relevant unixes without `openat`.

`openat` is important for more than just concurrency — `openat` is the only way to open files under [Capsicum](https://www.freebsd.org/cgi/man.cgi?query=capsicum&sektion=4) sandboxing: you open file descriptors to directories you need, call `cap_enter()`, and now you can only open files under the directories you have descriptors to.

**Pull request closed without merging**
