### PR TITLE
Fixes for documentation generator

### PR DESCRIPTION
**Pull request by BlaXpirit**
Before/after:

Before/after

### CODE REVIEW

**Comment by asterite** [comment]
How can I reproduce this problem? I tried the link in `File`, using Chrome and it seems to be working well.

I wouldn't remove the tags, I would instruct the method not to generate them in the first place (just in case that regex removes more than it should)

**Comment by BlaXpirit** [comment]
@asterite Hmm that was in Firefox but somehow I can't full reproduce this today???
Anyway, at least the final bracket is cut off, in both Firefox and Chrome

About removing the tags - you know how there is that `links = true` / `links: links` flag passed around everywhere? Well, another flag would have to join it, which is a real mess and I think it's not worth bothering. At first I thought I could just turn this `links = true` into a `html = false` but there are instances where some HTML is needed but not links.

The regex can't remove more than it should because non-tag brackets must already be `&lt;``&gt;` at that point anyway.

**Comment by asterite** [comment]
I think `links` can be replaced with `html`. Where would be the place where `links = false` but `html = true`?

(we could just merge this, but lately I'm trying to justify all code changes and come up with the best "correct" solution for everything)

**Comment by BlaXpirit** [comment]
In **Class Method Summary**, HTML is there for colors but links are not present.

**Comment by asterite** [comment]
@BlaXpirit Oh, right... Well, for now it's much easier to just remove the tags in that place, so let's do that.

**Pull request merged**
