### PR TITLE
Allow `Atomic`s of pointer types

### PR DESCRIPTION
**Pull request by HertzDevil**
This is needed for things like `Atomic(LibC::HANDLE)` (see #14389).

### CODE REVIEW

**Comment by straight-shoota** [comment]
Specs are failing

**Comment by HertzDevil** [comment]
The failure happens when compiling `spec/std/atomic_spec.cr` and `spec/std/xml/reader_spec.cr` together on Crystal 1.2 or below. Reduction:

```crystal
require "spec"
require "xml"

describe Atomic do
  describe "#compare_and_set" do
    it "with pointer" do
      atomic = Atomic.new(Pointer(Void).null)
      atomic.get.should eq(Pointer(Void).null)
    end
  end
end

module XML
  describe Reader do
    describe "#to_unsafe" do
      it "returns a pointer to the underlying LibXML::XMLTextReader" do
        reader = Reader.new("<root/>")
        reader.to_unsafe.should be_a(LibXML::XMLTextReader)
      end
    end
  end
end
```

This has been fixed in #11636.

**Comment by straight-shoota** [comment]
Oh what a mess. What options do we have? I suppose we could skip either of those specs when building with an old compiler? 🤔
It would only be necessary when *both* are combined, but that might be hard to detect? We could look whether `XML` is defined in the atomic spec though...

**Comment by HertzDevil** [comment]
We could also simply replace the typedefs with aliases on versions before 1.3, or even without a version check

**Comment by straight-shoota** [comment]
Related discussion about dropping `type` entirely from the language: #10031

**Review by straight-shoota — APPROVED** [review]

**Review by ysbaddaden — COMMENTED** [review]
This exhibits the same issue as #14402: Pointer#address and Pointer#object_id are both UInt64, whatever the actual pointer size, so that will require a DWCAS on 32-bit archs :(

**Comment by straight-shoota** [comment]
@ysbaddaden I suppose there's no way around that until we introduce arch-specific pointer sizes. If you *need* to put a pointer into an atomic, you'll have to eat that. This PR doesn't really change anything about that because the current workaround would be to put `Pointer#address` in the atomic.

I suppose you *could* technically downcast the integer type on a arch with smaller pointer size, but unlikely anyone is going this extra length. Anyways, if you want, you can still do that after this PR. It just enables an easier use case without invalidating anything that worked before.

**Comment by HertzDevil** [comment]
Looking at this again, pointer sizes are target-specific but the type of `Pointer#address` isn't, so this is simply wrong and leads to a stack corruption

**Review by ysbaddaden — APPROVED** [review]
Thanks @HertzDevil it looks perfect!

Shall we extract the libxml2 fix to have a distinct commit in master, or just squash it here?

**Comment by straight-shoota** [comment]
> Shall we extract the libxml2 fix to have a distinct commit in master, or just squash it here?

I missed this comment. But it seems like a good idea, it's an unrelated change.
Waiting for #14494

**Pull request merged**
