### PR TITLE
Update documentation to reflect compiler command change

### PR DESCRIPTION
**Pull request by keplersj**
Reflects changes made in #2725

### CODE REVIEW

**Comment by jhass** [comment]
Looks good, would you dare to [squash](https://github.com/crystal-lang/crystal/blob/master/Contributing.md#doing-an-interactive-rebase) the commits together?

**Comment by bcardiff** [comment]
This should not me merged prior the release of #2725  :-)
Otherwise it will get published right away.

**Comment by keplersj** [comment]
@jhass I thought GitHub allowed squashing on Pull Request merge?

**Comment by jhass** [comment]
It does, but it's apparently not enabled for this repo and I still like a merge commit referencing the PR ;)

**Comment by keplersj** [comment]
Okay, I'll squash!

**Comment by ysbaddaden** [comment]
@jhass I do have the option to squash when merging on this repo, and already used it when merging simple PR (like typos).

**Comment by keplersj** [comment]
Should I still squash these commits?

**Comment by asterite** [comment]
I started to use the squash button as soon as github added it, I think it's great :-)

(though it took me a while to find it)

**Comment by fernandes** [comment]
@jhass it keeps the PR reference inside the parenthesis 👍

**Pull request merged**
