### PR TITLE
Support --help for crystal eval 

### PR DESCRIPTION
**Pull request by amitsaha**
Fix for https://github.com/crystal-lang/crystal/issues/3196

### CODE REVIEW

**Comment by bcardiff** [comment]
Hi @amitsaha , the code is fine.

All other help commands that have --help are because there are options or subcommands. So eventually, for consistency, other --help should be added. 

I see not cons on adding this. But `/etc/completion.bash` and `/etc/completion.zsh` need to be updated also in order to update this IMO. 

Another alternative for this might be to contribute to https://crystal-lang.org/docs/using_the_compiler/index.html . Maybe there is more chance for people to learn how to use eval there than in --help. Just my 2 cents.

**Comment by amitsaha** [comment]
Thanks @bcardiff for taking a look. Note that you currently get an error when you try `crystal eval --help` which is my main motivation for fixing this. I will do the change to the completion files and update the PR well as update the doc in a separate PR.

**Comment by amitsaha** [comment]
Can I get some help with the zsh completion?

**Comment by asterite** [comment]
@amitsaha Would you mind if I implement this? Adding `--help` for a command that doesn't have any options doesn't add much to the command, so I'll make it possible to pass `--release`, `-s` and others.

**Comment by amitsaha** [comment]
Sure. Go ahead.

Note that I was not trying to implement --help because it would add
anything. But the fact that --help would throw an error is a bug. That is
what I aimed to fix.

**Pull request closed without merging**
