### PR TITLE
Add `LibLLVM::IS_50` constant

### PR DESCRIPTION
**Pull request by Sija**
SSIA

### CODE REVIEW

**Comment by akzhan** [comment]
Why not to build cycle in bash from 5 down to 3?)

**Comment by ysbaddaden** [comment]
This is no supporting, but making LLVM5 the default LLVM version to compile against. There is a difference.

**Comment by Sija** [comment]
@ysbaddaden It supports using _llvm-5.0 postfixed versions_, not _LLVM itself_. Title is copied from #5013 btw.

**Comment by ysbaddaden** [comment]
Yup, which was just recently merged, because when set at the top of the list, it will be tried out first, thus prefering LLVM5 over any other version, thus making it the default.

It may be fine, thought I'm not sure it has been tested much. I'm not even using Crystal with LLVM5 myself. The latest stable is compiled against LLVM 3.9 and current master against LLVM4.

**Comment by luislavena** [comment]
Hello,

The change in #5013 was to try for LLVM 4 prior others. That assumes that v4 is now considered stable in most of the distributions, however, v5 needs more testing.

Making that the default when detecting LLVM v5 might not be good. I might suggest adjust this so `IS_50` is available but leave the auto-detection out, at least for now.

Cheers.

**Comment by Sija** [comment]
fair 'nuff, I'll revert the changes except `LibLLVM::IS_50` constant. @asterite are you ok with that?

**Comment by asterite** [comment]
@Sija I'm not the one that gave opinions in this thread :-P

**Comment by asterite** [comment]
What I mean is, I don't want to be the one everyone has to consult before making a decision.

**Comment by Sija** [comment]
@asterite understandable, I just asked you because of your PR approval :)

**Pull request merged**
