### PR TITLE
Fix offsetof not being usable with macros

### LINKED ISSUE #7702: offsetof can't be used in macros
EDIT: Nevermind, I solved the issue. I'll open a pull request soon.

I just discovered a pretty important bug with `offsetof`, so sorry it's already released :(

`offsetof` produces weird syntax when used in macros:

```cr
macro do_nothing(exp)
  {{exp}}
end

do_nothing(offsetof(SomeType, @some_ivar))
```

I get the following error:
```
Error in src/main.cr:14: macro didn't expand to a valid program, it expanded to:

================================================================================
--------------------------------------------------------------------------------
   1.   offsetof(SomeType, @some_ivar)SomeType@some_ivar
--------------------------------------------------------------------------------
Syntax error in src/main.cr:14: unexpected token: SomeType

do_nothing(offsetof(SomeType, @some_ivar))
                    ^

================================================================================

do_nothing(offsetof(SomeType, @some_ivar))
^~~~~~~~~~
```
As you can see, the `offsetof(SomeType, @some_ivar)` becomes `offsetof(SomeType, @some_ivar)SomeType@some_ivar`. I have no idea where this comes from because `OffsetOf` basically does the same as `SizeOf` when compiling.

What would really help me fix this bug is knowing:
- Is it normal that AST nodes get transformed when used in macros?
- If so, why and where does this happen?

### PR DESCRIPTION
**Pull request by malte-v**
This fixes #7702.

### CODE REVIEW

**Comment by Sija** [comment]
Some specs would nice :)

**Comment by asterite** [comment]
I say it because visitor should be respected. This is probably some issue in ToSVisitor, check that you implement that and that you return false in the method so children aren't revisited/printed.

**Comment by asterite** [comment]
I can confirm that's the issue. Just add a new line at the end of the method overload for OffsetOf in ToSVisitor that says false (but please keep the test).

**Comment by asterite** [comment]
Or even better, remove this test and add a test to the to s visitor.

**Comment by malte-v** [comment]
I just realized my "solution" breaks much more that it fixes, e.g. type aliases stopped working with `offsetof`.
@asterite Thank you so much! I wouldn't have noticed that small detail. That must be the proper solution.

**Pull request merged**
