### PR TITLE
HTTP: consider quoted charset

### LINKED ISSUE #6353: HTTP response with content-type `text/html; charset="utf-8"` breaks HTTP::Client
It seems Facebook's response has:

```
text/html; charset="utf-8"
```

as the content-type header. We are not removing the quotes, which seem to be valid (there are tons of RFCs for this, but they do appear in https://tools.ietf.org/html/rfc7231

Let's fix this by checking if there are quotes.

### PR DESCRIPTION
**Pull request by asterite**
Fixes #6353

### CODE REVIEW

**Comment by jhass** [comment]
Do we also want to allow single quotes (`'`) here?

**Comment by asterite** [comment]
I'm not sure single quotes are allowed, but if others agree I can add it to this PR.

**Comment by straight-shoota** [comment]
No, single quotes should not be interpreted as string delimiters, see definition of `quoted-string` in [RFC 723 §3.2.6](https://tools.ietf.org/html/rfc7230#section-3.2.6),

**Comment by RX14** [comment]
Don't a lot of HTTP headers have the standard `value; optional-key="value"` format? Is there an RFC or standard of these headers - or even an unofficial standard - to implement a parser for them?

**Comment by straight-shoota** [comment]
@RX14 There are a ton of RFCs about mime type syntax. The most recent one is [RFC 7321](https://tools.ietf.org/html/rfc7231).

As already mentioned, I have a working parser implemented, it just needs #5765 and a little bit of finishing.

**Comment by RX14** [comment]
I'm not talking about mime types - i'm talking about the generic HTTP header value syntax.

**Comment by straight-shoota** [comment]
Yeah, I know what this is about. It's not specific to any protocol, neither HTTP nor mail. I'm not sure if there's a proper name, but this is commonly described as mime type (examples: [.NET](https://msdn.microsoft.com/en-us/library/system.net.mime.contenttype.parameters(v=vs.110).aspx), [Java](https://docs.oracle.com/javase/7/docs/api/javax/activation/MimeType.html#MimeType(java.lang.String)), [Rust](https://docs.rs/mime/0.3.8/mime/struct.Mime.html), [Go](https://golang.org/pkg/mime/#TypeByExtension))

**Comment by straight-shoota** [comment]
And despite any of this, it's still true that Crystal needs a proper parser implementation.

**Comment by RX14** [comment]
My bad, that was mime types; i'm a bit tired. I meant that mime types, set-cookie, and content-disposition have the same approximate header syntax with one or more initial values then the same `; key=value` format.

**Comment by straight-shoota** [comment]
As far as I know, this is called mime type, despite the fact that applications like `Set-Cookie` have nothing to to with mime. And yes, we should have a generic parser for this.

**Comment by RX14** [comment]
I've never seen it named as such and I can't imagine it being called that since it would be so confusing. "mime type" already means a specific concrete RFC.

**Comment by straight-shoota** [comment]
Sry, I meant media type. Doesn't make any difference, though. I guess it's just that this concept initially comes from mime type declarations and was adopted for other uses as well, without there being a proper name for this syntax.

Implementation wise, it is a MIME media type parser. This implementation can be applied to non-MIME contexts such as `Set-Cookie` or they can use a more specific, custom parser. Go for example uses `ParseMimeType` for `Content-Type`, `Content-Disposition` but a custom implementation which only recognizes a fixed set of attributes for `Set-Cookie`.

**Comment by RX14** [comment]
I'd never find such a parser as a user if I had to think "mime". So I think we shouldn't name it that way. It should be in the generic `HTTP` module.

**Comment by ysbaddaden** [comment]
Merging the fix. Discussion feels unrelated or that it could come later.

**Comment by RX14** [comment]
Yep, discussion was unrelated, sorry.

**Pull request merged**
