### PR TITLE
Improve File.symlink for Windows 

### PR DESCRIPTION
**Pull request by nof1000**
That's implements symlink on Windows. But please note that we cannot make symlink on Windows without Administrator privileges. It might be is worth writing about this in the documentation

### CODE REVIEW

**Comment by straight-shoota** [comment]
> It might be is worth writing about this in the documentation

Could you add such a note to `File.symlink`?

Also needs a rebase.

**Comment by mominshaikhdevs** [comment]
> please note that we cannot make symlink on Windows without Administrator privileges.

This is Wrong. 
Starting with Windows 10 v14972 and upwards, one can enable symlinks without admin privileges when Developer Mode is enabled. (settings > updates and security > for developers > toggle the developer mode on).

** https://blogs.windows.com/windowsdeveloper/2016/12/02/symlinks-windows-10/

** https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createsymboliclinkw
( notice the flag `SYMBOLIC_LINK_FLAG_ALLOW_UNPRIVILEGED_CREATE` ).

** https://learn.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development

**Comment by mominshaikhdevs** [comment]
should this PR be closed since #13141 is merged ?

**Comment by beta-ziliani** [comment]
Indeed, thanks!

**Pull request closed without merging**
