### PR TITLE
Use more robust ordering between def overloads

### LINKED ISSUE #10231: Wrong method resolution when using default values
```cr
class Foo
  def bar(a = 0, b = 0, c = 0, d = 0)
  end
 
  def bar
  end
end
 
foo = Foo.new
foo.bar 1, 1, 1, 1
```

fails to compile with error:

```
error in line 10
Error: wrong number of arguments for 'Foo#bar' (given 4, expected 0)

Overloads are:
 - Foo#bar()
```

https://carc.in/#/r/a8sd

---

It works when we switch the order of definitions:

```cr
class Foo
  def bar
  end
 
  def bar(a = 0, b = 0, c = 0, d = 0)
  end
end
 
foo = Foo.new
foo.bar 1, 1, 1, 1
```

https://carc.in/#/r/a8sf

---

Originally reported on IRC by _hightower2_

### PR DESCRIPTION
**Pull request by HertzDevil**
Fixes #10231. The first commit is a duplicate of #10594 + #10633. The new ordering is available only when `-Dpreview_overload_order` is specified. There is no decision on how it should be incorporated into the CI jobs.

Wording for the new overload ordering algorithm is available [here](https://gist.github.com/HertzDevil/b2150e2c1051fc29f191e5ac69644641). I have not decided on how it should be put into the reference manual.

### CODE REVIEW

**Comment by mfiano** [comment]
@Blacksmoke16 noted that this draft fixes an issue I was facing: https://play.crystal-lang.org/#/r/bncn

**Comment by stakach** [comment]
This is great stuff @HertzDevil

**Comment by HertzDevil** [comment]
Following `-Dstrict_multi_assign` I think we should make `-Dpreview_overload_order` the default on CI as well, but we'll also need smoke tests without this flag (and actually the other flags too).

**Comment by asterite** [comment]
I don't think I'll have time to review this for at least two weeks, but I agree with going in this direction, and I also see a lot of new specs to prove the expected behavior.

**Review by straight-shoota — APPROVED** [review]

**Review by straight-shoota — APPROVED** [review]

**Comment by zw963** [comment]
> I think the tests should now cover all the edge cases.

Why not enable it by default? user (e.g. like me)  always prefer define specific method at first, and put the generic one at the the last. 

```crystal
class Foo
  def bar(a = 0, b = 0, c = 0, d = 0)
    puts "1"
  end

  def bar
    puts "2"
  end
end

foo = Foo.new
foo.bar 1, 1, 1, 1 # 1
foo.bar            # 2
```

Above code broken on 1.11.1, but works when add `-Dpreview_overload_order`, even if define is reverse.

**Pull request merged**
