### PR TITLE
add support for gcm ciphers where tag getting/setting is required

### PR DESCRIPTION
**Pull request by repomaa**
if the tag isn't set before calling final when decrypting it raises an error. These changes allow you to get the tag from encrypted data and verify it by setting it when decrypting.

thanks to @mancha1 for troubleshooting and providing reference ciphertext and tag!

### CODE REVIEW

**Comment by jreinert** [comment]
anything else you need for this?

**Comment by ysbaddaden** [comment]
I'm afraid I don't know this cipher and what tag is about.

Why is it restricted to Linux only?

**Comment by jreinert** [comment]
@ysbaddaden https://en.wikipedia.org/wiki/Galois/Counter_Mode
In a nutshell: GCM ciphers don't need HMAC to verify the authenticity of an encrypted message. This is what the tag is for. It's kind of like a signature. You retrieve it from the cipher on encryption and verify it on decryption.

An example:

``` crystal
def encrypt(message, key)
  cipher = OpenSSL::Cipher.new("aes-256-gcm").tap(&.encrypt)
  cipher.key = key
  iv = cipher.iv = SecureRandom.random_bytes(12)
  ciphertext = String.build do |io|
    io.write(cipher.update(message))
    io.write(cipher.final)
  end
  [iv, cipher.tag, ciphertext]
end

def decrypt(iv, tag, ciphertext, key)
  cipher = OpenSSL::Cipher.new("aes-256-gcm").tap(&.decrypt)
  cipher.key = key
  cipher.iv = iv
  cipher.tag = tag
  String.build do |io|
    io.write(cipher.update(ciphertext))
    io.write(cipher.final)
  end
end

secret = SecureRandom.random_bytes(32)
iv, tag, ciphertext = encrypt("secret message", secret)
puts decrypt(iv, tag, ciphertext, secret) # all good

begin
  decrypt(iv, SecureRandom.random_bytes(4), ciphertext, secret) # using wrong tag
rescue OpenSSL::Cipher::Error
  puts "Message has been tampered with!"
end
```
openssl on mac doesn't ship with gcm ciphers. This is why it's limited to linux.

**Comment by ysbaddaden** [comment]
Thanks for explaining!

One may link a newer version of OpenSSL on OSX, we support FreeBSD too, and older Linux versions may have an older OpenSSL too. It would be better to have a version check.

**Comment by jhass** [comment]
Here's why we shouldn't blindly copy the Ruby API: https://github.com/ruby/openssl/issues/63

**Comment by asterite** [comment]
Anyone has any idea about this? I don't know about openssl so I can't really comment on this...

**Comment by chris-huxtable** [comment]
I was actually intending on doing something like this in a shard in the near future. I can speak to it more in a few weeks hopefully.

**Comment by chris-huxtable** [comment]
So I have managed to wrap this (GCM) and a number of other modes into a better structure. Its very much still a work in progress but I would like to know if this is something you guys would like in the Standard library, or if I should continue with doing this as a shard.

It currently would add:
- `Crypto::AES::GCM`
- `Crypto::AES::OFB`
- `Crypto::AES::CFB`
- `Crypto::AES::CTR`

and I am looking to implement:
- `Crypto::AES::CBC`
- `Crypto::AES::XTS`
- `Crypto::AES::ECB`

https://github.com/chris-huxtable/crypto-plus.cr

**Comment by bararchy** [comment]
@chris-huxtable I believe this should reside in a shard if needed, as the general notion is to extract things out of the stdlib.

I call to close this PR for the sake of cleanup

**Comment by j8r** [comment]
As @bararchy said more than a year ago, better to close this PR now.
@repomaa you can create a shard for this then, it looks like to be not commonly used, and moreover Linux specific.

**Pull request closed without merging**
