### PR TITLE
Fix FFI specs on release builds

### LINKED ISSUE #12592: ffi_spec fails with --release
## Bug Report

Running:
```
make all
make compiler_spec
```
works as expected and spec passes.

Running:
```
make all release=1
make compiler_spec release=1
```
fails with:

```
Failures:

  1) Crystal::FFI::CallInterface .new sum struct
     Failure/Error: pointer_value.should eq 50

       Expected: 50
            got: 0

     # spec/compiler/ffi/ffi_spec.cr:166

Finished in 16:17 minutes
10780 examples, 1 failures, 0 errors, 15 pending

Failed examples:

crystal spec spec/compiler/ffi/ffi_spec.cr:132 # Crystal::FFI::CallInterface .new sum struct
make: *** [Makefile:92: compiler_spec] Error 1
```

Crystal:
```
./bin/crystal -v
Using compiled compiler at .build/crystal
Crystal 1.6.1-dev [809c49e] (2022-10-11)

LLVM: 14.0.6
Default target: x86_64-unknown-linux-gnu
```

This affects the Nix builds: https://github.com/NixOS/nixpkgs/pull/173928
and possibly the solus ones: https://dev.getsol.us/source/crystal/browse/master/package.yml$36 (they remove `spec/compiler/ffi/ffi_spec.cr`)

### PR DESCRIPTION
**Pull request by HertzDevil**
Should fix #12592.

### CODE REVIEW

**Comment by straight-shoota** [comment]
Wouldn't it make sense to move that constant into the actual code in the `FFI` namespace?

**Comment by HertzDevil** [comment]
`Crystal::FFI` is not public yet and the interpreter itself doesn't need this type, so all this does is requiring longer qualified type names in that spec file.

**Comment by straight-shoota** [comment]
In the specs we could just use Int64 everywhere without needing ffi_arg at all. That should promote correctly.

**Comment by HertzDevil** [comment]
In case someone else or ourselves later try to publicize `FFI` based on what is already in the repository, it is a good idea to remind them of `ffi_arg`'s existence.

**Comment by straight-shoota** [comment]
Yes, that's exactly why I suggested to move it out of the spec into the implementation.
The current solution feels some middle ground compromise partly acknowledging, but not entirely. I'd either go full and move ffi_sarg to the implementation, or avoid it entirely (but mention it in a comment).

**Comment by beta-ziliani** [comment]
@straight-shoota am I getting it right that you meant to move the code for the Sarg type to `./src/compiler/crystal/ffi/ffi.cr`, instead of being in the spec as it is now?

**Comment by straight-shoota** [comment]
Yes, either that or remove it entirely (because it's only used in the spec and there we can simply just use the bigger type with Int64 and then there's no need for it).

**Review by straight-shoota — APPROVED** [review]
Regardless of that, I'm fine with merging it as is - or with changes in either of the directions I suggested.
I'd like to get this fix into 1.6.1 and not hold up the release for long.

**Comment by asterite** [comment]
But this can be done after 1.6.1. Just don't run the specs in release mode. I think ffi has been there since 1.5.0

**Comment by HertzDevil** [comment]
In theory we cannot take an `Int64*`, pass it to FFI as a `Void*`, and then have FFI reinterpret it as an `Int32*` because that would break on big-endian systems. So it is good practice to always use `ffi_sarg` and never assume `Int64` fits everything.

**Review by straight-shoota — APPROVED** [review]
Thank you ❤️

**Pull request merged**
