### PR TITLE
Add Int#ordinal and Int#to_ordinal methods

### PR DESCRIPTION
**Pull request by molovo**
Two simple, but useful methods. Happy to change the names of the methods if anyone has better suggestions. Specs and docs included.

### CODE REVIEW

**Comment by akzhan** [comment]
I'm sorry but it should be outside stdlib unless full ICU included. 

Separated `intl` shard should be preferred.

Just because English just one of languages.

**Comment by molovo** [comment]
@akzhan that's a very fair point that I totally overlooked

**Comment by akzhan** [comment]
See also https://github.com/amberframework/amber/issues/56.

**Comment by akzhan** [comment]
Looks like it should be closed.

**Pull request closed without merging**
