### PR TITLE
add custom extension support for Tempfile

### PR DESCRIPTION
**Pull request by jreinert**

### CODE REVIEW

**Comment by jhass** [comment]
Maybe switching to `mkstemps(3)` is a bit nicer for this case?

**Comment by asterite** [comment]
I though this was just letting you add an extension, but it completely changes the implementaiton. So 👎 from me.

**Comment by RX14** [comment]
mkstemp actually isn't more atomic than open, it's just that it ensures the name is securely random. We already have a easilly usable secure random generator, so I don't think an implementation which simply generates the path itself is neccesarily bad. That being said, it's much easier to just use `mkstemps`.

**Comment by jreinert** [comment]
Ahh I overlooked that mkstemps has the option to include a suffix! I'll update the pr.

**Comment by bcardiff** [comment]
@jreinert it seems the PR is based on a pretty old commit, could you rebase it on master?

**Comment by jreinert** [comment]
@bcardiff done!

**Comment by bcardiff** [comment]
Thanks @jreinert

**Comment by wmoxam** [comment]
`mkstemps` was added to all platforms except OpenBSD 😢

**Pull request merged**
