### PR TITLE
Parser: declare local vars of indirect type declarations in call args

### LINKED ISSUE #11982: Undefined method 'x' for top-level when using generics with Proc
## Bug Report

```shell
crystal --version
Crystal 1.4.0 [ef05e26d6] (2022-04-06)

LLVM: 10.0.0
Default target: x86_64-unknown-linux-gnu
```

I have an issue with generic parameters using forall.
The error message is completely confusing and doesn't make any sense to me.
I tried to find out where I have an error in my type annotations, but couldn't find any.
Then I crafted a "minimal" example which shows the weird behavior.

All these examples work as expected:

```crystal
def main
  result : Int32 = 123
  puts "Printing from main"
  puts result
  result
end

main

def main_generic(fnc : Proc(I, O), input : I) : O forall I, O
  result : O = fnc.call(input)
  puts "Printing from main_generic"
  puts result
  result
end

main_generic(->(i : String) : String { "Mapped #{i}" }, "input")

def main_generic_fnc(fnc : Proc(I, O)) : Proc(I, O) forall I, O
  ->(input : I) : O {
    result : O = fnc.call(input)
    puts "Printing from main_generic_fnc"
    puts result
    result
  }
end

main_generic_fnc(->(i : String) : String { "Mapped #{i}" }).call("input")
```

This one doesn't:

```crystal
struct Wrapper(I, O)
  def initialize(@parser : Proc(I, O))
  end

  def call(*args)
    @parser.call(*args)
  end
end

def main_generic_fnc_wrapper(fnc : Proc(I, O)) : Wrapper(I, O) forall I, O
  Wrapper.new(->(input : I) : O {
    result : O = fnc.call(input)
    puts "Printing from main_generic_fnc_wrapper"
    puts result
    result
  })
end

# Both of these doesn't work. I used the first one in previous examples, so I include it here.
# The second one is used to constraint I to String and O to Int32, so they are not ambiguous in the error messages.
#main_generic_fnc_wrapper(->(i : String) : String { "Mapped #{i}" }).call("input")
main_generic_fnc_wrapper(->(i : String) : Int32 { i.to_i }).call("123")
```

results in:

```
❯ crystal spec --error-trace
error in line 1
Error: while requiring "./spec/parser_spec.cr"


In spec/parser_spec.cr:162:1

 162 | main_generic_fnc_wrapper(->(i : String) : Int32 { i.to_i }).call("123")
       ^-----------------------
Error: instantiating 'main_generic_fnc_wrapper(Proc(String, Int32))'


In spec/parser_spec.cr:157:10

 157 | puts result
            ^-----
Error: undefined method 'result' for top-level

If you declared 'result' in a suffix if, declare it in a regular if for this to work. If the variable was declared in a macro it's not visible outside it)
```

The last example works when you change the `result : O = fnc.call(input)` to `result = fnc.call(input)`.
Then it compiles and works without any issues. Just by removing `: O`.
If you replace the type ` : O` with, for example, ` : I`, the error message correctly shows `Error: type must be String, not Int32`.

Is this a bug? Or a limitation? Am I doing something wrong?

### PR DESCRIPTION
**Pull request by asterite**
Fixes #11982

### CODE REVIEW

**Review by straight-shoota — APPROVED** [review]

**Comment by daliborfilus** [comment]
Hi guys, can this be merged or is it waiting for something? It's not urgent, just asking.

**Comment by asterite** [comment]
I think this will be a breaking change.

**Comment by straight-shoota** [comment]
Hm, is it a breaking change? What would be a program that did compile before this change and doesn't afterwards?

**Comment by asterite** [comment]
This one:

```crystal
macro let(x)
  {{x}}
end

let x : Int32 = 1
puts x
```

**Comment by asterite** [comment]
Oh, wait... it seems that didn't compile before either 🤔 

I'm surprised it didn't work before... I guess it's fine to merge this, then.

**Comment by straight-shoota** [comment]
Hm, yeah that's odd. Because the type restriction seems to actually apply to the local variable, so it must be declared:
```cr
macro let(x)
  {{x}}
end

let x : Int32 = 1

x = "" # type must be Int32, not (Int32 | String)
```

**Comment by asterite** [comment]
Will this go into 1.6?

**Comment by HertzDevil** [comment]
This currently works:

```crystal
macro let(x)
  {{ x }}
end

let x : Int32 = 1
puts {{ "x".id }} # => 1
```

**Review by beta-ziliani — COMMENTED** [review]
LGTM 👍

**Review by beta-ziliani — APPROVED** [review]

**Pull request merged**
