### PR TITLE
Added an interpreter spec for check `crystal i` is running on linux.

### PR DESCRIPTION
**Pull request by zw963**

### CODE REVIEW

**Comment by straight-shoota** [comment]
What's the point of this?
It seems this spec checks if an *installed* crystal compiler has interpreter support? That doen't make any sense because such a compiler binary would be completely independent of the spec context.

**Comment by zw963** [comment]
> What's the point of this? It seems this spec checks if an _installed_ crystal compiler has interpreter support? That doen't make any sense because such a compiler binary would be completely independent of the spec context.

Because build 1.11.0 failed on Arch Linux, see https://forum.crystal-lang.org/t/crystal-1-11-has-been-released/6284/4?u=zw963
If I remember correctly, and it really running failed this time, this should should be the second time the interpreter has broken?

So, instead of `.build/crystal i` should work? test on this no side effect.

**Comment by beta-ziliani** [comment]
The interpreter is tested in Linux, see for example https://github.com/crystal-lang/crystal/actions/runs/7460577216/job/20299250229?pr=14189 .

There might be an issue with Arch, or with any Linux distribution not tested in our CI, but that's a different topic.

**Comment by zw963** [comment]
> The interpreter is tested in Linux, see for example https://github.com/crystal-lang/crystal/actions/runs/7460577216/job/20299250229?pr=14189 .
> 
> There might be an issue with Arch, or with any Linux distribution not tested in our CI, but that's a different topic.

Hi, i thought this spec should be fix to let spec failed before merge #14198 @straight-shoota

**Pull request closed without merging**
