### PR TITLE
Remove unneeded parenthesis from calls in macro expression

### PR DESCRIPTION
**Pull request by straight-shoota**
As of 0.24.0 empty parenthesis are not needed anymore to denote calling a macro method.

see #4927

While at it, I also resolved a TODO in `crystal/system/unix/urandom.cr` though I'm not sure if this is correct because the conditions seem somewhat contradictory. But what target would match `flag?(:openbsd) && flag?(:linux)` in the first place?

### CODE REVIEW

**Comment by straight-shoota** [comment]
I hope I caught all occurences of `()` in macro calls not like the `doc`/`docs` rename where missed locations have been fixed in multiple followups...

**Comment by straight-shoota** [comment]
Okay, it fails on Mac OS. @ysbaddaden any advice?  Should I just remove it from this PR?

**Comment by straight-shoota** [comment]
It looks good when inverting the condition with `unless` 👍

**Comment by RX14** [comment]
Assuming this is all of them. More `skip_file`s may have been merged recently.

**Comment by straight-shoota** [comment]
Yes, there were some in `src/io/encoding.cr` and `spec/compiler/semantic/macro_spec.cr` :+1:

**Pull request merged**
