### PR TITLE
replace mapping with serializable in compiler

### PR DESCRIPTION
**Pull request by kostya**

### CODE REVIEW

**Comment by kostya** [comment]
travis crashed with getters:
```
in src/compiler/crystal/tools/expand.cr:122: undefined method 'expansions=' for Crystal::ExpandResult
        res.expansions = @found_nodes.map { |node| ExpandResult::Expansion.build(node) }

```

**Comment by straight-shoota** [comment]
Just use getters where no setters are needed. You don't have to wait for travis if you run the specs locally.

**Comment by kostya** [comment]
i don't know how it used and where, with mapping it all was as property.

**Comment by straight-shoota** [comment]
Well, it's just six ivars and you already know one needs a setter. Just trial and error will get you through very quickly.

**Comment by asterite** [comment]
Next we should remove mapping.

**Pull request merged**
