### PR TITLE
Check formatting early in CI

### PR DESCRIPTION
**Pull request by andrewhamon**
This commit makes formatting the first check, so that CI doesn't run for
hours only to fail on style.

### CODE REVIEW

**Comment by BlaXpirit** [comment]
This makes changes to the formatter impossible to test.

**Comment by andrewhamon** [comment]
@BlaXpirit couldn't that be mitigated by simply running the formatter before pushing changes to the formatter?

**Comment by andrewhamon** [comment]
As an added bonus, reviewers would get to see what the changes look like practice.

**Comment by BlaXpirit** [comment]
@andrewhamon, that is indeed what people do, but with this change the check will run the old formatter and conclude that there are difference in the result. Basically, any changes to formatter will always make this fail.

**Comment by andrewhamon** [comment]
I see now 😅 My apologies.

So I know very little about the build process... but could things be arranged like so:

1. `make crystal` build the new crystal
2. `./bin/crystal tool format --check samples spec src` check formatting
3. `make std_spec clean` run std lib tests
4. `make spec doc` run other specs and build docs
3. `find samples -name "*.cr" | xargs -L 1 ./bin/crystal build --no-codegen` do whatever this is for


Also, why does `make std_spec clean` run before the new crystal is built, currently?

**Comment by BlaXpirit** [comment]
@andrewhamon there are some things about the bootstrapping process that complicate everything. Perhaps newer standard library must always still work on older compiler, or something like that.

As I understand it:
`make` rebuilds crystal regardless of the following arguments, but only if there isn't already a compiled crystal.
The formatter check must always run after `clean`.

**Comment by andrewhamon** [comment]
Hmmm... well this really isn't a huge deal or anything, but it would help when noobs like me come along and forget to format. The CI wait times are brutal.

I'm going to close this since its not super important to me and I'm about to be offline for the next few days.

**Comment by RX14** [comment]
`make` doesn't always rebuild crystal, its just that the standard library has to compile with the latest release. However it doesn't have to format with the latest release.

**Pull request closed without merging**
