### PR TITLE
Fix `bin/crystal` in symlink working directory

### PR DESCRIPTION
**Pull request by straight-shoota**
This is a workaround for one immediate effect of https://github.com/crystal-lang/crystal/issues/12969

### CODE REVIEW

**Review by beta-ziliani — APPROVED** [review]
looks like a reasonable patch

**Comment by oprypin** [comment]
`realpath` is not very portable. From my experience, Linux systems usually have it, Mac and BSDs usually don't have it. Of course GitHub Actions will not show that because it installs everything. This may need to be reconsidered.

**Comment by HertzDevil** [comment]
This `realpath` is a custom function defined at the top of the file

**Comment by oprypin** [comment]
Oh. 😅

**Pull request merged**
