### PR TITLE
Mark spec as pending for the interpreter

### PR DESCRIPTION
**Pull request by asterite**

### CODE REVIEW

**Review by HertzDevil — APPROVED** [review]

**Comment by wontruefree** [comment]
I am sure this is obvious but why add a new method?

With windows support and now the interpreter it seems like tagging `it` blocks or `pending` blocks would allow flexibility with multiple work streams and be more clear to the readers.

something like:
```crystal
it "works", only: :windows do
end

it "will work", skip: :interpreter do
end
```

**Comment by asterite** [comment]
I think the main issue is that `it` is a general construct for tests and it doesn't allow arbitrary named arguments. So we'd have to make `it` support `only` and `skip` specifically for the compiler.

I think eventually we'll get rid of `pending_win32`, and hopefully the same for `pending_interpreter`, so maybe the effort of doing something like `only` or `skip` isn't worth the gain right now.

**Comment by HertzDevil** [comment]
Tags probably exist for that purpose. But also sometimes those pending specs simply do not compile on the disabled platforms yet by the time they are written; since `#it` is a method, not a macro, it cannot conditionally yield based on the tag contents.

**Review by HertzDevil — APPROVED** [review]

**Comment by asterite** [comment]
I'm thinking it's better to increase the wait time in interpreted mode.

**Pull request closed without merging**
