### PR TITLE
IO#encoding fix

### PR DESCRIPTION
**Pull request by Exilor**
[Fixes this error](https://play.crystal-lang.org/#/r/14uy).

### CODE REVIEW

**Comment by asterite** [comment]
Thank you! Maybe you can add a spec to MemoryIO, checking this?

**Comment by Exilor** [comment]
My Linux installation (with Git configured and all) doesn't boot anymore so I can only change one file at a time via github itself. If you don't mind having a separate PR for the spec I can go ahead and do it.

**Comment by asterite** [comment]
If you don't mind, I can commit the fix with the spec directly to master (it's a very small change)

**Comment by Exilor** [comment]
Done.

**Comment by asterite** [comment]
Merged in 7e9bd700c15830edd3876b8a37274a763d549f37. Thank you!

**Pull request closed without merging**
