### PR TITLE
Compiler: add `--check` flag to formatter tool. Fixes #2328

### LINKED ISSUE #2328: Check for format in specs.
We can add a check in specs for ```crystal tool format``` output. We can so:
- spot bugs in formatter (e. g. #2325, #2326, #2327).
- have a repository in a clean state while coding (it's annoying to revert  unrelated formatter fixes).
- check PRs format easily.

### PR DESCRIPTION
**Pull request by asterite**
With this you can now run

```
crystal tool format --check
```

in your project, and if formatting all `.cr` files doesn't produce a change, the exit code is 0. Otherwise it is non-zero.

We can use it in this project too in travis so we make sure that all code is properly formatted, and that all pull requests are too.

After releasing 0.14.0 I realized the formatter broke in a severe way. With this check we would have noticed this immediately, so I think this is a must have.

Finally, you can also do `crystal tool format src --check` or whatever file/dir you want, if you don't want to check this in all `.cr` files.

### CODE REVIEW

**Comment by jhass** [comment]
I'd still love a mode that prints to stdout, ideally only changed lines with the line number, so that we don't only know whether there are changes necessary, but also which.

**Comment by veelenga** [comment]
In conjunction with print to stdout that could be changed to `--dry-run` instead of `--check`.

**Comment by asterite** [comment]
The use case of this flag is this:

1. You add it in your .travis.yml file
2. You commit some files or a PR comes. The build fails because the source is not formatted.
3. You run `crystal tool format` to fix formatting errors.
4. You commit or accept the PR.

I mean, if the formatting is not right you just run `crystal tool format` to fix it. There's no need to know what needs to be changed in order to comply with the formatter, because you can just run the tool to do that.

And, finally, to know what has changed we would need to implement a diff algorithm. Formatting source code and computing a diff are two different things.

...

Not that we wouldn't like something like [Python's difflib](https://docs.python.org/2/library/difflib.html) in the standard library :blush: And then eventually we could implement the formatter diff, but I'd like to know a real use case for it.

**Comment by asterite** [comment]
I though I merged this before... I'll merge it now, we can always improve it later or add more options to it.

**Pull request merged**
