### PR TITLE
Added present? and blank?

### PR DESCRIPTION
**Pull request by Seachaos**
add present? and blank? in string, float, integer, array, hash. and add length for them

### CODE REVIEW

**Comment by Seachaos** [comment]
not pass in ci

**Comment by asterite** [comment]
@Seachaos but know that we don't want `length`, there's `size` for this and we don't want aliases. And we are also not sure about `blank?` and `present?`. For example:

```crystal
index = "foo".index(some_string)
if index.present?
  # compiler has no idea that `present?` means it can't be nil,
  # and also `present?` could be redefined to mean something else
  puts index + 1 # Error, undefined method `+` for Nil
end
```

In short, it will bring more confusion than solution.

**Comment by Seachaos** [comment]
I got.
I have use been Ruby on Rails, The method "present?" is good for show text in view
 (help me check it's have value for human)
It can check string is blank or exists.
But it's maybe will let people confusion about nil.
(nil or empty string or array.length = 0 will get present false)
I am think about it. Thanks a lot.

**Comment by jhass** [comment]
Ref #1299

**Pull request closed without merging**
