### PR TITLE
Fix using roundeven intrinsic on darwin 

### LINKED ISSUE #10475: Bug: Undefined symbol `_roundeven`
#10413 introduced `Number#round_even` which binds to the LLVM intrinsic `roundeven` which was only introduced in LLVM 11. For older LLVM versions it falls back to `rint`.
It seems that the intrinsic is not (yet) available on darwin, for some reason.

----

I can't compile the compiler anymore :-(

```
Undefined symbols for architecture x86_64:
  "_roundeven", referenced from:
      _*Float64#round_even:Float64 in F-loat64.o
```

This is on Mac OSX, LLVM 11.1.0

_Originally posted by @asterite in https://github.com/crystal-lang/crystal/issues/10474#issuecomment-792021817_

### PR DESCRIPTION
**Pull request by straight-shoota**
Resolves #10475

Based on #10476 to make sure it actually works (and continues to work).

### CODE REVIEW

**Comment by asterite** [comment]
Thank you!

Do you know why that function isn't there on Mac? And what's the benefit of using that over the alternative?

**Comment by straight-shoota** [comment]
I have no idea why it's missing on macos. But it should be available in LLVM 11 (https://releases.llvm.org/11.0.0/docs/LangRef.html#llvm-roundeven-intrinsic) and it does on linux.
Maybe we shouldn't use it altogether, or just for linux explicitly?

As far as I understand, `roundeven` was introduced for slightly improved semantics (it's about specific error conditions IIRC). rint might be removed at some point, but might not. It definitely feels better to use the more recent roundeven when it's available.

**Comment by asterite** [comment]
Well, the docs say it's not supported on all target. Maybe this is one case.

**Comment by straight-shoota** [comment]
Could be. But when a major platform doesn't support even the main float types, I'd expect a more clear message that it's only supported on some targets at all.
Btw. the same is said about `rint` so you could assume it should be unavailable on similar targets.

**Comment by asterite** [comment]
Is there a performance difference or something else? I think that if they are equivalent but one works in more platforms, we should use that alternative.

**Comment by straight-shoota** [comment]
Well `roundeven` is supposed to habe the better, standard-conformant semantics. Not sure if that really matters for our use case, but on platforms that support it, I don't think there's any reason to use `rint` over `roundeven`.

Since we don't know about other platforms, I'd limit usage to LLVM >= 11 on linux. That should be good.

**Comment by straight-shoota** [comment]
I actually think we should use `rint` for now on every platform. That seems to be more widely available. As Ary said there's no real downside to using `rint` over `roundeven`. So we should just go with that and not block ourselves for improving LLVM 11 support.
We can introduce `roundeven` later when it has more support.

**Comment by asterite** [comment]
@straight-shoota Thank you! And just to be clear, it might have looked like I'm totally against using `roundeven` but that's not the case. I'm sure eventually we'll want to use it, it just seems that it's poorly supported right now.

**Comment by SlayerShadow** [comment]
@straight-shoota, thank you! It fixes compiler at least on Alpine and with latest LLVM versions. Compiler compiled with `--release` flag still doesn't work but it seems unrelated issue.

**Pull request merged**
