### PR TITLE
Parser: push var for type declaration

### LINKED ISSUE #8611: TypeDeclaration variable in macro argument is not viewed as defined variable
The code:

```Crystal
macro let(*vars)
  {% for v in vars %}
    {% if v.is_a?(Assign) %}
      {{ v }}
    {% elsif v.is_a?(TypeDeclaration) %}
      {{ v }}
    {% elsif v.is_a?(UninitializedVar) %}
      {{ v }}
    {% end %}
  {% end %}
end

macro embed(&block)
end

z : Int32 = 1
let x = 1, y : Int32 = 1

embed do
  x += 2
  z += 1
  y += 1
end
```

The error:
```
Using compiled compiler at /home/developer/workspace/.build/crystal                                                                                                           
In /home/developer/workspace/tmp/test2.cr:22:7                                                                                                                                
                                                                                                                                                                              
 22 | y += 1                                                                                                                                                                  
          ^                                                                                                                                                                   
Error: '+=' before definition of 'y'
```

### PR DESCRIPTION
**Pull request by asterite**
Fixes #8611

### CODE REVIEW

**Comment by asterite** [comment]
It seems this conflicts with #4114 and #4106

I don't know what to do. Maybe reverting #4114 is good because #8611 will start working and #4106 will still give an error message, though not the ideal error message (but probably we can change the error message to say "undefined local variable blah blah").

**Comment by RX14** [comment]
I was trying to search for that issue, to bring it up against this change. I think being able to declare variables this way isn't necessary, and the previous behaviour was correct. In general, I don't think macros should be allowed to declare local variables.

In the absence of finding any past discussion though, I did approve this PR.

**Comment by asterite** [comment]
It does work if you assign to a variable, though. That's why I think it should work in all cases, or in none.

**Comment by RX14** [comment]
> That's why I think it should work in all cases, or in none.

I agree.

**Comment by asterite** [comment]
Closing because this didn't work.

**Pull request closed without merging**
