### PR TITLE
Extends documentation for Hash

### PR DESCRIPTION
**Pull request by robacarp**
- combines string and symbol shorthand sections
- adds "getting/setting" section with detail about []?

On issue #1971, I noted that the documentation for [Hash\[\], etc](http://crystal-lang.org/docs/syntax_and_semantics/literals/hash.html) could be improved. I've made a couple tweaks and added a section describing using ```[]=, [], []?, and fetch``` to interact with a hash.

On a more meta note, I have a few other places where I'd like to contribute to documentation. If this isn't the best way to do it, or if I'm missing some subtleties about the preferred documentation style, please point me in the right direction! :]

Screenshot:

### CODE REVIEW

**Comment by asterite** [comment]
Hi @robacarp,

Thanks for this, but I think I prefer having the docs of how to use a Hash in `hash.cr`. Otherwise we end up with duplicated documentation that we have to maintain. Right now Array's docs are in `array.cr`, and so on.

**Comment by robacarp** [comment]
Thanks for looking, @asterite.

When I was trying to decide where to put a better intro to the Crystal hash, I was uncertain where to put it because of the two sets of docs. In the end, I settled on putting it in ```/docs/``` instead of ```/api/``` because in the first section of ```hash.cr```, it says:

> Overview
>
> A Hash represents a mapping of keys to values.
>
> See the official docs for the basics.

Following that link to the basics, one of the most important functional basics is missing from the official docs. [Array](http://crystal-lang.org/api/Array.html) is a little better at this, but the tone of the document is generally to pretty minimal in ```/api/``` and more helpful in ```/docs/```. Can you help me understand what the hopeful future is for the two sets of docs? 

I'll move this intro to hash over to hash.cr.

**Comment by asterite** [comment]
The idea is that `/docs/` explain the language and `/api/` explains the API. Literals kind of fall inside both categories: they are part of the language because they are special, and they definitely create an instance of some type. So in the `docs` section we explain all literal forms and what they create, and in `api` we might explain them again as they are another way to construct an instance of such type.

But, documentation for `Hash#[]` and `Hash#[]=` should live inside `api`, because the syntax for `a[b] = c` is explained generally in the [operators](http://crystal-lang.org/docs/syntax_and_semantics/operators.html) section, then the particular semantic that Hash gives it is explained in that type.

**Comment by asterite** [comment]
I'll closing this. If you wish you can open another PR where docs are in `hash.cr`, not in the GitBook. Thanks!

**Pull request closed without merging**
